! Generated by azul-css codegen (Fortran). Do not edit by hand.
! Compile with -ffree-line-length-none (like the azul modules).
module azul_styles
  use azul
  implicit none
  private
  public :: style_text
  public :: style_box
  public :: style_flex
  public :: style_grid
  public :: style_borders
  public :: style_scroll
  public :: style_effects
  public :: style_fragment
  public :: style_shape
  public :: style_table
  public :: style_content
  public :: style_anim

contains

  ! CSS: .text
  ! dropped a value these bindings cannot build: `StyleInitialLetterValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleLineClampValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleHangingPunctuationValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleTextCombineUprightValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleUnicodeBidiValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleTextBoxTrimValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleTextBoxEdgeValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleDominantBaselineValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleAlignmentBaselineValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleBaselineSourceValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleLineFitEdgeValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleInitialLetterAlignValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleInitialLetterWrapValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleWhiteSpaceValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleHyphensValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleWordBreakValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleOverflowWrapValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleLineBreakValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleTextOverflowValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleTextOrientationValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleTextAlignLastValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleTextTransformValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleDirectionValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleHyphenationLanguageValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleExclusionMarginValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `CaretWidthValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `SelectionRadiusValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  function style_text() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    type(AzStyleFontFamily), target :: t1(2)
    type(AzStyleFontFamily), target :: t2(2)
    type(AzCssPropertyWithConditions), target :: t3(20)
    t1(1) = az_style_font_family_system(azul_string('Arial'))
    t1(2) = az_style_font_family_system(azul_string('sans-serif'))
    t2(1) = az_style_font_family_system(azul_string('Georgia'))
    t2(2) = az_style_font_family_system(azul_string('serif'))
    t3(1) = az_css_property_with_conditions_simple(az_css_property_text_color(AzStyleTextColor(inner=AzColorU(r_=51_c_int8_t, g=102_c_int8_t, b=-103_c_int8_t, a=-1_c_int8_t))))
    t3(2) = az_css_property_with_conditions_simple(az_css_property_font_size(AzStyleFontSize(inner=az_pixel_value_px(14.0_c_float))))
    t3(3) = az_css_property_with_conditions_simple(az_css_property_font_family(az_style_font_family_vec_copy_from_ptr(c_loc(t1(1)), 2_c_size_t)))
    t3(4) = az_css_property_with_conditions_simple(az_css_property_font_weight(StyleFontWeight_W600))
    t3(5) = az_css_property_with_conditions_simple(az_css_property_font_style(StyleFontStyle_Italic))
    t3(6) = az_css_property_with_conditions_simple(az_css_property_text_align(StyleTextAlign_Center))
    t3(7) = az_css_property_with_conditions_simple(az_css_property_text_justify(LayoutTextJustify_InterWord))
    t3(8) = az_css_property_with_conditions_simple(az_css_property_vertical_align(az_style_vertical_align_middle()))
    t3(9) = az_css_property_with_conditions_simple(az_css_property_letter_spacing(AzStyleLetterSpacing(inner=az_pixel_value_px(0.5_c_float))))
    t3(10) = az_css_property_with_conditions_simple(az_css_property_text_indent(AzStyleTextIndent(inner=az_pixel_value_em(2.0_c_float), each_line=.false._c_bool, hanging=.false._c_bool)))
    t3(11) = az_css_property_with_conditions_simple(az_css_property_line_height(az_style_line_height_number(az_float_value_create(1.5_c_float))))
    t3(12) = az_css_property_with_conditions_simple(az_css_property_word_spacing(AzStyleWordSpacing(inner=az_pixel_value_px(4.0_c_float))))
    t3(13) = az_css_property_with_conditions_simple(az_css_property_tab_size(AzStyleTabSize(inner=az_pixel_value_em(4.0_c_float))))
    t3(14) = az_css_property_with_conditions_simple(az_css_property_user_select(StyleUserSelect_None))
    t3(15) = az_css_property_with_conditions_simple(az_css_property_text_decoration(StyleTextDecoration_Underline))
    t3(16) = az_css_property_with_conditions_simple(az_css_property_caret_color(AzCaretColor(inner=AzColorU(r_=-1_c_int8_t, g=0_c_int8_t, b=0_c_int8_t, a=-1_c_int8_t))))
    t3(17) = az_css_property_with_conditions_simple(az_css_property_caret_animation_duration(AzCaretAnimationDuration(inner=AzCssDuration(inner=500_c_int32_t, unit=CssDurationUnit_Milliseconds))))
    t3(18) = az_css_property_with_conditions_simple(az_css_property_selection_background_color(AzSelectionBackgroundColor(inner=AzColorU(r_=51_c_int8_t, g=-103_c_int8_t, b=-1_c_int8_t, a=-1_c_int8_t))))
    t3(19) = az_css_property_with_conditions_simple(az_css_property_selection_color(AzSelectionColor(inner=AzColorU(r_=-1_c_int8_t, g=-1_c_int8_t, b=-1_c_int8_t, a=-1_c_int8_t))))
    t3(20) = az_css_property_with_conditions_simple(az_css_property_font(az_style_font_family_vec_copy_from_ptr(c_loc(t2(1)), 2_c_size_t)))
    r = az_css_property_with_conditions_vec_copy_from_ptr(c_loc(t3(1)), 20_c_size_t)
  end function style_text

  ! CSS: .box
  ! dropped a value these bindings cannot build: `LayoutFloatValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutPaddingInlineStartValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutPaddingInlineEndValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutOverflowValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleScrollbarGutterValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleOverflowClipMarginValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleClipRectValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutWritingModeValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutClearValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleZoomValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleObjectFitValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleObjectPositionValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleAspectRatioValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  function style_box() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    type(AzCssPropertyWithConditions), target :: t1(27)
    t1(1) = az_css_property_with_conditions_simple(az_css_property_display(LayoutDisplay_Block))
    t1(2) = az_css_property_with_conditions_simple(az_css_property_box_sizing(LayoutBoxSizing_BorderBox))
    t1(3) = az_css_property_with_conditions_simple(az_css_property_width(az_layout_width_px(az_pixel_value_percent(50.0_c_float))))
    t1(4) = az_css_property_with_conditions_simple(az_css_property_height(az_layout_height_px(az_pixel_value_px(200.0_c_float))))
    t1(5) = az_css_property_with_conditions_simple(az_css_property_min_width(AzLayoutMinWidth(inner=az_pixel_value_em(10.0_c_float))))
    t1(6) = az_css_property_with_conditions_simple(az_css_property_min_height(AzLayoutMinHeight(inner=az_pixel_value_rem(1.0_c_float))))
    t1(7) = az_css_property_with_conditions_simple(az_css_property_max_width(AzLayoutMaxWidth(inner=az_pixel_value_px(800.0_c_float))))
    t1(8) = az_css_property_with_conditions_simple(az_css_property_max_height(AzLayoutMaxHeight(inner=az_pixel_value_from_metric(SizeMetric_Vh, 90.0_c_float))))
    t1(9) = az_css_property_with_conditions_simple(az_css_property_position(LayoutPosition_Absolute))
    t1(10) = az_css_property_with_conditions_simple(az_css_property_top(AzLayoutTop(inner=az_pixel_value_px(0.0_c_float))))
    t1(11) = az_css_property_with_conditions_simple(az_css_property_right(AzLayoutRight(inner=az_pixel_value_px(10.0_c_float))))
    t1(12) = az_css_property_with_conditions_simple(az_css_property_bottom(AzLayoutInsetBottom(inner=az_pixel_value_pt(5.0_c_float))))
    t1(13) = az_css_property_with_conditions_simple(az_css_property_left(AzLayoutLeft(inner=az_pixel_value_from_metric(SizeMetric_In, 1.0_c_float))))
    t1(14) = az_css_property_with_conditions_simple(az_css_property_z_index(az_layout_z_index_integer(10_c_int32_t)))
    t1(15) = az_css_property_with_conditions_simple(az_css_property_padding_top(AzLayoutPaddingTop(inner=az_pixel_value_px(1.0_c_float))))
    t1(16) = az_css_property_with_conditions_simple(az_css_property_padding_right(AzLayoutPaddingRight(inner=az_pixel_value_px(2.0_c_float))))
    t1(17) = az_css_property_with_conditions_simple(az_css_property_padding_bottom(AzLayoutPaddingBottom(inner=az_pixel_value_px(3.0_c_float))))
    t1(18) = az_css_property_with_conditions_simple(az_css_property_padding_left(AzLayoutPaddingLeft(inner=az_pixel_value_px(4.0_c_float))))
    t1(19) = az_css_property_with_conditions_simple(az_css_property_margin_top(AzLayoutMarginTop(inner=az_pixel_value_px(7.0_c_float))))
    t1(20) = az_css_property_with_conditions_simple(az_css_property_margin_right(AzLayoutMarginRight(inner=az_pixel_value_px(8.0_c_float))))
    t1(21) = az_css_property_with_conditions_simple(az_css_property_margin_bottom(AzLayoutMarginBottom(inner=az_pixel_value_px(9.0_c_float))))
    t1(22) = az_css_property_with_conditions_simple(az_css_property_auto(CssPropertyType_MarginLeft))
    t1(23) = az_css_property_with_conditions_simple(az_css_property_overflow_x(LayoutOverflow_Hidden))
    t1(24) = az_css_property_with_conditions_simple(az_css_property_overflow_y(LayoutOverflow_Scroll))
    t1(25) = az_css_property_with_conditions_simple(az_css_property_visibility(StyleVisibility_Hidden))
    t1(26) = az_css_property_with_conditions_simple(az_css_property_opacity(AzStyleOpacity(inner=AzPercentageValue(number=az_float_value_create(50.0_c_float)))))
    t1(27) = az_css_property_with_conditions_simple(az_css_property_cursor(StyleCursor_Pointer))
    r = az_css_property_with_conditions_vec_copy_from_ptr(c_loc(t1(1)), 27_c_size_t)
  end function style_box

  ! CSS: .flex
  ! dropped a value these bindings cannot build: `LayoutFlexBasisValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutColumnGapValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutRowGapValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  function style_flex() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    type(AzCssPropertyWithConditions), target :: t1(8)
    t1(1) = az_css_property_with_conditions_simple(az_css_property_flex_wrap(LayoutFlexWrap_Wrap))
    t1(2) = az_css_property_with_conditions_simple(az_css_property_flex_direction(LayoutFlexDirection_Column))
    t1(3) = az_css_property_with_conditions_simple(az_css_property_flex_grow(AzLayoutFlexGrow(inner=az_float_value_create(2.0_c_float))))
    t1(4) = az_css_property_with_conditions_simple(az_css_property_flex_shrink(AzLayoutFlexShrink(inner=az_float_value_create(0.5_c_float))))
    t1(5) = az_css_property_with_conditions_simple(az_css_property_justify_content(LayoutJustifyContent_SpaceBetween))
    t1(6) = az_css_property_with_conditions_simple(az_css_property_align_items(LayoutAlignItems_Center))
    t1(7) = az_css_property_with_conditions_simple(az_css_property_align_content(LayoutAlignContent_Stretch))
    t1(8) = az_css_property_with_conditions_simple(az_css_property_align_self(LayoutAlignSelf_End))
    r = az_css_property_with_conditions_vec_copy_from_ptr(c_loc(t1(1)), 8_c_size_t)
  end function style_flex

  ! CSS: .grid
  ! dropped `grid-auto-rows: minmax(10px, 100fr)`: grid `minmax()` tracks hold raw pointers in the C ABI and cannot be built from the bindings
  ! dropped a value these bindings cannot build: `LayoutGridTemplateColumnsValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutGridTemplateRowsValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutGridAutoColumnsValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutGridAutoRowsValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutGridColumnValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutGridRowValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutGridTemplateAreasValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutRowGapValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutColumnGapValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  function style_grid() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    type(AzCssPropertyWithConditions), target :: t1(3)
    t1(1) = az_css_property_with_conditions_simple(az_css_property_grid_auto_flow(LayoutGridAutoFlow_Column))
    t1(2) = az_css_property_with_conditions_simple(az_css_property_justify_self(LayoutJustifySelf_Center))
    t1(3) = az_css_property_with_conditions_simple(az_css_property_justify_items(LayoutJustifyItems_Start))
    r = az_css_property_with_conditions_vec_copy_from_ptr(c_loc(t1(1)), 3_c_size_t)
  end function style_grid

  ! CSS: .borders
  function style_borders() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    type(AzCssPropertyWithConditions), target :: t1(20)
    t1(1) = az_css_property_with_conditions_simple(az_css_property_border_top_left_radius(AzStyleBorderTopLeftRadius(inner=az_pixel_value_px(4.0_c_float))))
    t1(2) = az_css_property_with_conditions_simple(az_css_property_border_top_right_radius(AzStyleBorderTopRightRadius(inner=az_pixel_value_px(5.0_c_float))))
    t1(3) = az_css_property_with_conditions_simple(az_css_property_border_bottom_left_radius(AzStyleBorderBottomLeftRadius(inner=az_pixel_value_px(6.0_c_float))))
    t1(4) = az_css_property_with_conditions_simple(az_css_property_border_bottom_right_radius(AzStyleBorderBottomRightRadius(inner=az_pixel_value_px(7.0_c_float))))
    t1(5) = az_css_property_with_conditions_simple(az_css_property_border_top_color(AzStyleBorderTopColor(inner=AzColorU(r_=17_c_int8_t, g=17_c_int8_t, b=17_c_int8_t, a=-1_c_int8_t))))
    t1(6) = az_css_property_with_conditions_simple(az_css_property_border_right_color(AzStyleBorderRightColor(inner=AzColorU(r_=34_c_int8_t, g=34_c_int8_t, b=34_c_int8_t, a=-1_c_int8_t))))
    t1(7) = az_css_property_with_conditions_simple(az_css_property_border_bottom_color(AzStyleBorderBottomColor(inner=AzColorU(r_=51_c_int8_t, g=51_c_int8_t, b=51_c_int8_t, a=-1_c_int8_t))))
    t1(8) = az_css_property_with_conditions_simple(az_css_property_border_left_color(AzStyleBorderLeftColor(inner=AzColorU(r_=68_c_int8_t, g=68_c_int8_t, b=68_c_int8_t, a=-1_c_int8_t))))
    t1(9) = az_css_property_with_conditions_simple(az_css_property_border_top_style(AzStyleBorderTopStyle(inner=BorderStyle_Solid)))
    t1(10) = az_css_property_with_conditions_simple(az_css_property_border_right_style(AzStyleBorderRightStyle(inner=BorderStyle_Dashed)))
    t1(11) = az_css_property_with_conditions_simple(az_css_property_border_bottom_style(AzStyleBorderBottomStyle(inner=BorderStyle_Dotted)))
    t1(12) = az_css_property_with_conditions_simple(az_css_property_border_left_style(AzStyleBorderLeftStyle(inner=BorderStyle_Double)))
    t1(13) = az_css_property_with_conditions_simple(az_css_property_border_top_width(AzLayoutBorderTopWidth(inner=az_pixel_value_px(1.0_c_float))))
    t1(14) = az_css_property_with_conditions_simple(az_css_property_border_right_width(AzLayoutBorderRightWidth(inner=az_pixel_value_px(2.0_c_float))))
    t1(15) = az_css_property_with_conditions_simple(az_css_property_border_bottom_width(AzLayoutBorderBottomWidth(inner=az_pixel_value_px(3.0_c_float))))
    t1(16) = az_css_property_with_conditions_simple(az_css_property_border_left_width(AzLayoutBorderLeftWidth(inner=az_pixel_value_px(4.0_c_float))))
    t1(17) = az_css_property_with_conditions_simple(az_css_property_box_shadow_left(AzStyleBoxShadow(offset_x=AzPixelValueNoPercent(inner=az_pixel_value_px(0.0_c_float)), offset_y=AzPixelValueNoPercent(inner=az_pixel_value_px(2.0_c_float)), blur_radius=AzPixelValueNoPercent(inner=az_pixel_value_px(4.0_c_float)), spread_radius=AzPixelValueNoPercent(inner=az_pixel_value_px(1.0_c_float)), clip_mode=BoxShadowClipMode_Outset, color=AzColorU(r_=0_c_int8_t, g=0_c_int8_t, b=0_c_int8_t, a=64_c_int8_t))))
    t1(18) = az_css_property_with_conditions_simple(az_css_property_box_shadow_right(AzStyleBoxShadow(offset_x=AzPixelValueNoPercent(inner=az_pixel_value_px(0.0_c_float)), offset_y=AzPixelValueNoPercent(inner=az_pixel_value_px(2.0_c_float)), blur_radius=AzPixelValueNoPercent(inner=az_pixel_value_px(4.0_c_float)), spread_radius=AzPixelValueNoPercent(inner=az_pixel_value_px(1.0_c_float)), clip_mode=BoxShadowClipMode_Outset, color=AzColorU(r_=0_c_int8_t, g=0_c_int8_t, b=0_c_int8_t, a=64_c_int8_t))))
    t1(19) = az_css_property_with_conditions_simple(az_css_property_box_shadow_top(AzStyleBoxShadow(offset_x=AzPixelValueNoPercent(inner=az_pixel_value_px(0.0_c_float)), offset_y=AzPixelValueNoPercent(inner=az_pixel_value_px(2.0_c_float)), blur_radius=AzPixelValueNoPercent(inner=az_pixel_value_px(4.0_c_float)), spread_radius=AzPixelValueNoPercent(inner=az_pixel_value_px(1.0_c_float)), clip_mode=BoxShadowClipMode_Outset, color=AzColorU(r_=0_c_int8_t, g=0_c_int8_t, b=0_c_int8_t, a=64_c_int8_t))))
    t1(20) = az_css_property_with_conditions_simple(az_css_property_box_shadow_bottom(AzStyleBoxShadow(offset_x=AzPixelValueNoPercent(inner=az_pixel_value_px(0.0_c_float)), offset_y=AzPixelValueNoPercent(inner=az_pixel_value_px(2.0_c_float)), blur_radius=AzPixelValueNoPercent(inner=az_pixel_value_px(4.0_c_float)), spread_radius=AzPixelValueNoPercent(inner=az_pixel_value_px(1.0_c_float)), clip_mode=BoxShadowClipMode_Outset, color=AzColorU(r_=0_c_int8_t, g=0_c_int8_t, b=0_c_int8_t, a=64_c_int8_t))))
    r = az_css_property_with_conditions_vec_copy_from_ptr(c_loc(t1(1)), 20_c_size_t)
  end function style_borders

  ! CSS: .scroll
  ! dropped a value these bindings cannot build: `StyleBackgroundContentValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `LayoutScrollbarWidthValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleScrollbarColorValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `OverscrollBehaviorValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `ScrollbarVisibilityModeValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `ScrollbarFadeDelayValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `ScrollbarFadeDurationValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleAppRegionValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleSpatialNavigationActionValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleSpatialNavigationContainValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleSpatialNavigationFunctionValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  function style_scroll() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    r = az_css_property_with_conditions_vec_create()
  end function style_scroll

  ! CSS: .effects
  ! dropped `text-shadow: 1px 1px 2px`: CssProperty::TextShadow holds a BoxOrStaticStyleBoxShadow (a pointer wrapper) and api.json has no constructor for it
  ! dropped a value these bindings cannot build: `StyleFilterVecValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  ! dropped a value these bindings cannot build: `StyleMixBlendModeValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  function style_effects() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    type(AzStyleBackgroundContent), target :: t1(1)
    type(AzStyleBackgroundPosition), target :: t2(1)
    type(AzStyleBackgroundSize), target :: t3(1)
    type(AzStyleBackgroundRepeat), target :: t4(1)
    type(AzStyleTransform), target :: t5(1)
    type(AzCssPropertyWithConditions), target :: t6(9)
    t1(1) = az_style_background_content_color(AzColorU(r_=-6_c_int8_t, g=-6_c_int8_t, b=-6_c_int8_t, a=-1_c_int8_t))
    t2(1) = AzStyleBackgroundPosition(horizontal=az_background_position_horizontal_center(), vertical=az_background_position_vertical_center())
    t3(1) = az_style_background_size_cover()
    t4(1) = StyleBackgroundRepeat_NoRepeat
    t5(1) = az_style_transform_rotate(AzAngleValue(metric=AngleMetric_Degree, number=az_float_value_create(45.0_c_float)))
    t6(1) = az_css_property_with_conditions_simple(az_css_property_background_content(az_style_background_content_vec_copy_from_ptr(c_loc(t1(1)), 1_c_size_t)))
    t6(2) = az_css_property_with_conditions_simple(az_css_property_background_position(az_style_background_position_vec_copy_from_ptr(c_loc(t2(1)), 1_c_size_t)))
    t6(3) = az_css_property_with_conditions_simple(az_css_property_background_size(az_style_background_size_vec_copy_from_ptr(c_loc(t3(1)), 1_c_size_t)))
    t6(4) = az_css_property_with_conditions_simple(az_css_property_background_repeat(az_style_background_repeat_vec_copy_from_ptr(c_loc(t4(1)), 1_c_size_t)))
    t6(5) = az_css_property_with_conditions_simple(az_css_property_background_clip(StyleBackgroundClip_PaddingBox))
    t6(6) = az_css_property_with_conditions_simple(az_css_property_transform(az_style_transform_vec_copy_from_ptr(c_loc(t5(1)), 1_c_size_t)))
    t6(7) = az_css_property_with_conditions_simple(az_css_property_transform_origin(AzStyleTransformOrigin(x=az_pixel_value_percent(50.0_c_float), y=az_pixel_value_percent(50.0_c_float))))
    t6(8) = az_css_property_with_conditions_simple(az_css_property_perspective_origin(AzStylePerspectiveOrigin(x=az_pixel_value_px(10.0_c_float), y=az_pixel_value_px(20.0_c_float))))
    t6(9) = az_css_property_with_conditions_simple(az_css_property_backface_visibility(StyleBackfaceVisibility_Hidden))
    r = az_css_property_with_conditions_vec_copy_from_ptr(c_loc(t6(1)), 9_c_size_t)
  end function style_effects

  ! CSS: .fragment
  function style_fragment() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    type(AzCssPropertyWithConditions), target :: t1(15)
    t1(1) = az_css_property_with_conditions_simple(az_css_property_break_before(PageBreak_Page))
    t1(2) = az_css_property_with_conditions_simple(az_css_property_break_after(PageBreak_Avoid))
    t1(3) = az_css_property_with_conditions_simple(az_css_property_break_inside(BreakInside_Avoid))
    t1(4) = az_css_property_with_conditions_simple(az_css_property_orphans(AzOrphans(inner=2_c_int32_t)))
    t1(5) = az_css_property_with_conditions_simple(az_css_property_widows(AzWidows(inner=3_c_int32_t)))
    t1(6) = az_css_property_with_conditions_simple(az_css_property_box_decoration_break(BoxDecorationBreak_Clone))
    t1(7) = az_css_property_with_conditions_simple(az_css_property_column_count(az_column_count_integer(3_c_int32_t)))
    t1(8) = az_css_property_with_conditions_simple(az_css_property_column_width(az_column_width_length(az_pixel_value_px(200.0_c_float))))
    t1(9) = az_css_property_with_conditions_simple(az_css_property_column_span(ColumnSpan_All))
    t1(10) = az_css_property_with_conditions_simple(az_css_property_column_fill(ColumnFill_Balance))
    t1(11) = az_css_property_with_conditions_simple(az_css_property_column_rule_width(AzColumnRuleWidth(inner=az_pixel_value_px(1.0_c_float))))
    t1(12) = az_css_property_with_conditions_simple(az_css_property_column_rule_style(AzColumnRuleStyle(inner=BorderStyle_Solid)))
    t1(13) = az_css_property_with_conditions_simple(az_css_property_column_rule_color(AzColumnRuleColor(inner=AzColorU(r_=-52_c_int8_t, g=-52_c_int8_t, b=-52_c_int8_t, a=-1_c_int8_t))))
    t1(14) = az_css_property_with_conditions_simple(az_css_property_flow_into(az_flow_into_named(azul_string('article'))))
    t1(15) = az_css_property_with_conditions_simple(az_css_property_flow_from(az_flow_from_named(azul_string('article'))))
    r = az_css_property_with_conditions_vec_copy_from_ptr(c_loc(t1(1)), 15_c_size_t)
  end function style_fragment

  ! CSS: .shape
  function style_shape() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    type(AzCssPropertyWithConditions), target :: t1(5)
    t1(1) = az_css_property_with_conditions_simple(az_css_property_shape_outside(az_shape_outside_shape(az_css_shape_circle(AzShapeCircle(center=AzShapePoint(x=0.0_c_float, y=0.0_c_float), radius=50.0_c_float)))))
    t1(2) = az_css_property_with_conditions_simple(az_css_property_shape_inside(az_shape_inside_shape(az_css_shape_circle(AzShapeCircle(center=AzShapePoint(x=50.0_c_float, y=50.0_c_float), radius=100.0_c_float)))))
    t1(3) = az_css_property_with_conditions_simple(az_css_property_clip_path(az_clip_path_shape(az_css_shape_circle(AzShapeCircle(center=AzShapePoint(x=0.0_c_float, y=0.0_c_float), radius=40.0_c_float)))))
    t1(4) = az_css_property_with_conditions_simple(az_css_property_shape_margin(AzShapeMargin(inner=az_pixel_value_px(10.0_c_float))))
    t1(5) = az_css_property_with_conditions_simple(az_css_property_shape_image_threshold(AzShapeImageThreshold(inner=az_float_value_create(0.5_c_float))))
    r = az_css_property_with_conditions_vec_copy_from_ptr(c_loc(t1(1)), 5_c_size_t)
  end function style_shape

  ! CSS: .table
  function style_table() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    type(AzCssPropertyWithConditions), target :: t1(5)
    t1(1) = az_css_property_with_conditions_simple(az_css_property_table_layout(LayoutTableLayout_Fixed))
    t1(2) = az_css_property_with_conditions_simple(az_css_property_border_collapse(StyleBorderCollapse_Collapse))
    t1(3) = az_css_property_with_conditions_simple(az_css_property_border_spacing(AzLayoutBorderSpacing(horizontal=az_pixel_value_px(2.0_c_float), vertical=az_pixel_value_px(4.0_c_float))))
    t1(4) = az_css_property_with_conditions_simple(az_css_property_caption_side(StyleCaptionSide_Bottom))
    t1(5) = az_css_property_with_conditions_simple(az_css_property_empty_cells(StyleEmptyCells_Hide))
    r = az_css_property_with_conditions_vec_copy_from_ptr(c_loc(t1(1)), 5_c_size_t)
  end function style_table

  ! CSS: .content
  function style_content() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    type(AzCssPropertyWithConditions), target :: t1(6)
    t1(1) = az_css_property_with_conditions_simple(az_css_property_content(AzContent(inner=azul_string('"Hello"'))))
    t1(2) = az_css_property_with_conditions_simple(az_css_property_counter_reset(AzCounterReset(counter_name=azul_string('section'), value_=1_c_int32_t)))
    t1(3) = az_css_property_with_conditions_simple(az_css_property_counter_increment(AzCounterIncrement(counter_name=azul_string('section'), value_=1_c_int32_t)))
    t1(4) = az_css_property_with_conditions_simple(az_css_property_list_style_type(StyleListStyleType_UpperRoman))
    t1(5) = az_css_property_with_conditions_simple(az_css_property_list_style_position(StyleListStylePosition_Inside))
    t1(6) = az_css_property_with_conditions_simple(az_css_property_string_set(AzStringSet(inner=azul_string('title "Chapter"'))))
    r = az_css_property_with_conditions_vec_copy_from_ptr(c_loc(t1(1)), 6_c_size_t)
  end function style_content

  ! CSS: .anim
  ! dropped a value these bindings cannot build: `StyleAnimationVecValue` is an ABI-opaque blob in the Fortran bindings (no constructor)
  function style_anim() result(r)
    type(AzCssPropertyWithConditionsVec) :: r
    r = az_css_property_with_conditions_vec_create()
  end function style_anim

end module azul_styles
