<?php
// examples/php/hello-world.php
//
// PHP port of examples/c/hello-world.c using the autogenerated FFI
// bindings produced by `lang_php/`.
//
// Same data model (a `MyDataModel` struct with a uint32 counter), same
// callback semantics (mouse click increments, layout rebuilds the DOM).
//
// Requirements:
//   * PHP 7.4 or newer
//   * `ffi` extension enabled in php.ini:
//
//         ffi.enable=true
//
//     (or `ffi.enable=preload` if you wire OPcache preloading)
//
//   * `libazul.so` / `libazul.dylib` / `azul.dll` reachable by the
//     dynamic loader.
//
// Run via:
//
//     php -d ffi.enable=true hello-world.php

declare(strict_types=1);

require_once __DIR__ . '/Azul.php';

use Azul\Azul;
use Azul\App;
use Azul\Button;
use Azul\Dom;
use Azul\WindowCreateOptions;

// ── PHP-FFI lifetime caveat ────────────────────────────────────────────
//
// `FFI::cast(...)` on a PHP closure produces a cdata function-pointer
// that must remain reachable from PHP for the lifetime of the C-side
// reference. If the cdata is collected, the next call into it from C
// jumps into freed memory. We therefore stash every casted callback in
// a module-level array so it stays referenced for the whole process.
$liveCallbacks = [];

/**
 * Cast a PHP callable to a named FFI function-pointer type and pin
 * the resulting cdata for the rest of the process.
 */
function makeCallback(string $cType, callable $fn)
{
    global $liveCallbacks;
    $cb = Azul::lib()->cast($cType, $fn);
    $liveCallbacks[] = $cb;
    return $cb;
}

// ── Data model ────────────────────────────────────────────────────────
//
// We declare the MyDataModel struct as part of the *user-side* cdef. It
// does not need to live in the shared azul.h cdef because the framework
// only ever sees an opaque AzRefAny.

Azul::lib()->cdef("typedef struct { uint32_t counter; } MyDataModel;", '');
// SKIPPED: Azul::lib()->cdef(...) only works on FFI handles obtained via
// FFI::cdef() at top level. The line above is documentation of intent;
// the working approach is to declare MyDataModel against a separate FFI
// handle. For the hello-world we keep it minimal and embed the struct
// definition through a sibling FFI instance:

$userFfi = FFI::cdef("typedef struct { uint32_t counter; } MyDataModel;");

// Stable RTTI id for the data model. Any 64-bit value works as long as
// no other RefAny in this process collides with it.
const MY_DATA_MODEL_RTTI_ID = 0xA2010001;

/** Destructor stub — MyDataModel owns no heap memory. */
$modelDestructor = makeCallback('AzRefAnyDestructorType', function ($_ptr): void {
    // intentionally empty
});

/**
 * Upcast a PHP-allocated MyDataModel into an AzRefAny.
 */
function upcastModel($model, $modelDestructor)
{
    global $userFfi;
    $ffi = Azul::lib();
    $name = 'MyDataModel';
    $bytes = FFI::new("uint8_t[" . strlen($name) . "]");
    for ($i = 0, $n = strlen($name); $i < $n; $i++) {
        $bytes[$i] = ord($name[$i]);
    }
    $nameStr = $ffi->AzString_copyFromBytes(
        FFI::cast('const uint8_t*', FFI::addr($bytes[0])),
        0,
        strlen($name)
    );
    return $ffi->AzRefAny_newC(
        FFI::cast('void*', FFI::addr($model)),
        FFI::sizeof($model),
        FFI::alignof($model),
        MY_DATA_MODEL_RTTI_ID,
        $nameStr,
        $modelDestructor
    );
}

/**
 * Borrow a *mut MyDataModel from a RefAny. Returns null on RTTI mismatch.
 */
function downcastMut($refany)
{
    global $userFfi;
    $ffi = Azul::lib();
    if (!$ffi->AzRefAny_isType($refany, MY_DATA_MODEL_RTTI_ID)) {
        return null;
    }
    $raw = $ffi->AzRefAny_getDataPtr($refany);
    return FFI::cast('MyDataModel*', $raw);
}

// ── Callback: button click ────────────────────────────────────────────

$onClick = function ($data, $info) {
    $ffi = Azul::lib();
    $m = downcastMut($data);
    if ($m === null) {
        return $ffi->AzUpdate_DoNothing;
    }
    $m->counter = $m->counter + 1;
    return $ffi->AzUpdate_RefreshDom;
};
$onClickCb = makeCallback('AzCallbackType', $onClick);

// ── Callback: layout ──────────────────────────────────────────────────

$layout = function ($data, $info) use (&$onClickCb) {
    $ffi = Azul::lib();
    $m = downcastMut($data);
    if ($m === null) {
        return $ffi->AzDom_createBody();
    }

    // Counter label, wrapped in a div so it lays out as block-level.
    $buf = (string) $m->counter;
    $bytes = FFI::new("uint8_t[" . strlen($buf) . "]");
    for ($i = 0, $n = strlen($buf); $i < $n; $i++) {
        $bytes[$i] = ord($buf[$i]);
    }
    $txt = $ffi->AzString_copyFromBytes(
        FFI::cast('const uint8_t*', FFI::addr($bytes[0])),
        0,
        strlen($buf)
    );
    $label = $ffi->AzDom_createText($txt);
    $labelWrapper = $ffi->AzDom_createDiv();
    $ffi->AzDom_addCssProperty(
        FFI::addr($labelWrapper),
        $ffi->AzCssPropertyWithConditions_simple(
            $ffi->AzCssProperty_fontSize($ffi->AzStyleFontSize_px(32.0))
        )
    );
    $ffi->AzDom_addChild(FFI::addr($labelWrapper), $label);

    // Button.
    $btnLabel = 'Increase counter';
    $btnBytes = FFI::new("uint8_t[" . strlen($btnLabel) . "]");
    for ($i = 0, $n = strlen($btnLabel); $i < $n; $i++) {
        $btnBytes[$i] = ord($btnLabel[$i]);
    }
    $btnText = $ffi->AzString_copyFromBytes(
        FFI::cast('const uint8_t*', FFI::addr($btnBytes[0])),
        0,
        strlen($btnLabel)
    );
    $button = $ffi->AzButton_create($btnText);
    $ffi->AzButton_setButtonType(FFI::addr($button), $ffi->AzButtonType_Primary);
    $dataClone = $ffi->AzRefAny_clone($data);
    $ffi->AzButton_setOnClick(FFI::addr($button), $dataClone, $onClickCb);
    $buttonDom = $ffi->AzButton_dom($button);

    // Body.
    $body = $ffi->AzDom_createBody();
    $ffi->AzDom_addChild(FFI::addr($body), $labelWrapper);
    $ffi->AzDom_addChild(FFI::addr($body), $buttonDom);

    return $ffi->AzDom_style($body, $ffi->AzCss_empty());
};
$layoutCb = makeCallback('AzLayoutCallbackType', $layout);

// ── Main ──────────────────────────────────────────────────────────────

$ffi = Azul::lib();
$model = $userFfi->new('MyDataModel');
$model->counter = 5;

$data = upcastModel($model, $modelDestructor);

$window = $ffi->AzWindowCreateOptions_create($layoutCb);

// Set window title.
$titleStr = 'Hello World';
$titleBytes = FFI::new("uint8_t[" . strlen($titleStr) . "]");
for ($i = 0, $n = strlen($titleStr); $i < $n; $i++) {
    $titleBytes[$i] = ord($titleStr[$i]);
}
$window->window_state->title = $ffi->AzString_copyFromBytes(
    FFI::cast('const uint8_t*', FFI::addr($titleBytes[0])),
    0,
    strlen($titleStr)
);
$window->window_state->size->dimensions->width = 400.0;
$window->window_state->size->dimensions->height = 300.0;

// NoTitleAutoInject: OS draws close/min/max buttons; framework
// auto-injects a Titlebar with drag support.
$window->window_state->flags->decorations = $ffi->AzWindowDecorations_NoTitleAutoInject;
$window->window_state->flags->background_material = $ffi->AzWindowBackgroundMaterial_Sidebar;

// Use the idiomatic wrapper for App so the destructor wires up
// AzApp_delete via PHP's __destruct() automatically.
$app = App::create($data, $ffi->AzAppConfig_create());
$app->run($window);
// $app falls out of scope at end-of-script — App::__destruct() fires
// AzApp_delete on its underlying cdata.
