//! Pascal (Free Pascal / Lazarus) binding generator.
//!
//! Generates a single `azul.pas` unit file that:
//!
//! 1. Declares all C-ABI types as Pascal `record` definitions (POD/blittable),
//!    Pascal enums for unit-only enumerations, and variant records for
//!    tagged unions.
//! 2. Forward-declares typed pointers (`PAzFoo = ^TAzFoo;`) at the top of
//!    the type block so all later `record` and `external` declarations may
//!    refer to them in any order.
//! 3. Declares every C-API function as a `cdecl; external 'azul';` import
//!    using the verbatim `Az` prefix so the linker can match symbol names.
//! 4. Wraps every type that owns heap memory (i.e. has a matching
//!    `<TypeName>_delete` C function) in an idiomatic Pascal `class` whose
//!    `destructor Destroy; override;` calls the matching `_delete`. The
//!    user calls `obj.Free;` and the destructor fires automatically.
//!
//! # Output structure (high-level)
//!
//! ```pascal
//! unit Azul;
//! {$mode objfpc}{$H+}
//! {$PACKRECORDS C}
//!
//! interface
//! uses ctypes;
//!
//! const
//!   AzulLib = 'azul';
//!
//! type
//!   { Forward pointer declarations }
//!   PAzApp = ^TAzApp;
//!   PAzDom = ^TAzDom;
//!   { ... }
//!
//!   { POD records }
//!   TAzAppConfig = record ... end;
//!
//!   { Unit enums }
//!   TAzButtonType = (TAzButtonType_Primary, TAzButtonType_Secondary, ...);
//!
//!   { Variant records (tagged unions) }
//!   TAzOptionI64 = record case Tag: TAzOptionI64Tag of ... end;
//!
//! { External declarations }
//! function AzApp_create(data: TAzRefAny; config: TAzAppConfig): TAzApp; cdecl; external AzulLib;
//! procedure AzApp_run(app: PAzApp; window: TAzWindowCreateOptions); cdecl; external AzulLib;
//! procedure AzApp_delete(app: PAzApp); cdecl; external AzulLib;
//!
//! { Idiomatic wrapper classes }
//! type
//!   TApp = class
//!   private
//!     FRaw: TAzApp;
//!   public
//!     constructor Create(data: TAzRefAny; config: TAzAppConfig);
//!     destructor Destroy; override;
//!     procedure Run(window: TAzWindowCreateOptions);
//!   end;
//!
//! implementation
//! { ... method bodies ... }
//! end.
//! ```
//!
//! # Wiring
//!
//! This module is intentionally *not* wired from `v2/mod.rs` yet. The
//! orchestrator is responsible for adding `pub mod lang_pascal;` and a
//! `pub fn generate_pascal(api_data) -> Result<String>` helper that
//! mirrors `generate_python` and is invoked from
//! `GenerationTargets::generate_all`.

use anyhow::Result;

use super::config::CodegenConfig;
use super::generator::CodeBuilder;
use super::ir::CodegenIR;

pub mod functions;
pub mod lpi;
pub mod types;
pub mod wrappers;

/// Library name used in `external 'azul';`.
///
/// Matches the prebuilt artifact's name without extension; FPC resolves
/// this to `azul.dll` on Windows, `libazul.so` on Linux, and
/// `libazul.dylib` on macOS.
pub const LIB_NAME: &str = "azul";

/// Public entry point. Produces the full `azul.pas` unit as a `String`.
///
/// The caller is expected to write the result to disk (e.g.
/// `target/codegen/v2/azul.pas`) and to separately emit the accompanying
/// Lazarus `.lpi` project via [`lpi::generate_lpi`].
pub fn generate(ir: &CodegenIR, config: &CodegenConfig) -> Result<String> {
    let mut builder = CodeBuilder::new("  ");

    // File banner
    emit_header(&mut builder);

    // Unit declaration + compiler directives
    builder.line("unit Azul;");
    builder.blank();
    builder.line("{$mode objfpc}{$H+}");
    builder.line("{$PACKRECORDS C}");
    builder.line("{$MACRO ON}");
    builder.blank();

    // === interface section ===
    builder.line("interface");
    builder.blank();
    builder.line("uses ctypes;");
    builder.blank();

    // Library name constant
    builder.line("const");
    builder.indent();
    builder.line(&format!("AzulLib = '{}';", LIB_NAME));
    builder.dedent();
    builder.blank();

    // 1. Type forward declarations + record/enum/variant-record definitions
    types::generate_types(&mut builder, ir, config)?;

    // 2. External cdecl function declarations
    functions::generate_externals(&mut builder, ir, config)?;

    // 3. Idiomatic class wrappers (interface side)
    wrappers::generate_wrapper_interface(&mut builder, ir, config)?;

    // === implementation section ===
    builder.blank();
    builder.line("implementation");
    builder.blank();

    // Wrapper method bodies
    wrappers::generate_wrapper_implementation(&mut builder, ir, config)?;

    builder.line("end.");

    Ok(builder.finish())
}

fn emit_header(builder: &mut CodeBuilder) {
    builder.line("{ ============================================================================");
    builder.line("  Auto-generated Pascal (FPC/Lazarus) bindings for the Azul GUI framework.");
    builder.line("  Generated by azul-doc codegen v2 (lang_pascal).");
    builder.line("  DO NOT EDIT MANUALLY.");
    builder.line("");
    builder.line("  Compatible with Free Pascal Compiler 3.2+ in {$mode objfpc}.");
    builder.line("  The {$PACKRECORDS C} directive is critical: it forces C-ABI struct");
    builder.line("  layout so values passed by value match the Rust extern \"C\" ABI.");
    builder.line("  ============================================================================ }");
    builder.blank();
}

// ============================================================================
// Shared type-name helpers (used by submodules)
// ============================================================================

/// The Az-prefixed FFI type name for a given IR type (e.g. `Dom` -> `AzDom`).
pub fn ffi_type_name(name: &str) -> String {
    format!("Az{}", name)
}

/// The Pascal record type name for a given IR type (e.g. `Dom` -> `TAzDom`).
///
/// FPC convention prefixes user-defined record types with `T` so that
/// pointer aliases can use `P` without collision.
pub fn record_type_name(name: &str) -> String {
    format!("T{}", ffi_type_name(name))
}

/// The Pascal pointer-type name for a given IR type (e.g. `Dom` -> `PAzDom`).
pub fn pointer_type_name(name: &str) -> String {
    format!("P{}", ffi_type_name(name))
}

/// Map a Rust/IR type name to its Pascal equivalent.
///
/// Pointers and references are turned into the matching `PAzFoo` typed
/// pointer when the inner type is a known IR type, or `Pointer` (untyped)
/// otherwise. Primitives map to `ctypes` aliases (`cint32`, `cfloat`, ...)
/// so the binding is correct on both 32- and 64-bit hosts.
pub fn map_type_to_pascal(rust_type: &str, ir: &CodegenIR) -> String {
    let trimmed = rust_type.trim();

    // Pointers and references — turn into a typed P-pointer when possible.
    if let Some(rest) = trimmed.strip_prefix("*const ") {
        return ptr_to_pascal(rest, ir);
    }
    if let Some(rest) = trimmed.strip_prefix("*mut ") {
        return ptr_to_pascal(rest, ir);
    }
    if let Some(rest) = trimmed.strip_prefix("&mut ") {
        return ptr_to_pascal(rest, ir);
    }
    if let Some(rest) = trimmed.strip_prefix('&') {
        return ptr_to_pascal(rest, ir);
    }

    // Arrays: `[T; N]` -> `array[0..N-1] of <PascalT>`
    if trimmed.starts_with('[') && trimmed.ends_with(']') {
        let inner = &trimmed[1..trimmed.len() - 1];
        if let Some(semi) = inner.rfind(';') {
            let elem = inner[..semi].trim();
            if let Ok(count) = inner[semi + 1..].trim().parse::<usize>() {
                let pas_elem = map_type_to_pascal(elem, ir);
                if count == 0 {
                    return format!("array[0..0] of {}", pas_elem);
                }
                return format!("array[0..{}] of {}", count - 1, pas_elem);
            }
        }
    }

    match trimmed {
        // Void / unit
        "void" | "c_void" | "()" => "Pointer".to_string(),

        // Booleans
        "bool" | "GLboolean" => "cbool".to_string(),

        // Signed / unsigned integers via ctypes (size-correct on all platforms)
        "i8" | "c_char" | "char" => "cint8".to_string(),
        "u8" | "c_uchar" => "cuint8".to_string(),
        "i16" => "cint16".to_string(),
        "u16" => "cuint16".to_string(),
        "i32" | "c_int" | "GLint" | "GLsizei" => "cint32".to_string(),
        "u32" | "c_uint" | "GLuint" | "GLenum" | "GLbitfield" => "cuint32".to_string(),
        "i64" | "GLint64" => "cint64".to_string(),
        "u64" | "GLuint64" => "cuint64".to_string(),
        "f32" | "GLfloat" | "GLclampf" => "cfloat".to_string(),
        "f64" | "GLdouble" | "GLclampd" => "cdouble".to_string(),
        "usize" | "size_t" | "uintptr_t" => "csize_t".to_string(),
        "isize" | "ssize_t" | "intptr_t" | "GLsizeiptr" | "GLintptr" => "cssize_t".to_string(),

        // Anything else: assume it's a known IR type and emit a record name.
        _ => {
            if ir.find_struct(trimmed).is_some()
                || ir.find_enum(trimmed).is_some()
                || ir.find_type_alias(trimmed).is_some()
                || ir.callback_typedefs.iter().any(|c| c.name == trimmed)
            {
                record_type_name(trimmed)
            } else {
                // Unknown -> opaque pointer.
                "Pointer".to_string()
            }
        }
    }
}

/// Helper: turn `<inner>` (the part after `*const`/`*mut`/`&`/`&mut`) into a
/// Pascal pointer expression. Tries the typed `PAzFoo` when the inner is a
/// known IR type; falls back to `PChar` for `c_char`/`char` and to plain
/// untyped `Pointer` otherwise.
fn ptr_to_pascal(inner: &str, ir: &CodegenIR) -> String {
    let inner = inner.trim();
    match inner {
        "c_char" | "char" | "i8" | "u8" => "PChar".to_string(),
        "c_void" | "void" | "()" => "Pointer".to_string(),
        _ => {
            if ir.find_struct(inner).is_some()
                || ir.find_enum(inner).is_some()
                || ir.find_type_alias(inner).is_some()
            {
                pointer_type_name(inner)
            } else {
                "Pointer".to_string()
            }
        }
    }
}

/// Sanitize a name for use as a Pascal identifier. Pascal reserved words
/// get a trailing underscore; this keeps the symbol unambiguous without
/// shadowing FPC keywords.
pub fn sanitize_identifier(name: &str) -> String {
    if is_pascal_reserved(name) {
        return format!("{}_", name);
    }
    name.to_string()
}

/// Pascal reserved words (FPC + Object Pascal). Subset that's likely to
/// collide with field/argument names in api.json.
fn is_pascal_reserved(name: &str) -> bool {
    matches!(
        name,
        "absolute"
            | "and"
            | "array"
            | "as"
            | "asm"
            | "begin"
            | "case"
            | "class"
            | "const"
            | "constructor"
            | "destructor"
            | "div"
            | "do"
            | "downto"
            | "else"
            | "end"
            | "except"
            | "exports"
            | "external"
            | "file"
            | "finalization"
            | "finally"
            | "for"
            | "function"
            | "goto"
            | "if"
            | "implementation"
            | "in"
            | "inherited"
            | "initialization"
            | "inline"
            | "interface"
            | "is"
            | "label"
            | "library"
            | "mod"
            | "nil"
            | "not"
            | "object"
            | "of"
            | "on"
            | "operator"
            | "or"
            | "out"
            | "packed"
            | "procedure"
            | "program"
            | "property"
            | "raise"
            | "record"
            | "repeat"
            | "resourcestring"
            | "self"
            | "set"
            | "shl"
            | "shr"
            | "string"
            | "then"
            | "threadvar"
            | "to"
            | "try"
            | "type"
            | "unit"
            | "until"
            | "uses"
            | "var"
            | "while"
            | "with"
            | "xor"
    )
}

/// Convert a snake_case or lowerCamelCase name to PascalCase (idiomatic
/// Pascal method names use PascalCase / CamelCase like the rest of the
/// language).
pub fn to_pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper_next = true;
    for c in s.chars() {
        if c == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}
