//! The passphrase generator's word list: 1024 short, common English words (3 to 8 letters, lower
//! case ASCII, no two alike), so every word adds exactly 10 bits. Sorted, so a word is found by
//! binary search.

/// The words.
pub const WORDS: [&str; 1024] = [
    "able", "acid", "acorn", "acre", "actor", "adapt", "adult", "aero", "agent", "agile", "aglow",
    "agree", "ahead", "airy", "aisle", "alarm", "album", "alert", "algae", "alien", "alive",
    "alley", "allow", "alloy", "aloft", "alpha", "alpine", "amber", "amend", "amid", "amigo",
    "ample", "anchor", "angel", "angle", "ankle", "annex", "anvil", "apple", "april", "apron",
    "aqua", "arbor", "arch", "area", "arena", "argue", "armor", "army", "aroma", "arrow", "artist",
    "ascot", "ashen", "aside", "aspen", "atlas", "atom", "atop", "attic", "audio", "audit", "aunt",
    "auto", "autumn", "avenue", "avid", "avocado", "awake", "award", "axis", "axle", "bacon",
    "badge", "bagel", "baker", "balloon", "balmy", "bamboo", "banana", "banjo", "barge", "barley",
    "barn", "baron", "basil", "basin", "batch", "baton", "bazaar", "beach", "beacon", "beagle",
    "beard", "beaver", "beetle", "bench", "berry", "bike", "birch", "bison", "blade", "blank",
    "blaze", "blend", "bliss", "block", "bloom", "blossom", "blue", "blunt", "board", "boat",
    "bobcat", "bonfire", "bonus", "boost", "booth", "border", "bottle", "boulder", "bounce",
    "bouquet", "brain", "brave", "bread", "breadth", "breeze", "brick", "bridge", "brief",
    "bright", "brisk", "brook", "broom", "brunch", "brush", "bubble", "bucket", "buckle", "buddy",
    "budget", "buffalo", "bugle", "bundle", "bunker", "bunny", "burrow", "butter", "button",
    "buzzer", "cabbage", "cabin", "cable", "cactus", "cadet", "camel", "cameo", "camera", "canal",
    "candle", "candy", "canoe", "canvas", "canyon", "caramel", "cargo", "carol", "carpet",
    "carrot", "cart", "cashew", "castle", "catfish", "cattle", "cavern", "cedar", "celery",
    "cello", "cement", "chalk", "chamber", "chapel", "charm", "chart", "cheese", "cheetah",
    "cherry", "chess", "chest", "chick", "chime", "chimney", "chorus", "cider", "cinema", "circle",
    "citrus", "civic", "clam", "clamp", "clay", "clever", "cliff", "climb", "clock", "cloud",
    "clover", "coach", "coast", "cobalt", "cocoa", "coconut", "coffee", "collar", "comet", "comic",
    "compass", "condor", "cookie", "copper", "coral", "cord", "corn", "cotton", "couch", "cougar",
    "cousin", "cove", "cozy", "crab", "cradle", "crane", "crater", "crayon", "cream", "creek",
    "cricket", "crisp", "cross", "crown", "cruise", "crumb", "crystal", "cube", "cupcake",
    "curtain", "curve", "custard", "cycle", "cymbal", "daisy", "dance", "dawn", "decal", "decoy",
    "delta", "denim", "depot", "desert", "desk", "dial", "diary", "diesel", "dinner", "disco",
    "dish", "dive", "dock", "dolphin", "domain", "donut", "dove", "dragon", "drama", "drift",
    "drill", "drum", "duck", "dune", "dusk", "duvet", "dwarf", "eagle", "earring", "easel", "echo",
    "eclipse", "edge", "eel", "eggnog", "elbow", "elder", "elegant", "elephant", "elk", "elm",
    "ember", "emblem", "emerald", "empire", "emu", "enamel", "engine", "enjoy", "envoy", "epic",
    "equal", "essay", "estate", "ether", "exact", "expert", "fabric", "facet", "fairy", "falcon",
    "fame", "fancy", "farm", "fawn", "feast", "feather", "fence", "ferry", "fiber", "fiddle",
    "field", "fig", "film", "finch", "fjord", "flag", "flame", "flamingo", "flannel", "flask",
    "fleet", "flint", "flora", "flour", "flute", "foam", "focus", "fog", "folio", "forest",
    "forge", "fossil", "fox", "fresco", "frog", "frost", "fruit", "fudge", "funnel", "fuse",
    "gadget", "galaxy", "gallery", "gallon", "garage", "garden", "garlic", "garnet", "gate",
    "gazebo", "gecko", "gem", "genie", "giant", "ginger", "giraffe", "glacier", "glade", "glass",
    "glider", "glitter", "globe", "glove", "glow", "gnome", "goat", "goblet", "gold", "golf",
    "gondola", "goose", "gorilla", "gospel", "gourd", "grain", "granite", "grape", "graph",
    "grass", "gravel", "gravy", "green", "grid", "grill", "grove", "guava", "guest", "guide",
    "guitar", "gull", "gumbo", "gumdrop", "gust", "habit", "haiku", "hallway", "hammer", "hammock",
    "hamster", "harbor", "harp", "harvest", "hatch", "haven", "hawk", "hazel", "heart", "hedge",
    "helium", "helmet", "hero", "heron", "highway", "hiking", "hilltop", "hippo", "hobby", "honey",
    "hoop", "horizon", "horn", "horse", "hotel", "hound", "hug", "humble", "hummus", "hut", "hymn",
    "iceberg", "icicle", "icon", "idea", "igloo", "image", "impact", "inch", "index", "indigo",
    "inlet", "input", "insect", "iris", "iron", "island", "ivory", "ivy", "jacket", "jade",
    "jaguar", "jam", "jar", "jasmine", "javelin", "jazz", "jeans", "jelly", "jester", "jet",
    "jewel", "jigsaw", "jockey", "jogger", "joke", "journal", "joy", "judge", "juice", "jumbo",
    "jungle", "juniper", "jury", "kale", "kangaroo", "kayak", "kazoo", "kebab", "kelp", "kennel",
    "kernel", "ketchup", "kettle", "keyboard", "kilt", "kimono", "kind", "king", "kingdom",
    "kiosk", "kitchen", "kite", "kitten", "kiwi", "knee", "knight", "knot", "koala", "label",
    "ladder", "ladle", "lagoon", "lake", "lamb", "lamp", "lantern", "lapel", "laptop", "larch",
    "laser", "latch", "lava", "lawn", "layer", "leaf", "ledge", "lemon", "lens", "leopard",
    "letter", "lettuce", "level", "lever", "lilac", "lily", "lime", "linen", "lion", "liquid",
    "lizard", "llama", "lobby", "lobster", "locket", "lodge", "lotus", "lucky", "lumber", "lunar",
    "lunch", "lute", "lyric", "macaw", "magnet", "mailbox", "maize", "mammoth", "mango", "manor",
    "maple", "marble", "margin", "marina", "market", "marmot", "marsh", "mascot", "mason",
    "meadow", "medal", "melody", "melon", "memo", "mentor", "merit", "mesa", "metal", "meteor",
    "mill", "mimic", "mint", "mirror", "mitten", "moat", "mocha", "model", "mohair", "monk",
    "moose", "mosaic", "moss", "motel", "motor", "mountain", "mouse", "muffin", "mural", "museum",
    "mushroom", "mussel", "myth", "nacho", "napkin", "narrow", "native", "navy", "nectar",
    "needle", "nephew", "nest", "nickel", "night", "nimble", "noble", "nomad", "noodle", "north",
    "notch", "novel", "nugget", "nurse", "nutmeg", "nylon", "oasis", "oat", "oatmeal", "oboe",
    "ocean", "octave", "octopus", "office", "olive", "omelet", "onion", "onyx", "opal", "opera",
    "orange", "orbit", "orchid", "organ", "origin", "osprey", "ostrich", "otter", "outfit", "oval",
    "oven", "owl", "oxygen", "oyster", "paddle", "pagoda", "palace", "palm", "pancake", "panda",
    "panel", "panther", "papaya", "parade", "parcel", "parrot", "parsley", "pasta", "pastel",
    "patio", "pause", "peach", "peacock", "peanut", "pear", "pebble", "pecan", "pedal", "pelican",
    "pencil", "penguin", "pepper", "petal", "piano", "picnic", "pigeon", "pillow", "pilot", "pine",
    "pioneer", "pirate", "pitch", "pixel", "pizza", "planet", "plank", "plaza", "plum", "plume",
    "plywood", "pocket", "poem", "polar", "pollen", "pond", "pony", "popcorn", "poppy", "porch",
    "portal", "potato", "pottery", "prairie", "pretzel", "prism", "pulse", "pumpkin", "puppet",
    "puzzle", "pyramid", "quail", "quake", "quart", "quarter", "quartz", "queen", "quest",
    "quiche", "quiet", "quill", "quilt", "quince", "quiver", "quota", "rabbit", "raccoon", "radar",
    "radio", "radish", "raft", "rain", "rainbow", "raisin", "rally", "ramp", "ranch", "raven",
    "razor", "recipe", "reef", "relic", "remedy", "rhino", "rhythm", "ribbon", "rice", "riddle",
    "ridge", "ring", "ripple", "river", "road", "robin", "robot", "rocket", "rodeo", "roof",
    "rooftop", "rose", "rover", "royal", "ruby", "rudder", "rugby", "ruler", "rumba", "runway",
    "rustic", "saddle", "saffron", "saga", "sage", "sail", "salad", "salmon", "salsa", "salt",
    "sandal", "sandbox", "sardine", "satin", "sauce", "sauna", "savanna", "scallop", "scarf",
    "scene", "scholar", "scone", "scout", "scroll", "sculpt", "seagull", "seal", "season", "seed",
    "sequel", "sesame", "shadow", "shark", "shelf", "shell", "sherpa", "shield", "ship", "shore",
    "shrimp", "siesta", "signal", "silk", "silver", "siren", "skate", "sketch", "ski", "skylark",
    "skyline", "slate", "sled", "slope", "smile", "smoke", "snail", "snow", "snowman", "soap",
    "sofa", "solar", "sonnet", "soup", "spark", "sparrow", "spice", "spider", "spinach", "sponge",
    "spoon", "spring", "sprout", "spruce", "squash", "squid", "squirrel", "stable", "stadium",
    "stamp", "star", "statue", "steam", "steel", "stem", "stone", "stork", "storm", "stove",
    "straw", "stream", "studio", "sugar", "summit", "sun", "sundial", "sunset", "surf", "swan",
    "sweater", "swift", "symbol", "syrup", "table", "taco", "talent", "tango", "tank", "target",
    "tavern", "teacup", "teapot", "tempo", "tennis", "tent", "terrace", "thistle", "thread",
    "thunder", "ticket", "tide", "tiger", "timber", "toast", "toffee", "tomato", "toolbox",
    "topaz", "torch", "totem", "towel", "tower", "tractor", "trail", "train", "trellis", "trophy",
    "trout", "truffle", "trumpet", "tugboat", "tulip", "tundra", "tunnel", "turkey", "turnip",
    "turtle", "tuxedo", "twig", "twin", "ukulele", "umbrella", "uncle", "unicorn", "union", "unit",
    "upland", "urban", "urchin", "utensil", "vacuum", "valley", "valve", "vanilla", "vanity",
    "vapor", "vase", "velvet", "vendor", "venture", "verse", "vessel", "vest", "viking", "villa",
    "vine", "violet", "violin", "visor", "vista", "vivid", "vocal", "volcano", "voyage", "waffle",
    "wagon", "walkway", "wallet", "walnut", "walrus", "wand", "warmth", "warthog", "wasabi",
    "water", "wave", "wax", "weasel", "weaver", "wedge", "weekend", "whale", "wheat", "wheel",
    "whisk", "whistle", "widget", "wildcat", "willow", "window", "winter", "wizard", "wolf",
    "wombat", "wonder", "woods", "wool", "world", "wren", "wrist", "xenon", "yacht", "yak", "yard",
    "yarn", "yeast", "yellow", "yeti", "yodel", "yogurt", "yolk", "young", "yucca", "yummy",
    "zebra", "zenith", "zephyr", "zero", "zigzag", "zinc", "zipper", "zircon", "zodiac", "zone",
    "zoom",
];
