// Generated by azul-css codegen (Kotlin). Do not edit by hand.
package com.azul

import com.sun.jna.Memory
import com.sun.jna.Pointer
import com.sun.jna.Structure

// CSS: .btn, .btn:hover
fun styleBtn(): AzCssPropertyWithConditionsVec.ByValue {
    return azVec(
        AzulNativeVec::AzCssPropertyWithConditionsVec_copyFromPtr,
        AzulNativeCss.AzCssPropertyWithConditions_simple(AzulNativeCss.AzCssProperty_width(AzulNativeCss.AzLayoutWidth_px(AzulNativeCss.AzPixelValue_px(100.0f)))),
        AzulNativeCss.AzCssPropertyWithConditions_simple(AzulNativeCss.AzCssProperty_textColor(AzStyleTextColor.ByValue().apply { inner = AzColorU.ByValue().apply { r = 255.toByte(); g = 0.toByte(); b = 0.toByte(); a = 255.toByte() } })),
        AzulNativeCss.AzCssPropertyWithConditions_simple(AzulNativeCss.AzCssProperty_display(LayoutDisplay.Flex.value)),
        AzulNativeCss.AzCssPropertyWithConditions_simple(AzulNativeCss.AzCssProperty_flexGrow(AzLayoutFlexGrow.ByValue().apply { inner = AzulNativeCss.AzFloatValue_create(1.0f) })),
        AzulNativeCss.AzCssPropertyWithConditions_simple(AzulNativeCss.AzCssProperty_inherit(CssPropertyType.MinWidth.value)),
        AzulNativeCss.AzCssPropertyWithConditions_simple(AzulNativeCss.AzCssProperty_whiteSpace(AzStyleWhiteSpaceValue.ByValue().apply { Exact.tag = AzStyleWhiteSpaceValue_Tag.Exact.value.toByte(); Exact.payload = StyleWhiteSpace.Nowrap.value; setType("Exact") })),
        AzulNativeCss.AzCssPropertyWithConditions_onHover(AzulNativeCss.AzCssProperty_fontWeight(StyleFontWeight.Bold.value))
    )
}

// Copies the items into native memory; AzXxxVec_copyFromPtr clones them.
internal fun <V> azVec(copy: (Pointer?, Long) -> V, vararg items: Structure): V {
    val size = items[0].size()
    val mem = Memory(size.toLong() * items.size)
    items.forEachIndexed { i, item ->
        item.write()
        mem.write(i.toLong() * size, item.pointer.getByteArray(0, size), 0, size)
    }
    return copy(mem, items.size.toLong())
}

// The same for a Vec of C-like enum values.
internal fun <V> azVecInts(copy: (Pointer?, Long) -> V, vararg items: Int): V {
    val mem = Memory(4L * items.size)
    items.forEachIndexed { i, item -> mem.setInt(4L * i, item) }
    return copy(mem, items.size.toLong())
}

internal fun azStr(s: String): AzString.ByValue {
    val bytes = s.toByteArray(Charsets.UTF_8)
    val mem = Memory(maxOf(1, bytes.size).toLong())
    mem.write(0, bytes, 0, bytes.size)
    return AzulNativeStr.AzString_fromUtf8(mem, bytes.size.toLong())
}
