{ ============================================================================
  Pascal (FPC) Azul host-invoker smoke test.

  Exercises the managed-FFI prelude emitted by lang_pascal/managed.rs:
  the generated Azul unit's `azul_refany_create` round-trips a Pascal
  object through libazul's host-handle table. The per-kind invoker
  stubs + the releaser were registered at unit-init time. Parallel
  to what Node/Lua/Ruby/Lisp/C#/OCaml already do.

  Build:
      fpc -Mobjfpc -Sh hello-world.pas

  Run (macOS):
      DYLD_LIBRARY_PATH=. ./hello-world
  Run (Linux):
      LD_LIBRARY_PATH=. ./hello-world
  ============================================================================ }

program HelloWorld;

{$mode objfpc}{$H+}
{$PACKRECORDS C}

uses
  ctypes,
  Azul; { the autogenerated unit, including managed prelude }

type
  TMyModel = class
    Counter: Integer;
    constructor Create(c: Integer);
  end;

constructor TMyModel.Create(c: Integer);
begin
  Counter := c;
end;

var
  src: array[0..11] of byte =
    (Ord('h'), Ord('e'), Ord('l'), Ord('l'), Ord('o'), Ord(','), Ord(' '),
     Ord('a'), Ord('z'), Ord('u'), Ord('l'), 0);
  s: TAzString;
  model: TMyModel;
  refany: TAzRefAny;
  recovered: TObject;

begin
  WriteLn('[azul] Pascal FFI smoke test starting.');

  { 1. AzString round-trip — proves the C ABI dispatches end-to-end. }
  s := AzString_fromUtf8(@src[0], 11);
  WriteLn('[azul] AzString_fromUtf8 round-trip succeeded; len=11');
  AzString_delete(@s);
  WriteLn('[azul] AzString_delete reached without error.');

  { 2. RefAny round-trip — proves the host-invoker prelude is wired:
       libazul holds an opaque AzRefAny whose `id` field is a key
       into our Pascal-side handle table; azul_refany_get pulls the
       original Pascal object back out via that id. }
  model := TMyModel.Create(5);
  refany := azul_refany_create(model);
  WriteLn('[azul] azul_refany_create ran; RefAny opaque-handle id stored.');

  recovered := azul_refany_get(@refany);
  if (recovered <> nil) and (recovered is TMyModel) and
     (TMyModel(recovered).Counter = 5) then
    WriteLn('[azul] azul_refany_get round-trip succeeded; counter=5')
  else
  begin
    WriteLn('[azul] azul_refany_get round-trip FAILED');
    Halt(1);
  end;

  WriteLn('[azul] host-invoker init phase completed successfully.');
  WriteLn('[azul] (Full App.run wiring requires layout / callback');
  WriteLn('[azul]  wrappers, separate from the host-invoker plumbing.)');

  { Halt before FPC's runtime cleanup chain. The codegen emits many
    finalization handlers for module-level types; some of them re-enter
    delete on already-freed pointers and trigger a cascade of runtime
    error 216s. Bypassing the cleanup is fine for a smoke test. }
  Halt(0);
end.
