-- Generated by azul-css codegen (Haskell). Do not edit by hand.
module Styles (styleHero, styleHalo, styleDial, stylePhoto, styleCaption) where

import Azul
import qualified Azul.Types as T
import qualified Azul.CssPropertyWithConditions as CssPropertyWithConditions

-- CSS: .hero
-- dropped a value these bindings cannot build: a StyleBackgroundContentVec has no pure constructor in Azul.Types
-- dropped a value these bindings cannot build: a StyleTransformVec has no pure constructor in Azul.Types
-- dropped a value these bindings cannot build: a StyleFilterVec has no pure constructor in Azul.Types
-- dropped a value these bindings cannot build: a StyleFilterVec has no pure constructor in Azul.Types
styleHero :: IO [CssPropertyWithConditions]
styleHero = sequence
  [
    (CssPropertyWithConditions.simple (T.CssProperty_BoxShadowLeft (T.StyleBoxShadowValue_Exact (T.StyleBoxShadow (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 0))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 4000))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 12000))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 2000))) T.BoxShadowClipMode_Outset (T.ColorU 0 0 0 77))))),
    (CssPropertyWithConditions.simple (T.CssProperty_BoxShadowRight (T.StyleBoxShadowValue_Exact (T.StyleBoxShadow (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 0))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 4000))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 12000))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 2000))) T.BoxShadowClipMode_Outset (T.ColorU 0 0 0 77))))),
    (CssPropertyWithConditions.simple (T.CssProperty_BoxShadowTop (T.StyleBoxShadowValue_Exact (T.StyleBoxShadow (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 0))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 4000))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 12000))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 2000))) T.BoxShadowClipMode_Outset (T.ColorU 0 0 0 77))))),
    (CssPropertyWithConditions.simple (T.CssProperty_BoxShadowBottom (T.StyleBoxShadowValue_Exact (T.StyleBoxShadow (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 0))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 4000))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 12000))) (T.PixelValueNoPercent (T.PixelValue T.SizeMetric_Px (T.FloatValue 2000))) T.BoxShadowClipMode_Outset (T.ColorU 0 0 0 77)))))
  ]

-- CSS: .halo
-- dropped a value these bindings cannot build: a StyleBackgroundContentVec has no pure constructor in Azul.Types
styleHalo :: IO [CssPropertyWithConditions]
styleHalo = sequence
  []

-- CSS: .dial
-- dropped a value these bindings cannot build: a StyleBackgroundContentVec has no pure constructor in Azul.Types
styleDial :: IO [CssPropertyWithConditions]
styleDial = sequence
  []

-- CSS: .photo
-- dropped a value these bindings cannot build: a StyleBackgroundContentVec has no pure constructor in Azul.Types
-- dropped a value these bindings cannot build: a StyleBackgroundSizeVec has no pure constructor in Azul.Types
-- dropped a value these bindings cannot build: a StyleBackgroundPositionVec has no pure constructor in Azul.Types
-- dropped a value these bindings cannot build: a StyleBackgroundRepeatVec has no pure constructor in Azul.Types
stylePhoto :: IO [CssPropertyWithConditions]
stylePhoto = sequence
  []

-- CSS: .caption
-- dropped a value these bindings cannot build: a StyleFontFamilyVec has no pure constructor in Azul.Types
-- dropped a value these bindings cannot build: an AzString has no pure constructor in Azul.Types
styleCaption :: IO [CssPropertyWithConditions]
styleCaption = sequence
  []
