#!/usr/bin/env perl
#
# Manual port of examples/c/hello-world.c using the autogenerated Perl
# bindings (see doc/src/codegen/v2/lang_perl/). The data flow is identical:
# a single-counter model is upcast into a RefAny, the layout callback
# rebuilds the DOM each frame, and the button click increments the counter
# and asks for a redraw.
#
# Run with:
#     cpanm --installdeps .
#     perl -Ilib hello-world.pl
#
# `lib/` is expected to contain the generated `Azul.pm` (the orchestrator
# wires this up at `target/codegen/v2/perl/lib/Azul.pm` once the codegen
# step has run; symlink or set PERL5LIB if your output lives elsewhere).

use strict;
use warnings;
use FindBin qw($Bin);
use lib "$Bin/../../target/codegen/v2/perl/lib";
use lib "$Bin/lib";

use Azul;

# Convenient short aliases. We deliberately do NOT `use Azul ':all'` --
# Perl's `String` is just a package name (no built-in clash like Ruby), but
# being explicit keeps the call sites readable.
use constant {
    Update_DoNothing   => Azul::AzUpdate::DoNothing,
    Update_RefreshDom  => Azul::AzUpdate::RefreshDom,
};

# -- Data model ---------------------------------------------------------

# Plain Perl hash holder. Native code only ever sees the upcast RefAny;
# this hashref is just somewhere to keep the counter during callbacks.
my $model = { counter => 5 };

# -- Callback: button click --------------------------------------------

my $on_click = sub {
    my ($data, $info) = @_;
    # downcast_mut would normally come from the Azul::MyDataModel helper
    # generated by AZ_REFLECT_JSON; for this hand-port we just bump the
    # captured Perl hash directly.
    $model->{counter}++;
    return Update_RefreshDom;
};

# -- Callback: layout (rebuilds DOM each frame) ------------------------

my $layout = sub {
    my ($data, $info) = @_;

    # Counter label (wrapped in a div so the font-size sticks)
    my $label_text = Azul::String->copy_from_string("$model->{counter}");
    my $label = Azul::Dom->create_text($label_text);
    my $label_wrapper = Azul::Dom->create_div();
    $label_wrapper->add_css_property(
        Azul::CssPropertyWithConditions->simple(
            Azul::CssProperty->font_size(
                Azul::StyleFontSize->px(32.0)
            )
        )
    );
    $label_wrapper->add_child($label);

    # Increment button
    my $button = Azul::Button->create(
        Azul::String->copy_from_string('Increase counter')
    );
    $button->set_button_type(Azul::AzButtonType::Primary);
    $button->set_on_click(Azul::RefAny->clone($data), $on_click);
    my $button_dom = $button->dom();

    # Body
    my $body = Azul::Dom->create_body();
    $body->add_child($label_wrapper);
    $body->add_child($button_dom);
    return $body->style(Azul::Css->empty());
};

# -- Main --------------------------------------------------------------

my $data = Azul::RefAny->new_from_perl($model);

my $window = Azul::WindowCreateOptions->create($layout);
$window->window_state->title(
    Azul::String->copy_from_string('Hello World')
);
$window->window_state->size->dimensions->width(400.0);
$window->window_state->size->dimensions->height(300.0);

# NoTitleAutoInject: OS draws close/min/max buttons,
# framework auto-injects a Titlebar with drag support.
$window->window_state->flags->decorations(
    Azul::AzWindowDecorations::NoTitleAutoInject
);
$window->window_state->flags->background_material(
    Azul::AzWindowBackgroundMaterial::Sidebar
);

my $app = Azul::App->create($data, Azul::AppConfig->create());
$app->run($window);

# $app falls out of scope here; DESTROY calls Azul::FFI::AzApp_delete.
exit 0;
