//! PHP extension generator v2 — host-invoker tier.
//!
//! Emits `target/codegen/php_api.rs`, a Rust source file `include!`'d
//! by `dll/src/php_extension.rs` under the `php-extension` Cargo
//! feature. The generated file uses `ext-php-rs` macros
//! (`#[php_function]`, `#[php_module]`, `wrap_function!`) to expose
//! libazul as a native Zend-engine extension.
//!
//! ## Why a separate generator (vs. inline-hand-written)
//!
//! Mirrors the Python extension's `lang_python.rs` → `python_api.rs`
//! split. Hand-coding the host-invoker primitives is fine for ~5
//! functions; the Dom builder + App.run + per-widget callback
//! factories add ~hundreds more, all derivable from the IR. Keeping
//! the surface inside `php_extension.rs` (as Phase 47 did) doesn't
//! scale — the generator owns the IR→#[php_function] mapping so
//! adding a callback kind upstream lights up the PHP side
//! automatically.
//!
//! ## Generated surface (Phase 48 scope)
//!
//! Phase 48 generates just the host-invoker primitives + a per-kind
//! `azul_register_<wrapper>_callback` thunk that wires libazul's
//! invoker setter from PHP-supplied callables. Future sub-phases
//! extend to Dom builders, App.run, and typed wrappers — each
//! sub-phase is a discrete IR pass + smoke-test cycle.

use anyhow::Result;

use super::generator::CodeBuilder;
use super::ir::CodegenIR;
use super::managed_host_invoker::{has_return, host_invoker_kinds, wrapper_name};

/// Header banner emitted at the top of `php_api.rs`. Marks the file
/// as autogenerated and explains how to regenerate.
const HEADER: &str = "\
// WARNING: autogenerated PHP/Zend extension bindings for azul api
// Generated for ext-php-rs by azul-doc codegen v2.
// This file is included via include!() in dll/src/php_extension.rs.
// Regenerate with:
//     cd doc && cargo run --release -- codegen all
// DO NOT EDIT MANUALLY — changes will be overwritten.
";

/// Generate the contents of `target/codegen/php_api.rs`.
///
/// The output is a Rust source fragment (not a full crate): it
/// expects `use ext_php_rs::prelude::*;` and the host-invoker C-ABI
/// externs to be in scope at the include site. `php_extension.rs`
/// supplies both before the `include!()` call.
pub fn generate(ir: &CodegenIR) -> Result<String> {
    let mut builder = CodeBuilder::new("    ");

    builder.line(HEADER);
    builder.blank();

    emit_handle_table(&mut builder);
    emit_releaser(&mut builder);

    emit_primitive_functions(&mut builder);

    for cb in host_invoker_kinds(ir) {
        emit_callback_kind_helpers(&mut builder, cb);
    }

    emit_get_module(&mut builder, ir);

    Ok(builder.finish())
}

/// The handle table the PHP side uses to store user values
/// (JSON-encoded) keyed by the host-handle id libazul stamps onto
/// each RefAny.
fn emit_handle_table(builder: &mut CodeBuilder) {
    builder.line("// ------------------------------------------------------------------------");
    builder.line("// Handle table — keyed by the host-handle id libazul stamps onto");
    builder.line("// each AzRefAny. Values are JSON snapshots; the Phase 49 codegen");
    builder.line("// switches to a refcount-rooted Azul\\RefAny class.");
    builder.line("// ------------------------------------------------------------------------");
    builder.line("static HANDLES: ::once_cell::sync::Lazy<::std::sync::Mutex<::std::collections::HashMap<u64, String>>> =");
    builder.line(
        "    ::once_cell::sync::Lazy::new(|| ::std::sync::Mutex::new(::std::collections::HashMap::new()));",
    );
    builder
        .line("static NEXT_HANDLE_ID: ::once_cell::sync::Lazy<::std::sync::Mutex<u64>> =");
    builder.line("    ::once_cell::sync::Lazy::new(|| ::std::sync::Mutex::new(0));");
    builder.blank();
}

/// The C-ABI releaser libazul fires when the last RefAny clone of
/// a host-handle drops. Removes the entry from `HANDLES` so the
/// JSON snapshot doesn't leak.
fn emit_releaser(builder: &mut CodeBuilder) {
    builder.line("/// Drop the handle table entry for `id`. Called by libazul on");
    builder.line("/// the last-clone destructor of a host-handle RefAny.");
    builder.line("unsafe extern \"C\" fn host_handle_releaser(id: u64) {");
    builder.indent();
    builder.line("if let Ok(mut tbl) = HANDLES.lock() {");
    builder.indent();
    builder.line("tbl.remove(&id);");
    builder.dedent();
    builder.line("}");
    builder.dedent();
    builder.line("}");
    builder.blank();
}

/// The three #[php_function]s that constitute the host-invoker
/// surface on the PHP side: refany_create / refany_get /
/// host_invoker_init.
fn emit_primitive_functions(builder: &mut CodeBuilder) {
    builder.line("/// PHP function: `azul_version() : string`.");
    builder.line("#[::ext_php_rs::prelude::php_function]");
    builder.line("pub fn azul_version() -> &'static str {");
    builder.indent();
    builder.line("\"0.0.7\"");
    builder.dedent();
    builder.line("}");
    builder.blank();

    builder.line("/// PHP function: `azul_refany_create(string $json) : int`.");
    builder.line("///");
    builder.line("/// Allocates a host-handle id for `$json` and stores the JSON");
    builder.line("/// snapshot. Recovery via `azul_refany_get`.");
    builder.line("#[::ext_php_rs::prelude::php_function]");
    builder.line("pub fn azul_refany_create(value: String) -> u64 {");
    builder.indent();
    builder.line("let mut next = NEXT_HANDLE_ID.lock().unwrap();");
    builder.line("*next += 1;");
    builder.line("let id = *next;");
    builder.line("HANDLES.lock().unwrap().insert(id, value);");
    builder.line("id");
    builder.dedent();
    builder.line("}");
    builder.blank();

    builder.line("/// PHP function: `azul_refany_get(int $id) : ?string`.");
    builder.line("///");
    builder.line("/// Returns the JSON snapshot previously stored under `$id`, or");
    builder.line("/// `null` if the id has been released by libazul's destructor.");
    builder.line("#[::ext_php_rs::prelude::php_function]");
    builder.line("pub fn azul_refany_get(id: u64) -> Option<String> {");
    builder.indent();
    builder.line("HANDLES.lock().unwrap().get(&id).cloned()");
    builder.dedent();
    builder.line("}");
    builder.blank();

    builder.line("/// PHP function: `azul_host_invoker_init() : void`.");
    builder.line("///");
    builder.line("/// Idempotent — installs the host-handle releaser with libazul.");
    builder.line("/// Per-kind invoker registration follows in the kind-specific");
    builder.line("/// `azul_register_<wrapper>_callback` helpers below.");
    builder.line("#[::ext_php_rs::prelude::php_function]");
    builder.line("pub fn azul_host_invoker_init() {");
    builder.indent();
    builder.line("unsafe {");
    builder.indent();
    builder.line("AzApp_setHostHandleReleaser(Some(host_handle_releaser));");
    builder.dedent();
    builder.line("}");
    builder.dedent();
    builder.line("}");
    builder.blank();
}

/// Per callback kind, emit a stub `azul_register_<wrapper>_callback`
/// PHP function that takes an id (the handle in HANDLES) and returns
/// the Az<Wrapper> struct id-only (no libffi closure yet — Zend
/// callable→fnpointer marshalling needs an `Arg::callable()` accept
/// + libffi dispatch which we wire in Phase 49). For now this is a
/// stub that records intent and keeps the generator → emit shape
/// stable across iterations.
fn emit_callback_kind_helpers(
    builder: &mut CodeBuilder,
    cb: &super::ir::CallbackTypedefDef,
) {
    let wrapper = wrapper_name(cb);
    let fn_name = callback_helper_fn_name(&wrapper);
    let _ = has_return(cb); // Reserved for Phase 49 — return-arity-aware dispatch.

    builder.line(&format!(
        "/// PHP function stub: `{fn_name}(int $handle_id) : int`.",
        fn_name = fn_name
    ));
    builder.line("///");
    builder.line(
        "/// Phase 48 stub — accepts a handle id (PHP side stashes the callable",
    );
    builder.line(
        "/// in HANDLES via azul_refany_create) and returns it unchanged so the",
    );
    builder.line(&format!(
        "/// PHP caller can pass it back through the Az{wrapper}_createFromHostHandle",
        wrapper = wrapper
    ));
    builder.line(
        "/// path once libffi-closure-from-Zend-callable marshalling lands. Keeps",
    );
    builder.line("/// the codegen-to-extension wiring testable end-to-end today.");
    builder.line("#[::ext_php_rs::prelude::php_function]");
    builder.line(&format!(
        "pub fn {fn_name}(handle_id: u64) -> u64 {{",
        fn_name = fn_name
    ));
    builder.indent();
    builder.line("handle_id");
    builder.dedent();
    builder.line("}");
    builder.blank();
}

/// Map a wrapper name (PascalCase, e.g. "Callback", "LayoutCallback",
/// "ButtonOnClick") to the PHP function name. Strips a trailing
/// "Callback" suffix from the wrapper to avoid emitting
/// `azul_register_callback_callback`.
fn callback_helper_fn_name(wrapper: &str) -> String {
    // If the wrapper IS "Callback" verbatim, emit `azul_register_callback`
    // (otherwise we'd get the ugly `azul_register_callback_callback`).
    // Otherwise strip a trailing "Callback" suffix and append our own,
    // so "LayoutCallback" → "azul_register_layout_callback".
    if wrapper == "Callback" {
        return "azul_register_callback".to_string();
    }
    let base = wrapper.strip_suffix("Callback").unwrap_or(wrapper);
    format!("azul_register_{}_callback", camel_to_snake(base))
}

/// The `#[php_module]` entry point. Registers every #[php_function]
/// emitted above via `wrap_function!`. Without this PHP loads the
/// extension successfully but `get_extension_funcs('azul-dll')`
/// returns an empty array.
fn emit_get_module(builder: &mut CodeBuilder, ir: &CodegenIR) {
    builder.line("/// Zend entry point. PHP calls this once at extension load to");
    builder.line("/// build the function table. Every #[php_function] must be");
    builder.line("/// registered here via wrap_function!.");
    builder.line("#[::ext_php_rs::prelude::php_module]");
    builder.line(
        "pub fn get_module(module: ::ext_php_rs::builders::ModuleBuilder) -> ::ext_php_rs::builders::ModuleBuilder {",
    );
    builder.indent();
    builder.line("module");
    builder.indent();
    builder.line(".function(::ext_php_rs::wrap_function!(azul_version))");
    builder.line(".function(::ext_php_rs::wrap_function!(azul_refany_create))");
    builder.line(".function(::ext_php_rs::wrap_function!(azul_refany_get))");
    builder.line(".function(::ext_php_rs::wrap_function!(azul_host_invoker_init))");
    for cb in host_invoker_kinds(ir) {
        let fn_name = callback_helper_fn_name(wrapper_name(cb));
        builder.line(&format!(
            ".function(::ext_php_rs::wrap_function!({fn_name}))",
            fn_name = fn_name
        ));
    }
    builder.dedent();
    builder.dedent();
    builder.line("}");
    builder.blank();
}

/// CamelCase → snake_case (e.g., "LayoutCallback" → "layout_callback").
fn camel_to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}
