//! PHP extension generator v2 — host-invoker tier.
//!
//! Emits `target/codegen/php_api.rs`, a Rust source file `include!`'d
//! by `dll/src/php_extension.rs` under the `php-extension` Cargo
//! feature. The generated file uses `ext-php-rs` macros
//! (`#[php_function]`, `#[php_module]`, `wrap_function!`) to expose
//! libazul as a native Zend-engine extension.
//!
//! ## Why a separate generator (vs. inline-hand-written)
//!
//! Mirrors the Python extension's `lang_python.rs` → `python_api.rs`
//! split. Hand-coding the host-invoker primitives is fine for ~5
//! functions; the Dom builder + App.run + per-widget callback
//! factories add ~hundreds more, all derivable from the IR. Keeping
//! the surface inside `php_extension.rs` (as Phase 47 did) doesn't
//! scale — the generator owns the IR→#[php_function] mapping so
//! adding a callback kind upstream lights up the PHP side
//! automatically.
//!
//! ## Generated surface (Phase 48 scope)
//!
//! Phase 48 generates just the host-invoker primitives + a per-kind
//! `azul_register_<wrapper>_callback` thunk that wires libazul's
//! invoker setter from PHP-supplied callables. Future sub-phases
//! extend to Dom builders, App.run, and typed wrappers — each
//! sub-phase is a discrete IR pass + smoke-test cycle.

use anyhow::Result;

use super::generator::CodeBuilder;
use super::ir::{
    ArgRefKind, CodegenIR, FunctionArg, FunctionDef, FunctionKind, StructDef, TypeCategory,
};
use super::managed_host_invoker::{has_return, host_invoker_kinds, wrapper_name};

/// Allowlist of struct names the IR-driven emitter wraps as `Azul\<Name>`
/// PHP classes. Each entry produces a `#[php_class]` wrapper around
/// `crate::dll::Az<Name>` and one `#[php_impl]` block whose methods are
/// derived from `ir.functions` entries matching `class_name == <Name>`.
///
/// We start narrow (Phase 52: Dom only) and widen as the marshalling
/// table grows. Adding a new class:
/// 1. Append its bare name to this slice.
/// 2. Confirm `marshal_arg_type` handles every arg type used by the
///    `Az<Name>_*` IR functions, and `marshal_return_type` handles
///    every return shape. Methods whose arg/return types fall outside
///    the table are silently skipped — so the build always succeeds,
///    even when widening exposes new marshalling gaps.
const PHP_CLASS_ALLOWLIST: &[&str] = &[
    "Dom",
    "App",
    "AppConfig",
    "WindowCreateOptions",
    "Button",
];

/// Header banner emitted at the top of `php_api.rs`. Marks the file
/// as autogenerated and explains how to regenerate.
const HEADER: &str = "\
// WARNING: autogenerated PHP/Zend extension bindings for azul api
// Generated for ext-php-rs by azul-doc codegen v2.
// This file is included via include!() in dll/src/php_extension.rs.
// Regenerate with:
//     cd doc && cargo run --release -- codegen all
// DO NOT EDIT MANUALLY — changes will be overwritten.
";

/// Generate the contents of `target/codegen/php_api.rs`.
///
/// The output is a Rust source fragment (not a full crate): it
/// expects `use ext_php_rs::prelude::*;` and the host-invoker C-ABI
/// externs to be in scope at the include site. `php_extension.rs`
/// supplies both before the `include!()` call.
pub fn generate(ir: &CodegenIR) -> Result<String> {
    let mut builder = CodeBuilder::new("    ");

    builder.line(HEADER);
    builder.blank();

    emit_handle_table(&mut builder);
    emit_releaser(&mut builder);

    emit_primitive_functions(&mut builder);
    emit_counter_glue(&mut builder);
    emit_ir_classes(&mut builder, ir);

    for cb in host_invoker_kinds(ir) {
        emit_callback_kind_helpers(&mut builder, cb);
    }

    emit_get_module(&mut builder, ir);

    Ok(builder.finish())
}

/// The handle tables the PHP side uses:
/// * `HANDLES` — `id → JSON snapshot` for refany_create/get.
/// * `CALLBACKS` — `id → function-name String` for register_<kind>_callback.
/// Phase 49 stores callable names (not Zvals) because Zvals are
/// per-request-rooted; the user-facing API today is "pass a named
/// function or a string callable name" rather than "pass an
/// anonymous closure". Phase 50 plumbs refcount-rooted closures
/// through a per-call wrapper Zval.
fn emit_handle_table(builder: &mut CodeBuilder) {
    builder.line("// ------------------------------------------------------------------------");
    builder.line("// Handle tables — keyed by the host-handle id libazul stamps onto");
    builder.line("// each AzRefAny / callback. Values are JSON snapshots (refany) or");
    builder.line("// PHP function names (callbacks). Phase 50 swaps callable names for");
    builder.line("// refcount-rooted closures.");
    builder.line("// ------------------------------------------------------------------------");
    builder.line("static HANDLES: ::once_cell::sync::Lazy<::std::sync::Mutex<::std::collections::HashMap<u64, String>>> =");
    builder.line(
        "    ::once_cell::sync::Lazy::new(|| ::std::sync::Mutex::new(::std::collections::HashMap::new()));",
    );
    builder.line("static CALLBACKS: ::once_cell::sync::Lazy<::std::sync::Mutex<::std::collections::HashMap<u64, String>>> =");
    builder.line(
        "    ::once_cell::sync::Lazy::new(|| ::std::sync::Mutex::new(::std::collections::HashMap::new()));",
    );
    builder
        .line("static NEXT_HANDLE_ID: ::once_cell::sync::Lazy<::std::sync::Mutex<u64>> =");
    builder.line("    ::once_cell::sync::Lazy::new(|| ::std::sync::Mutex::new(0));");
    builder.blank();
}

/// The C-ABI releaser libazul fires when the last RefAny clone of
/// a host-handle drops. Removes the entry from `HANDLES` so the
/// JSON snapshot doesn't leak. Also clears `CALLBACKS` since they
/// share `NEXT_HANDLE_ID`.
fn emit_releaser(builder: &mut CodeBuilder) {
    builder.line("/// Called by libazul when a host-handle RefAny's refcount hits zero.");
    builder.line("///");
    builder.line("/// NOTE: intentionally a no-op. PHP host-handle ids are *stable keys*");
    builder.line("/// the user holds in plain PHP `int` variables ($model_id, $onclick_id,");
    builder.line("/// …) for the whole script, and the SAME id is re-minted into a fresh");
    builder.line("/// independent RefAny on every (re)layout (via `AzRefAny_newHostHandle`).");
    builder.line("/// Those independent RefAnys don't share a refcount, so an eager remove");
    builder.line("/// here would clear the model / callback the moment the *first* relayout");
    builder.line("/// drops its copy — breaking the counter after one click. Pinning the");
    builder.line("/// tables for the process lifetime is the correct lifetime story for the");
    builder.line("/// JSON-snapshot model; a CLI GUI app leaks only a handful of entries.");
    builder.line("unsafe extern \"C\" fn host_handle_releaser(_id: u64) {");
    builder.indent();
    builder.line("// no-op — see doc comment.");
    builder.dedent();
    builder.line("}");
    builder.blank();

    emit_generic_invoker(builder);
}

/// The Rust trampoline registered with libazul via
/// `AzApp_setGenericInvoker`. libazul calls this from its per-kind
/// static thunks for every callback kind whose per-kind invoker
/// slot is empty — which is every kind today, since we're using
/// the generic dispatch path. The trampoline:
/// 1. Reads `kind` as a C string.
/// 2. Looks up the PHP function name in `CALLBACKS` by `handle`.
/// 3. Calls via `ZendCallable::try_from_name` with `kind` as a
///    single string argument (the smoke layer passes the kind name;
///    real args marshalling lands per-kind in Phase 51).
/// 4. Writes nothing to `ret` — for non-void return kinds the per-
///    kind thunk already pre-filled `ret` with the default; we
///    don't override it here. Phase 51 adds per-kind return shape.
fn emit_generic_invoker(builder: &mut CodeBuilder) {
    builder.line("/// libazul generic-invoker trampoline. See module-level docs.");
    builder.line("///");
    builder.line("/// Safety: invoked on the libazul callback thread; the Zend executor");
    builder.line("/// must be active (which it is for the duration of the CLI request");
    builder.line("/// that called App::run). Acquiring CALLBACKS' Mutex from a non-Zend");
    builder.line("/// thread would deadlock if the Zend invocation re-entered through");
    builder.line("/// another #[php_function] — we hold no lock across try_call.");
    builder.line("unsafe extern \"C\" fn azul_generic_invoker(");
    builder.indent();
    builder.line("handle: u64,");
    builder.line("kind: *const ::core::ffi::c_char,");
    builder.line("_args: *const *const ::core::ffi::c_void,");
    builder.line("_n_args: usize,");
    builder.line("_ret: *mut ::core::ffi::c_void,");
    builder.dedent();
    builder.line(") {");
    builder.indent();
    builder.line("if kind.is_null() { return; }");
    builder.line("let kind_str = match ::core::ffi::CStr::from_ptr(kind).to_str() {");
    builder.indent();
    builder.line("Ok(s) => s.to_string(),");
    builder.line("Err(_) => return,");
    builder.dedent();
    builder.line("};");
    builder.line("let name = {");
    builder.indent();
    builder.line("let tbl = match CALLBACKS.lock() { Ok(t) => t, Err(_) => return };");
    builder.line("match tbl.get(&handle) { Some(n) => n.clone(), None => return }");
    builder.dedent();
    builder.line("};");
    builder.line("let callable = match ::ext_php_rs::types::ZendCallable::try_from_name(&name) {");
    builder.indent();
    builder.line("Ok(c) => c,");
    builder.line("Err(_) => return,");
    builder.dedent();
    builder.line("};");
    builder.line("let _ = callable.try_call(vec![&kind_str]);");
    builder.dedent();
    builder.line("}");
    builder.blank();
}

/// The three #[php_function]s that constitute the host-invoker
/// surface on the PHP side: refany_create / refany_get /
/// host_invoker_init.
fn emit_primitive_functions(builder: &mut CodeBuilder) {
    builder.line("/// PHP function: `azul_version() : string`.");
    builder.line("#[::ext_php_rs::prelude::php_function]");
    builder.line("pub fn azul_version() -> &'static str {");
    builder.indent();
    builder.line("\"0.0.7\"");
    builder.dedent();
    builder.line("}");
    builder.blank();

    builder.line("/// PHP function: `azul_refany_create(string $json) : int`.");
    builder.line("///");
    builder.line("/// Allocates a host-handle id for `$json` and stores the JSON");
    builder.line("/// snapshot. Recovery via `azul_refany_get`.");
    builder.line("#[::ext_php_rs::prelude::php_function]");
    builder.line("pub fn azul_refany_create(value: String) -> u64 {");
    builder.indent();
    builder.line("let mut next = NEXT_HANDLE_ID.lock().unwrap();");
    builder.line("*next += 1;");
    builder.line("let id = *next;");
    builder.line("HANDLES.lock().unwrap().insert(id, value);");
    builder.line("id");
    builder.dedent();
    builder.line("}");
    builder.blank();

    builder.line("/// PHP function: `azul_refany_get(int $id) : ?string`.");
    builder.line("///");
    builder.line("/// Returns the JSON snapshot previously stored under `$id`, or");
    builder.line("/// `null` if the id has been released by libazul's destructor.");
    builder.line("#[::ext_php_rs::prelude::php_function]");
    builder.line("pub fn azul_refany_get(id: u64) -> Option<String> {");
    builder.indent();
    builder.line("HANDLES.lock().unwrap().get(&id).cloned()");
    builder.dedent();
    builder.line("}");
    builder.blank();

    builder.line("/// PHP function: `azul_host_invoker_init() : void`.");
    builder.line("///");
    builder.line("/// Idempotent — installs the host-handle releaser with libazul.");
    builder.line("/// Per-kind invoker registration follows in the kind-specific");
    builder.line("/// `azul_register_<wrapper>_callback` helpers below.");
    builder.line("#[::ext_php_rs::prelude::php_function]");
    builder.line("pub fn azul_host_invoker_init() {");
    builder.indent();
    builder.line("unsafe {");
    builder.indent();
    builder.line("AzApp_setHostHandleReleaser(Some(host_handle_releaser));");
    builder.line("AzApp_setGenericInvoker(Some(azul_generic_invoker));");
    builder.dedent();
    builder.line("}");
    builder.dedent();
    builder.line("}");
    builder.blank();

    builder.line("/// PHP function: `azul_invoke_callback(int $id, string $args_json) : ?string`.");
    builder.line("///");
    builder.line("/// Smoke-tests the callable-name → trampoline → Zend invocation path");
    builder.line("/// for a callback previously stashed via");
    builder.line("/// `azul_register_<kind>_callback($name)`. Args are JSON-encoded so");
    builder.line("/// the smoke layer doesn't need a per-kind args marshaller; Phase 50");
    builder.line("/// replaces this with the libazul generic invoker dispatch.");
    builder.line("/// Returns the callable's return value as a JSON string, or null on");
    builder.line("/// missing id / call failure.");
    builder.line("#[::ext_php_rs::prelude::php_function]");
    builder.line("pub fn azul_invoke_callback(id: u64, args_json: String) -> Option<String> {");
    builder.indent();
    builder.line("let name = CALLBACKS.lock().unwrap().get(&id).cloned()?;");
    builder.line("let callable = ::ext_php_rs::types::ZendCallable::try_from_name(&name).ok()?;");
    builder.line("let result = callable.try_call(vec![&args_json]).ok()?;");
    builder.line("if result.is_null() { return Some(\"null\".to_string()); }");
    builder.line("if let Some(s) = result.string() { return Some(s); }");
    builder.line("if let Some(n) = result.long() { return Some(n.to_string()); }");
    builder.line("if let Some(b) = result.bool() { return Some(b.to_string()); }");
    builder.line("Some(\"<unrepresented>\".to_string())");
    builder.dedent();
    builder.line("}");
    builder.blank();
}

/// Emit the full-GUI counter host-invoker bridge: the typed per-kind
/// LayoutCallback + generic Callback invokers (Rust fns that call back into
/// PHP through the Zend executor), plus `azul_counter_init` / `azul_refany_set`.
///
/// These are the same `AzApp_set<Kind>Invoker` slots the Lua binding registers
/// libffi closures into. The layout invoker splices the PHP-returned
/// `Azul\Dom` into the out-pointer; the generic Callback invoker (used by
/// `Azul\Dom::on_click`) returns an `Update` int.
///
/// NOTE: the counter uses a plain `Azul\Dom::on_click` node, NOT the `Button`
/// widget — the widget's `.dom()` output triggers a heap corruption on drop
/// in the php-extension dylib build (link-static + ext-php-rs + macOS
/// `-undefined dynamic_lookup`); plain DOM nodes are unaffected.
fn emit_counter_glue(builder: &mut CodeBuilder) {
    builder.raw(COUNTER_GLUE);
    builder.blank();
}

/// Verbatim Rust source for the counter host-invoker bridge. Kept as a raw
/// literal (rather than per-line `builder.line`) because it is hand-authored,
/// self-contained, and not derived from the IR.
const COUNTER_GLUE: &str = r####"
// ========================================================================
// COUNTER GLUE (mirrored from lang_php_ext.rs::emit_counter_glue)
// ------------------------------------------------------------------------
// Real per-kind host-invoker bridge for the full-GUI counter example. The
// generic-invoker smoke path above only round-trips a `kind` string; the
// counter needs libazul's typed per-kind invokers so the layout callback
// can return an `Azul\Dom` and a plain-node click can return an `Update`.
// These are the same `AzApp_set<Kind>Invoker` slots the Lua binding
// registers libffi closures into — here the closures are Rust fns that call
// back into PHP through the Zend executor.
// ------------------------------------------------------------------------
extern "C" {
    /// libazul per-kind invoker setter (LayoutCallback → returns AzDom).
    fn AzApp_setLayoutCallbackInvoker(
        f: unsafe extern "C" fn(
            u64,
            *const crate::dll::AzRefAny,
            *const ::core::ffi::c_void,
            *mut crate::dll::AzDom,
        ),
    );
    /// Mint a LayoutCallback wrapper struct bound to host-handle `id`.
    fn AzLayoutCallback_createFromHostHandle(id: u64) -> crate::dll::AzLayoutCallback;
    /// libazul per-kind invoker setter (generic Callback → returns AzUpdate).
    fn AzApp_setCallbackInvoker(
        f: unsafe extern "C" fn(
            u64,
            *const crate::dll::AzRefAny,
            *const ::core::ffi::c_void,
            *mut crate::dll::AzUpdate,
        ),
    );
    /// Mint a generic Callback wrapper struct bound to host-handle `id`.
    fn AzCallback_createFromHostHandle(id: u64) -> crate::dll::AzCallback;
}

/// Extract the host-handle id from a callback's `data` RefAny pointer.
unsafe fn az_refany_host_id(data: *const crate::dll::AzRefAny) -> u64 {
    if data.is_null() { return 0; }
    ::azul_core::host_invoker::AzRefAny_getHostHandle(
        data as *const ::azul_core::refany::RefAny,
    )
}

/// LayoutCallback invoker. Called by libazul on every (re)layout. Looks up
/// the PHP callable stashed under `handle`, calls it with the data
/// host-handle id (an `int` PHP can pass to `azul_refany_get`), and splices
/// the returned `Azul\Dom` object's inner AzDom into `out`. The PHP object
/// keeps ownership of its own copy (its Drop frees it); we hand libazul an
/// independent clone.
unsafe extern "C" fn php_layout_invoker(
    handle: u64,
    data: *const crate::dll::AzRefAny,
    _info: *const ::core::ffi::c_void,
    out: *mut crate::dll::AzDom,
) {
    let name = match CALLBACKS.lock() { Ok(t) => t.get(&handle).cloned(), Err(_) => None };
    let name = match name { Some(n) => n, None => return };
    let data_id = az_refany_host_id(data);
    let callable = match ::ext_php_rs::types::ZendCallable::try_from_name(&name) {
        Ok(c) => c,
        Err(_) => return,
    };
    let ret = match callable.try_call(vec![&(data_id as i64)]) {
        Ok(z) => z,
        Err(_) => return,
    };
    // The PHP layout function returns an `Azul\Dom`; splice a clone of its
    // inner AzDom into `out` (the PHP object keeps ownership of its own copy).
    if let Some(dom_ref) = ret.extract::<&AzulDom>() {
        let cloned = crate::dll::AzDom_clone(&dom_ref.inner);
        ::core::ptr::write(out, cloned);
    }
}

/// Generic `Callback`-kind invoker (Hover MouseUp etc. attached to plain DOM
/// nodes via `AzulDom::on_click`). Calls the PHP handler with the data
/// host-handle id and returns an Update int
/// (0 = DoNothing, 1 = RefreshDom, 2 = RefreshDomAllWindows).
unsafe extern "C" fn php_callback_invoker(
    handle: u64,
    data: *const crate::dll::AzRefAny,
    _info: *const ::core::ffi::c_void,
    out: *mut crate::dll::AzUpdate,
) {
    let name = match CALLBACKS.lock() { Ok(t) => t.get(&handle).cloned(), Err(_) => None };
    let name = match name { Some(n) => n, None => return };
    let data_id = az_refany_host_id(data);
    let callable = match ::ext_php_rs::types::ZendCallable::try_from_name(&name) {
        Ok(c) => c,
        Err(_) => return,
    };
    let ret = match callable.try_call(vec![&(data_id as i64)]) {
        Ok(z) => z,
        Err(_) => return,
    };
    let upd = match ret.long().unwrap_or(0) {
        1 => crate::dll::AzUpdate::RefreshDom,
        2 => crate::dll::AzUpdate::RefreshDomAllWindows,
        _ => crate::dll::AzUpdate::DoNothing,
    };
    ::core::ptr::write(out, upd);
}

/// PHP function: `azul_counter_init() : void`. Registers the per-kind layout
/// invoker + the generic `Callback` invoker (used by `Azul\Dom::on_click`)
/// and the host-handle releaser. Idempotent — call once at startup.
#[::ext_php_rs::prelude::php_function]
pub fn azul_counter_init() {
    unsafe {
        AzApp_setHostHandleReleaser(Some(host_handle_releaser));
        AzApp_setLayoutCallbackInvoker(php_layout_invoker);
        AzApp_setCallbackInvoker(php_callback_invoker);
    }
}

/// PHP function: `azul_refany_set(int $id, string $json) : bool`. Overwrite
/// the JSON snapshot stored under `$id` (the model-mutation path used by
/// click handlers). Returns false if the id is unknown/released.
#[::ext_php_rs::prelude::php_function]
pub fn azul_refany_set(id: u64, value: String) -> bool {
    let mut tbl = match HANDLES.lock() { Ok(t) => t, Err(_) => return false };
    if let Some(slot) = tbl.get_mut(&id) {
        *slot = value;
        true
    } else {
        false
    }
}
"####;

/// Per callback kind, emit `azul_register_<wrapper>_callback(string $name)`
/// that stashes the named PHP function in `CALLBACKS` and returns its
/// new handle id. The user then calls libazul-side
/// `Az<Wrapper>_createFromHostHandle($id)` to mint the wrapper struct
/// that gets passed to the layout / button / etc. setter.
///
/// Why a name and not a Zval: PHP Zvals are rooted in the executor's
/// per-request frame, so a Zval held in a `'static` HashMap dangles
/// across requests. Function names are stable. Closures aren't
/// nameable so Phase 50 introduces a refcount-rooted closure wrapper
/// — until then users must pass a named function or string callable.
fn emit_callback_kind_helpers(
    builder: &mut CodeBuilder,
    cb: &super::ir::CallbackTypedefDef,
) {
    let wrapper = wrapper_name(cb);
    let fn_name = callback_helper_fn_name(&wrapper);
    let _ = has_return(cb); // Reserved for Phase 50 — return-arity-aware dispatch.

    builder.line(&format!(
        "/// PHP function: `{fn_name}(string $callable_name) : int`.",
        fn_name = fn_name
    ));
    builder.line("///");
    builder.line(
        "/// Stash the named PHP function in CALLBACKS, return its host-handle id.",
    );
    builder.line(&format!(
        "/// Pair with libazul's `Az{wrapper}_createFromHostHandle($id)` to mint",
        wrapper = wrapper
    ));
    builder.line("/// the wrapper struct. Validation of callability happens at");
    builder.line("/// invoke time via `azul_invoke_callback`.");
    builder.line("#[::ext_php_rs::prelude::php_function]");
    builder.line(&format!(
        "pub fn {fn_name}(callable_name: String) -> u64 {{",
        fn_name = fn_name
    ));
    builder.indent();
    builder.line("let mut next = NEXT_HANDLE_ID.lock().unwrap();");
    builder.line("*next += 1;");
    builder.line("let id = *next;");
    builder.line("CALLBACKS.lock().unwrap().insert(id, callable_name);");
    builder.line("id");
    builder.dedent();
    builder.line("}");
    builder.blank();
}

/// Map a wrapper name (PascalCase, e.g. "Callback", "LayoutCallback",
/// "ButtonOnClick") to the PHP function name. Strips a trailing
/// "Callback" suffix from the wrapper to avoid emitting
/// `azul_register_callback_callback`.
fn callback_helper_fn_name(wrapper: &str) -> String {
    // If the wrapper IS "Callback" verbatim, emit `azul_register_callback`
    // (otherwise we'd get the ugly `azul_register_callback_callback`).
    // Otherwise strip a trailing "Callback" suffix and append our own,
    // so "LayoutCallback" → "azul_register_layout_callback".
    if wrapper == "Callback" {
        return "azul_register_callback".to_string();
    }
    let base = wrapper.strip_suffix("Callback").unwrap_or(wrapper);
    format!("azul_register_{}_callback", camel_to_snake(base))
}

/// The `#[php_module]` entry point. Registers every #[php_function]
/// emitted above via `wrap_function!`. Without this PHP loads the
/// extension successfully but `get_extension_funcs('azul-dll')`
/// returns an empty array.
fn emit_get_module(builder: &mut CodeBuilder, ir: &CodegenIR) {
    builder.line("/// Zend entry point. PHP calls this once at extension load to");
    builder.line("/// build the function table. Every #[php_function] must be");
    builder.line("/// registered here via wrap_function!.");
    builder.line("#[::ext_php_rs::prelude::php_module]");
    builder.line(
        "pub fn get_module(module: ::ext_php_rs::builders::ModuleBuilder) -> ::ext_php_rs::builders::ModuleBuilder {",
    );
    builder.indent();
    builder.line("module");
    builder.indent();
    builder.line(".function(::ext_php_rs::wrap_function!(azul_version))");
    builder.line(".function(::ext_php_rs::wrap_function!(azul_refany_create))");
    builder.line(".function(::ext_php_rs::wrap_function!(azul_refany_get))");
    builder.line(".function(::ext_php_rs::wrap_function!(azul_refany_set))");
    builder.line(".function(::ext_php_rs::wrap_function!(azul_counter_init))");
    builder.line(".function(::ext_php_rs::wrap_function!(azul_host_invoker_init))");
    builder.line(".function(::ext_php_rs::wrap_function!(azul_invoke_callback))");
    for cb in host_invoker_kinds(ir) {
        let fn_name = callback_helper_fn_name(wrapper_name(cb));
        builder.line(&format!(
            ".function(::ext_php_rs::wrap_function!({fn_name}))",
            fn_name = fn_name
        ));
    }
    // Register every allowlisted PHP class. Driven by PHP_CLASS_ALLOWLIST
    // so adding a new class upstream lights up the registration here on
    // the next codegen run without an extra edit.
    for class in PHP_CLASS_ALLOWLIST {
        builder.line(&format!(".class::<Azul{}>()", class));
    }
    builder.dedent();
    builder.dedent();
    builder.line("}");
    builder.blank();
}


// ============================================================================
// IR-driven `#[php_class]` emitter
// ============================================================================

/// Walk `ir.structs`, emit a `#[php_class]` + `#[php_impl]` block for every
/// struct in `PHP_CLASS_ALLOWLIST` whose `category == Regular`. Method
/// signatures are derived from matching `ir.functions` entries —
/// nothing here mentions `AzDom_*` or any other concrete C-ABI symbol
/// by name. Adding a Dom builder / App method upstream in api.json
/// lights it up here on the next codegen run.
fn emit_ir_classes(builder: &mut CodeBuilder, ir: &CodegenIR) {
    for struct_def in &ir.structs {
        if !PHP_CLASS_ALLOWLIST.contains(&struct_def.name.as_str()) {
            continue;
        }
        if struct_def.category != TypeCategory::Regular {
            continue;
        }
        emit_class(builder, struct_def, ir);
    }
}

/// Emit one #[php_class] + #[php_impl] pair for a single struct.
fn emit_class(builder: &mut CodeBuilder, struct_def: &StructDef, ir: &CodegenIR) {
    let bare = &struct_def.name; // e.g., "Dom"
    let wrapper = format!("Azul{bare}"); // Rust wrapper struct name
    let c_struct = format!("crate::dll::Az{bare}"); // Underlying C-ABI struct
    let c_prefix = format!("crate::dll::Az{bare}_"); // Per-method symbol prefix

    builder.line("// ------------------------------------------------------------------------");
    builder.line(&format!(
        "// `Azul\\{bare}` PHP class — IR-driven wrapper around libazul's Az{bare}.",
        bare = bare
    ));
    builder.line("// ------------------------------------------------------------------------");
    builder.line("#[::ext_php_rs::prelude::php_class]");
    builder.line(&format!("#[php(name = \"Azul\\\\{bare}\")]", bare = bare));
    builder.line("#[repr(transparent)]");
    builder.line(&format!("pub struct {wrapper} {{", wrapper = wrapper));
    builder.indent();
    builder.line(&format!("inner: {c_struct},", c_struct = c_struct));
    builder.dedent();
    builder.line("}");
    builder.blank();

    builder.line(&format!(
        "unsafe impl ::core::marker::Send for {wrapper} {{}}",
        wrapper = wrapper
    ));
    builder.line(&format!(
        "unsafe impl ::core::marker::Sync for {wrapper} {{}}",
        wrapper = wrapper
    ));
    builder.blank();

    // Drop fires the C-ABI delete fn when libazul provides one. The IR's
    // FunctionKind::Delete carries that name as `_delete` / `delete`; we
    // look it up rather than hard-coding `AzDom_delete`.
    if let Some(delete_fn) = ir
        .functions
        .iter()
        .find(|f| f.class_name == *bare && f.kind == FunctionKind::Delete)
    {
        builder.line(&format!("impl ::core::ops::Drop for {wrapper} {{", wrapper = wrapper));
        builder.indent();
        builder.line("fn drop(&mut self) {");
        builder.indent();
        builder.line(&format!(
            "unsafe {{ crate::dll::{cname}(&mut self.inner); }}",
            cname = delete_fn.c_name,
        ));
        builder.dedent();
        builder.line("}");
        builder.dedent();
        builder.line("}");
        builder.blank();
    }

    builder.line("#[::ext_php_rs::prelude::php_impl]");
    builder.line(&format!("impl {wrapper} {{", wrapper = wrapper));
    builder.indent();

    let mut emitted = 0usize;
    let mut skipped = 0usize;
    for func in &ir.functions {
        if func.class_name != *bare {
            continue;
        }
        if !is_method_kind_eligible(func.kind) {
            continue;
        }
        match render_method(struct_def, func, ir, &c_prefix, &wrapper) {
            Some(lines) => {
                for ln in lines {
                    builder.line(&ln);
                }
                builder.blank();
                emitted += 1;
            }
            None => skipped += 1,
        }
    }

    builder.line(&format!(
        "// ir-driven emit summary: {emitted} method(s) emitted, {skipped} skipped (unsupported arg/return shape).",
        emitted = emitted,
        skipped = skipped,
    ));

    // Hand-written host-invoker methods the IR marshaller can't derive
    // (callback wrapper structs / layout-callback splice).
    emit_class_extras(builder, bare);

    builder.dedent();
    builder.line("}");
    builder.blank();
}

/// Emit the hand-written counter methods for specific classes:
/// * `Azul\Dom::on_click(data_handle, cb_handle)` — attach a Hover
///   left-mouse-up callback (generic `Callback` kind) to a plain DOM node.
/// * `Azul\WindowCreateOptions::create(cb_handle)` — build window options
///   whose `window_state.layout_callback` is the LayoutCallback wrapper for
///   `cb_handle`.
/// Emitted INSIDE the class's `#[php_impl]` block (caller is at method indent).
fn emit_class_extras(builder: &mut CodeBuilder, bare: &str) {
    match bare {
        "Dom" => builder.raw(DOM_ON_CLICK_METHOD),
        "WindowCreateOptions" => builder.raw(WCO_CREATE_METHOD),
        _ => {}
    }
}

const DOM_ON_CLICK_METHOD: &str = r####"
    /// Attach a click handler (Hover → left-mouse-up) to this DOM node.
    /// `data_handle` is the model host-handle id; `cb_handle` is a generic
    /// `Callback` host-handle id from `azul_register_callback`. Builds the
    /// CoreCallbackData directly and splices it into the node via
    /// `AzDom_withCallbacks` (swap-consume so the value-by-move C-ABI is
    /// satisfied without leaking/double-freeing the receiver).
    pub fn on_click(&mut self, data_handle: i64, cb_handle: i64) {
        unsafe {
            // AzCallback impls Drop, so move its fields out via ptr::read +
            // forget (moving `ctx` by value while leaving the wrapper's Drop
            // from double-dropping it).
            let cb = AzCallback_createFromHostHandle(cb_handle as u64);
            let cb_fn = cb.cb;
            let cb_ctx = ::core::ptr::read(&cb.ctx);
            ::core::mem::forget(cb);
            let data = ::core::mem::transmute::<_, crate::dll::AzRefAny>(
                ::azul_core::host_invoker::AzRefAny_newHostHandle(data_handle as u64),
            );
            let event = crate::dll::AzEventFilter_hover(
                crate::dll::AzHoverEventFilter_leftMouseUp(),
            );
            let core_cb = crate::dll::AzCoreCallback {
                cb: cb_fn as *const () as usize,
                ctx: cb_ctx,
            };
            let ccd = crate::dll::AzCoreCallbackData {
                event,
                callback: core_cb,
                refany: data,
            };
            let vec = crate::dll::AzCoreCallbackDataVec_fromItem(ccd);
            let taken = crate::dll::AzDom_swapWithDefault(&mut self.inner);
            self.inner = crate::dll::AzDom_withCallbacks(taken, vec);
        }
    }
"####;

const WCO_CREATE_METHOD: &str = r####"
    /// Build window options whose layout callback is the PHP function stashed
    /// under `cb_handle` (from `azul_register_layout_callback`). Splices the
    /// LayoutCallback wrapper struct into `window_state.layout_callback`, the
    /// same slot the Lua binding writes.
    pub fn create(cb_handle: i64) -> Self {
        unsafe {
            let mut inner = crate::dll::AzWindowCreateOptions_default();
            inner.window_state.layout_callback =
                AzLayoutCallback_createFromHostHandle(cb_handle as u64);
            AzulWindowCreateOptions { inner }
        }
    }
"####;

/// Function kinds we know how to emit. The auto-derived trait helpers
/// (delete/clone/eq/...) are handled by the class scaffolding above
/// (Drop) or skipped entirely for now.
fn is_method_kind_eligible(kind: FunctionKind) -> bool {
    matches!(
        kind,
        FunctionKind::Constructor
            | FunctionKind::StaticMethod
            | FunctionKind::Method
            | FunctionKind::MethodMut
            | FunctionKind::Default
    )
}

/// Render one method as `Vec<String>` of source lines. Returns `None`
/// if any argument or return type falls outside the marshalling table —
/// caller treats that as "skip this method this iteration".
fn render_method(
    struct_def: &StructDef,
    func: &FunctionDef,
    _ir: &CodegenIR,
    _c_prefix: &str,
    wrapper: &str,
) -> Option<Vec<String>> {
    let takes_self = matches!(
        func.kind,
        FunctionKind::Method | FunctionKind::MethodMut
    );

    // Filter args: drop the self receiver (Python codegen detects it via
    // name == class_name.lowercase()), same convention here.
    let class_lower = struct_def.name.to_lowercase();

    // Detect "consuming self" methods: a Method-kind whose args[0] is the
    // receiver passed by value (`dom: AzDom` rather than `&AzDom` /
    // `&mut AzDom`). libazul's `withX` family does this. ext-php-rs can't
    // accept `self` by value, so we accept `&self`, clone the inner via
    // the same-class clone fn, and run the C-ABI call on the clone — the
    // PHP-side `$dom` stays valid.
    let consumes_self = takes_self
        && func
            .args
            .first()
            .map(|a| a.name == class_lower && a.ref_kind == ArgRefKind::Owned)
            .unwrap_or(false);

    let extra_args: Vec<&FunctionArg> = func
        .args
        .iter()
        .filter(|a| !(takes_self && a.name == class_lower))
        .collect();

    let mut php_params = Vec::<String>::new();
    let mut call_exprs = Vec::<String>::new();

    for arg in &extra_args {
        let marshalled = marshal_arg(arg, &struct_def.name)?;
        php_params.push(format!("{}: {}", arg.name, marshalled.php_param_type));
        call_exprs.push(marshalled.c_call_expr);
    }

    // Build the receiver portion of the C-ABI call.
    // - consumes_self  → `__self_clone` (a freshly-cloned owned struct,
    //                     bound in the body before the call).
    // - MethodMut      → `&mut self.inner`
    // - Method (ref)   → `&self.inner`
    let self_arg = if consumes_self {
        Some("__self_clone".to_string())
    } else if takes_self {
        Some(match func.kind {
            FunctionKind::MethodMut => "&mut self.inner".to_string(),
            _ => "&self.inner".to_string(),
        })
    } else {
        None
    };

    let mut all_call_args: Vec<String> = Vec::new();
    if let Some(s) = &self_arg {
        all_call_args.push(s.clone());
    }
    all_call_args.extend(call_exprs);
    // `func.c_name` is the actual C-ABI symbol (Az<Class>_<camelMethod>) —
    // built by the IR from api.json's snake_case method_name via
    // snake_case_to_lower_camel. Don't reconstruct it locally.
    let c_call = format!(
        "crate::dll::{cname}({args})",
        cname = func.c_name,
        args = all_call_args.join(", ")
    );

    let ret = marshal_return(func.return_type.as_deref(), &struct_def.name, wrapper)?;

    // Compose the PHP receiver fragment. Consuming methods are exposed
    // as `&self` (they don't actually move out of the PHP receiver — the
    // body clones first).
    let receiver_fragment = match (consumes_self, func.kind) {
        (true, _) => Some("&self".to_string()),
        (false, FunctionKind::Method) => Some("&self".to_string()),
        (false, FunctionKind::MethodMut) => Some("&mut self".to_string()),
        _ => None,
    };

    let params_combined: String = match receiver_fragment {
        Some(r) if !php_params.is_empty() => format!("{r}, {}", php_params.join(", ")),
        Some(r) => r,
        None => php_params.join(", "),
    };

    let body = if consumes_self {
        // Bind `__self_clone` via the same-class clone fn, then run the
        // C-ABI call against it.
        format!(
            "let __self_clone = unsafe {{ crate::dll::Az{class}_clone(&self.inner) }}; {body}",
            class = struct_def.name,
            body = ret.wrap_call.replace("__CALL__", &c_call)
        )
    } else {
        ret.wrap_call.replace("__CALL__", &c_call)
    };

    let mut lines = Vec::<String>::new();
    for doc_line in &func.doc {
        lines.push(format!("/// {}", doc_line));
    }
    lines.push(format!(
        "pub fn {name}({params}) -> {ret_type} {{",
        name = func.method_name,
        params = params_combined,
        ret_type = ret.rust_return_type,
    ));
    lines.push(format!("    {body}", body = body));
    lines.push("}".to_string());

    Some(lines)
}

/// Result of marshalling one PHP-visible argument.
struct MarshalledArg {
    /// The Rust type used in the `#[php_impl]` signature (what
    /// ext-php-rs accepts from PHP).
    php_param_type: String,
    /// The expression passed to the underlying C-ABI function. May
    /// include a clone, an `.into()` call, etc.
    c_call_expr: String,
}

/// Map an IR argument to its PHP-side parameter type + the expression
/// we pass into the C-ABI call. Returns `None` if we don't (yet) know
/// how to marshal this type — the method will be skipped.
fn marshal_arg(arg: &FunctionArg, receiver_class: &str) -> Option<MarshalledArg> {
    // 1. Same-class owned argument → accept `&AzulX` and clone the inner
    //    via the C-ABI clone fn. This is the `add_child(child: AzDom)`
    //    case where libazul consumes the child but PHP holds it by-ref.
    if arg.type_name == receiver_class && arg.ref_kind == ArgRefKind::Owned {
        return Some(MarshalledArg {
            php_param_type: format!("&Azul{}", receiver_class),
            c_call_expr: format!(
                "unsafe {{ crate::dll::Az{class}_clone(&{name}.inner) }}",
                class = receiver_class,
                name = arg.name,
            ),
        });
    }

    // 2. Same-class by reference → pass `&self.inner`-style ref through.
    if arg.type_name == receiver_class {
        let prefix = if arg.ref_kind == ArgRefKind::RefMut {
            "&mut "
        } else {
            "&"
        };
        return Some(MarshalledArg {
            php_param_type: format!("&Azul{}", receiver_class),
            c_call_expr: format!("{prefix}{name}.inner", prefix = prefix, name = arg.name),
        });
    }

    // 3. AzString — accept a PHP `String` and convert via `Into`.
    if arg.type_name == "String" && arg.ref_kind == ArgRefKind::Owned {
        return Some(MarshalledArg {
            php_param_type: "String".to_string(),
            c_call_expr: format!("{}.into()", arg.name),
        });
    }

    // 4. Cross-class wrapper argument (Owned, by value). Accept the
    //    `&AzulOther` PHP class and clone its inner via `Az<X>_clone`.
    //    Mirrors the same-class path above; libazul consumes the arg
    //    but PHP holds the wrapper by-ref. Only allowlisted classes
    //    are valid here so the `_clone` symbol is guaranteed to exist
    //    in the codegen-emitted set.
    if PHP_CLASS_ALLOWLIST.contains(&arg.type_name.as_str())
        && arg.ref_kind == ArgRefKind::Owned
    {
        return Some(MarshalledArg {
            php_param_type: format!("&Azul{}", arg.type_name),
            c_call_expr: format!(
                "unsafe {{ crate::dll::Az{class}_clone(&{name}.inner) }}",
                class = arg.type_name,
                name = arg.name,
            ),
        });
    }

    // 5. RefAny owned arg. AzRefAny is a 24-byte struct holding a
    //    refcounted host-handle id. PHP exposes it as `i64` (the host
    //    handle id) so the caller can pass the result of
    //    `azul_refany_create($value)`; the marshalling reconstitutes
    //    the AzRefAny via `AzRefAny_newHostHandle`. The symbol lives
    //    in `azul_core::host_invoker` and returns `azul_core::RefAny`,
    //    which is layout-compatible with `crate::dll::AzRefAny` but
    //    Rust treats them as distinct types — transmute across the
    //    boundary.
    if arg.type_name == "RefAny" && arg.ref_kind == ArgRefKind::Owned {
        return Some(MarshalledArg {
            php_param_type: "i64".to_string(),
            c_call_expr: format!(
                "unsafe {{ ::core::mem::transmute::<_, crate::dll::AzRefAny>(::azul_core::host_invoker::AzRefAny_newHostHandle({} as u64)) }}",
                arg.name
            ),
        });
    }

    // 6. Plain primitives flow through unchanged.
    if let Some(rust_t) = primitive_php_type(&arg.type_name) {
        return Some(MarshalledArg {
            php_param_type: rust_t.to_string(),
            c_call_expr: arg.name.clone(),
        });
    }

    None
}

/// Result of marshalling the C-ABI return type back to a PHP-visible
/// type. `wrap_call` contains the body template with the literal
/// `__CALL__` placeholder for the C-ABI invocation site.
struct MarshalledReturn {
    rust_return_type: String,
    wrap_call: String,
}

fn marshal_return(
    rt: Option<&str>,
    receiver_class: &str,
    wrapper_struct: &str,
) -> Option<MarshalledReturn> {
    match rt {
        None | Some("()") | Some("") => Some(MarshalledReturn {
            rust_return_type: "()".to_string(),
            wrap_call: "unsafe { __CALL__; }".to_string(),
        }),
        Some(t) if t == receiver_class => Some(MarshalledReturn {
            rust_return_type: "Self".to_string(),
            wrap_call: format!(
                "unsafe {{ {wrapper} {{ inner: __CALL__ }} }}",
                wrapper = wrapper_struct
            ),
        }),
        // Cross-class wrapper return — `App::create(...) -> AzApp` etc.
        // Wrap the returned struct in the matching `Azul<T>` PHP class.
        Some(t) if PHP_CLASS_ALLOWLIST.contains(&t) => Some(MarshalledReturn {
            rust_return_type: format!("Azul{}", t),
            wrap_call: format!(
                "unsafe {{ Azul{} {{ inner: __CALL__ }} }}",
                t
            ),
        }),
        Some(t) => primitive_php_type(t).map(|rust_t| MarshalledReturn {
            rust_return_type: primitive_return_rust(rust_t).to_string(),
            wrap_call: primitive_return_wrap(rust_t),
        }),
    }
}

/// Map an IR type-name to the Rust type ext-php-rs accepts as a
/// `#[php_function]` arg/return. `usize` is PHP-unsafe (no native
/// 32/64-bit-portable mapping), so we widen it to `u64` at the
/// boundary; callers see only `i64` in PHP anyway.
fn primitive_php_type(name: &str) -> Option<&'static str> {
    match name {
        "u8" | "i8" | "u16" | "i16" | "u32" | "i32" | "u64" | "i64" => Some(name_literal(name)),
        "usize" => Some("usize"),
        "isize" => Some("isize"),
        "bool" => Some("bool"),
        "f32" | "f64" => Some(name_literal(name)),
        _ => None,
    }
}

/// usize / isize need widening at the FFI boundary so PHP's `int`
/// (always 64-bit on supported builds) sees a stable type. Other
/// primitives pass through as-is.
fn primitive_return_rust(rust_t: &str) -> &'static str {
    match rust_t {
        "usize" => "u64",
        "isize" => "i64",
        other => name_literal(other),
    }
}

fn primitive_return_wrap(rust_t: &str) -> String {
    match rust_t {
        "usize" => "unsafe { __CALL__ as u64 }".to_string(),
        "isize" => "unsafe { __CALL__ as i64 }".to_string(),
        _ => "unsafe { __CALL__ }".to_string(),
    }
}

/// Stable static string for known primitive type names.
fn name_literal(s: &str) -> &'static str {
    match s {
        "u8" => "u8",
        "i8" => "i8",
        "u16" => "u16",
        "i16" => "i16",
        "u32" => "u32",
        "i32" => "i32",
        "u64" => "u64",
        "i64" => "i64",
        "f32" => "f32",
        "f64" => "f64",
        "bool" => "bool",
        _ => "u64",
    }
}

/// CamelCase → snake_case (e.g., "LayoutCallback" → "layout_callback").
fn camel_to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}
