-- Generated by azul-css codegen (Lua). Do not edit by hand.
local azul = require('azul')
local ffi = require('ffi')
local C = azul.C

local M = {}

-- CSS: .text
function M.style_text()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[47]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_caretWidth(ffi.new('AzCaretWidthValue', { Exact = { tag = 6, payload = ffi.new('AzCaretWidth', { inner = C.AzPixelValue_px(2.0) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_exclusionMargin(ffi.new('AzStyleExclusionMarginValue', { Exact = { tag = 6, payload = ffi.new('AzStyleExclusionMargin', { inner = C.AzFloatValue_create(10.5) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_hyphenationLanguage(ffi.new('AzStyleHyphenationLanguageValue', { Exact = { tag = 6, payload = ffi.new('AzStyleHyphenationLanguage', { inner = azul._az_string("en-US") }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_selectionBackgroundColor(ffi.new('AzSelectionBackgroundColor', { inner = ffi.new('AzColorU', { r = 51, g = 153, b = 255, a = 255 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_selectionColor(ffi.new('AzSelectionColor', { inner = ffi.new('AzColorU', { r = 255, g = 255, b = 255, a = 255 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_selectionRadius(ffi.new('AzSelectionRadiusValue', { Exact = { tag = 6, payload = ffi.new('AzSelectionRadius', { inner = C.AzPixelValue_px(3.0) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_alignmentBaseline(ffi.new('AzStyleAlignmentBaselineValue', { Exact = { tag = 6, payload = C.AzStyleAlignmentBaseline_Middle } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_baselineSource(ffi.new('AzStyleBaselineSourceValue', { Exact = { tag = 6, payload = C.AzStyleBaselineSource_Last } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_caretAnimationDuration(ffi.new('AzCaretAnimationDuration', { inner = ffi.new('AzCssDuration', { inner = 500, unit = C.AzCssDurationUnit_Milliseconds }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_caretColor(ffi.new('AzCaretColor', { inner = ffi.new('AzColorU', { r = 255, g = 0, b = 0, a = 255 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textColor(ffi.new('AzStyleTextColor', { inner = ffi.new('AzColorU', { r = 51, g = 102, b = 153, a = 255 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_direction(ffi.new('AzStyleDirectionValue', { Exact = { tag = 6, payload = C.AzStyleDirection_Rtl } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_dominantBaseline(ffi.new('AzStyleDominantBaselineValue', { Exact = { tag = 6, payload = C.AzStyleDominantBaseline_Central } }))),
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_font(
                C.AzStyleFontFamilyVec_copyFromPtr(ffi.new('AzStyleFontFamily[2]', {
                    C.AzStyleFontFamily_system(azul._az_string("Georgia")),
                    C.AzStyleFontFamily_system(azul._az_string("serif")),
                }), 2)
            )
        ),
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_fontFamily(
                C.AzStyleFontFamilyVec_copyFromPtr(ffi.new('AzStyleFontFamily[2]', {
                    C.AzStyleFontFamily_system(azul._az_string("Arial")),
                    C.AzStyleFontFamily_system(azul._az_string("sans-serif")),
                }), 2)
            )
        ),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_fontSize(ffi.new('AzStyleFontSize', { inner = C.AzPixelValue_px(14.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_fontStyle(C.AzStyleFontStyle_Italic)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_fontWeight(C.AzStyleFontWeight_W600)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_hangingPunctuation(ffi.new('AzStyleHangingPunctuationValue', { Exact = { tag = 6, payload = ffi.new('AzStyleHangingPunctuation', { first = true, force_end = false, allow_end = false, last = false }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_hyphens(ffi.new('AzStyleHyphensValue', { Exact = { tag = 6, payload = C.AzStyleHyphens_Auto } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_initialLetter(ffi.new('AzStyleInitialLetterValue', { Exact = { tag = 6, payload = ffi.new('AzStyleInitialLetter', { size = 3, sink = C.AzOptionU32_none() }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_initialLetterAlign(ffi.new('AzStyleInitialLetterAlignValue', { Exact = { tag = 6, payload = C.AzStyleInitialLetterAlign_Alphabetic } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_initialLetterWrap(ffi.new('AzStyleInitialLetterWrapValue', { Exact = { tag = 6, payload = C.AzStyleInitialLetterWrap_First } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_letterSpacing(ffi.new('AzStyleLetterSpacing', { inner = C.AzPixelValue_px(0.5) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_lineBreak(ffi.new('AzStyleLineBreakValue', { Exact = { tag = 6, payload = C.AzStyleLineBreak_Strict } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_lineClamp(ffi.new('AzStyleLineClampValue', { Exact = { tag = 6, payload = ffi.new('AzStyleLineClamp', { max_lines = 3 }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_lineFitEdge(ffi.new('AzStyleLineFitEdgeValue', { Exact = { tag = 6, payload = C.AzStyleLineFitEdge_Leading } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_lineHeight(ffi.new('AzStyleLineHeight', { inner = ffi.new('AzPercentageValue', { number = C.AzFloatValue_create(150.0) }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_overflowWrap(ffi.new('AzStyleOverflowWrapValue', { Exact = { tag = 6, payload = C.AzStyleOverflowWrap_Anywhere } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_tabSize(ffi.new('AzStyleTabSize', { inner = C.AzPixelValue_em(4.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textAlign(C.AzStyleTextAlign_Center)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textAlignLast(ffi.new('AzStyleTextAlignLastValue', { Exact = { tag = 6, payload = C.AzStyleTextAlignLast_Justify } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textBoxEdge(ffi.new('AzStyleTextBoxEdgeValue', { Exact = { tag = 6, payload = ffi.new('AzStyleTextBoxEdge', { over = C.AzTextBoxEdgeOver_Cap, under = C.AzTextBoxEdgeUnder_Alphabetic }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textBoxTrim(ffi.new('AzStyleTextBoxTrimValue', { Exact = { tag = 6, payload = C.AzStyleTextBoxTrim_TrimBoth } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textCombineUpright(ffi.new('AzStyleTextCombineUprightValue', { Exact = { tag = 6, payload = C.AzStyleTextCombineUpright_digits(2) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textDecoration(C.AzStyleTextDecoration_Underline)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textIndent(ffi.new('AzStyleTextIndent', { inner = C.AzPixelValue_em(2.0), each_line = false, hanging = false }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textJustify(C.AzLayoutTextJustify_InterWord)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textOrientation(ffi.new('AzStyleTextOrientationValue', { Exact = { tag = 6, payload = C.AzStyleTextOrientation_Upright } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textOverflow(ffi.new('AzStyleTextOverflowValue', { Exact = { tag = 6, payload = C.AzStyleTextOverflow_Ellipsis } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textTransform(ffi.new('AzStyleTextTransformValue', { Exact = { tag = 6, payload = C.AzStyleTextTransform_Uppercase } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_unicodeBidi(ffi.new('AzStyleUnicodeBidiValue', { Exact = { tag = 6, payload = C.AzStyleUnicodeBidi_Isolate } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_userSelect(C.AzStyleUserSelect_None)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_verticalAlign(C.AzStyleVerticalAlign_middle())),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_whiteSpace(ffi.new('AzStyleWhiteSpaceValue', { Exact = { tag = 6, payload = C.AzStyleWhiteSpace_PreWrap } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_wordBreak(ffi.new('AzStyleWordBreakValue', { Exact = { tag = 6, payload = C.AzStyleWordBreak_BreakAll } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_wordSpacing(ffi.new('AzStyleWordSpacing', { inner = C.AzPixelValue_px(4.0) }))),
    }), 47)
end

-- CSS: .box
function M.style_box()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[40]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_aspectRatio(ffi.new('AzStyleAspectRatioValue', { Exact = { tag = 6, payload = C.AzStyleAspectRatio_ratio(ffi.new('AzAspectRatioValue', { width = 16000, height = 9000 })) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_bottom(ffi.new('AzLayoutInsetBottom', { inner = C.AzPixelValue_pt(5.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_boxSizing(C.AzLayoutBoxSizing_BorderBox)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_clear(ffi.new('AzLayoutClearValue', { Exact = { tag = 6, payload = C.AzLayoutClear_Both } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_clip(ffi.new('AzStyleClipRectValue', { Exact = { tag = 6, payload = ffi.new('AzStyleClipRect', { top = C.AzOptionF32_some(0.0), right = C.AzOptionF32_some(10.0), bottom = C.AzOptionF32_some(10.0), left = C.AzOptionF32_some(0.0) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_cursor(C.AzStyleCursor_Pointer)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_display(C.AzLayoutDisplay_Block)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_float(ffi.new('AzLayoutFloatValue', { Exact = { tag = 6, payload = C.AzLayoutFloat_Left } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_height(C.AzLayoutHeight_px(C.AzPixelValue_px(200.0)))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_left(ffi.new('AzLayoutLeft', { inner = C.AzPixelValue_fromMetric(C.AzSizeMetric_In, 1.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_marginBottom(ffi.new('AzLayoutMarginBottom', { inner = C.AzPixelValue_px(9.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_auto(C.AzCssPropertyType_MarginLeft)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_marginRight(ffi.new('AzLayoutMarginRight', { inner = C.AzPixelValue_px(8.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_marginTop(ffi.new('AzLayoutMarginTop', { inner = C.AzPixelValue_px(7.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_maxHeight(ffi.new('AzLayoutMaxHeight', { inner = C.AzPixelValue_fromMetric(C.AzSizeMetric_Vh, 90.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_maxWidth(ffi.new('AzLayoutMaxWidth', { inner = C.AzPixelValue_px(800.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_minHeight(ffi.new('AzLayoutMinHeight', { inner = C.AzPixelValue_rem(1.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_minWidth(ffi.new('AzLayoutMinWidth', { inner = C.AzPixelValue_em(10.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_objectFit(ffi.new('AzStyleObjectFitValue', { Exact = { tag = 6, payload = C.AzStyleObjectFit_Cover } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_objectPosition(ffi.new('AzStyleObjectPositionValue', { Exact = { tag = 6, payload = ffi.new('AzStyleObjectPosition', { horizontal = C.AzBackgroundPositionHorizontal_center(), vertical = C.AzBackgroundPositionVertical_top() }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_opacity(ffi.new('AzStyleOpacity', { inner = ffi.new('AzPercentageValue', { number = C.AzFloatValue_create(50.0) }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_overflowBlock(ffi.new('AzLayoutOverflowValue', { Exact = { tag = 6, payload = C.AzLayoutOverflow_Clip } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_overflowClipMargin(ffi.new('AzStyleOverflowClipMarginValue', { Exact = { tag = 6, payload = ffi.new('AzStyleOverflowClipMargin', { clip_edge = C.AzVisualBox_ContentBox, inner = C.AzPixelValue_px(0.0) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_overflowInline(ffi.new('AzLayoutOverflowValue', { Exact = { tag = 6, payload = C.AzLayoutOverflow_Auto } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_overflowX(C.AzLayoutOverflow_Hidden)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_overflowY(C.AzLayoutOverflow_Scroll)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_paddingBottom(ffi.new('AzLayoutPaddingBottom', { inner = C.AzPixelValue_px(3.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_paddingInlineEnd(ffi.new('AzLayoutPaddingInlineEndValue', { Exact = { tag = 6, payload = ffi.new('AzLayoutPaddingInlineEnd', { inner = C.AzPixelValue_px(6.0) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_paddingInlineStart(ffi.new('AzLayoutPaddingInlineStartValue', { Exact = { tag = 6, payload = ffi.new('AzLayoutPaddingInlineStart', { inner = C.AzPixelValue_px(5.0) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_paddingLeft(ffi.new('AzLayoutPaddingLeft', { inner = C.AzPixelValue_px(4.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_paddingRight(ffi.new('AzLayoutPaddingRight', { inner = C.AzPixelValue_px(2.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_paddingTop(ffi.new('AzLayoutPaddingTop', { inner = C.AzPixelValue_px(1.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_position(C.AzLayoutPosition_Absolute)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_right(ffi.new('AzLayoutRight', { inner = C.AzPixelValue_px(10.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_scrollbarGutter(ffi.new('AzStyleScrollbarGutterValue', { Exact = { tag = 6, payload = C.AzStyleScrollbarGutter_StableBothEdges } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_top(ffi.new('AzLayoutTop', { inner = C.AzPixelValue_px(0.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_visibility(C.AzStyleVisibility_Hidden)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_width(C.AzLayoutWidth_px(C.AzPixelValue_percent(50.0)))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_writingMode(ffi.new('AzLayoutWritingModeValue', { Exact = { tag = 6, payload = C.AzLayoutWritingMode_VerticalRl } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_zIndex(C.AzLayoutZIndex_integer(10))),
    }), 40)
end

-- CSS: .flex
function M.style_flex()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[13]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_alignContent(C.AzLayoutAlignContent_Stretch)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_alignItems(C.AzLayoutAlignItems_Center)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_alignSelf(C.AzLayoutAlignSelf_End)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_columnGap(ffi.new('AzLayoutColumnGapValue', { Exact = { tag = 6, payload = ffi.new('AzLayoutColumnGap', { inner = C.AzPixelValue_px(8.0) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_flexBasis(ffi.new('AzLayoutFlexBasisValue', { Exact = { tag = 6, payload = C.AzLayoutFlexBasis_exact(C.AzPixelValue_percent(30.0)) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_flexDirection(C.AzLayoutFlexDirection_Column)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_flexGrow(ffi.new('AzLayoutFlexGrow', { inner = C.AzFloatValue_create(2.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_flexShrink(ffi.new('AzLayoutFlexShrink', { inner = C.AzFloatValue_create(0.5) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_flexWrap(C.AzLayoutFlexWrap_Wrap)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_rowGap(ffi.new('AzLayoutRowGapValue', { Exact = { tag = 6, payload = ffi.new('AzLayoutRowGap', { inner = C.AzPixelValue_px(6.0) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_columnGap(ffi.new('AzLayoutColumnGapValue', { Exact = { tag = 6, payload = ffi.new('AzLayoutColumnGap', { inner = C.AzPixelValue_px(6.0) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_justifyContent(C.AzLayoutJustifyContent_SpaceBetween)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_rowGap(ffi.new('AzLayoutRowGapValue', { Exact = { tag = 6, payload = ffi.new('AzLayoutRowGap', { inner = C.AzPixelValue_px(4.0) }) } }))),
    }), 13)
end

-- CSS: .grid
-- dropped `grid-auto-rows: minmax(10px, 100fr)`: grid `minmax()` tracks hold raw pointers in the C ABI and cannot be built from the bindings
function M.style_grid()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[11]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_gridAutoColumns(ffi.new('AzLayoutGridAutoColumnsValue', { Exact = { tag = 6, payload = ffi.new('AzGridAutoTracks', { tracks = C.AzGridTrackSizingVec_copyFromPtr(ffi.new('AzGridTrackSizing[1]', { C.AzGridTrackSizing_fixed(C.AzPixelValue_px(50.0)) }), 1) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_gridAutoFlow(C.AzLayoutGridAutoFlow_Column)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_gridColumn(ffi.new('AzLayoutGridColumnValue', { Exact = { tag = 6, payload = ffi.new('AzGridPlacement', { grid_start = C.AzGridLine_line(1), grid_end = C.AzGridLine_line(3) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_rowGap(ffi.new('AzLayoutRowGapValue', { Exact = { tag = 6, payload = ffi.new('AzLayoutRowGap', { inner = C.AzPixelValue_px(10.0) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_columnGap(ffi.new('AzLayoutColumnGapValue', { Exact = { tag = 6, payload = ffi.new('AzLayoutColumnGap', { inner = C.AzPixelValue_px(10.0) }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_gridRow(ffi.new('AzLayoutGridRowValue', { Exact = { tag = 6, payload = ffi.new('AzGridPlacement', { grid_start = C.AzGridLine_span(2), grid_end = C.AzGridLine_auto() }) } }))),
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_gridTemplateAreas(
                ffi.new(
                    'AzLayoutGridTemplateAreasValue',
                    {
                        Exact = {
                            tag = 6,
                            payload = ffi.new(
                                'AzGridTemplateAreas',
                                {
                                    areas = C.AzGridAreaDefinitionVec_copyFromPtr(ffi.new('AzGridAreaDefinition[3]', {
                                        ffi.new('AzGridAreaDefinition', { name = azul._az_string("header"), row_start = 1, row_end = 2, column_start = 1, column_end = 3 }),
                                        ffi.new('AzGridAreaDefinition', { name = azul._az_string("main"), row_start = 2, row_end = 3, column_start = 2, column_end = 3 }),
                                        ffi.new('AzGridAreaDefinition', { name = azul._az_string("sidebar"), row_start = 2, row_end = 3, column_start = 1, column_end = 2 }),
                                    }), 3),
                                }
                            )
                        }
                    }
                )
            )
        ),
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_gridTemplateColumns(
                ffi.new(
                    'AzLayoutGridTemplateColumnsValue',
                    {
                        Exact = {
                            tag = 6,
                            payload = ffi.new(
                                'AzGridTemplate',
                                {
                                    tracks = C.AzGridTrackSizingVec_copyFromPtr(ffi.new('AzGridTrackSizing[3]', {
                                        C.AzGridTrackSizing_fr(100),
                                        C.AzGridTrackSizing_fixed(C.AzPixelValue_px(200.0)),
                                        C.AzGridTrackSizing_auto(),
                                    }), 3),
                                }
                            )
                        }
                    }
                )
            )
        ),
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_gridTemplateRows(
                ffi.new(
                    'AzLayoutGridTemplateRowsValue',
                    {
                        Exact = {
                            tag = 6,
                            payload = ffi.new(
                                'AzGridTemplate',
                                {
                                    tracks = C.AzGridTrackSizingVec_copyFromPtr(ffi.new('AzGridTrackSizing[2]', {
                                        C.AzGridTrackSizing_fixed(C.AzPixelValue_px(100.0)),
                                        C.AzGridTrackSizing_fr(100),
                                    }), 2),
                                }
                            )
                        }
                    }
                )
            )
        ),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_justifyItems(C.AzLayoutJustifyItems_Start)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_justifySelf(C.AzLayoutJustifySelf_Center)),
    }), 11)
end

-- CSS: .borders
function M.style_borders()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[20]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderBottomColor(ffi.new('AzStyleBorderBottomColor', { inner = ffi.new('AzColorU', { r = 51, g = 51, b = 51, a = 255 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderBottomLeftRadius(ffi.new('AzStyleBorderBottomLeftRadius', { inner = C.AzPixelValue_px(6.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderBottomRightRadius(ffi.new('AzStyleBorderBottomRightRadius', { inner = C.AzPixelValue_px(7.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderBottomStyle(ffi.new('AzStyleBorderBottomStyle', { inner = C.AzBorderStyle_Dotted }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderBottomWidth(ffi.new('AzLayoutBorderBottomWidth', { inner = C.AzPixelValue_px(3.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderLeftColor(ffi.new('AzStyleBorderLeftColor', { inner = ffi.new('AzColorU', { r = 68, g = 68, b = 68, a = 255 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderLeftStyle(ffi.new('AzStyleBorderLeftStyle', { inner = C.AzBorderStyle_Double }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderLeftWidth(ffi.new('AzLayoutBorderLeftWidth', { inner = C.AzPixelValue_px(4.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderRightColor(ffi.new('AzStyleBorderRightColor', { inner = ffi.new('AzColorU', { r = 34, g = 34, b = 34, a = 255 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderRightStyle(ffi.new('AzStyleBorderRightStyle', { inner = C.AzBorderStyle_Dashed }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderRightWidth(ffi.new('AzLayoutBorderRightWidth', { inner = C.AzPixelValue_px(2.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderTopColor(ffi.new('AzStyleBorderTopColor', { inner = ffi.new('AzColorU', { r = 17, g = 17, b = 17, a = 255 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderTopLeftRadius(ffi.new('AzStyleBorderTopLeftRadius', { inner = C.AzPixelValue_px(4.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderTopRightRadius(ffi.new('AzStyleBorderTopRightRadius', { inner = C.AzPixelValue_px(5.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderTopStyle(ffi.new('AzStyleBorderTopStyle', { inner = C.AzBorderStyle_Solid }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderTopWidth(ffi.new('AzLayoutBorderTopWidth', { inner = C.AzPixelValue_px(1.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_boxShadowLeft(ffi.new('AzStyleBoxShadow', { offset_x = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(0.0) }), offset_y = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(2.0) }), blur_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(4.0) }), spread_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(1.0) }), clip_mode = C.AzBoxShadowClipMode_Outset, color = ffi.new('AzColorU', { r = 0, g = 0, b = 0, a = 64 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_boxShadowRight(ffi.new('AzStyleBoxShadow', { offset_x = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(0.0) }), offset_y = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(2.0) }), blur_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(4.0) }), spread_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(1.0) }), clip_mode = C.AzBoxShadowClipMode_Outset, color = ffi.new('AzColorU', { r = 0, g = 0, b = 0, a = 64 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_boxShadowTop(ffi.new('AzStyleBoxShadow', { offset_x = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(0.0) }), offset_y = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(2.0) }), blur_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(4.0) }), spread_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(1.0) }), clip_mode = C.AzBoxShadowClipMode_Outset, color = ffi.new('AzColorU', { r = 0, g = 0, b = 0, a = 64 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_boxShadowBottom(ffi.new('AzStyleBoxShadow', { offset_x = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(0.0) }), offset_y = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(2.0) }), blur_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(4.0) }), spread_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(1.0) }), clip_mode = C.AzBoxShadowClipMode_Outset, color = ffi.new('AzColorU', { r = 0, g = 0, b = 0, a = 64 }) }))),
    }), 20)
end

-- CSS: .scroll
function M.style_scroll()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[16]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_appRegion(ffi.new('AzStyleAppRegionValue', { Exact = { tag = 6, payload = C.AzStyleAppRegion_Drag } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_scrollbarButton(ffi.new('AzStyleBackgroundContentValue', { Exact = { tag = 6, payload = C.AzStyleBackgroundContent_color(ffi.new('AzColorU', { r = 204, g = 204, b = 204, a = 255 })) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_scrollbarCorner(ffi.new('AzStyleBackgroundContentValue', { Exact = { tag = 6, payload = C.AzStyleBackgroundContent_color(ffi.new('AzColorU', { r = 221, g = 221, b = 221, a = 255 })) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_scrollbarFadeDelay(ffi.new('AzScrollbarFadeDelayValue', { Exact = { tag = 6, payload = ffi.new('AzScrollbarFadeDelay', { ms = 500 }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_scrollbarFadeDuration(ffi.new('AzScrollbarFadeDurationValue', { Exact = { tag = 6, payload = ffi.new('AzScrollbarFadeDuration', { ms = 200 }) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_scrollbarResizer(ffi.new('AzStyleBackgroundContentValue', { Exact = { tag = 6, payload = C.AzStyleBackgroundContent_color(ffi.new('AzColorU', { r = 187, g = 187, b = 187, a = 255 })) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_scrollbarThumb(ffi.new('AzStyleBackgroundContentValue', { Exact = { tag = 6, payload = C.AzStyleBackgroundContent_color(ffi.new('AzColorU', { r = 136, g = 136, b = 136, a = 255 })) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_scrollbarTrack(ffi.new('AzStyleBackgroundContentValue', { Exact = { tag = 6, payload = C.AzStyleBackgroundContent_color(ffi.new('AzColorU', { r = 238, g = 238, b = 238, a = 255 })) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_scrollbarVisibility(ffi.new('AzScrollbarVisibilityModeValue', { Exact = { tag = 6, payload = C.AzScrollbarVisibilityMode_WhenScrolling } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_overscrollBehaviorX(ffi.new('AzOverscrollBehaviorValue', { Exact = { tag = 6, payload = C.AzOverscrollBehavior_Contain } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_overscrollBehaviorY(ffi.new('AzOverscrollBehaviorValue', { Exact = { tag = 6, payload = C.AzOverscrollBehavior_None } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_scrollbarColor(ffi.new('AzStyleScrollbarColorValue', { Exact = { tag = 6, payload = C.AzStyleScrollbarColor_custom(ffi.new('AzScrollbarColorCustom', { thumb = ffi.new('AzColorU', { r = 136, g = 136, b = 136, a = 255 }), track = ffi.new('AzColorU', { r = 238, g = 238, b = 238, a = 255 }) })) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_scrollbarWidth(ffi.new('AzLayoutScrollbarWidthValue', { Exact = { tag = 6, payload = C.AzLayoutScrollbarWidth_Thin } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_spatialNavigationAction(ffi.new('AzStyleSpatialNavigationActionValue', { Exact = { tag = 6, payload = C.AzStyleSpatialNavigationAction_Focus } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_spatialNavigationContain(ffi.new('AzStyleSpatialNavigationContainValue', { Exact = { tag = 6, payload = C.AzStyleSpatialNavigationContain_Contain } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_spatialNavigationFunction(ffi.new('AzStyleSpatialNavigationFunctionValue', { Exact = { tag = 6, payload = C.AzStyleSpatialNavigationFunction_Grid } }))),
    }), 16)
end

-- CSS: .effects
-- dropped `text-shadow: 1px 1px 2px`: CssProperty::TextShadow holds a BoxOrStaticStyleBoxShadow (a pointer wrapper) and api.json has no constructor for it
function M.style_effects()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[11]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_backdropFilter(ffi.new('AzStyleFilterVecValue', { Exact = { tag = 6, payload = C.AzStyleFilterVec_copyFromPtr(ffi.new('AzStyleFilter[1]', { C.AzStyleFilter_grayscale(ffi.new('AzPercentageValue', { number = C.AzFloatValue_create(50.0) })) }), 1) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_backfaceVisibility(C.AzStyleBackfaceVisibility_Hidden)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_backgroundContent(C.AzStyleBackgroundContentVec_copyFromPtr(ffi.new('AzStyleBackgroundContent[1]', { C.AzStyleBackgroundContent_color(ffi.new('AzColorU', { r = 250, g = 250, b = 250, a = 255 })) }), 1))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_backgroundPosition(C.AzStyleBackgroundPositionVec_copyFromPtr(ffi.new('AzStyleBackgroundPosition[1]', { ffi.new('AzStyleBackgroundPosition', { horizontal = C.AzBackgroundPositionHorizontal_center(), vertical = C.AzBackgroundPositionVertical_center() }) }), 1))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_backgroundRepeat(C.AzStyleBackgroundRepeatVec_copyFromPtr(ffi.new('AzStyleBackgroundRepeat[1]', { C.AzStyleBackgroundRepeat_NoRepeat }), 1))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_backgroundSize(C.AzStyleBackgroundSizeVec_copyFromPtr(ffi.new('AzStyleBackgroundSize[1]', { C.AzStyleBackgroundSize_cover() }), 1))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_filter(ffi.new('AzStyleFilterVecValue', { Exact = { tag = 6, payload = C.AzStyleFilterVec_copyFromPtr(ffi.new('AzStyleFilter[1]', { C.AzStyleFilter_blur(ffi.new('AzStyleBlur', { width = C.AzPixelValue_px(2.0), height = C.AzPixelValue_px(2.0) })) }), 1) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_mixBlendMode(ffi.new('AzStyleMixBlendModeValue', { Exact = { tag = 6, payload = C.AzStyleMixBlendMode_Multiply } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_perspectiveOrigin(ffi.new('AzStylePerspectiveOrigin', { x = C.AzPixelValue_px(10.0), y = C.AzPixelValue_px(20.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_transform(C.AzStyleTransformVec_copyFromPtr(ffi.new('AzStyleTransform[1]', { C.AzStyleTransform_rotate(ffi.new('AzAngleValue', { metric = C.AzAngleMetric_Degree, number = C.AzFloatValue_create(45.0) })) }), 1))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_transformOrigin(ffi.new('AzStyleTransformOrigin', { x = C.AzPixelValue_percent(50.0), y = C.AzPixelValue_percent(50.0) }))),
    }), 11)
end

-- CSS: .fragment
function M.style_fragment()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[15]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_boxDecorationBreak(C.AzBoxDecorationBreak_Clone)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_breakAfter(C.AzPageBreak_Avoid)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_breakBefore(C.AzPageBreak_Page)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_breakInside(C.AzBreakInside_Avoid)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_columnCount(C.AzColumnCount_integer(3))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_columnFill(C.AzColumnFill_Balance)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_columnRuleColor(ffi.new('AzColumnRuleColor', { inner = ffi.new('AzColorU', { r = 204, g = 204, b = 204, a = 255 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_columnRuleStyle(ffi.new('AzColumnRuleStyle', { inner = C.AzBorderStyle_Solid }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_columnRuleWidth(ffi.new('AzColumnRuleWidth', { inner = C.AzPixelValue_px(1.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_columnSpan(C.AzColumnSpan_All)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_columnWidth(C.AzColumnWidth_length(C.AzPixelValue_px(200.0)))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_flowFrom(C.AzFlowFrom_named(azul._az_string("article")))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_flowInto(C.AzFlowInto_named(azul._az_string("article")))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_orphans(ffi.new('AzOrphans', { inner = 2 }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_widows(ffi.new('AzWidows', { inner = 3 }))),
    }), 15)
end

-- CSS: .shape
function M.style_shape()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[5]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_clipPath(C.AzClipPath_shape(C.AzCssShape_circle(ffi.new('AzShapeCircle', { center = ffi.new('AzShapePoint', { x = 0.0, y = 0.0 }), radius = 40.0 }))))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_shapeImageThreshold(ffi.new('AzShapeImageThreshold', { inner = C.AzFloatValue_create(0.5) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_shapeInside(C.AzShapeInside_shape(C.AzCssShape_circle(ffi.new('AzShapeCircle', { center = ffi.new('AzShapePoint', { x = 50.0, y = 50.0 }), radius = 100.0 }))))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_shapeMargin(ffi.new('AzShapeMargin', { inner = C.AzPixelValue_px(10.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_shapeOutside(C.AzShapeOutside_shape(C.AzCssShape_circle(ffi.new('AzShapeCircle', { center = ffi.new('AzShapePoint', { x = 0.0, y = 0.0 }), radius = 50.0 }))))),
    }), 5)
end

-- CSS: .table
function M.style_table()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[5]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderCollapse(C.AzStyleBorderCollapse_Collapse)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_borderSpacing(ffi.new('AzLayoutBorderSpacing', { horizontal = C.AzPixelValue_px(2.0), vertical = C.AzPixelValue_px(4.0) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_captionSide(C.AzStyleCaptionSide_Bottom)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_emptyCells(C.AzStyleEmptyCells_Hide)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_tableLayout(C.AzLayoutTableLayout_Fixed)),
    }), 5)
end

-- CSS: .content
function M.style_content()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[6]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_content(ffi.new('AzContent', { inner = azul._az_string("\"Hello\"") }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_counterIncrement(ffi.new('AzCounterIncrement', { counter_name = azul._az_string("section"), value = 1 }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_counterReset(ffi.new('AzCounterReset', { counter_name = azul._az_string("section"), value = 1 }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_listStylePosition(C.AzStyleListStylePosition_Inside)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_listStyleType(C.AzStyleListStyleType_UpperRoman)),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_stringSet(ffi.new('AzStringSet', { inner = azul._az_string("title \"Chapter\"") }))),
    }), 6)
end

-- CSS: .anim
function M.style_anim()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[3]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_animationIn(ffi.new('AzStyleAnimationVecValue', { Exact = { tag = 6, payload = C.AzStyleAnimationVec_copyFromPtr(ffi.new('AzStyleAnimation[1]', { ffi.new('AzStyleAnimation', { name = azul._az_string("flyInLeft"), duration = ffi.new('AzCssDuration', { inner = 500, unit = C.AzCssDurationUnit_Milliseconds }), delay = ffi.new('AzCssDuration', { inner = 0, unit = C.AzCssDurationUnit_Milliseconds }), iterations = C.AzAnimationIterationCount_count(1), timing = C.AzAnimationTiming_spring(), clip = true }) }), 1) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_animationOut(ffi.new('AzStyleAnimationVecValue', { Exact = { tag = 6, payload = C.AzStyleAnimationVec_copyFromPtr(ffi.new('AzStyleAnimation[1]', { ffi.new('AzStyleAnimation', { name = azul._az_string("fadeOut"), duration = ffi.new('AzCssDuration', { inner = 200, unit = C.AzCssDurationUnit_Milliseconds }), delay = ffi.new('AzCssDuration', { inner = 0, unit = C.AzCssDurationUnit_Milliseconds }), iterations = C.AzAnimationIterationCount_count(1), timing = C.AzAnimationTiming_linear(), clip = true }) }), 1) } }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_animation(ffi.new('AzStyleAnimationVecValue', { Exact = { tag = 6, payload = C.AzStyleAnimationVec_copyFromPtr(ffi.new('AzStyleAnimation[1]', { ffi.new('AzStyleAnimation', { name = azul._az_string("fadeIn"), duration = ffi.new('AzCssDuration', { inner = 300, unit = C.AzCssDurationUnit_Milliseconds }), delay = ffi.new('AzCssDuration', { inner = 0, unit = C.AzCssDurationUnit_Milliseconds }), iterations = C.AzAnimationIterationCount_count(1), timing = C.AzAnimationTiming_easeInOut(), clip = true }) }), 1) } }))),
    }), 3)
end

return M
