-- Generated by azul-css codegen (Lua). Do not edit by hand.
local azul = require('azul')
local ffi = require('ffi')
local C = azul.C

local M = {}

-- CSS: .hero
function M.style_hero()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[8]', {
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_backgroundContent(
                C.AzStyleBackgroundContentVec_copyFromPtr(ffi.new('AzStyleBackgroundContent[1]', {
                    C.AzStyleBackgroundContent_linearGradient(
                        ffi.new(
                            'AzLinearGradient',
                            {
                                direction = C.AzDirection_angle(ffi.new('AzAngleValue', { metric = C.AzAngleMetric_Degree, number = C.AzFloatValue_create(135.0) })),
                                extend_mode = C.AzExtendMode_Clamp,
                                stops = C.AzNormalizedLinearColorStopVec_copyFromPtr(ffi.new('AzNormalizedLinearColorStop[3]', {
                                    ffi.new('AzNormalizedLinearColorStop', { offset = ffi.new('AzPercentageValue', { number = C.AzFloatValue_create(0.0) }), color = C.AzColorOrSystem_color(ffi.new('AzColorU', { r = 255, g = 0, b = 0, a = 255 })) }),
                                    ffi.new('AzNormalizedLinearColorStop', { offset = ffi.new('AzPercentageValue', { number = C.AzFloatValue_create(50.0) }), color = C.AzColorOrSystem_color(ffi.new('AzColorU', { r = 0, g = 255, b = 0, a = 255 })) }),
                                    ffi.new('AzNormalizedLinearColorStop', { offset = ffi.new('AzPercentageValue', { number = C.AzFloatValue_create(100.0) }), color = C.AzColorOrSystem_color(ffi.new('AzColorU', { r = 0, g = 0, b = 255, a = 255 })) }),
                                }), 3),
                            }
                        )
                    ),
                }), 1)
            )
        ),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_boxShadowLeft(ffi.new('AzStyleBoxShadow', { offset_x = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(0.0) }), offset_y = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(4.0) }), blur_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(12.0) }), spread_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(2.0) }), clip_mode = C.AzBoxShadowClipMode_Outset, color = ffi.new('AzColorU', { r = 0, g = 0, b = 0, a = 77 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_boxShadowRight(ffi.new('AzStyleBoxShadow', { offset_x = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(0.0) }), offset_y = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(4.0) }), blur_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(12.0) }), spread_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(2.0) }), clip_mode = C.AzBoxShadowClipMode_Outset, color = ffi.new('AzColorU', { r = 0, g = 0, b = 0, a = 77 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_boxShadowTop(ffi.new('AzStyleBoxShadow', { offset_x = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(0.0) }), offset_y = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(4.0) }), blur_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(12.0) }), spread_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(2.0) }), clip_mode = C.AzBoxShadowClipMode_Outset, color = ffi.new('AzColorU', { r = 0, g = 0, b = 0, a = 77 }) }))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_boxShadowBottom(ffi.new('AzStyleBoxShadow', { offset_x = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(0.0) }), offset_y = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(4.0) }), blur_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(12.0) }), spread_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(2.0) }), clip_mode = C.AzBoxShadowClipMode_Outset, color = ffi.new('AzColorU', { r = 0, g = 0, b = 0, a = 77 }) }))),
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_transform(
                C.AzStyleTransformVec_copyFromPtr(ffi.new('AzStyleTransform[4]', {
                    C.AzStyleTransform_translate(ffi.new('AzStyleTransformTranslate2D', { x = C.AzPixelValue_px(10.0), y = C.AzPixelValue_px(20.0) })),
                    C.AzStyleTransform_rotate(ffi.new('AzAngleValue', { metric = C.AzAngleMetric_Degree, number = C.AzFloatValue_create(45.0) })),
                    C.AzStyleTransform_scale(ffi.new('AzStyleTransformScale2D', { x = C.AzFloatValue_create(1.5), y = C.AzFloatValue_create(1.5) })),
                    C.AzStyleTransform_skew(ffi.new('AzStyleTransformSkew2D', { x = ffi.new('AzAngleValue', { metric = C.AzAngleMetric_Degree, number = C.AzFloatValue_create(10.0) }), y = ffi.new('AzAngleValue', { metric = C.AzAngleMetric_Degree, number = C.AzFloatValue_create(5.0) }) })),
                }), 4)
            )
        ),
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_filter(
                ffi.new(
                    'AzStyleFilterVecValue',
                    {
                        Exact = {
                            tag = 6,
                            payload = C.AzStyleFilterVec_copyFromPtr(ffi.new('AzStyleFilter[3]', {
                                C.AzStyleFilter_blur(ffi.new('AzStyleBlur', { width = C.AzPixelValue_px(4.0), height = C.AzPixelValue_px(4.0) })),
                                C.AzStyleFilter_grayscale(ffi.new('AzPercentageValue', { number = C.AzFloatValue_create(50.0) })),
                                C.AzStyleFilter_dropShadow(ffi.new('AzStyleBoxShadow', { offset_x = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(2.0) }), offset_y = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(2.0) }), blur_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(4.0) }), spread_radius = ffi.new('AzPixelValueNoPercent', { inner = C.AzPixelValue_px(0.0) }), clip_mode = C.AzBoxShadowClipMode_Outset, color = ffi.new('AzColorU', { r = 0, g = 0, b = 0, a = 255 }) })),
                            }), 3)
                        }
                    }
                )
            )
        ),
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_backdropFilter(
                ffi.new(
                    'AzStyleFilterVecValue',
                    {
                        Exact = {
                            tag = 6,
                            payload = C.AzStyleFilterVec_copyFromPtr(ffi.new('AzStyleFilter[2]', {
                                C.AzStyleFilter_brightness(ffi.new('AzPercentageValue', { number = C.AzFloatValue_create(120.0) })),
                                C.AzStyleFilter_contrast(ffi.new('AzPercentageValue', { number = C.AzFloatValue_create(80.0) })),
                            }), 2)
                        }
                    }
                )
            )
        ),
    }), 8)
end

-- CSS: .halo
function M.style_halo()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[1]', {
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_backgroundContent(
                C.AzStyleBackgroundContentVec_copyFromPtr(ffi.new('AzStyleBackgroundContent[1]', {
                    C.AzStyleBackgroundContent_radialGradient(
                        ffi.new(
                            'AzRadialGradient',
                            {
                                shape = C.AzShape_Circle,
                                size = C.AzRadialGradientSize_FarthestCorner,
                                position = ffi.new('AzStyleBackgroundPosition', { horizontal = C.AzBackgroundPositionHorizontal_left(), vertical = C.AzBackgroundPositionVertical_top() }),
                                extend_mode = C.AzExtendMode_Clamp,
                                stops = C.AzNormalizedLinearColorStopVec_copyFromPtr(ffi.new('AzNormalizedLinearColorStop[2]', {
                                    ffi.new('AzNormalizedLinearColorStop', { offset = ffi.new('AzPercentageValue', { number = C.AzFloatValue_create(0.0) }), color = C.AzColorOrSystem_color(ffi.new('AzColorU', { r = 255, g = 255, b = 255, a = 255 })) }),
                                    ffi.new('AzNormalizedLinearColorStop', { offset = ffi.new('AzPercentageValue', { number = C.AzFloatValue_create(100.0) }), color = C.AzColorOrSystem_color(ffi.new('AzColorU', { r = 0, g = 0, b = 0, a = 255 })) }),
                                }), 2),
                            }
                        )
                    ),
                }), 1)
            )
        ),
    }), 1)
end

-- CSS: .dial
function M.style_dial()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[1]', {
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_backgroundContent(
                C.AzStyleBackgroundContentVec_copyFromPtr(ffi.new('AzStyleBackgroundContent[1]', {
                    C.AzStyleBackgroundContent_conicGradient(
                        ffi.new(
                            'AzConicGradient',
                            {
                                extend_mode = C.AzExtendMode_Clamp,
                                center = ffi.new('AzStyleBackgroundPosition', { horizontal = C.AzBackgroundPositionHorizontal_left(), vertical = C.AzBackgroundPositionVertical_top() }),
                                angle = ffi.new('AzAngleValue', { metric = C.AzAngleMetric_Degree, number = C.AzFloatValue_create(90.0) }),
                                stops = C.AzNormalizedRadialColorStopVec_copyFromPtr(ffi.new('AzNormalizedRadialColorStop[2]', {
                                    ffi.new('AzNormalizedRadialColorStop', { angle = ffi.new('AzAngleValue', { metric = C.AzAngleMetric_Degree, number = C.AzFloatValue_create(0.0) }), color = C.AzColorOrSystem_color(ffi.new('AzColorU', { r = 255, g = 0, b = 0, a = 255 })) }),
                                    ffi.new('AzNormalizedRadialColorStop', { angle = ffi.new('AzAngleValue', { metric = C.AzAngleMetric_Degree, number = C.AzFloatValue_create(360.0) }), color = C.AzColorOrSystem_color(ffi.new('AzColorU', { r = 0, g = 0, b = 255, a = 255 })) }),
                                }), 2),
                            }
                        )
                    ),
                }), 1)
            )
        ),
    }), 1)
end

-- CSS: .photo
function M.style_photo()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[4]', {
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_backgroundContent(C.AzStyleBackgroundContentVec_copyFromPtr(ffi.new('AzStyleBackgroundContent[1]', { C.AzStyleBackgroundContent_image(azul._az_string("images/photo.png")) }), 1))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_backgroundSize(C.AzStyleBackgroundSizeVec_copyFromPtr(ffi.new('AzStyleBackgroundSize[1]', { C.AzStyleBackgroundSize_cover() }), 1))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_backgroundPosition(C.AzStyleBackgroundPositionVec_copyFromPtr(ffi.new('AzStyleBackgroundPosition[1]', { ffi.new('AzStyleBackgroundPosition', { horizontal = C.AzBackgroundPositionHorizontal_center(), vertical = C.AzBackgroundPositionVertical_center() }) }), 1))),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_backgroundRepeat(C.AzStyleBackgroundRepeatVec_copyFromPtr(ffi.new('AzStyleBackgroundRepeat[1]', { C.AzStyleBackgroundRepeat_NoRepeat }), 1))),
    }), 4)
end

-- CSS: .caption
function M.style_caption()
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(ffi.new('AzCssPropertyWithConditions[2]', {
        C.AzCssPropertyWithConditions_simple(
            C.AzCssProperty_fontFamily(
                C.AzStyleFontFamilyVec_copyFromPtr(ffi.new('AzStyleFontFamily[2]', {
                    C.AzStyleFontFamily_system(azul._az_string("Fira Code")),
                    C.AzStyleFontFamily_system(azul._az_string("monospace")),
                }), 2)
            )
        ),
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_content(ffi.new('AzContent', { inner = azul._az_string("\"say \\\"hi\\\" \\\\ bye\"") }))),
    }), 2)
end

return M
