//! Android backend using NativeActivity + the `android-activity` crate.
//!
//! Mirrors the structure of `headless/mod.rs` — a `CpuBackend` does layout-driven
//! CPU rendering into an `AzulPixmap`, then we blit those pixels into an
//! `ANativeWindow` lock buffer (`ANativeWindow_lock` → memcpy → `unlockAndPost`).
//!
//! There is **no Java/Kotlin code on the build path** for Phase 1-4. The whole
//! event loop, input handling, and rendering happens inside Rust via
//! `android-activity` (which provides the `android_main` entry point and the
//! `MainEvent`/`InputEvent` enums) plus `ndk` (for `NativeWindow_lock`).
//!
//! Soft-keyboard / IME support (Phase 5) needs a ~50-line Java JNI bridge that
//! is compiled with plain `javac` + `d8` — still no Gradle.

use std::{cell::RefCell, ffi::c_void, sync::Arc, time::Duration};

use azul_core::{
    callbacks::RelayoutReason,
    gl::OptionGlContextPtr,
    hit_test::DocumentId,
    icon::SharedIconProvider,
    refany::RefAny,
    resources::{AppConfig, IdNamespace, ImageCache, RendererResources},
    window::{AndroidHandle, RawWindowHandle},
};
use azul_layout::{
    window::{LayoutWindow, ScrollbarDragState},
    window_state::{FullWindowState, WindowCreateOptions},
};
use rust_fontconfig::{registry::FcFontRegistry, FcFontCache};

use crate::desktop::shell2::common::{
    debug_server::LogCategory,
    event::{self, CommonWindowState, HitTestNode, PlatformWindow},
    WindowError,
};
use crate::desktop::shell2::headless::CpuBackend;
use crate::desktop::wr_translate2::{AsyncHitTester, WrRenderApi};
use crate::{impl_platform_window_getters, log_debug, log_error, log_info};

pub mod accessibility;

#[cfg(feature = "android-activity")]
use android_activity::{
    input::{Axis, InputEvent, KeyAction, Keycode, MotionAction, ToolType},
    AndroidApp, InputStatus, MainEvent, PollEvent,
};
#[cfg(feature = "ndk")]
use ndk::native_window::NativeWindow;

/// Events generated by the Android backend (currently only the close signal).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AndroidEvent {
    Close,
}

/// Rendering backend selector. CPU only on day 1 (mirrors the headless backend).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RenderBackend {
    Cpu,
}

/// Android platform window backed by an `ANativeWindow`.
///
/// The window pointer is `None` while the activity is in the background
/// (`MainEvent::TerminateWindow` fires before `Pause`). All rendering and hit
/// testing must be guarded against that case.
pub struct AndroidWindow {
    /// Cross-platform window state (layout, resources, event diffing).
    pub common: CommonWindowState,
    /// CPU rendering backend (replaces WebRender).
    pub cpu_backend: CpuBackend,
    /// Currently-attached `ANativeWindow`. Released on `TerminateWindow`.
    #[cfg(feature = "ndk")]
    pub native_window: Option<NativeWindow>,
    /// Rendering backend selector (always Cpu for now).
    pub backend: RenderBackend,
    /// `false` once `MainEvent::Destroy` arrives; breaks the outer loop.
    pub is_open: bool,
    /// Theme change queued by the Java-UI-thread JNI hook
    /// (`nativeOnUiModeChanged`), drained on the LOOP thread each iteration.
    /// Encoding matches the JNI contract: 0 = none pending, 1 = light,
    /// 2 = dark. The Java thread must never mutate window state or run a
    /// pass itself — that is what left a live delta for the validation check
    /// and raced the loop's own reads.
    pub pending_theme: std::sync::atomic::AtomicI32,
    /// Shared icon provider — needed by `regenerate_layout()` so widgets
    /// (notably button/icon containers) can resolve `IconReference`s.
    pub icon_provider: SharedIconProvider,
    /// Shared font registry for async font discovery / loading.
    /// `None` means the registry was never installed; defaults to disabled.
    pub font_registry: Option<Arc<FcFontRegistry>>,
    /// `AccessibilityNodeProvider` bridge: the virtual-view tree TalkBack
    /// reads and the queue the actions it performs land in. Hand-written
    /// because `accesskit` has no Android adapter.
    ///
    /// Read from the Java UI thread via JNI while the loop thread writes it,
    /// which is why its state is behind a lock and why nothing in it touches
    /// the `LayoutWindow`.
    pub accessibility_adapter: accessibility::AndroidAccessibilityAdapter,
}

impl AndroidWindow {
    /// Construct a window with no native surface attached yet.
    /// `InitWindow` later swaps in the real `ANativeWindow`.
    pub fn new(
        options: WindowCreateOptions,
        fc_cache: Arc<FcFontCache>,
        mut config: AppConfig,
        app_data: RefAny,
        undo_manager: event::SharedUndoManager,
        font_registry: Option<Arc<FcFontRegistry>>,
    ) -> Result<Self, WindowError> {
        // `WindowCreateOptions::window_state` is already a `FullWindowState`,
        // mirroring how `HeadlessWindow::new` consumes it. No constructor call.
        let full_window_state = options.window_state;

        // Extract the SharedIconProvider out of the config (same pattern
        // as run_headless) so we can pass it to regenerate_layout later.
        let icon_provider_handle = core::mem::take(&mut config.icon_provider);
        let icon_provider = SharedIconProvider::from_handle(icon_provider_handle);

        let mut layout_window = LayoutWindow::new(fc_cache.as_ref().clone())
            .map_err(|e| WindowError::PlatformError(format!("Layout init failed: {:?}", e)))?;
        layout_window.current_window_state = full_window_state.clone();
        layout_window.routes = config.routes.clone();

        let mut common = CommonWindowState::new(
            full_window_state,
            fc_cache,
            Arc::new(azul_css::system::SystemStyle::default()),
            Arc::new(RefCell::new(app_data)),
            undo_manager,
        );
        common.layout_window = Some(layout_window);
        common.cpu_hit_tester = Some(azul_layout::headless::CpuHitTester::new());

        Ok(Self {
            common,
            cpu_backend: CpuBackend::new(),
            #[cfg(feature = "ndk")]
            native_window: None,
            backend: RenderBackend::Cpu,
            is_open: true,
            pending_theme: std::sync::atomic::AtomicI32::new(0),
            icon_provider,
            font_registry,
            accessibility_adapter: accessibility::AndroidAccessibilityAdapter::new(),
        })
    }

    pub fn is_open(&self) -> bool {
        self.is_open
    }

    /// Drain the accessibility actions TalkBack queued and apply them.
    ///
    /// Mirrors `Win32Window::process_accessibility_actions` /
    /// `X11Window::process_accessibility_actions`: poll the adapter, route each
    /// action through `LayoutWindow::process_accessibility_action`, dispatch the
    /// callbacks it maps to, honour the `Update` they return. Android had NO
    /// such method, so even once the provider existed a `performAction` would
    /// have had nowhere to go.
    ///
    /// Runs on the loop thread, never in the JNI upcall: `performAction`
    /// arrives on the Java UI thread, and mutating the `LayoutWindow` from
    /// there would race the frame loop.
    #[cfg(feature = "a11y")]
    pub fn process_accessibility_actions(&mut self) {
        let mut actions = Vec::new();
        while let Some(action) = self.accessibility_adapter.poll_action() {
            actions.push(action);
        }
        if actions.is_empty() {
            return;
        }
        self.dispatch_accessibility_actions(actions);
        // Unconditional, like every desktop backend's `request_redraw()`:
        // Focus / Blur / the Scroll* family map to no callback and return an
        // empty affected set while having genuinely changed the screen.
        self.common
            .request_regeneration(azul_core::callbacks::RelayoutReason::RefreshDom);
    }

    /// Rebuild the virtual-view tree the Java provider reads.
    ///
    /// Android's equivalent of the desktop backends' `adapter.update_tree()`.
    /// The Java side is additionally told to invalidate, so TalkBack re-reads
    /// instead of highlighting where things used to be.
    #[cfg(feature = "a11y")]
    fn refresh_accessibility_tree(&mut self) {
        let Some(lw) = self.common.layout_window.as_ref() else {
            return;
        };
        let snapshot = lw.build_a11y_snapshot();
        // Android wants physical pixels. `android_main` derives the framework
        // dpi as `density * 96 / 160`, so the android scale (`density / 160`)
        // is exactly `dpi / 96` — the same factor everything else here uses.
        let scale = self.common.current_window_state().size.dpi as f32 / 96.0;
        self.accessibility_adapter.update_snapshot(snapshot, scale);
        self.common.a11y_dirty = false;
    }
    pub fn close(&mut self) {
        // See CommonWindowState::deinit_renderer — webrender requires it.
        self.common.deinit_renderer();
        self.is_open = false;
    }

    /// Run a full layout regeneration pass and CPU-render the resulting
    /// display list. Mirrors `HeadlessWindow::regenerate_layout()`; the
    /// lifecycle-event dispatch step is skipped for now (Android backend
    /// has no callback driver yet — pending sprint H).
    pub fn regenerate_layout_inner(
        &mut self,
    ) -> Result<crate::desktop::shell2::common::layout::LayoutRegenerateResult, String> {
        // Captured BEFORE the pass: `regenerate_layout` (the trait wrapper that
        // calls this) drains lifecycle callbacks between passes, and one of
        // those returning `Update::RefreshDom` raises a NEW request. Retiring
        // by epoch at the end means this pass only retires the request it
        // actually saw.
        let regen_epoch_seen = self.common.regen_epoch();

        // Consume the reason tag BEFORE borrowing the layout window: this is
        // the regeneration this window asked for, and the tag travels with
        // the request (see CommonWindowState::request_regeneration).
        let relayout_reason = self.common.take_relayout_reason();

        let borrows = self.common.layout_borrows();
        let layout_window = borrows.layout_window.ok_or("No layout window")?;

        let debug_enabled = crate::desktop::shell2::common::debug_server::is_debug_enabled();
        let mut debug_messages = if debug_enabled {
            Some(Vec::new())
        } else {
            None
        };

        let result = crate::desktop::shell2::common::layout::regenerate_layout(
            layout_window,
            borrows.app_data,
            borrows.current_window_state,
            borrows.renderer_resources,
            borrows.gl_context_ptr,
            borrows.fc_cache,
            &self.font_registry,
            borrows.system_style,
            &self.icon_provider,
            &mut debug_messages,
            relayout_reason,
        )?;

        if let Some(msgs) = debug_messages {
            for msg in msgs {
                crate::desktop::shell2::common::debug_server::log(
                    crate::desktop::shell2::common::debug_server::LogLevel::Debug,
                    crate::desktop::shell2::common::debug_server::LogCategory::Layout,
                    msg.message.as_str().to_string(),
                    None,
                );
            }
        }

        // Rebuild CPU hit-tester from new layout results
        if let Some(lw) = self.common.layout_window.as_ref() {
            self.cpu_backend
                .hit_tester
                .rebuild_from_layout_with_gpu(&lw.layout_results, Some(&lw.gpu_state_manager));
        }

        // Drain lifecycle events (Mount / AfterMount / Unmount) produced by this
        // layout's reconciliation — the SAME step headless + X11 run. Without it,
        // EventFilter::Component(AfterMount) callbacks never fire on Android (e.g.
        // the MapWidget's first tile fetch never starts).

        // #27 native backbuffer: Android stays LEGACY by design.
        // `ANativeWindow_lock` rotates double/triple buffers with NO content
        // guarantee and no way to preserve a buffer's pixels across cycles
        // (NDK-documented), so the renderer's incremental base would be
        // garbage. Going native needs the Wayland slot model keyed by the
        // returned bits pointer (per-buffer stale tracking + the in/out
        // dirty-bounds contract); design when a device run exists to verify.
        //
        // CPU-render the frame — populates `self.cpu_backend.last_frame`
        // so the next `render_frame()` call can blit pixels.
        #[cfg(feature = "cpurender")]
        {
            let ws = self.common.current_window_state();
            let width = ws.size.dimensions.width;
            let height = ws.size.dimensions.height;
            let dpi = ws.size.dpi as f32 / 96.0;
            // Shared per-frame content preparation (journal clock, image
            // callbacks through the content chokepoint, scrollbar cache).
            // Before this, image callbacks were NEVER invoked on this host —
            // every callback image rendered as the announced grey placeholder.
            if let Some(lw) = self.common.layout_window.as_mut() {
                lw.prepare_frame_cpu();
            }
            if let Some(lw) = self.common.layout_window.as_ref() {
                self.cpu_backend.render_frame(
                    lw,
                    &self.common.renderer_resources,
                    width,
                    height,
                    dpi,
                );
            }
        }

        // Republish the virtual-view tree. Bounds, labels and the focused node
        // all just changed and TalkBack reads a cached tree, so without this it
        // keeps announcing (and highlighting) the previous layout.
        #[cfg(feature = "a11y")]
        self.refresh_accessibility_tree();

        self.common
            .clear_regeneration_unless_reraised(regen_epoch_seen);
        Ok(result)
    }
}

impl PlatformWindow for AndroidWindow {
    fn regenerate_layout_once(
        &mut self,
    ) -> Result<crate::desktop::shell2::common::layout::LayoutRegenerateResult, String> {
        // The single pass. The bounded lifecycle loop lives in the trait
        // default `regenerate_layout`, which is what frame paths call.
        self.regenerate_layout_inner()
    }

    impl_platform_window_getters!(common);

    fn get_raw_window_handle(&self) -> RawWindowHandle {
        #[cfg(feature = "ndk")]
        let ptr = self
            .native_window
            .as_ref()
            .map(|nw| nw.ptr().as_ptr() as *mut c_void)
            .unwrap_or(std::ptr::null_mut());
        #[cfg(not(feature = "ndk"))]
        let ptr = std::ptr::null_mut();

        RawWindowHandle::Android(AndroidHandle {
            a_native_window: ptr,
        })
    }

    fn prepare_callback_invocation(&mut self) -> event::InvokeSingleCallbackBorrows<'_> {
        let borrows = self.common.layout_borrows();
        event::InvokeSingleCallbackBorrows {
            layout_window: borrows
                .layout_window
                .expect("Layout window must exist for callback invocation"),
            window_handle: RawWindowHandle::Android(AndroidHandle {
                a_native_window: std::ptr::null_mut(),
            }),
            gl_context_ptr: borrows.gl_context_ptr,
            fc_cache_clone: (**borrows.fc_cache).clone(),
            system_style: borrows.system_style.clone(),
            previous_window_state: borrows.previous_window_state,
            current_window_state: borrows.current_window_state,
            renderer_resources: borrows.renderer_resources,
        }
    }

    fn start_timer(&mut self, timer_id: usize, timer: azul_layout::timer::Timer) {
        if let Some(lw) = self.common.layout_window.as_mut() {
            lw.timers
                .insert(azul_core::task::TimerId { id: timer_id }, timer);
        }
    }
    fn stop_timer(&mut self, timer_id: usize) {
        if let Some(lw) = self.common.layout_window.as_mut() {
            lw.timers.remove(&azul_core::task::TimerId { id: timer_id });
        }
    }
    fn start_thread_poll_timer(&mut self) {}
    fn stop_thread_poll_timer(&mut self) {}

    fn add_threads(
        &mut self,
        threads: std::collections::BTreeMap<azul_core::task::ThreadId, azul_layout::thread::Thread>,
    ) {
        if let Some(lw) = self.common.layout_window.as_mut() {
            for (id, thread) in threads {
                lw.threads.insert(id, thread);
            }
        }
    }
    fn remove_threads(
        &mut self,
        thread_ids: &std::collections::BTreeSet<azul_core::task::ThreadId>,
    ) {
        if let Some(lw) = self.common.layout_window.as_mut() {
            for id in thread_ids {
                lw.threads.remove(id);
            }
        }
    }

    fn queue_window_create(&mut self, _options: WindowCreateOptions) {
        // No popup windows on Android; ignored. Sub-activities are a future
        // enhancement and would require launching new Intents from Java.
    }

    fn show_menu_from_callback(
        &mut self,
        _menu: &azul_core::menu::Menu,
        _position: azul_core::geom::LogicalPosition,
        _anchor: Option<azul_core::geom::LogicalRect>,
    ) {
    }

    fn show_tooltip_from_callback(
        &mut self,
        _text: &str,
        _position: azul_core::geom::LogicalPosition,
    ) {
    }

    fn hide_tooltip_from_callback(&mut self) {}

    /// The activity owns the window geometry outright, so there is nothing to
    /// push and no OS-sync baseline to diff (`os_synced_state` stays `None`).
    fn sync_window_state(&mut self) {}
}

// ---------------------------------------------------------------------------
// android_main entry point (called by the NativeActivity glue thread)
// ---------------------------------------------------------------------------

/// `android_main` is the entry point that the `android-activity` crate's
/// `ANativeActivity_onCreate` shim invokes on the Android UI thread.
///
/// The user's `azul_run(app_data, ...)` call stashes `INITIAL_OPTIONS` into a
/// global static *before* the dylib hands control to `ANativeActivity_onCreate`,
/// so by the time we get here the options are ready.
#[cfg(all(target_os = "android", feature = "android-activity"))]
#[no_mangle]
pub fn android_main(app: AndroidApp) {
    log_info!(LogCategory::EventLoop, "[Android] android_main entered");

    // Retrieve initial options stashed by `run()`
    let (app_data, undo_manager, config, fc_cache, font_registry, root_window) = unsafe {
        match crate::desktop::shell2::run::ANDROID_INITIAL_OPTIONS.take() {
            Some(opts) => opts,
            None => {
                log_error!(
                    LogCategory::EventLoop,
                    "[Android] android_main called without INITIAL_OPTIONS set — \
                     did azul_run() run first?",
                );
                return;
            }
        }
    };

    let mut window = match AndroidWindow::new(
        root_window,
        fc_cache,
        config,
        app_data,
        undo_manager,
        font_registry,
    ) {
        Ok(w) => w,
        Err(e) => {
            log_error!(
                LogCategory::EventLoop,
                "[Android] AndroidWindow::new failed: {:?}",
                e
            );
            return;
        }
    };

    // Publish the window address so AzulActivity.onWindowFocusChanged can
    // hand it to NativeGestureBridge. `&mut window` is stable for the
    // duration of this function (window stays on the stack frame). Once
    // AzulActivity has constructed the bridge, the Java side never
    // dereferences the pointer except from JNI callbacks that this same
    // thread eventually processes via MainEvent::InputAvailable.
    ANDROID_WINDOW_PTR.store(
        &mut window as *mut AndroidWindow as i64,
        core::sync::atomic::Ordering::SeqCst,
    );

    // Publish the JavaVM + Activity pointers so dll::extra::file_picker
    // (and future native-call paths — permission, soft keyboard) can
    // reach into Java without re-receiving them per call.
    publish_jni_context(&app);

    // Outer driver loop — exits when MainEvent::Destroy clears window.is_open.
    while window.is_open() {
        // Block forever when we have no native surface (background); poll
        // at frame rate when we do (foreground rendering).
        let timeout = {
            #[cfg(feature = "ndk")]
            {
                if window.native_window.is_some() {
                    Some(Duration::from_millis(16))
                } else {
                    None
                }
            }
            #[cfg(not(feature = "ndk"))]
            {
                Some(Duration::from_millis(16))
            }
        };

        app.poll_events(timeout, |event| {
            handle_poll_event(&app, &mut window, event);
        });

        // Timers, Thread writebacks and animations. This call had NO call site
        // on Android at all, so nothing time-driven ever ran here: no Timer
        // fired, no background Thread result was ever collected, and no
        // animation advanced. The 16 ms poll above was already the right place
        // to drive it; it simply was never wired.
        if window.process_timers_and_threads() {
            window
                .common
                .request_regeneration(RelayoutReason::RefreshDom);
        }

        // Accessibility actions arrive off-loop: TalkBack calls
        // `AccessibilityNodeProvider.performAction` on the Java UI thread, which
        // only QUEUES the action (mutating the LayoutWindow from there would
        // race this loop). This is where they get applied — the same per-frame
        // slot `run.rs` gives the four desktop backends.
        #[cfg(feature = "a11y")]
        window.process_accessibility_actions();

        // Regenerate layout when something invalidated the frame (init,
        // resize, input). Populates cpu_backend.last_frame.
        // Drain the Java-thread theme queue on the loop thread: snapshot →
        // mutate → pass, like every other OS-state change.
        drain_pending_theme(&mut window);

        let mut frame_dirty = false;
        if window.common.regeneration_pending() {
            match window.regenerate_layout() {
                Ok(_) => frame_dirty = true,
                Err(e) => {
                    log_error!(
                        LogCategory::Layout,
                        "[Android] regenerate_layout failed: {}",
                        e
                    );
                }
            }
        }

        // Present ONLY when this iteration produced a frame. The loop wakes
        // every 16 ms for timers, and presenting unconditionally locked,
        // full-copied (~10 MB at 1080p RGBA) and unlockAndPost'ed an
        // identical buffer on every wake — keeping SurfaceFlinger compositing
        // at 60 Hz while the app sat idle. Everything that changes what is on
        // screen funnels through request_regeneration (input, timers, thread
        // writebacks, a11y, InitWindow, RedrawNeeded), so a clean iteration
        // has nothing new to post.
        if frame_dirty {
            let _ = render_frame(&mut window);
        }
    }

    log_info!(
        LogCategory::EventLoop,
        "[Android] android_main exiting cleanly"
    );
}

/// The reason tag for a geometry/density-driven regeneration.
///
/// `Resize` is what every desktop backend tags window resizes with — it is the
/// variant responsive layout callbacks branch on (see the enum's own doc) —
/// and Android tagged them all `RefreshDom`, so a breakpoint-style layout
/// could never distinguish a rotation from an app-state change. The one
/// exception is the very first pass: `RegenerationState::pending_initial` is
/// already queued as `Initial` and the user's layout callback must see THAT,
/// so return the implicit `RefreshDom` (which `request_regeneration` never
/// lets overwrite a more specific queued reason) while it is still pending.
/// Apply a theme change queued by the Java UI thread (see `pending_theme`).
/// Runs on the loop thread: contract shape (snapshot → mutate → pass), so
/// `ThemeChanged` dispatches and no live delta is left behind.
#[cfg(all(target_os = "android", feature = "android-activity"))]
fn drain_pending_theme(window: &mut AndroidWindow) {
    let raw = window
        .pending_theme
        .swap(0, std::sync::atomic::Ordering::AcqRel);
    let theme = match raw {
        1 => azul_core::window::WindowTheme::LightMode,
        2 => azul_core::window::WindowTheme::DarkMode,
        _ => return,
    };
    if window.common.current_window_state().theme == theme {
        return;
    }
    window.snapshot_window_state_baseline("android.drain_pending_theme");
    window.common.update_unsynced_state(|ws| ws.theme = theme);
    window
        .common
        .request_regeneration(RelayoutReason::ThemeChange);
    let _ = window.process_window_events(0);
}

#[cfg(all(target_os = "android", feature = "android-activity"))]
fn resize_reason(window: &AndroidWindow) -> RelayoutReason {
    if window.common.regeneration_pending()
        && window.common.regeneration_reason() == RelayoutReason::Initial
    {
        RelayoutReason::RefreshDom
    } else {
        RelayoutReason::Resize
    }
}

#[cfg(all(target_os = "android", feature = "android-activity"))]
fn handle_poll_event(app: &AndroidApp, window: &mut AndroidWindow, event: PollEvent<'_>) {
    match event {
        PollEvent::Main(main_event) => match main_event {
            MainEvent::InitWindow { .. } => {
                // Contract shape (snapshot → mutate → pass): Android never
                // dispatched WindowResize/WindowDpiChanged — these arms wrote
                // geometry with no snapshot and no pass, so the diff either
                // never existed or tripped the validation check later.
                window.snapshot_window_state_baseline("android.main_event.init_window");
                // Sync the framework's window state to the native
                // surface: physical dimensions + DPI. azul-layout uses
                // 96 as the "1x" baseline (CSS pixel = 1/96 inch), so
                // Android's density-dpi (160 = mdpi = 1x) must be
                // scaled by 96/160 = 0.6 before we hand it over:
                //   mdpi 160 -> 96, xhdpi 320 -> 192, xxhdpi 480 -> 288.
                // The drain_input physical-to-logical scale below
                // separately uses density / 160 directly (which is the
                // Android-native scale factor, not the framework's).
                let density = app.config().density().filter(|&d| d > 0).unwrap_or(160);
                let dpi = ((density as f32) * 96.0 / 160.0).round() as u32;
                window
                    .common
                    .update_window_state(event::WindowStateSource::Os, |ws| {
                        ws.size.dpi = dpi.max(1);
                    });
                #[cfg(feature = "ndk")]
                {
                    if let Some(nw) = app.native_window() {
                        // Logical = physical / android-scale, where
                        // android-scale = density / 160 (NOT dpi/96).
                        let android_scale = (density as f32) / 160.0;
                        let logical_w = (nw.width() as f32) / android_scale;
                        let logical_h = (nw.height() as f32) / android_scale;
                        log_debug!(
                            LogCategory::Window,
                            "[Android] InitWindow physical={}x{} density={} (azul dpi={}) logical={}x{}",
                            nw.width(), nw.height(), density, dpi, logical_w, logical_h,
                        );
                        window
                            .common
                            .update_window_state(event::WindowStateSource::Os, |ws| {
                                ws.size.dimensions.width = logical_w;
                                ws.size.dimensions.height = logical_h;
                            });
                        window.native_window = Some(nw);
                        // On the launch InitWindow this preserves the queued
                        // `Initial`; on a re-attach (rotation recreates the
                        // surface with new dimensions and does NOT deliver
                        // WindowResized) it tags the pass `Resize`.
                        let reason = resize_reason(window);
                        window.common.request_regeneration(reason);
                    }
                }
                let _ = window.process_window_events(0);
            }
            MainEvent::TerminateWindow { .. } => {
                log_debug!(LogCategory::Window, "[Android] TerminateWindow");
                #[cfg(feature = "ndk")]
                {
                    window.native_window = None;
                }
            }
            MainEvent::WindowResized { .. } => {
                // Contract shape (snapshot → mutate → pass) — see InitWindow.
                window.snapshot_window_state_baseline("android.main_event.window_resized");
                #[cfg(feature = "ndk")]
                {
                    if let Some(nw) = window.native_window.as_ref() {
                        let density = app.config().density().filter(|&d| d > 0).unwrap_or(160);
                        let android_scale = (density as f32) / 160.0;
                        window
                            .common
                            .update_window_state(event::WindowStateSource::Os, |ws| {
                                ws.size.dimensions.width = (nw.width() as f32) / android_scale;
                                ws.size.dimensions.height = (nw.height() as f32) / android_scale;
                            });
                    }
                }
                let reason = resize_reason(window);
                window.common.request_regeneration(reason);
                let _ = window.process_window_events(0);
            }
            MainEvent::ConfigChanged { .. } => {
                // Density can change while running: fold/unfold, moving the
                // app to an external display, the user's display-size setting.
                // WindowResized alone misses pure-density changes (same
                // surface size, different scale), which left every
                // physical<->logical conversion — layout dpi, input scaling,
                // a11y bounds — on the stale factor.
                let density = app.config().density().filter(|&d| d > 0).unwrap_or(160);
                let dpi = (((density as f32) * 96.0 / 160.0).round() as u32).max(1);
                if window.common.current_window_state().size.dpi != dpi {
                    // Contract shape (snapshot → mutate → pass) — the dpi
                    // diff is what dispatches WindowDpiChanged.
                    window.snapshot_window_state_baseline("android.main_event.config_changed");
                    let reason = resize_reason(window);
                    window
                        .common
                        .update_window_state(event::WindowStateSource::Os, |ws| {
                            ws.size.dpi = dpi;
                        });
                    #[cfg(feature = "ndk")]
                    if let Some(nw) = window.native_window.as_ref() {
                        let android_scale = (density as f32) / 160.0;
                        window
                            .common
                            .update_window_state(event::WindowStateSource::Os, |ws| {
                                ws.size.dimensions.width = (nw.width() as f32) / android_scale;
                                ws.size.dimensions.height = (nw.height() as f32) / android_scale;
                            });
                    }
                    window.common.request_regeneration(reason);
                    let _ = window.process_window_events(0);
                }
            }
            MainEvent::InputAvailable => {
                drain_input(app, window);
            }
            MainEvent::RedrawNeeded { .. } => {
                // The system needs the window's content re-posted (resume,
                // compositor state loss). Presents are gated on regeneration,
                // so raise the request — the regenerate takes the incremental
                // "nothing changed" path and the blit re-posts the pixmap.
                window
                    .common
                    .request_regeneration(RelayoutReason::RefreshDom);
            }
            MainEvent::Destroy => {
                window.close();
            }
            MainEvent::Pause | MainEvent::Resume { .. } => {
                // No-op for now; future: pause timers, stop animations.
            }
            _ => {}
        },
        _ => {}
    }
}

/// Drain the input queue once. Maps the first pointer of every motion event
/// to the mouse left button — enough for hover/click in the existing event
/// system; multi-touch (`TouchStart`/`TouchMove`/`TouchEnd`) is deferred.
#[cfg(all(target_os = "android", feature = "android-activity"))]
fn drain_input(app: &AndroidApp, window: &mut AndroidWindow) {
    use azul_core::geom::LogicalPosition;
    use azul_core::window::CursorPosition;

    let mut iter = match app.input_events_iter() {
        Ok(it) => it,
        Err(e) => {
            log_debug!(LogCategory::Input, "[Android] input_events_iter: {:?}", e);
            return;
        }
    };

    // dpi factor: device pixels per logical px. Android's baseline
    // density is 160 dpi (mdpi); a 480-dpi xxhdpi screen returns 480,
    // so logical = physical * (160/480) = physical * 0.333. Fall back
    // to 1.0 on the rare device that returns no density.
    let dpi = match app.config().density() {
        Some(d) if d > 0 => (d as f32) / 160.0_f32,
        _ => 1.0_f32,
    };

    // Collect state-update tuples first; do the actual state diff +
    // process_window_events outside the iterator's closure because the
    // closure borrows `app` for the input queue and we need &mut window.
    //
    // `mouse_pos` mirrors what the framework's mouse pipe sees: the
    // primary (index 0) pointer position. Multi-finger state lives on
    // `touch_points` below.
    struct MotionUpdate {
        action: MotionAction,
        mouse_pos: LogicalPosition,
        touch_points: Vec<azul_core::window::TouchPoint>,
    }
    let mut motion_updates: Vec<MotionUpdate> = Vec::new();
    // (KeyAction, Option<VirtualKeyCode>) — None for unmapped keycodes.
    let mut key_updates: Vec<(KeyAction, Option<azul_core::window::VirtualKeyCode>)> = Vec::new();
    // Pen / stylus samples — populated when any pointer in a MotionEvent
    // reports `ToolType::Stylus` or `ToolType::Eraser`. tilt is decomposed
    // into (x_tilt_deg, y_tilt_deg) so it matches the W3C
    // `PointerEvent.tiltX/tiltY` shape that the desktop pen-tablet path
    // uses too.
    struct PenSample {
        action: MotionAction,
        pos: LogicalPosition,
        pressure: f32,
        x_tilt_deg: f32,
        y_tilt_deg: f32,
        is_eraser: bool,
        barrel_button_pressed: bool,
    }
    let mut pen_updates: Vec<PenSample> = Vec::new();

    while iter.next(|event| {
        match event {
            InputEvent::MotionEvent(m) => {
                let mut mouse_pos = LogicalPosition::new(0.0, 0.0);
                let mut touch_points: Vec<azul_core::window::TouchPoint> = Vec::new();
                let mut first_pointer = true;

                // ACTION_POINTER_UP still lists the LIFTING finger in
                // pointers() — the classic index-vs-id trap's sibling. Keep it
                // out of touch_state or the lifted finger stays "touching"
                // until the next MOVE happens to rebuild the list.
                // MotionEvent::pointer_index() identifies which pointer the
                // action is about (only meaningful for the Down/Up family).
                let lifted_index = if matches!(m.action(), MotionAction::PointerUp) {
                    Some(m.pointer_index())
                } else {
                    None
                };

                for p in m.pointers() {
                    // Window-relative coordinates (AMotionEvent_getX/getY), NOT
                    // raw_x/raw_y: raw is DISPLAY-relative, so in split-screen /
                    // freeform / pop-up multi-window the window's offset shifted
                    // every touch and hit tests landed on the wrong node. The
                    // surface we render into lives in window space; getX/getY is
                    // the matching input space (they only coincide when the
                    // window sits at the display origin).
                    let pos = LogicalPosition::new(p.x() / dpi, p.y() / dpi);
                    if first_pointer {
                        mouse_pos = pos;
                        first_pointer = false;
                    }

                    // The finger this PointerUp is about is lifting — it still
                    // appears in pointers(), but it is no longer touching.
                    // (Stylus lift is handled separately below via the action.)
                    if Some(p.pointer_index()) != lifted_index {
                        let pressure = p.pressure();
                        let force = if pressure > 0.0 && pressure <= 1.0 {
                            pressure
                        } else {
                            0.5 // TouchPoint sentinel for "pressure not available"
                        };
                        touch_points.push(azul_core::window::TouchPoint {
                            id: p.pointer_id() as u64,
                            position: pos,
                            force,
                            // Contact geometry: 0.0 = not reported by this backend.
                            major: 0.0,
                            minor: 0.0,
                            orientation_rad: 0.0,
                            tool_type: azul_core::window::TouchToolType::Unknown,
                        });
                    }

                    let tool = p.tool_type();
                    if matches!(tool, ToolType::Stylus | ToolType::Eraser) {
                        let pressure = p.pressure().clamp(0.0, 1.0);
                        let tilt_rad = p.axis_value(Axis::Tilt);
                        let orientation = p.axis_value(Axis::Orientation);
                        let (sin_o, cos_o) = orientation.sin_cos();
                        let tan_tilt = tilt_rad.tan();
                        let x_tilt_deg = (sin_o * tan_tilt).atan().to_degrees();
                        let y_tilt_deg = (-cos_o * tan_tilt).atan().to_degrees();
                        pen_updates.push(PenSample {
                            action: m.action(),
                            pos,
                            pressure,
                            x_tilt_deg,
                            y_tilt_deg,
                            is_eraser: matches!(tool, ToolType::Eraser),
                            barrel_button_pressed: m.button_state().stylus_primary(),
                        });
                    }
                }

                if !first_pointer {
                    motion_updates.push(MotionUpdate {
                        action: m.action(),
                        mouse_pos,
                        touch_points,
                    });
                }
            }
            InputEvent::KeyEvent(k) => {
                key_updates.push((k.action(), map_keycode(k.key_code())));
            }
            _ => {}
        }
        // unicode_char mapping (KeyCharacterMap) still TODO — gets us
        // text input from a hardware keyboard. State-diff already fires
        // VirtualKeyDown / VirtualKeyUp HoverEventFilters from the
        // current_virtual_keycode change below, which is enough for the
        // most common test cases (Enter to submit, Tab to navigate).
        InputStatus::Unhandled
    }) {}

    for update in motion_updates {
        // Snapshot previous state — required by the state-diffing event system.
        window.snapshot_window_state_baseline("android.drain_input.motion");

        {
            let ms = window.common.mouse_state_mut();
            match update.action {
                MotionAction::Down | MotionAction::PointerDown => {
                    ms.cursor_position = CursorPosition::InWindow(update.mouse_pos);
                    ms.left_down = true;
                }
                MotionAction::Move | MotionAction::HoverMove => {
                    ms.cursor_position = CursorPosition::InWindow(update.mouse_pos);
                }
                MotionAction::Up | MotionAction::Cancel => {
                    ms.left_down = false;
                }
                MotionAction::PointerUp => {
                    // A secondary finger lifted; primary is still down.
                    // Leave left_down alone.
                }
                _ => {}
            }

            // Refresh TouchState. Android delivers all currently-active
            // pointers on every MotionEvent, so the rebuild is
            // straightforward (no need for the per-ID merge iOS does).
            let ts = window.common.touch_state_mut();
            match update.action {
                MotionAction::Up | MotionAction::Cancel => {
                    // Last finger lifted — clear.
                    ts.touch_points = azul_core::window::TouchPointVec::from_const_slice(&[]);
                }
                _ => {
                    ts.touch_points =
                        azul_core::window::TouchPointVec::from_vec(update.touch_points);
                }
            }
            ts.num_touches = ts.touch_points.len();
        }

        // Update CPU hit-tester at the new cursor; dispatch callbacks.
        window.update_hit_test_at(update.mouse_pos);
        let r = window.process_window_events(0);
        if !matches!(r, azul_core::events::ProcessEventResult::DoNothing) {
            window
                .common
                .request_regeneration(RelayoutReason::RefreshDom);
        }
    }

    // Apply pen samples. Run *after* the motion-state diff so the
    // mouse-pipe view of the world (left_down, cursor_position) is
    // already up-to-date by the time gesture-detection in the callback
    // reads it.
    for sample in pen_updates {
        let in_contact = matches!(sample.action, MotionAction::Down | MotionAction::Move);
        if let Some(lw) = window.common.layout_window.as_mut() {
            if in_contact {
                lw.gesture_drag_manager.update_pen_state(
                    sample.pos,
                    sample.pressure,
                    (sample.x_tilt_deg, sample.y_tilt_deg),
                    true,
                    sample.is_eraser,
                    sample.barrel_button_pressed,
                    0, // device_id — Android has no stable per-device cookie at this layer
                );
            } else {
                lw.gesture_drag_manager.clear_pen_state();
            }
            window
                .common
                .request_regeneration(RelayoutReason::RefreshDom);
        }
    }

    // Apply collected key updates.
    for (action, vkc) in key_updates {
        window.snapshot_window_state_baseline("android.drain_input.key");
        {
            let ks = window.common.keyboard_state_mut();
            match (action, vkc) {
                (KeyAction::Down, Some(code)) => {
                    ks.current_virtual_keycode = Some(code).into();
                    // Add to pressed set if not already present (no
                    // VirtualKeyCodeVec dedup API exposed; rely on the
                    // event-determination to dedupe).
                    let mut v = ks.pressed_virtual_keycodes.clone().into_library_owned_vec();
                    if !v.iter().any(|c| *c == code) {
                        v.push(code);
                    }
                    ks.pressed_virtual_keycodes = v.into();
                }
                (KeyAction::Up, Some(code)) => {
                    ks.current_virtual_keycode = None.into();
                    let mut v = ks.pressed_virtual_keycodes.clone().into_library_owned_vec();
                    v.retain(|c| *c != code);
                    ks.pressed_virtual_keycodes = v.into();
                }
                _ => {}
            }
        }
        let r = window.process_window_events(0);
        if !matches!(r, azul_core::events::ProcessEventResult::DoNothing) {
            window
                .common
                .request_regeneration(RelayoutReason::RefreshDom);
        }
    }

    // After callbacks have observed any native-gesture override the
    // Android `GestureDetector` JNI bridge injected this frame, clear
    // the slot so a stale OS gesture doesn't keep firing. No-op until
    // #17 wires real injection.
    if let Some(lw) = window.common.layout_window.as_mut() {
        lw.gesture_drag_manager.clear_native_gesture();
    }
}

/// Map the Android `Keycode` enum to Azul's `VirtualKeyCode` for the
/// most common navigation / editing keys. Letters and digits arrive via
/// the soft keyboard's text-input path (Sprint H follow-up — wires
/// `KeyCharacterMap.get` for unicode), so this map only handles the
/// non-character keys that callbacks query through
/// `KeyboardState::is_key_down` / `current_virtual_keycode`.
#[cfg(all(target_os = "android", feature = "android-activity"))]
fn map_keycode(k: Keycode) -> Option<azul_core::window::VirtualKeyCode> {
    use azul_core::window::VirtualKeyCode as V;
    Some(match k {
        Keycode::Enter | Keycode::NumpadEnter => V::Return,
        Keycode::Space => V::Space,
        Keycode::Tab => V::Tab,
        Keycode::Escape => V::Escape,
        Keycode::Del => V::Back,
        Keycode::ForwardDel => V::Delete,
        Keycode::DpadLeft => V::Left,
        Keycode::DpadRight => V::Right,
        Keycode::DpadUp => V::Up,
        Keycode::DpadDown => V::Down,
        Keycode::ShiftLeft => V::LShift,
        Keycode::ShiftRight => V::RShift,
        Keycode::CtrlLeft => V::LControl,
        Keycode::CtrlRight => V::RControl,
        Keycode::AltLeft => V::LAlt,
        Keycode::AltRight => V::RAlt,
        _ => return None,
    })
}

#[cfg(all(
    target_os = "android",
    feature = "android-activity",
    feature = "ndk",
    feature = "cpurender"
))]
fn render_frame(window: &mut AndroidWindow) -> Result<(), WindowError> {
    // Sprint G: pixmap → ANativeWindow_lock → memcpy → unlockAndPost.
    //
    // Caller must arrange for `window.cpu_backend.last_frame` to be populated
    // (typically by a regenerate_layout() invocation). Until that wiring is
    // in place we present whatever pixmap is present, or no-op.
    let nw = match window.native_window.as_ref() {
        Some(nw) => nw,
        None => return Ok(()), // background — surface released
    };

    let pixmap = match window.cpu_backend.last_frame.as_ref() {
        Some(p) => p,
        None => return Ok(()), // nothing to present yet
    };

    let pw = pixmap.width() as i32;
    let ph = pixmap.height() as i32;
    if pw <= 0 || ph <= 0 {
        return Ok(());
    }

    // Tell the surface we want RGBA8 of this exact size. If Android can't
    // satisfy (surface gone, surfaceflinger rejected the format) SKIP the
    // frame: locking anyway hands us a buffer whose format/geometry does not
    // match the bytes we are about to write, and the old `let _ =` swallow
    // then blitted RGBA rows into it regardless.
    if let Err(e) = nw.set_buffers_geometry(
        pw,
        ph,
        Some(ndk::hardware_buffer_format::HardwareBufferFormat::R8G8B8A8_UNORM),
    ) {
        log_debug!(
            LogCategory::Rendering,
            "[Android] setBuffersGeometry({}x{} RGBA8) failed: {}; skipping frame",
            pw,
            ph,
            e,
        );
        return Ok(());
    }

    let mut guard = match nw.lock(None) {
        Ok(g) => g,
        Err(e) => {
            log_debug!(
                LogCategory::Rendering,
                "[Android] ANativeWindow_lock failed: {}",
                e
            );
            return Ok(());
        }
    };

    // The locked buffer's REAL format. `lines()` derives its bytes-per-pixel
    // from this, so a producer that ignored the RGBA8 request (legacy fixed-
    // format surfaces) would make the copy below reinterpret RGBA bytes as
    // 565/etc. — garbage on every pixel. There is no "unlock without post"
    // in the NDK (ANativeWindow_unlockAndPost is the only unlock), so on a
    // mismatch present a deterministic cleared frame instead of the buffer's
    // undefined contents.
    {
        use ndk::hardware_buffer_format::HardwareBufferFormat as Hbf;
        let format = guard.format();
        if !matches!(format, Hbf::R8G8B8A8_UNORM | Hbf::R8G8B8X8_UNORM) {
            log_debug!(
                LogCategory::Rendering,
                "[Android] lock returned non-RGBA8 buffer format {:?}; clearing frame",
                format,
            );
            if let Some(bytes) = guard.bytes() {
                // SAFETY: writing initialised bytes into MaybeUninit is sound.
                unsafe {
                    core::ptr::write_bytes(bytes.as_mut_ptr().cast::<u8>(), 0, bytes.len());
                }
            }
            return Ok(()); // guard drop unlockAndPosts the cleared buffer
        }
    }

    // Per-line blit. `lines()` returns one mutable slice per scanline,
    // trimmed to the visible width — exactly what we need for an RGBA→RGBA
    // copy where stride may exceed width.
    //
    // Any part of the buffer the pixmap does not cover MUST still be written:
    // ANativeWindow_lock hands back a dequeued buffer with UNDEFINED contents
    // (typically a stale frame from several swaps ago — Android does not
    // guarantee back-buffer preservation), so rows/columns we skip would show
    // garbage. Normally geometry matches the pixmap exactly and the fills
    // below are no-ops; they only run if the buffer disagrees with the
    // geometry we just set.
    let src = pixmap.data();
    let src_stride = (pw as usize) * 4;
    if let Some(lines) = guard.lines() {
        for (y, line) in lines.enumerate() {
            let dst_ptr = line.as_mut_ptr().cast::<u8>();
            if y >= ph as usize {
                // SAFETY: in-bounds write of initialised bytes.
                unsafe { core::ptr::write_bytes(dst_ptr, 0, line.len()) };
                continue;
            }
            let src_off = y * src_stride;
            let end = (src_off + src_stride).min(src.len());
            let src_row = &src[src_off..end];
            let n = src_row.len().min(line.len());
            // SAFETY: line is &mut [MaybeUninit<u8>]; writing initialised
            // bytes is sound. We never read line before writing it.
            unsafe {
                core::ptr::copy_nonoverlapping(src_row.as_ptr(), dst_ptr, n);
                if n < line.len() {
                    core::ptr::write_bytes(dst_ptr.add(n), 0, line.len() - n);
                }
            }
        }
    }
    // guard.drop() calls ANativeWindow_unlockAndPost
    Ok(())
}

/// Fallback stub for non-android-activity / non-ndk / non-cpurender builds.
#[cfg(not(all(
    target_os = "android",
    feature = "android-activity",
    feature = "ndk",
    feature = "cpurender"
)))]
fn render_frame(_window: &mut AndroidWindow) -> Result<(), WindowError> {
    Ok(())
}

/// Stub for non-android-activity builds. Calling this on non-Android hosts is
/// a no-op so other platforms can keep referencing it from feature-gated code.
#[cfg(not(all(target_os = "android", feature = "android-activity")))]
pub fn android_main_stub() {}

// ---------------------------------------------------------------------------
// Static window-pointer slot.
//
// Published by `android_main` once `AndroidWindow::new` returns, read by the
// Java `AzulActivity.nativeGetWindowPointer()` (via the `extern "system"` fn
// below) so the activity can construct `NativeGestureBridge` with a valid
// `nativePtr`. `i64` so it survives the `jni::sys::jlong` round-trip.
// ---------------------------------------------------------------------------

#[cfg(all(target_os = "android", feature = "android-activity"))]
static ANDROID_WINDOW_PTR: core::sync::atomic::AtomicI64 = core::sync::atomic::AtomicI64::new(0);

#[cfg(all(target_os = "android", feature = "android-activity"))]
#[no_mangle]
pub unsafe extern "system" fn Java_com_azul_app_AzulActivity_nativeGetWindowPointer(
    _env: *mut core::ffi::c_void,
    _class: *mut core::ffi::c_void,
) -> i64 {
    ANDROID_WINDOW_PTR.load(core::sync::atomic::Ordering::SeqCst)
}

// JavaVM* + Activity-instance pointers, published by `android_main`. The
// dll/extra/file_picker/android.rs path needs both: attach the current
// thread to the VM (so we get a JNIEnv*), find the AzulFilePicker class,
// and call its static dispatch method with the activity reference.
//
// Stored as `AtomicPtr<c_void>` so dispatch_open_file can read them
// without locking. The values come from `AndroidApp::vm_as_ptr()` /
// `AndroidApp::activity_as_ptr()`, both of which are stable for the
// lifetime of the activity (android-activity 0.6 holds them in a
// `&'static`-equivalent slot).

#[cfg(all(target_os = "android", feature = "android-activity"))]
static ANDROID_JAVA_VM: core::sync::atomic::AtomicPtr<core::ffi::c_void> =
    core::sync::atomic::AtomicPtr::new(core::ptr::null_mut());

#[cfg(all(target_os = "android", feature = "android-activity"))]
static ANDROID_ACTIVITY: core::sync::atomic::AtomicPtr<core::ffi::c_void> =
    core::sync::atomic::AtomicPtr::new(core::ptr::null_mut());

/// Read the JavaVM* the activity published on startup. `null` until
/// `android_main` has run far enough to call `publish_jni_context`.
#[cfg(all(target_os = "android", feature = "android-activity"))]
pub fn java_vm_ptr() -> *mut core::ffi::c_void {
    ANDROID_JAVA_VM.load(core::sync::atomic::Ordering::SeqCst)
}

/// Read the Java Activity instance pointer (a `jobject` global ref the
/// activity layer keeps alive for us).
#[cfg(all(target_os = "android", feature = "android-activity"))]
pub fn activity_ptr() -> *mut core::ffi::c_void {
    ANDROID_ACTIVITY.load(core::sync::atomic::Ordering::SeqCst)
}

/// Cross-target stubs so dll/extra/file_picker/android.rs can call these
/// regardless of whether the android-activity feature is on (it isn't on
/// non-Android targets, but the file_picker submodule is cfg-gated on
/// `target_os = "android"` anyway — defensive double-gate).
#[cfg(not(all(target_os = "android", feature = "android-activity")))]
pub fn java_vm_ptr() -> *mut core::ffi::c_void {
    core::ptr::null_mut()
}
#[cfg(not(all(target_os = "android", feature = "android-activity")))]
pub fn activity_ptr() -> *mut core::ffi::c_void {
    core::ptr::null_mut()
}

#[cfg(all(target_os = "android", feature = "android-activity"))]
fn publish_jni_context(app: &AndroidApp) {
    ANDROID_JAVA_VM.store(app.vm_as_ptr(), core::sync::atomic::Ordering::SeqCst);
    ANDROID_ACTIVITY.store(app.activity_as_ptr(), core::sync::atomic::Ordering::SeqCst);
}

// ---------------------------------------------------------------------------
// JNI bridge — surfaces NativeGestureBridge.java callbacks to Rust.
//
// The Java side (scripts/android/NativeGestureBridge.java) attaches to the
// activity's content view, then dispatches each detected gesture into one
// of these `extern "C"` symbols, passing the AndroidWindow address as a
// `jlong`. We turn that back into `&mut AndroidWindow` and forward to
// `GestureAndDragManager::inject_native_gesture`.
//
// Java declares the methods `private static native ...`, so the JNI lookup
// name is `Java_com_azul_gesture_NativeGestureBridge_nativeOn<Verb>`.
// `extern "system"` is the cross-platform JNI calling convention (== "C" on
// most Unixes, `__stdcall` on Win32).
// ---------------------------------------------------------------------------

#[cfg(all(target_os = "android", feature = "android-activity"))]
mod jni_bridge {
    use azul_core::geom::LogicalPosition;
    use azul_layout::managers::gesture::{
        DetectedLongPress, DetectedPinch, DetectedRotation, GestureDirection, NativeGestureEvent,
    };
    // A nested `mod` does NOT inherit the file's `use` items, and this one
    // was missing the reason type entirely — `inject()` below has always
    // referred to a `RelayoutReason` that is not in scope here. It surfaced
    // only now because android is the one target that compiles this file and
    // nothing had forced it to resolve.
    use azul_core::callbacks::RelayoutReason;

    /// SAFETY: `native_ptr` is the AndroidWindow address handed to the
    /// Java side by `android_main`. We are the only Rust thread mutating
    /// the window in response to UI events, so the brief mutable
    /// reference is sound.
    unsafe fn with_window<F>(native_ptr: i64, f: F)
    where
        F: FnOnce(&mut super::AndroidWindow),
    {
        if native_ptr == 0 {
            return;
        }
        let window = &mut *(native_ptr as *mut super::AndroidWindow);
        f(window);
    }

    fn inject(window: &mut super::AndroidWindow, gesture: NativeGestureEvent) {
        if let Some(lw) = window.common.layout_window.as_mut() {
            lw.gesture_drag_manager.inject_native_gesture(gesture);
            window
                .common
                .request_regeneration(RelayoutReason::RefreshDom);
        }
    }

    #[no_mangle]
    pub unsafe extern "system" fn Java_com_azul_app_AzulActivity_nativeOnUiModeChanged(
        _env: *mut core::ffi::c_void,
        _class: *mut core::ffi::c_void,
        native_ptr: i64,
        night_mode: i32,
    ) {
        // `night_mode` is azul's own encoding, mapped Java-side from
        // UI_MODE_NIGHT_MASK: 0 = undefined, 1 = light, 2 = dark. Android's
        // constants stay on the Java side of JNI, like the a11y bridge's.
        //
        // Called from AzulActivity.onConfigurationChanged AND once from
        // onWindowFocusChanged, because Android built its window from
        // SystemStyle::default() and never read the device setting at all — an
        // app launched on a dark-mode device rendered light and stayed light.
        // The change hook alone would only have fixed the second half.
        //
        // This runs on the JAVA UI THREAD, not the loop thread. It only writes
        // window state that the next loop iteration reads, exactly as the
        // gesture bridge does.
        let theme = match night_mode {
            1 => azul_core::window::WindowTheme::LightMode,
            2 => azul_core::window::WindowTheme::DarkMode,
            // Undefined: the device is not expressing a preference, so keep
            // whatever the window already carries.
            _ => return,
        };
        // Queue only — the LOOP thread drains this (drain_pending_theme),
        // snapshots the event-diff baseline, applies the theme and runs the
        // pass there. Mutating window state from the Java thread raced the
        // loop and left a live delta the validation check rightly flags.
        let _ = theme;
        with_window(native_ptr, |w| {
            w.pending_theme
                .store(night_mode, std::sync::atomic::Ordering::Release);
        });
    }

    #[no_mangle]
    pub unsafe extern "system" fn Java_com_azul_gesture_NativeGestureBridge_nativeOnDoubleTap(
        _env: *mut core::ffi::c_void,
        _class: *mut core::ffi::c_void,
        native_ptr: i64,
    ) {
        with_window(native_ptr, |w| inject(w, NativeGestureEvent::DoubleClick));
    }

    #[no_mangle]
    pub unsafe extern "system" fn Java_com_azul_gesture_NativeGestureBridge_nativeOnLongPress(
        _env: *mut core::ffi::c_void,
        _class: *mut core::ffi::c_void,
        native_ptr: i64,
        x: f32,
        y: f32,
        duration_ms: i64,
    ) {
        with_window(native_ptr, |w| {
            inject(
                w,
                NativeGestureEvent::LongPress(DetectedLongPress {
                    position: LogicalPosition { x, y },
                    duration_ms: duration_ms as u64,
                    callback_invoked: false,
                    session_id: 0,
                }),
            );
        });
    }

    #[no_mangle]
    pub unsafe extern "system" fn Java_com_azul_gesture_NativeGestureBridge_nativeOnSwipe(
        _env: *mut core::ffi::c_void,
        _class: *mut core::ffi::c_void,
        native_ptr: i64,
        direction: i32,
    ) {
        // Must match DIR_UP/DOWN/LEFT/RIGHT in NativeGestureBridge.java
        let dir = match direction {
            0 => GestureDirection::Up,
            1 => GestureDirection::Down,
            2 => GestureDirection::Left,
            3 => GestureDirection::Right,
            _ => return,
        };
        with_window(native_ptr, |w| inject(w, NativeGestureEvent::Swipe(dir)));
    }

    #[no_mangle]
    pub unsafe extern "system" fn Java_com_azul_gesture_NativeGestureBridge_nativeOnPinch(
        _env: *mut core::ffi::c_void,
        _class: *mut core::ffi::c_void,
        native_ptr: i64,
        scale: f32,
        center_x: f32,
        center_y: f32,
        initial_distance: f32,
        current_distance: f32,
        duration_ms: i64,
    ) {
        with_window(native_ptr, |w| {
            inject(
                w,
                NativeGestureEvent::Pinch(DetectedPinch {
                    scale,
                    center: LogicalPosition {
                        x: center_x,
                        y: center_y,
                    },
                    initial_distance,
                    current_distance,
                    duration_ms: duration_ms as u64,
                }),
            );
        });
    }

    #[no_mangle]
    pub unsafe extern "system" fn Java_com_azul_gesture_NativeGestureBridge_nativeOnRotation(
        _env: *mut core::ffi::c_void,
        _class: *mut core::ffi::c_void,
        native_ptr: i64,
        angle_radians: f32,
        center_x: f32,
        center_y: f32,
        duration_ms: i64,
    ) {
        with_window(native_ptr, |w| {
            inject(
                w,
                NativeGestureEvent::Rotation(DetectedRotation {
                    angle_radians,
                    center: LogicalPosition {
                        x: center_x,
                        y: center_y,
                    },
                    duration_ms: duration_ms as u64,
                }),
            );
        });
    }
}

/// JNI entry points for Android text input.
///
/// Android does not hand a NativeActivity keystrokes for text: the soft
/// keyboard talks to an `InputConnection`, a Java object, and there is no way
/// to reach one from native code. So the Java side owns a `BaseInputConnection`
/// on the activity's view and forwards each edit down here — the same shape the
/// gesture bridge already uses, for the same reason.
///
/// This is why `shell2/android` had NO text input at all despite having a full
/// key path: `KeyEvent` carries navigation and modifier keys, but a soft
/// keyboard sends `commitText` and `setComposingText` and never synthesizes
/// key events for them. An IME typing Japanese produces no `KeyEvent` whatsoever.
#[cfg(target_os = "android")]
pub mod text_bridge {
    use super::{with_window, RelayoutReason};

    /// Decode a Java string handed over as UTF-8 bytes.
    ///
    /// Bytes rather than a `jstring` because the alternative is calling
    /// `GetStringUTFChars` through a raw `JNIEnv` vtable, and the Java side has
    /// to touch the string either way — doing the conversion there keeps the
    /// unsafe surface here down to a slice.
    unsafe fn utf8(ptr: *const u8, len: i32) -> String {
        if ptr.is_null() || len <= 0 {
            return String::new();
        }
        let slice = core::slice::from_raw_parts(ptr, len as usize);
        String::from_utf8_lossy(slice).into_owned()
    }

    /// `InputConnection.commitText` — the IME finished composing and this is
    /// the result.
    #[no_mangle]
    pub unsafe extern "system" fn Java_com_azul_text_NativeTextBridge_nativeCommitText(
        _env: *mut core::ffi::c_void,
        _class: *mut core::ffi::c_void,
        native_ptr: i64,
        bytes: *const u8,
        len: i32,
    ) {
        let text = utf8(bytes, len);
        with_window(native_ptr, |w| {
            if let Some(lw) = w.common.layout_window.as_mut() {
                // Commit, not clear: this carries the committed string so
                // CompositionEnd can report it, exactly as the desktop shells
                // do.
                lw.text_edit_manager.commit_composition(text.clone());
                let _ = lw.record_text_input(&text);
            }
            w.common.request_regeneration(RelayoutReason::RefreshDom);
        });
    }

    /// `InputConnection.setComposingText` — the IME's in-progress preedit.
    ///
    /// `cursor_pos` is Android's own convention: > 0 counts from the END of the
    /// composing text, <= 0 from its start. Normalised to a byte offset here so
    /// the engine sees the same shape Wayland and Win32 produce.
    #[no_mangle]
    pub unsafe extern "system" fn Java_com_azul_text_NativeTextBridge_nativeSetComposingText(
        _env: *mut core::ffi::c_void,
        _class: *mut core::ffi::c_void,
        native_ptr: i64,
        bytes: *const u8,
        len: i32,
        cursor_pos: i32,
    ) {
        let text = utf8(bytes, len);
        let byte_len = text.len() as i32;
        let caret = if cursor_pos > 0 {
            byte_len
        } else {
            0
        };
        with_window(native_ptr, |w| {
            if let Some(lw) = w.common.layout_window.as_mut() {
                lw.text_edit_manager.set_preedit(text.clone(), caret, caret);
            }
            w.common.request_regeneration(RelayoutReason::RefreshDom);
        });
    }

    /// `InputConnection.finishComposingText` — composition ended without a
    /// separate commit (the user tapped away, or the IME gave up).
    #[no_mangle]
    pub unsafe extern "system" fn Java_com_azul_text_NativeTextBridge_nativeFinishComposing(
        _env: *mut core::ffi::c_void,
        _class: *mut core::ffi::c_void,
        native_ptr: i64,
    ) {
        with_window(native_ptr, |w| {
            if let Some(lw) = w.common.layout_window.as_mut() {
                // clear_preedit records CompositionEnd on its own, so a
                // cancelled composition still tells the app to close its
                // overlay.
                lw.text_edit_manager.clear_preedit();
            }
            w.common.request_regeneration(RelayoutReason::RefreshDom);
        });
    }

    /// `InputConnection.deleteSurroundingText` — the IME asking for a
    /// backspace it did not express as a key.
    #[no_mangle]
    pub unsafe extern "system" fn Java_com_azul_text_NativeTextBridge_nativeDeleteSurrounding(
        _env: *mut core::ffi::c_void,
        _class: *mut core::ffi::c_void,
        native_ptr: i64,
        before: i32,
        after: i32,
    ) {
        with_window(native_ptr, |w| {
            if let Some(lw) = w.common.layout_window.as_mut() {
                let Some(focused) = lw.focus_manager.get_focused_node().copied() else {
                    return;
                };
                for _ in 0..before.max(0) {
                    lw.delete_selection(focused, true);
                }
                for _ in 0..after.max(0) {
                    lw.delete_selection(focused, false);
                }
            }
            w.common.request_regeneration(RelayoutReason::RefreshDom);
        });
    }

    /// Whether a composition is currently open — the Java side asks so it can
    /// answer `InputConnection.getComposingText` without duplicating state.
    #[no_mangle]
    pub unsafe extern "system" fn Java_com_azul_text_NativeTextBridge_nativeIsComposing(
        _env: *mut core::ffi::c_void,
        _class: *mut core::ffi::c_void,
        native_ptr: i64,
    ) -> i32 {
        let mut composing = 0;
        with_window(native_ptr, |w| {
            if let Some(lw) = w.common.layout_window.as_ref() {
                composing = i32::from(lw.text_edit_manager.preedit_text.is_some());
            }
        });
        composing
    }
}
