//! Android backend using NativeActivity + the `android-activity` crate.
//!
//! Mirrors the structure of `headless/mod.rs` — a `CpuBackend` does layout-driven
//! CPU rendering into an `AzulPixmap`, then we blit those pixels into an
//! `ANativeWindow` lock buffer (`ANativeWindow_lock` → memcpy → `unlockAndPost`).
//!
//! There is **no Java/Kotlin code on the build path** for Phase 1-4. The whole
//! event loop, input handling, and rendering happens inside Rust via
//! `android-activity` (which provides the `android_main` entry point and the
//! `MainEvent`/`InputEvent` enums) plus `ndk` (for `NativeWindow_lock`).
//!
//! Soft-keyboard / IME support (Phase 5) needs a ~50-line Java JNI bridge that
//! is compiled with plain `javac` + `d8` — still no Gradle.

use std::{
    cell::RefCell,
    ffi::c_void,
    sync::Arc,
    time::Duration,
};

use azul_core::{
    callbacks::RelayoutReason,
    gl::OptionGlContextPtr,
    hit_test::DocumentId,
    icon::SharedIconProvider,
    refany::RefAny,
    resources::{AppConfig, IdNamespace, ImageCache, RendererResources},
    window::{AndroidHandle, RawWindowHandle},
};
use azul_layout::{
    window::{LayoutWindow, ScrollbarDragState},
    window_state::{FullWindowState, WindowCreateOptions},
};
use rust_fontconfig::{registry::FcFontRegistry, FcFontCache};

use crate::desktop::shell2::common::{
    event::{self, CommonWindowState, HitTestNode, PlatformWindow},
    debug_server::LogCategory,
    WindowError,
};
use crate::desktop::shell2::headless::CpuBackend;
use crate::desktop::wr_translate2::{AsyncHitTester, WrRenderApi};
use crate::{impl_platform_window_getters, log_debug, log_error, log_info};

#[cfg(feature = "android-activity")]
use android_activity::{
    input::{InputEvent, KeyAction, MotionAction},
    AndroidApp, InputStatus, MainEvent, PollEvent,
};
#[cfg(feature = "ndk")]
use ndk::native_window::NativeWindow;

/// Events generated by the Android backend (currently only the close signal).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AndroidEvent {
    Close,
}

/// Rendering backend selector. CPU only on day 1 (mirrors the headless backend).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RenderBackend {
    Cpu,
}

/// Android platform window backed by an `ANativeWindow`.
///
/// The window pointer is `None` while the activity is in the background
/// (`MainEvent::TerminateWindow` fires before `Pause`). All rendering and hit
/// testing must be guarded against that case.
pub struct AndroidWindow {
    /// Cross-platform window state (layout, resources, event diffing).
    pub common: CommonWindowState,
    /// CPU rendering backend (replaces WebRender).
    pub cpu_backend: CpuBackend,
    /// Currently-attached `ANativeWindow`. Released on `TerminateWindow`.
    #[cfg(feature = "ndk")]
    pub native_window: Option<NativeWindow>,
    /// Rendering backend selector (always Cpu for now).
    pub backend: RenderBackend,
    /// `false` once `MainEvent::Destroy` arrives; breaks the outer loop.
    pub is_open: bool,
    /// Shared icon provider — needed by `regenerate_layout()` so widgets
    /// (notably button/icon containers) can resolve `IconReference`s.
    pub icon_provider: SharedIconProvider,
    /// Shared font registry for async font discovery / loading.
    /// `None` means the registry was never installed; defaults to disabled.
    pub font_registry: Option<Arc<FcFontRegistry>>,
}

impl AndroidWindow {
    /// Construct a window with no native surface attached yet.
    /// `InitWindow` later swaps in the real `ANativeWindow`.
    pub fn new(
        options: WindowCreateOptions,
        fc_cache: Arc<FcFontCache>,
        mut config: AppConfig,
        app_data: RefAny,
        font_registry: Option<Arc<FcFontRegistry>>,
    ) -> Result<Self, WindowError> {
        // `WindowCreateOptions::window_state` is already a `FullWindowState`,
        // mirroring how `HeadlessWindow::new` consumes it. No constructor call.
        let full_window_state = options.window_state;

        // Extract the SharedIconProvider out of the config (same pattern
        // as run_headless) so we can pass it to regenerate_layout later.
        let icon_provider_handle = core::mem::take(&mut config.icon_provider);
        let icon_provider = SharedIconProvider::from_handle(icon_provider_handle);

        let mut layout_window = LayoutWindow::new(fc_cache.as_ref().clone())
            .map_err(|e| WindowError::PlatformError(format!("Layout init failed: {:?}", e)))?;
        layout_window.current_window_state = full_window_state.clone();
        layout_window.routes = config.routes.clone();

        Ok(Self {
            common: CommonWindowState {
                layout_window: Some(layout_window),
                current_window_state: full_window_state,
                previous_window_state: None,
                image_cache: ImageCache::default(),
                renderer_resources: RendererResources::default(),
                fc_cache,
                gl_context_ptr: azul_core::gl::OptionGlContextPtr::None,
                system_style: Arc::new(azul_css::system::SystemStyle::default()),
                app_data: Arc::new(RefCell::new(app_data)),
                scrollbar_drag_state: None,
                hit_tester: None,
                cpu_hit_tester: Some(azul_layout::headless::CpuHitTester::new()),
                last_hovered_node: None,
                document_id: None,
                id_namespace: None,
                render_api: None,
                renderer: None,
                frame_needs_regeneration: true,
                next_relayout_reason: RelayoutReason::Initial,
                display_list_initialized: false,
                display_list_dirty: false,
                a11y_dirty: true,
            },
            cpu_backend: CpuBackend::new(),
            #[cfg(feature = "ndk")]
            native_window: None,
            backend: RenderBackend::Cpu,
            is_open: true,
            icon_provider,
            font_registry,
        })
    }

    pub fn is_open(&self) -> bool { self.is_open }
    pub fn close(&mut self) { self.is_open = false; }

    /// Run a full layout regeneration pass and CPU-render the resulting
    /// display list. Mirrors `HeadlessWindow::regenerate_layout()`; the
    /// lifecycle-event dispatch step is skipped for now (Android backend
    /// has no callback driver yet — pending sprint H).
    pub fn regenerate_layout(
        &mut self,
    ) -> Result<crate::desktop::shell2::common::layout::LayoutRegenerateResult, String> {
        let layout_window = self
            .common
            .layout_window
            .as_mut()
            .ok_or("No layout window")?;

        let debug_enabled =
            crate::desktop::shell2::common::debug_server::is_debug_enabled();
        let mut debug_messages = if debug_enabled { Some(Vec::new()) } else { None };

        let result = crate::desktop::shell2::common::layout::regenerate_layout(
            layout_window,
            &self.common.app_data,
            &self.common.current_window_state,
            &mut self.common.renderer_resources,
            &self.common.image_cache,
            &self.common.gl_context_ptr,
            &self.common.fc_cache,
            &self.font_registry,
            &self.common.system_style,
            &self.icon_provider,
            &mut debug_messages,
            self.common.next_relayout_reason,
        )?;
        self.common.next_relayout_reason =
            azul_core::callbacks::RelayoutReason::RefreshDom;

        if let Some(msgs) = debug_messages {
            for msg in msgs {
                crate::desktop::shell2::common::debug_server::log(
                    crate::desktop::shell2::common::debug_server::LogLevel::Debug,
                    crate::desktop::shell2::common::debug_server::LogCategory::Layout,
                    msg.message.as_str().to_string(),
                    None,
                );
            }
        }

        // Rebuild CPU hit-tester from new layout results
        if let Some(lw) = self.common.layout_window.as_ref() {
            self.cpu_backend.hit_tester.rebuild_from_layout(&lw.layout_results);
        }

        // CPU-render the frame — populates `self.cpu_backend.last_frame`
        // so the next `render_frame()` call can blit pixels.
        #[cfg(feature = "cpurender")]
        {
            let ws = &self.common.current_window_state;
            let width = ws.size.dimensions.width;
            let height = ws.size.dimensions.height;
            let dpi = ws.size.dpi as f32 / 96.0;
            if let Some(lw) = self.common.layout_window.as_ref() {
                self.cpu_backend.render_frame(
                    lw,
                    &self.common.renderer_resources,
                    width,
                    height,
                    dpi,
                );
            }
        }

        self.common.frame_needs_regeneration = false;
        Ok(result)
    }
}

impl PlatformWindow for AndroidWindow {
    impl_platform_window_getters!(common);

    fn get_raw_window_handle(&self) -> RawWindowHandle {
        #[cfg(feature = "ndk")]
        let ptr = self.native_window.as_ref()
            .map(|nw| nw.ptr().as_ptr() as *mut c_void)
            .unwrap_or(std::ptr::null_mut());
        #[cfg(not(feature = "ndk"))]
        let ptr = std::ptr::null_mut();

        RawWindowHandle::Android(AndroidHandle { a_native_window: ptr })
    }

    fn prepare_callback_invocation(&mut self) -> event::InvokeSingleCallbackBorrows<'_> {
        let layout_window = self
            .common
            .layout_window
            .as_mut()
            .expect("Layout window must exist for callback invocation");
        event::InvokeSingleCallbackBorrows {
            layout_window,
            window_handle: RawWindowHandle::Android(AndroidHandle {
                a_native_window: std::ptr::null_mut(),
            }),
            gl_context_ptr: &self.common.gl_context_ptr,
            image_cache: &mut self.common.image_cache,
            fc_cache_clone: (*self.common.fc_cache).clone(),
            system_style: self.common.system_style.clone(),
            previous_window_state: &self.common.previous_window_state,
            current_window_state: &self.common.current_window_state,
            renderer_resources: &mut self.common.renderer_resources,
        }
    }

    fn start_timer(&mut self, timer_id: usize, timer: azul_layout::timer::Timer) {
        if let Some(lw) = self.common.layout_window.as_mut() {
            lw.timers.insert(azul_core::task::TimerId { id: timer_id }, timer);
        }
    }
    fn stop_timer(&mut self, timer_id: usize) {
        if let Some(lw) = self.common.layout_window.as_mut() {
            lw.timers.remove(&azul_core::task::TimerId { id: timer_id });
        }
    }
    fn start_thread_poll_timer(&mut self) {}
    fn stop_thread_poll_timer(&mut self) {}

    fn add_threads(
        &mut self,
        threads: std::collections::BTreeMap<
            azul_core::task::ThreadId,
            azul_layout::thread::Thread,
        >,
    ) {
        if let Some(lw) = self.common.layout_window.as_mut() {
            for (id, thread) in threads {
                lw.threads.insert(id, thread);
            }
        }
    }
    fn remove_threads(
        &mut self,
        thread_ids: &std::collections::BTreeSet<azul_core::task::ThreadId>,
    ) {
        if let Some(lw) = self.common.layout_window.as_mut() {
            for id in thread_ids {
                lw.threads.remove(id);
            }
        }
    }

    fn queue_window_create(&mut self, _options: WindowCreateOptions) {
        // No popup windows on Android; ignored. Sub-activities are a future
        // enhancement and would require launching new Intents from Java.
    }

    fn show_menu_from_callback(
        &mut self,
        _menu: &azul_core::menu::Menu,
        _position: azul_core::geom::LogicalPosition,
    ) {}

    fn show_tooltip_from_callback(
        &mut self,
        _text: &str,
        _position: azul_core::geom::LogicalPosition,
    ) {}

    fn hide_tooltip_from_callback(&mut self) {}

    fn sync_window_state(&mut self) {}
}

// ---------------------------------------------------------------------------
// android_main entry point (called by the NativeActivity glue thread)
// ---------------------------------------------------------------------------

/// `android_main` is the entry point that the `android-activity` crate's
/// `ANativeActivity_onCreate` shim invokes on the Android UI thread.
///
/// The user's `azul_run(app_data, ...)` call stashes `INITIAL_OPTIONS` into a
/// global static *before* the dylib hands control to `ANativeActivity_onCreate`,
/// so by the time we get here the options are ready.
#[cfg(all(target_os = "android", feature = "android-activity"))]
#[no_mangle]
pub fn android_main(app: AndroidApp) {
    log_info!(LogCategory::EventLoop, "[Android] android_main entered");

    // Retrieve initial options stashed by `run()`
    let (app_data, config, fc_cache, font_registry, root_window) = unsafe {
        match crate::desktop::shell2::run::ANDROID_INITIAL_OPTIONS.take() {
            Some(opts) => opts,
            None => {
                log_error!(
                    LogCategory::EventLoop,
                    "[Android] android_main called without INITIAL_OPTIONS set — \
                     did azul_run() run first?",
                );
                return;
            }
        }
    };

    let mut window =
        match AndroidWindow::new(root_window, fc_cache, config, app_data, font_registry) {
            Ok(w) => w,
            Err(e) => {
                log_error!(
                    LogCategory::EventLoop,
                    "[Android] AndroidWindow::new failed: {:?}",
                    e
                );
                return;
            }
        };

    // Outer driver loop — exits when MainEvent::Destroy clears window.is_open.
    while window.is_open() {
        // Block forever when we have no native surface (background); poll
        // at frame rate when we do (foreground rendering).
        let timeout = {
            #[cfg(feature = "ndk")]
            { if window.native_window.is_some() { Some(Duration::from_millis(16)) } else { None } }
            #[cfg(not(feature = "ndk"))]
            { Some(Duration::from_millis(16)) }
        };

        app.poll_events(timeout, |event| {
            handle_poll_event(&app, &mut window, event);
        });

        // Regenerate layout when something invalidated the frame (init,
        // resize, input). Populates cpu_backend.last_frame.
        if window.common.frame_needs_regeneration {
            if let Err(e) = window.regenerate_layout() {
                log_error!(
                    LogCategory::Layout,
                    "[Android] regenerate_layout failed: {}",
                    e
                );
            }
        }

        // After draining events + relayout, present a frame.
        let _ = render_frame(&mut window);
    }

    log_info!(LogCategory::EventLoop, "[Android] android_main exiting cleanly");
}

#[cfg(all(target_os = "android", feature = "android-activity"))]
fn handle_poll_event(app: &AndroidApp, window: &mut AndroidWindow, event: PollEvent<'_>) {
    match event {
        PollEvent::Main(main_event) => match main_event {
            MainEvent::InitWindow { .. } => {
                #[cfg(feature = "ndk")]
                {
                    if let Some(nw) = app.native_window() {
                        log_debug!(LogCategory::Window, "[Android] InitWindow {}x{}",
                            nw.width(), nw.height());
                        window.native_window = Some(nw);
                        window.common.frame_needs_regeneration = true;
                    }
                }
            }
            MainEvent::TerminateWindow { .. } => {
                log_debug!(LogCategory::Window, "[Android] TerminateWindow");
                #[cfg(feature = "ndk")]
                { window.native_window = None; }
            }
            MainEvent::WindowResized { .. } => {
                window.common.frame_needs_regeneration = true;
            }
            MainEvent::InputAvailable => {
                drain_input(app, window);
            }
            MainEvent::Destroy => {
                window.close();
            }
            MainEvent::Pause | MainEvent::Resume { .. } => {
                // No-op for now; future: pause timers, stop animations.
            }
            _ => {}
        },
        _ => {}
    }
}

/// Drain the input queue once. Maps the first pointer of every motion event
/// to the mouse left button — enough for hover/click in the existing event
/// system; multi-touch (`TouchStart`/`TouchMove`/`TouchEnd`) is deferred.
#[cfg(all(target_os = "android", feature = "android-activity"))]
fn drain_input(app: &AndroidApp, window: &mut AndroidWindow) {
    use azul_core::geom::LogicalPosition;
    use azul_core::window::CursorPosition;

    let mut iter = match app.input_events_iter() {
        Ok(it) => it,
        Err(e) => {
            log_debug!(LogCategory::Input, "[Android] input_events_iter: {:?}", e);
            return;
        }
    };

    // dpi factor: device pixels per logical px. Default to 1.0 until
    // sprint H wires the real Configuration.density_dpi lookup.
    let dpi = 1.0_f32;

    // Collect state-update tuples first; do the actual state diff +
    // process_window_events outside the iterator's closure because the
    // closure borrows `app` for the input queue and we need &mut window.
    let mut updates: Vec<(MotionAction, LogicalPosition)> = Vec::new();
    while iter.next(|event| {
        if let InputEvent::MotionEvent(m) = event {
            if let Some(p) = m.pointers().next() {
                let pos = LogicalPosition::new(p.raw_x() / dpi, p.raw_y() / dpi);
                updates.push((m.action(), pos));
            }
        }
        // KeyEvent handling deferred (Keycode → VirtualKeyCode +
        // KeyCharacterMap unicode lookup is its own non-trivial step).
        InputStatus::Unhandled
    }) {}

    for (action, pos) in updates {
        // Snapshot previous state — required by the state-diffing event system.
        window.common.previous_window_state =
            Some(window.common.current_window_state.clone());

        {
            let ms = &mut window.common.current_window_state.mouse_state;
            match action {
                MotionAction::Down => {
                    ms.cursor_position = CursorPosition::InWindow(pos);
                    ms.left_down = true;
                }
                MotionAction::Move | MotionAction::HoverMove => {
                    ms.cursor_position = CursorPosition::InWindow(pos);
                }
                MotionAction::Up | MotionAction::Cancel => {
                    ms.left_down = false;
                }
                _ => {}
            }
        }

        // Update CPU hit-tester at the new cursor; dispatch callbacks.
        window.update_hit_test_at(pos);
        let r = window.process_window_events(0);
        if !matches!(r, azul_core::events::ProcessEventResult::DoNothing) {
            window.common.frame_needs_regeneration = true;
        }
    }
}

#[cfg(all(target_os = "android", feature = "android-activity", feature = "ndk", feature = "cpurender"))]
fn render_frame(window: &mut AndroidWindow) -> Result<(), WindowError> {
    // Sprint G: pixmap → ANativeWindow_lock → memcpy → unlockAndPost.
    //
    // Caller must arrange for `window.cpu_backend.last_frame` to be populated
    // (typically by a regenerate_layout() invocation). Until that wiring is
    // in place we present whatever pixmap is present, or no-op.
    let nw = match window.native_window.as_ref() {
        Some(nw) => nw,
        None => return Ok(()), // background — surface released
    };

    let pixmap = match window.cpu_backend.last_frame.as_ref() {
        Some(p) => p,
        None => return Ok(()), // nothing to present yet
    };

    let pw = pixmap.width() as i32;
    let ph = pixmap.height() as i32;
    if pw <= 0 || ph <= 0 { return Ok(()); }

    // Tell the surface we want RGBA8 of this exact size. Returns an
    // io::Error if Android can't satisfy — surface is gone or surfaceflinger
    // rejected the format; we just skip the frame.
    let _ = nw.set_buffers_geometry(
        pw, ph,
        Some(ndk::hardware_buffer_format::HardwareBufferFormat::R8G8B8A8_UNORM),
    );

    let mut guard = match nw.lock(None) {
        Ok(g) => g,
        Err(e) => {
            log_debug!(LogCategory::Rendering, "[Android] ANativeWindow_lock failed: {}", e);
            return Ok(());
        }
    };

    // Per-line blit. `lines()` returns one mutable slice per scanline,
    // trimmed to the visible width — exactly what we need for an RGBA→RGBA
    // copy where stride may exceed width.
    let src = pixmap.data();
    let src_stride = (pw as usize) * 4;
    if let Some(lines) = guard.lines() {
        for (y, line) in lines.enumerate() {
            if y >= ph as usize { break; }
            let src_off = y * src_stride;
            let end = (src_off + src_stride).min(src.len());
            let src_row = &src[src_off..end];
            let n = src_row.len().min(line.len());
            // SAFETY: line is &mut [MaybeUninit<u8>]; writing initialised
            // bytes is sound. We never read line before writing it.
            unsafe {
                let dst_ptr = line.as_mut_ptr().cast::<u8>();
                core::ptr::copy_nonoverlapping(src_row.as_ptr(), dst_ptr, n);
            }
        }
    }
    // guard.drop() calls ANativeWindow_unlockAndPost
    Ok(())
}

/// Fallback stub for non-android-activity / non-ndk / non-cpurender builds.
#[cfg(not(all(target_os = "android", feature = "android-activity", feature = "ndk", feature = "cpurender")))]
fn render_frame(_window: &mut AndroidWindow) -> Result<(), WindowError> {
    Ok(())
}

/// Stub for non-android-activity builds. Calling this on non-Android hosts is
/// a no-op so other platforms can keep referencing it from feature-gated code.
#[cfg(not(all(target_os = "android", feature = "android-activity")))]
pub fn android_main_stub() {}
