// Generated by azul-css codegen (Node.js). Do not edit by hand.
'use strict';
const azul = require('azul');
const lib = azul.__lib;

// not expressible with the Node bindings: DOM export (builder methods and parameters) is not implemented for this language's printer yet
function renderUi() {
    return undefined;
}

module.exports = { renderUi };
