//! Smalltalk (Pharo) binding generator.
//!
//! Produces a single `Azul.st` source file in **Tonel** format — the
//! modern, text-based, one-class-per-paragraph Pharo source format.
//! Tonel is line-oriented and Git-friendly; older `.sources`/`.changes`
//! and "chunk" formats are intentionally avoided.
//!
//! ## Pharo / UnifiedFFI design
//!
//! The generated file has four conceptual layers, top-to-bottom:
//!
//! 1. A header with file-format documentation.
//! 2. **Type declarations** (`types.rs`):
//!    - `FFIExternalEnumeration subclass: #AzFoo` for unit enums.
//!    - `FFIExternalStructure subclass: #AzFoo` for plain records.
//!    - `FFIExternalUnion subclass: #AzFoo` + a wrapper struct for
//!      tagged unions (the union holds the payload variants, the
//!      wrapper struct prepends the discriminant tag).
//! 3. **FFI call site** (`functions.rs`): a single class
//!    `AzulNative` whose **class side** holds one `ffiCall:` method per
//!    exported C symbol. Each method carries the standard
//!    `<primitive: #primitiveNativeCall module: #UnifiedFFI>` pragma and
//!    forwards to `self ffiCall: #(...) module: 'azul'`.
//! 4. **Idiomatic wrappers** (`wrappers.rs`): plain Smalltalk classes
//!    in the `Azul-Core` package. The `Az` prefix is stripped, methods
//!    are camelCase keyword selectors. Disposable wrappers register
//!    themselves with Pharo's `WeakRegistry` / `FFIExternalResourceManager`
//!    so `finalize` is called automatically on GC and forwarded to
//!    `AzulNative class>>azFooDelete:`.
//!
//! ## File format reference (Tonel)
//!
//! Tonel is the canonical Pharo source format used by Iceberg / Git.
//! A class shape:
//!
//! ```text
//! Class {
//!     #name : #ClassName,
//!     #superclass : #SuperclassName,
//!     #instVars : [ 'inst1' 'inst2' ],
//!     #classVars : [ 'CV' ],
//!     #pools : [ 'PoolDictName' ],
//!     #category : 'Azul-Core'
//! }
//! ```
//!
//! Followed by methods, each preceded by a single-keyword "category"
//! comment (a Pharo convention) and using the `>>` separator:
//!
//! ```text
//! Class >> selector: arg [
//!     <pragma>
//!     "method body"
//!     ^ result
//! ]
//! ```
//!
//! The orchestrator should emit two artifacts:
//! 1. The `Azul.st` produced by [`generate`].
//! 2. A `BaselineOfAzul.st` produced by [`baseline::generate_baseline`]
//!    that lets users load the package with Metacello.

pub mod baseline;
pub mod functions;
pub mod types;
pub mod wrappers;

use anyhow::Result;

use super::config::CodegenConfig;
use super::generator::CodeBuilder;
use super::ir::CodegenIR;

/// The Smalltalk class on whose **class side** every FFI primitive
/// lives. By convention all C symbols are reachable as
/// `AzulNative azFoo: arg` class-side messages.
pub const NATIVE_CLASS: &str = "AzulNative";

/// The package name used in every Tonel `#category` slot for
/// generated artifacts. Pharo's package browser will show this as a
/// flat "Azul-Core" / "Azul-Native" / "Azul-Types" tree.
pub const PACKAGE_CORE: &str = "Azul-Core";
pub const PACKAGE_NATIVE: &str = "Azul-Native";
pub const PACKAGE_TYPES: &str = "Azul-Types";

/// Name passed to UnifiedFFI's `module:` selector. UFFI resolves this
/// against the platform-specific lookup chain (`libazul.so`,
/// `libazul.dylib`, `azul.dll`).
pub const FFI_MODULE: &str = "azul";

/// Public entry point. Generates the complete `Azul.st` file as a
/// `String`. The caller is expected to write the result to disk
/// (e.g. `target/codegen/v2/Azul.st`) and to separately emit the
/// accompanying `BaselineOfAzul.st` via [`baseline::generate_baseline`].
pub fn generate(ir: &CodegenIR, config: &CodegenConfig) -> Result<String> {
    let mut builder = CodeBuilder::new(&config.indent);

    generate_header(&mut builder);

    // 1. Type declarations: enumerations, plain structs, tagged unions.
    types::generate_types(&mut builder, ir, config)?;

    // 2. The single AzulNative class declaration + every FFI primitive
    //    method on its class side.
    functions::generate_native_methods(&mut builder, ir, config)?;

    // 3. Idiomatic wrapper classes with `finalize`.
    wrappers::generate_wrappers(&mut builder, ir, config)?;

    Ok(builder.finish())
}

fn generate_header(builder: &mut CodeBuilder) {
    builder.line("\"=============================================================================");
    builder.line(" Auto-generated Smalltalk (Pharo) bindings for the Azul GUI framework.");
    builder.line(" Generated by azul-doc codegen v2 (lang_smalltalk).");
    builder.line(" DO NOT EDIT MANUALLY.");
    builder.line("");
    builder.line(" File format: Tonel — modern text-based Pharo source. Each `Class { ... }`");
    builder.line(" paragraph defines a class; methods follow as `Class >> selector [ ... ]`.");
    builder.line(" Load the file with Iceberg or by `'Azul.st' asFileReference fileIn`.");
    builder.line("");
    builder.line(" FFI: requires UnifiedFFI (default in Pharo 8+). The native library must");
    builder.line(" be reachable via the OS loader (libazul.so / libazul.dylib / azul.dll).");
    builder.line("=============================================================================\"");
    builder.blank();
}

// ============================================================================
// Shared helpers (used by submodules)
// ============================================================================

/// Az-prefixed name (`Dom` -> `AzDom`). Used in FFI signatures and as
/// the public name of `FFIExternalStructure` / `FFIExternalUnion` /
/// `FFIExternalEnumeration` subclasses.
pub fn ffi_type_name(name: &str) -> String {
    format!("Az{}", name)
}

/// Idiomatic wrapper class name — strips the `Az` prefix and prepends
/// `Azul`. So the user calls `AzulApp create` rather than `AzApp_create`.
pub fn wrapper_class_name(name: &str) -> String {
    // Avoid clashing with stdlib types (e.g., String): always prefix
    // with `Azul`. This keeps the `Azul-Core` package self-contained.
    format!("Azul{}", name)
}

/// Map a Rust/IR type name to its UnifiedFFI type spec string. The
/// returned string is suitable for use inside `#( ... )` array literals
/// in `ffiCall:` and `fields` declarations.
///
/// UFFI accepts a dialect of C type names: `void*`, `int32`, `float32`,
/// `String` (auto-marshals to `char*`), and any `FFIExternalStructure`
/// subclass name (passed by value or by pointer when suffixed with `*`).
pub fn map_type_to_uffi(rust_type: &str, ir: &CodegenIR) -> String {
    let trimmed = rust_type.trim();

    // Pointer prefixes — UFFI uses `<type>*` syntax.
    if let Some(rest) = trimmed.strip_prefix("*const ") {
        return format!("{}*", map_type_to_uffi(rest, ir));
    }
    if let Some(rest) = trimmed.strip_prefix("*mut ") {
        return format!("{}*", map_type_to_uffi(rest, ir));
    }
    if let Some(rest) = trimmed.strip_prefix("&mut ") {
        return format!("{}*", map_type_to_uffi(rest, ir));
    }
    if let Some(rest) = trimmed.strip_prefix('&') {
        return format!("{}*", map_type_to_uffi(rest, ir));
    }

    match trimmed {
        // Smalltalk has no `bool`-by-default in UFFI; map to the C ABI
        // 1-byte boolean.
        "bool" => "bool".to_string(),
        "u8" | "c_uchar" | "char" => "uint8".to_string(),
        "i8" | "c_char" => "int8".to_string(),
        "u16" => "uint16".to_string(),
        "i16" => "int16".to_string(),
        "u32" | "c_uint" => "uint32".to_string(),
        "i32" | "c_int" => "int32".to_string(),
        "u64" => "uint64".to_string(),
        "i64" => "int64".to_string(),
        "f32" => "float32".to_string(),
        "f64" => "float64".to_string(),
        "usize" => "size_t".to_string(),
        "isize" => "ssize_t".to_string(),
        "c_void" | "()" | "void" => "void".to_string(),

        _ => {
            // Known IR type — refer to its FFIExternalStructure/Union/
            // Enumeration class.
            if ir.find_struct(trimmed).is_some()
                || ir.find_enum(trimmed).is_some()
                || ir.find_type_alias(trimmed).is_some()
                || ir.callback_typedefs.iter().any(|c| c.name == trimmed)
            {
                ffi_type_name(trimmed)
            } else {
                // Unknown — degrade to a typed opaque pointer.
                "void*".to_string()
            }
        }
    }
}

/// Sanitize a Smalltalk identifier. The Smalltalk reserved set is tiny
/// (`self`, `super`, `nil`, `true`, `false`, `thisContext`); we
/// rename them with a trailing underscore. Anything else is returned
/// verbatim.
pub fn sanitize_identifier(name: &str) -> String {
    match name {
        "self" | "super" | "nil" | "true" | "false" | "thisContext" => format!("{}_", name),
        _ => name.to_string(),
    }
}

/// Convert a snake_case or lowerCamelCase method name into Smalltalk's
/// preferred lowerCamelCase form. Smalltalk selectors are always
/// camelCase — never snake_case.
pub fn snake_to_lower_camel(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper = false;
    for (i, c) in s.chars().enumerate() {
        if c == '_' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else if i == 0 {
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// Helper: emit a Tonel category-comment line for a method. Pharo's
/// browser groups methods by category; we use `'ffi'`, `'accessing'`,
/// `'finalization'` per convention.
pub(crate) fn method_category_line(builder: &mut CodeBuilder, category: &str) {
    builder.line(&format!("{{ #category : '{}' }}", category));
}
