//! ALGOL 68 (Algol 68 Genie): `azul.a68` (generated by
//! `doc/src/codegen/v2/lang_algol68`), textually included with
//! `PR include "azul.a68" PR`.
//!
//! Spellings: every C function is an `ALIEN` PROC named lowercase with
//! spaces (`AzCssProperty_textColor` -> `az css property text color`,
//! variant constructor `AzLayoutWidth_px` -> `az layout width px`), a
//! nullary PROC is called without parentheses; C-like enums are INT
//! constants WITHOUT the `az` (`layout display flex`); types are upper-case
//! MODEs with digits spelled out (`AZCOLORU`). Field modes: u8 -> CHAR
//! (`REPR 255`), usize / isize / 64-bit -> LONG INT (`LENG 7`), f32 -> REAL,
//! f64 -> LONG REAL.
//!
//! Calls nest; a struct of 2+ fields is a cast structure display
//! (`AZCOLORU (REPR 255, ..)`), a 1-field struct (no display exists) and a
//! Vec's row are declared ([`super::linear`]); rows are 1-based
//! (`az x vec copy from ptr (t1[1], LENG n)`).
//!
//! Limitation: the bindings declare no MODE for the `CssPropertyValue<T>`
//! aliases (`AZLAYOUTWIDTHVALUE`, ...), so neither they nor a hand-built
//! `CssProperty` union can be written. Strings use the `STRING` ->
//! `az string copy from bytes` helper of `examples/algol68`.

use alloc::{
    format,
    string::{String, ToString},
    vec,
    vec::Vec,
};

use super::linear::{item_blocker, linear_comments, lower_to_statements, LinearSyntax};
use crate::codegen::{
    ir::{snake_to_lower_camel, EnumShape, Expr, Item, Module, Prim},
    lang::{module_any, variant_ctor_method},
    CodegenBackend, GeneratedFile,
};

/// The ALGOL 68 printer.
#[derive(Debug, Copy, Clone, Default)]
pub struct Algol68;

/// `is_algol_reserved` of `lang_algol68/mod.rs`.
const RESERVED: &[&str] = &[
    "abs", "alien", "and", "andth", "begin", "bits", "bool", "by", "bytes", "case", "channel",
    "char", "co", "comment", "complex", "compl", "do", "elif", "else", "empty", "end", "esac",
    "exit", "false", "fi", "file", "finish", "flex", "for", "format", "from", "go", "goto",
    "heap", "if", "in", "int", "is", "isnt", "long", "loc", "mode", "nil", "not", "od", "of",
    "op", "or", "orel", "ouse", "out", "par", "pr", "pragmat", "priority", "proc", "real", "ref",
    "sema", "short", "skip", "string", "struct", "then", "to", "true", "union", "until", "void",
    "while",
];

/// `camel_or_snake_to_spaced_lower` of `lang_algol68/mod.rs`.
fn spaced(s: &str) -> String {
    let mut out = String::new();
    let mut first = true;
    for c in s.chars() {
        if c == '_' {
            if !out.ends_with(' ') && !first {
                out.push(' ');
            }
            continue;
        }
        if c.is_ascii_uppercase() && !first && !out.ends_with(' ') {
            out.push(' ');
        }
        out.push(c.to_ascii_lowercase());
        first = false;
    }
    out.trim().to_string()
}

/// `algol_mode_name` of `lang_algol68/mod.rs`: `AZ` + upper case, digits
/// spelled out.
fn mode(ty: &str) -> String {
    let mut out = String::new();
    for c in format!("Az{ty}").to_ascii_uppercase().chars() {
        let digit = match c {
            '0' => "ZERO",
            '1' => "ONE",
            '2' => "TWO",
            '3' => "THREE",
            '4' => "FOUR",
            '5' => "FIVE",
            '6' => "SIX",
            '7' => "SEVEN",
            '8' => "EIGHT",
            '9' => "NINE",
            _ => {
                out.push(c);
                continue;
            }
        };
        out.push_str(digit);
    }
    out
}

/// `sanitize_identifier` of `lang_algol68/mod.rs` (struct field names).
fn field(name: &str) -> String {
    let name = if name.starts_with('_') {
        format!("f{name}")
    } else {
        name.to_string()
    };
    if RESERVED.contains(&name.to_ascii_lowercase().as_str()) {
        format!("{name}_")
    } else {
        name
    }
}

fn apply(f: &str, args: &[String]) -> String {
    if args.is_empty() {
        f.to_string()
    } else {
        format!("{f} ({})", args.join(", "))
    }
}

/// `LENG n` (a LONG INT from an INT denotation).
fn leng(value: &str) -> String {
    if value.starts_with('-') {
        format!("LENG ({value})")
    } else {
        format!("LENG {value}")
    }
}

impl LinearSyntax for Algol68 {
    fn int(&self, value: i128, ty: Prim) -> String {
        match ty {
            Prim::U8 | Prim::I8 => format!("REPR {value}"),
            Prim::U16 | Prim::I16 => {
                if value < 0 {
                    format!("SHORTEN ({value})")
                } else {
                    format!("SHORTEN {value}")
                }
            }
            Prim::U64 | Prim::I64 | Prim::Usize | Prim::Isize => leng(&value.to_string()),
            _ => value.to_string(),
        }
    }

    fn float(&self, text: &str, ty: Prim) -> String {
        if ty == Prim::F64 {
            leng(text)
        } else {
            text.to_string()
        }
    }

    fn boolean(&self, b: bool) -> String {
        String::from(if b { "TRUE" } else { "FALSE" })
    }

    fn clike(&self, ty: &str, variant: &str) -> String {
        format!("{} {}", spaced(ty), spaced(variant))
    }

    fn type_name(&self, ty: &str) -> String {
        mode(ty)
    }

    fn array_type(&self, elem: &str, n: usize) -> String {
        format!("[{n}] {}", mode(elem))
    }

    fn call(&self, target: &str, class: &str, method: &str, args: &[String]) -> Vec<String> {
        let e = self.call_expr(class, method, args).unwrap_or_default();
        vec![format!("{target} := {e};")]
    }

    fn variant_call(&self, target: &str, ty: &str, variant: &str, args: &[String]) -> Vec<String> {
        let e = self.variant_expr(ty, variant, args).unwrap_or_default();
        vec![format!("{target} := {e};")]
    }

    fn union(
        &self,
        target: &str,
        _ty: &str,
        _variant: &str,
        tag: usize,
        _payload: Option<&str>,
    ) -> Vec<String> {
        // unreachable: `limitation` rejects every hand-built union
        vec![format!("tag OF {target} := {tag};")]
    }

    fn set_field(&self, target: &str, _ty: &str, name: &str, value: &str) -> String {
        format!("{} OF {target} := {value};", field(name))
    }

    fn set_elem(&self, arr: &str, index: usize, value: &str) -> String {
        format!("{arr}[{}] := {value};", index + 1)
    }

    fn vec_from_array(&self, target: &str, ty: &str, elem: &str, arr: &str, count: &str) -> Vec<String> {
        let e = self.vec_expr(ty, elem, arr, count).unwrap_or_default();
        vec![format!("{target} := {e};")]
    }

    fn vec_empty(&self, target: &str, ty: &str) -> Vec<String> {
        vec![format!("{target} := az {} create;", spaced(ty))]
    }

    fn string(&self, target: &str, s: &str) -> Vec<String> {
        vec![format!("{target} := css str ({});", a68_string(s))]
    }

    fn limitation(&self, e: &Expr) -> Option<String> {
        match e {
            Expr::Variant {
                ty,
                shape: EnumShape::Generic { .. },
                ..
            } => Some(format!(
                "the ALGOL 68 bindings declare no MODE for `{ty}` (CssPropertyValue<T>)"
            )),
            Expr::Variant {
                ty,
                shape: EnumShape::TaggedShadowed,
                ..
            } => Some(format!(
                "the ALGOL 68 bindings cannot build a `{ty}` union by hand (its payload \
                 UNION names undeclared CssPropertyValue<T> MODEs)"
            )),
            Expr::Float { text, .. } if text == "nan" || text.ends_with("inf") => {
                Some("ALGOL 68 has no denotation for NaN / infinity".to_string())
            }
            _ => None,
        }
    }

    fn call_expr(&self, class: &str, method: &str, args: &[String]) -> Option<String> {
        let f = format!("az {} {}", spaced(class), spaced(&snake_to_lower_camel(method)));
        Some(apply(&f, args))
    }

    fn variant_expr(&self, ty: &str, variant: &str, args: &[String]) -> Option<String> {
        let f = format!("az {} {}", spaced(ty), spaced(&variant_ctor_method(variant)));
        Some(apply(&f, args))
    }

    fn struct_expr(&self, ty: &str, fields: &[(String, String)]) -> Option<String> {
        // a structure display needs 2+ fields; a 1-field struct is declared
        if fields.len() < 2 {
            return None;
        }
        let values: Vec<&str> = fields.iter().map(|(_, v)| v.as_str()).collect();
        Some(format!("{} ({})", mode(ty), values.join(", ")))
    }

    fn string_expr(&self, s: &str) -> Option<String> {
        Some(format!("css str ({})", a68_string(s)))
    }

    fn vec_expr(&self, ty: &str, _elem: &str, arr: &str, count: &str) -> Option<String> {
        Some(format!("az {} copy from ptr ({arr}[1], {count})", spaced(ty)))
    }

    fn vec_empty_expr(&self, ty: &str) -> Option<String> {
        Some(format!("az {} create", spaced(ty)))
    }
}

/// An ALGOL 68 string denotation (`"` doubled); other non-printable bytes
/// are joined in as `REPR n`.
fn a68_string(s: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    let mut run = String::new();
    for b in s.bytes() {
        if (0x20..0x7f).contains(&b) {
            if b == b'"' {
                run.push_str("\"\"");
            } else {
                run.push(char::from(b));
            }
        } else {
            if !run.is_empty() || parts.is_empty() {
                parts.push(format!("\"{run}\""));
                run.clear();
            }
            parts.push(format!("REPR {b}"));
        }
    }
    if !run.is_empty() || parts.is_empty() {
        parts.push(format!("\"{run}\""));
    }
    parts.join(" + ")
}

fn proc_name(item: &Item) -> String {
    let words: Vec<String> = item.name.snake().split('_').map(field).collect();
    words.join(" ")
}

fn comment(text: &str) -> String {
    format!("# {} #", text.replace('#', "?"))
}

fn item_proc(item: &Item) -> (bool, String) {
    let name = proc_name(item);
    if let Some(reason) = item_blocker(&Algol68, item) {
        return (
            false,
            format!(
                "{}\n",
                comment(&format!("{name}: not expressible with the ALGOL 68 bindings: {reason}"))
            ),
        );
    }
    let st = lower_to_statements(&Algol68, &item.value);
    let mut out = String::new();
    for line in linear_comments(item, &st) {
        out.push_str(&comment(&line));
        out.push('\n');
    }
    out.push_str(&format!("PROC {name} = {}:\nBEGIN\n", mode(&item.ty)));
    for (n, t) in &st.decls {
        out.push_str(&format!("   {t} {n};\n"));
    }
    for s in &st.body {
        out.push_str(&format!("   {s}\n"));
    }
    out.push_str(&format!("   {}\nEND;\n", st.result));
    (true, out)
}

const CSS_STR: &str = "PROC css str = (STRING s) AZSTRING:
   az string copy from bytes (s, LENG 0, LENG UPB s);
";

impl CodegenBackend for Algol68 {
    fn lang(&self) -> &'static str {
        "algol68"
    }

    fn aliases(&self) -> &'static [&'static str] {
        &["a68", "algol", "a68g"]
    }

    fn display_name(&self) -> &'static str {
        "ALGOL 68"
    }

    fn extension(&self) -> &'static str {
        "a68"
    }

    fn emit_module(&self, m: &Module) -> String {
        let mut out = String::from(
            "# Generated by azul-css codegen (ALGOL 68). Do not edit by hand. #\n# Include after \
             azul.a68: PR include \"styles.a68\" PR #\n",
        );
        if module_any(m, &|e| matches!(e, Expr::Str(_))) {
            out.push('\n');
            out.push_str(CSS_STR);
        }
        for item in &m.items {
            out.push('\n');
            out.push_str(&item_proc(item).1);
        }
        out
    }

    fn emit_project_files(&self, m: &Module) -> Vec<GeneratedFile> {
        let mut main = String::from(
            "# Copy target/codegen/azul.a68 and libazul here, then: a68g main.a68 #\nPR include \
             \"azul.a68\" PR\nPR include \"styles.a68\" PR\n\n",
        );
        let built: Vec<&Item> = m.items.iter().filter(|i| item_proc(i).0).collect();
        for item in &built {
            let name = proc_name(item);
            main.push_str(&format!("{} {name} value = {name};\n", mode(&item.ty)));
        }
        let prints: Vec<String> = built
            .iter()
            .map(|item| {
                let name = proc_name(item);
                format!(
                    "print ((\"{name}: \", whole (len OF {name} value, 0), \" properties\", new \
                     line))"
                )
            })
            .collect();
        if prints.is_empty() {
            main.push_str("SKIP\n");
        } else {
            main.push_str(&prints.join(";\n"));
            main.push('\n');
        }
        vec![
            GeneratedFile {
                path: "styles.a68".to_string(),
                contents: self.emit_module(m),
            },
            GeneratedFile {
                path: "main.a68".to_string(),
                contents: main,
            },
        ]
    }
}
