//! Node.js: the koffi bindings `azul` (`target/codegen/node/azul.js`,
//! generated by `doc/src/codegen/v2/lang_node`).
//!
//! The wrapper classes consume their arguments and cannot be nested inside
//! the plain objects koffi takes for structs and unions, so the generated
//! code drives the raw C symbols the module exports as `azul.__lib`
//! (`lib.AzCssProperty_textColor(..)`, the variant constructors
//! `lib.AzLayoutWidth_px(..)`), passes structs as plain objects with the C
//! field names (`{ r: 255, g: 0, b: 0, a: 255 }`), unions as
//! `{ Exact: { tag: 6, payload: .. } }`, C-like enums as the frozen number
//! tables (`azul.LayoutDisplay.Flex`), a Vec's items as a JS array
//! (`lib.AzXxxVec_copyFromPtr([..], n)`), strings through `azul._azString`,
//! and wraps the finished value in its class (`new azul.CssPropertyWithConditionsVec(..)`).

use alloc::{
    format,
    string::{String, ToString},
    vec,
    vec::Vec,
};

use crate::codegen::{
    doc::{render, Doc},
    ir::{snake_to_lower_camel, EnumShape, Item, Module, Prim},
    lang::{escape_quoted, item_comments, item_doc, unicode_braced, variant_ctor_method, ExprSyntax},
    lower_types::union_tag,
    CodegenBackend, GeneratedFile,
};

/// The Node.js printer.
#[derive(Debug, Copy, Clone, Default)]
pub struct Node;

/// `{ Variant: { tag: n, payload: x } }` for a union koffi builds from a
/// plain object (shared with the other koffi/luajit-style printers).
pub(crate) fn object_union(ty: &str, variant: &str, args: Vec<Doc>, broken: bool, kv: &str) -> Doc {
    let tag = union_tag(ty, variant).unwrap_or(0);
    let mut inner = vec![Doc::text(format!("tag{kv}{tag}"))];
    if let Some(payload) = args.into_iter().next() {
        inner.push(Doc::cat(vec![Doc::text(format!("payload{kv}")), payload]));
    }
    Doc::list(
        "{",
        vec![Doc::cat(vec![
            Doc::text(format!("{variant}{kv}")),
            Doc::list("{", inner, ", ", "}", true, broken, false),
        ])],
        ", ",
        "}",
        true,
        broken,
        false,
    )
}

impl ExprSyntax for Node {
    fn int(&self, value: i128, _ty: Prim) -> String {
        value.to_string()
    }

    fn float(&self, text: &str, _ty: Prim) -> String {
        match text {
            "nan" => "NaN".to_string(),
            "inf" => "Infinity".to_string(),
            "-inf" => "-Infinity".to_string(),
            _ => text.to_string(),
        }
    }

    fn boolean(&self, b: bool) -> String {
        b.to_string()
    }

    fn string(&self, s: &str) -> Doc {
        Doc::text(format!(
            "azul._azString(\"{}\")",
            escape_quoted(s, &[], &unicode_braced)
        ))
    }

    fn call(&self, class: &str, method: &str, args: Vec<Doc>, broken: bool) -> Doc {
        Doc::call(format!("lib.Az{class}_{}", snake_to_lower_camel(method)), args, broken)
    }

    fn variant(&self, ty: &str, shape: EnumShape, variant: &str, args: Vec<Doc>, broken: bool) -> Doc {
        match shape {
            EnumShape::CLike => Doc::text(format!("azul.{ty}.{variant}")),
            EnumShape::Tagged => Doc::call(
                format!("lib.Az{ty}_{}", variant_ctor_method(variant)),
                args,
                broken,
            ),
            EnumShape::TaggedShadowed | EnumShape::Generic { .. } => {
                object_union(ty, variant, args, broken, ": ")
            }
        }
    }

    fn strukt(&self, _ty: &str, fields: Vec<(String, Doc)>, broken: bool) -> Doc {
        let fields = fields
            .into_iter()
            .map(|(k, v)| Doc::cat(vec![Doc::text(format!("{k}: ")), v]))
            .collect();
        Doc::list("{", fields, ", ", "}", true, broken, true)
    }

    fn vec(&self, ty: &str, _elem: &str, items: Vec<Doc>, broken: bool) -> Doc {
        if items.is_empty() {
            return Doc::text(format!("lib.Az{ty}_create()"));
        }
        let n = items.len();
        Doc::cat(vec![
            Doc::text(format!("lib.Az{ty}_copyFromPtr(")),
            Doc::list("[", items, ", ", "]", false, broken, true),
            Doc::text(format!(", {n})")),
        ])
    }

    fn unsupported(&self, what: &str) -> Doc {
        Doc::text(format!("undefined /* not expressible: {} */", super::block_comment_safe(what)))
    }
}

fn item_fn(item: &Item) -> String {
    let mut out = String::new();
    for line in &item_comments(&Node, item) {
        out.push_str(&format!("// {line}\n"));
    }
    let name = item.name.lower_camel();
    match item_doc(&Node, item) {
        Ok(doc) => out.push_str(&format!(
            "function {name}() {{\n    return new azul.{}({});\n}}\n",
            item.ty,
            render(&doc, "    ", 1)
        )),
        Err(reason) => out.push_str(&format!(
            "// not expressible with the Node bindings: {reason}\nfunction {name}() {{\n    return \
             undefined;\n}}\n"
        )),
    }
    out
}

impl CodegenBackend for Node {
    fn lang(&self) -> &'static str {
        "node"
    }

    fn aliases(&self) -> &'static [&'static str] {
        &["js", "javascript", "nodejs"]
    }

    fn display_name(&self) -> &'static str {
        "Node.js"
    }

    fn extension(&self) -> &'static str {
        "js"
    }

    fn emit_module(&self, m: &Module) -> String {
        let mut out = String::from(
            "// Generated by azul-css codegen (Node.js). Do not edit by hand.\n'use strict';\nconst \
             azul = require('azul');\nconst lib = azul.__lib;\n",
        );
        for item in &m.items {
            out.push('\n');
            out.push_str(&item_fn(item));
        }
        let names: Vec<String> = m.items.iter().map(|i| i.name.lower_camel()).collect();
        out.push_str(&format!("\nmodule.exports = {{ {} }};\n", names.join(", ")));
        out
    }

    fn emit_project_files(&self, m: &Module) -> Vec<GeneratedFile> {
        let names: Vec<String> = m.items.iter().map(|i| i.name.lower_camel()).collect();
        let mut main = format!(
            "'use strict';\nconst {{ {} }} = require('./styles');\n",
            names.join(", ")
        );
        for name in &names {
            main.push_str(&format!(
                "\nconst {name}Value = {name}();\nconsole.log(`{name}: ${{{name}Value.raw.len}} properties`);\n"
            ));
        }
        vec![
            GeneratedFile {
                path: "package.json".to_string(),
                contents: "{\n  \"name\": \"azul-styles\",\n  \"version\": \"0.1.0\",\n  \
                           \"private\": true,\n  \"main\": \"main.js\",\n  \"dependencies\": {\n    \
                           \"azul\": \"file:./azul-node\",\n    \"koffi\": \"^2.16.3\"\n  }\n}\n"
                    .to_string(),
            },
            GeneratedFile {
                path: "styles.js".to_string(),
                contents: self.emit_module(m),
            },
            GeneratedFile {
                path: "main.js".to_string(),
                contents: main,
            },
        ]
    }
}
