//! Rust: the `azul` crate (`dll/`, re-exports in `target/codegen/reexports.rs`).
//!
//! Spellings (from the generated `dll_api_external.rs` / `reexports.rs`):
//! types without the `Az` prefix under `azul::<api module>::*`; api.json
//! constructors keep their snake_case names (`CssProperty::text_color`,
//! `FloatValue::create`); enums are native Rust enums (variants, and
//! `LayoutWidthValue::Exact(..)` through the `CssPropertyValue<T>` alias);
//! structs have pub fields; `XxxVec: From<Vec<Xxx>>`; `azul::str::String:
//! From<&str>`.

use alloc::{
    format,
    string::{String, ToString},
    vec,
    vec::Vec,
};

use crate::codegen::{
    doc::{render, Doc},
    ir::{EnumShape, Item, Module, Prim},
    lang::{expr_doc_top, item_comments, used_api_modules, ExprSyntax},
    CodegenBackend, GeneratedFile, AZUL_VERSION,
};

/// The Rust printer.
#[derive(Debug, Copy, Clone, Default)]
pub struct Rust;

/// Rust keywords that need a raw identifier (`r#type`) as a field name.
const KEYWORDS: &[&str] = &[
    "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
    "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
    "mut", "pub", "ref", "return", "static", "struct", "trait", "true", "type", "unsafe", "use",
    "where", "while", "abstract", "become", "box", "do", "final", "macro", "override", "priv",
    "typeof", "unsized", "virtual", "yield", "try", "gen",
];

fn ident(name: &str) -> String {
    if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

impl ExprSyntax for Rust {
    fn int(&self, value: i128, _ty: Prim) -> String {
        value.to_string()
    }

    fn float(&self, text: &str, ty: Prim) -> String {
        let t = if ty == Prim::F64 { "f64" } else { "f32" };
        match text {
            "nan" => format!("{t}::NAN"),
            "inf" => format!("{t}::INFINITY"),
            "-inf" => format!("{t}::NEG_INFINITY"),
            _ => text.to_string(),
        }
    }

    fn boolean(&self, b: bool) -> String {
        b.to_string()
    }

    fn string(&self, s: &str) -> Doc {
        Doc::text(format!("azul::str::String::from({s:?})"))
    }

    fn call(&self, class: &str, method: &str, args: Vec<Doc>, broken: bool) -> Doc {
        Doc::call(format!("{class}::{}", ident(method)), args, broken)
    }

    fn variant(&self, ty: &str, _shape: EnumShape, variant: &str, args: Vec<Doc>, broken: bool) -> Doc {
        if args.is_empty() {
            Doc::text(format!("{ty}::{variant}"))
        } else {
            Doc::call(format!("{ty}::{variant}"), args, broken)
        }
    }

    fn strukt(&self, ty: &str, fields: Vec<(String, Doc)>, broken: bool) -> Doc {
        let fields = fields
            .into_iter()
            .map(|(k, v)| Doc::cat(vec![Doc::text(format!("{}: ", ident(&k))), v]))
            .collect();
        Doc::cat(vec![
            Doc::text(format!("{ty} ")),
            Doc::list("{", fields, ", ", "}", true, broken, true),
        ])
    }

    fn vec(&self, ty: &str, _elem: &str, items: Vec<Doc>, broken: bool) -> Doc {
        if items.is_empty() {
            return Doc::text(format!("{ty}::create()"));
        }
        Doc::cat(vec![
            Doc::text(format!("{ty}::from(vec!")),
            Doc::list("[", items, ", ", "]", false, broken, true),
            Doc::text(")"),
        ])
    }

    fn unsupported(&self, what: &str) -> Doc {
        Doc::text(format!("unimplemented!({what:?})"))
    }
}

fn item_fn(item: &Item) -> String {
    let mut out = String::new();
    for line in &item_comments(&Rust, item) {
        out.push_str(&format!("/// {line}\n"));
    }
    let body = render(&expr_doc_top(&Rust, &item.value), "    ", 1);
    out.push_str(&format!(
        "pub fn {}() -> {} {{\n    {body}\n}}\n",
        item.name.snake(),
        item.ty
    ));
    out
}

impl CodegenBackend for Rust {
    fn lang(&self) -> &'static str {
        "rust"
    }

    fn aliases(&self) -> &'static [&'static str] {
        &["rs"]
    }

    fn display_name(&self) -> &'static str {
        "Rust"
    }

    fn extension(&self) -> &'static str {
        "rs"
    }

    fn emit_module(&self, m: &Module) -> String {
        let mut out = String::from("// Generated by azul-css codegen (Rust). Do not edit by hand.\n\n");
        for module in used_api_modules(m) {
            if module == "str" {
                continue; // strings are spelled `azul::str::String::from(..)`
            }
            out.push_str(&format!("#[allow(unused_imports)]\nuse azul::{module}::*;\n"));
        }
        for item in &m.items {
            out.push('\n');
            out.push_str(&item_fn(item));
        }
        out
    }

    fn emit_project_files(&self, m: &Module) -> Vec<GeneratedFile> {
        let mut main = String::from("mod styles;\n\nfn main() {\n");
        for item in &m.items {
            let name = item.name.snake();
            if item.ty.ends_with("Vec") {
                main.push_str(&format!(
                    "    let {name} = styles::{name}();\n    println!(\"{name}: {{}} properties\", {name}.len());\n"
                ));
            } else {
                main.push_str(&format!(
                    "    let _{name} = styles::{name}();\n    println!(\"{name}: built\");\n"
                ));
            }
        }
        main.push_str("}\n");
        vec![
            GeneratedFile {
                path: "Cargo.toml".to_string(),
                contents: format!(
                    "[package]\nname = \"azul-styles\"\nversion = \"0.1.0\"\nedition = \
                     \"2021\"\n\n[dependencies]\n# The bindings are served from the azul.rs \
                     registry (see .cargo/config.toml).\n# Link against the prebuilt library: \
                     export AZ_LINK_PATH=/path/to/libazul.so\nazul = {{ version = \
                     \"{AZUL_VERSION}\", registry = \"azul\" }}\n"
                ),
            },
            GeneratedFile {
                path: ".cargo/config.toml".to_string(),
                contents: "[registries]\nazul = { index = \"sparse+https://azul.rs/ui/cargo/\" }\n"
                    .to_string(),
            },
            GeneratedFile {
                path: "src/styles.rs".to_string(),
                contents: self.emit_module(m),
            },
            GeneratedFile {
                path: "src/main.rs".to_string(),
                contents: main,
            },
        ]
    }
}
