//! Swift: the `Azul` module (`target/codegen/azul.swift`, generated by
//! `doc/src/codegen/v2/lang_swift`).
//!
//! Spellings: native Swift enums with lowerCamel cases (`LayoutDisplay.flex`,
//! `LayoutWidth.px(..)`, `LayoutWidthValue.exact(..)`, `CssProperty.whiteSpace(..)`
//! for the variant, the static func `CssProperty.width(_: LayoutWidth)` for
//! the api.json constructor), structs with labelled initialisers
//! (`ColorU(r: 255, g: 0, b: 0, a: 255)`, `StyleTextColor(inner: ..)`),
//! api `create` constructors as `init(_:)` (`FloatValue(1.0)`), first
//! argument unlabelled and the rest labelled (`PixelValue.fromMetric(.., value:)`),
//! native `String`s, and native arrays wherever a Vec is expected.
//!
//! A DOM uses the same native API: a static `create_x` is `x`
//! (`Dom.div()`, `Dom.a(href, text: .., aria: ..)`, the generator's rule in
//! `lang_swift/wrappers.rs`), a by-value `self` method mutates its receiver
//! and returns it (`.withChild(..)`, chained). A component instance calls
//! the component's function with the argument labels it declares
//! (`renderBadge(text: tag)`). An app is
//! `WindowCreateOptions(layout)` with a typed layout function over any
//! class, `App(AppData(), AppConfig())` and `app.run(window)`.

use alloc::{
    format,
    string::{String, ToString},
    vec,
    vec::Vec,
};

use crate::codegen::{
    doc::{render, Doc},
    ir::{EnumShape, Ident, Item, Module, Prim},
    lang::{
        call_param_names,
        dom::{is_dom_item, one_line, registration_note},
        escape_quoted, expr_doc, is_droppable_vec, item_comments, item_doc, unicode_braced,
        ConcatPart, ExprSyntax, MethodLayout,
    },
    CodegenBackend, GeneratedFile,
};

/// The Swift printer.
#[derive(Debug, Copy, Clone, Default)]
pub struct Swift;

/// `lower_leading` + `camel` of `doc/src/codegen/v2/lang_swift/mod.rs`:
/// `text_color` -> `textColor`, `MacOS` -> `macOS`, `IOS` -> `ios`,
/// `W500` -> `w500`.
#[must_use]
pub fn swift_camel(name: &str) -> String {
    let mut out = String::new();
    for (i, part) in name.split('_').filter(|p| !p.is_empty()).enumerate() {
        if i == 0 {
            let chars: Vec<char> = part.chars().collect();
            let run = chars.iter().take_while(|c| c.is_ascii_uppercase()).count();
            let lower_to = if run <= 1 || run == chars.len() {
                run
            } else if chars[run].is_ascii_lowercase() {
                run - 1
            } else {
                run
            };
            out.extend(chars.iter().enumerate().map(|(j, c)| {
                if j < lower_to {
                    c.to_ascii_lowercase()
                } else {
                    *c
                }
            }));
        } else {
            out.push_str(&crate::codegen::ir::capitalize(part));
        }
    }
    out
}

/// `reserved_member` of the Swift generator: these get a trailing `_`.
const RESERVED_MEMBERS: &[&str] = &[
    "description", "debugDescription", "hashValue", "hash", "copy", "init", "deinit", "self",
    "Type", "Protocol", "default", "downcast", "subscript",
];

/// Swift keywords, wrapped in backticks when used as a name.
const KEYWORDS: &[&str] = &[
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import",
    "init", "inout", "internal", "let", "open", "operator", "private", "precedencegroup",
    "protocol", "public", "rethrows", "static", "struct", "subscript", "typealias", "var",
    "break", "case", "catch", "continue", "default", "defer", "do", "else", "fallthrough", "for",
    "guard", "if", "in", "repeat", "return", "switch", "where", "while", "as", "Any", "false",
    "is", "true", "nil", "self", "super", "throw", "throws", "try",
];

/// A parameter's Swift name (a keyword or reserved member gets a `_`).
fn swift_param(name: &Ident) -> String {
    let n = name.lower_camel();
    if KEYWORDS.contains(&n.as_str()) || RESERVED_MEMBERS.contains(&n.as_str()) {
        format!("{n}_")
    } else {
        n
    }
}

/// A member / case name as the Swift generator spells it.
fn member(name: &str) -> String {
    let mut n = swift_camel(name);
    if RESERVED_MEMBERS.contains(&n.as_str()) {
        n.push('_');
    }
    if KEYWORDS.contains(&n.as_str()) {
        format!("`{n}`")
    } else {
        n
    }
}

impl ExprSyntax for Swift {
    fn int(&self, value: i128, _ty: Prim) -> String {
        value.to_string()
    }

    fn float(&self, text: &str, ty: Prim) -> String {
        let t = if ty == Prim::F64 { "Double" } else { "Float" };
        match text {
            "nan" => format!("{t}.nan"),
            "inf" => format!("{t}.infinity"),
            "-inf" => format!("-{t}.infinity"),
            _ => text.to_string(),
        }
    }

    fn boolean(&self, b: bool) -> String {
        b.to_string()
    }

    fn string(&self, s: &str) -> Doc {
        Doc::text(format!("\"{}\"", escape_quoted(s, &[], &unicode_braced)))
    }

    fn call(&self, class: &str, method: &str, args: Vec<Doc>, broken: bool) -> Doc {
        let names = call_param_names(class, method);
        let args = args
            .into_iter()
            .enumerate()
            .map(|(i, a)| match names.get(i) {
                Some(n) if i > 0 => Doc::cat(vec![Doc::text(format!("{}: ", swift_camel(n))), a]),
                _ => a,
            })
            .collect();
        if method == "create" {
            Doc::call(class.to_string(), args, broken)
        } else if let Some(rest) = method.strip_prefix("create_") {
            // A static `create_x` is `x` (`Dom.div()`); the CSS lowering
            // emits none of these.
            Doc::call(format!("{class}.{}", member(rest)), args, broken)
        } else {
            Doc::call(format!("{class}.{}", member(method)), args, broken)
        }
    }

    fn variant(&self, ty: &str, _shape: EnumShape, variant: &str, args: Vec<Doc>, broken: bool) -> Doc {
        let case = format!("{ty}.{}", member(variant));
        if args.is_empty() {
            Doc::text(case)
        } else {
            Doc::call(case, args, broken)
        }
    }

    fn strukt(&self, ty: &str, fields: Vec<(String, Doc)>, broken: bool) -> Doc {
        let fields = fields
            .into_iter()
            .map(|(k, v)| {
                let mut label = swift_camel(&k);
                if RESERVED_MEMBERS.contains(&label.as_str()) {
                    label.push('_');
                }
                Doc::cat(vec![Doc::text(format!("{label}: ")), v])
            })
            .collect();
        Doc::call(ty.to_string(), fields, broken)
    }

    fn vec(&self, _ty: &str, _elem: &str, items: Vec<Doc>, broken: bool) -> Doc {
        Doc::list("[", items, ", ", "]", false, broken, true)
    }

    fn unsupported(&self, what: &str) -> Doc {
        Doc::text(format!("fatalError({:?})", format!("not expressible: {what}")))
    }

    fn dom_limitation(&self) -> Option<&'static str> {
        None
    }

    /// `.withChild(..)`: the first argument unlabelled (every builder
    /// method the DOM lowering emits takes one).
    fn method(&self, recv: Doc, _class: &str, method: &str, args: Vec<Doc>, layout: MethodLayout) -> Doc {
        Doc::chained(recv, Doc::call(format!(".{}", member(method)), args, layout.args_tall))
    }

    fn param(&self, name: &Ident) -> Doc {
        Doc::text(swift_param(name))
    }

    /// String interpolation.
    fn concat(&self, parts: &[ConcatPart<'_>]) -> Doc {
        let mut out = String::from("\"");
        for p in parts {
            match p {
                ConcatPart::Lit(s) => out.push_str(&escape_quoted(s, &[], &unicode_braced)),
                ConcatPart::Param(i) => out.push_str(&format!("\\({})", swift_param(i))),
            }
        }
        out.push('"');
        Doc::text(out)
    }

    fn item_call_limitation(&self) -> Option<&'static str> {
        None
    }

    /// `renderBadge(text: tag)`: another function of the module, each
    /// argument labelled with the callee's parameter name, spelled like its
    /// declaration (the native `String` arguments are the default
    /// `native_string`).
    fn item_call(&self, item: &Ident, params: &[Ident], args: Vec<Doc>, broken: bool) -> Doc {
        let args = args
            .into_iter()
            .enumerate()
            .map(|(i, a)| match params.get(i) {
                Some(p) => Doc::cat(vec![Doc::text(format!("{}: ", swift_param(p))), a]),
                None => a,
            })
            .collect();
        Doc::call(item.lower_camel(), args, broken)
    }
}

/// A DOM item: a function with labelled `String` parameters that default
/// to the values the item was made with.
fn dom_item_fn(item: &Item) -> String {
    let mut out = String::new();
    for line in &item_comments(&Swift, item) {
        out.push_str(&format!("// {line}\n"));
    }
    let name = item.name.lower_camel();
    let params = item
        .params
        .iter()
        .map(|p| match &p.default {
            Some(d) => format!("{}: String = {}", swift_param(&p.name), expr_doc(&Swift, d).flat()),
            None => format!("{}: String", swift_param(&p.name)),
        })
        .collect::<Vec<_>>()
        .join(", ");
    match item_doc(&Swift, item) {
        Ok(doc) => out.push_str(&format!(
            "public func {name}({params}) -> {} {{\n    return {}\n}}\n",
            item.ty,
            render(&doc, "    ", 1)
        )),
        Err(reason) => out.push_str(&format!(
            "// not expressible with the Swift bindings: {reason}\npublic func {name}({params}) -> \
             {}? {{\n    return nil\n}}\n",
            item.ty
        )),
    }
    out
}

/// Why the Swift bindings cannot register a component library.
const NO_REGISTRATION: &str = "the Swift bindings cannot fill one: ComponentDef and \
                               ComponentLibrary have no public initializer, and no wrapper class \
                               hands out its raw value (`_take` is internal), so a render_fn \
                               cannot pass the Dom a render function builds to \
                               AzStyledDom_createFromDom";

/// The app's `main.swift` around a DOM module (`m.app`).
fn app_main(m: &Module) -> String {
    let Some(app) = &m.app else {
        return String::new();
    };
    let root = format!("{}()", app.root.lower_camel());
    let body = if app.is_body {
        root
    } else {
        format!("Dom.body().withChild({root})")
    };
    format!(
        "// {} - generated by AzBuilder (azul-css codegen, Swift).\nimport Azul\n\n// The app's \
         data: the layout callback gets it back.\nfinal class AppData {{}}\n\nfunc layout(_ data: \
         AppData, _ info: LayoutCallbackInfo) -> Dom {{\n    return {body}\n}}\n\nlet window = \
         WindowCreateOptions(layout)\nwindow.windowState.title = {}\nlet app = App(AppData(), \
         AppConfig())\napp.run(window)\n",
        one_line(&app.title),
        Swift.string(&app.title).flat()
    )
}

fn item_fn(item: &Item) -> String {
    if is_dom_item(item) {
        return dom_item_fn(item);
    }
    let mut out = String::new();
    for line in &item_comments(&Swift, item) {
        out.push_str(&format!("// {line}\n"));
    }
    let name = item.name.lower_camel();
    let ty = if is_droppable_vec(&item.ty) {
        "[CssPropertyWithConditions]".to_string()
    } else {
        item.ty.clone()
    };
    match item_doc(&Swift, item) {
        Ok(doc) => out.push_str(&format!(
            "public func {name}() -> {ty} {{\n    return {}\n}}\n",
            render(&doc, "    ", 1)
        )),
        Err(reason) => out.push_str(&format!(
            "// not expressible with the Swift bindings: {reason}\npublic func {name}() -> {ty}? \
             {{\n    return nil\n}}\n"
        )),
    }
    out
}

impl CodegenBackend for Swift {
    fn lang(&self) -> &'static str {
        "swift"
    }

    fn display_name(&self) -> &'static str {
        "Swift"
    }

    fn extension(&self) -> &'static str {
        "swift"
    }

    fn exports_dom(&self) -> bool {
        true
    }

    fn emit_module(&self, m: &Module) -> String {
        let mut out =
            String::from("// Generated by azul-css codegen (Swift). Do not edit by hand.\nimport Azul\n");
        for item in &m.items {
            out.push('\n');
            out.push_str(&item_fn(item));
        }
        if let Some(lib) = &m.library {
            out.push('\n');
            for line in registration_note(lib, NO_REGISTRATION) {
                out.push_str(&format!("// {line}\n"));
            }
        }
        out
    }

    fn emit_project_files(&self, m: &Module) -> Vec<GeneratedFile> {
        if m.app.is_some() {
            return vec![
                GeneratedFile {
                    path: "Package.swift".to_string(),
                    contents: package("AzulApp"),
                },
                GeneratedFile {
                    path: "Sources/AzulApp/UI.swift".to_string(),
                    contents: self.emit_module(m),
                },
                GeneratedFile {
                    path: "Sources/AzulApp/main.swift".to_string(),
                    contents: app_main(m),
                },
            ];
        }
        let mut main = String::new();
        for item in &m.items {
            let name = item.name.lower_camel();
            main.push_str(&format!(
                "let {name}Value = {name}()\nprint(\"{name}: \\({name}Value.count) properties\")\n"
            ));
        }
        vec![
            GeneratedFile {
                path: "Package.swift".to_string(),
                contents: package("AzulStyles"),
            },
            GeneratedFile {
                path: "Sources/AzulStyles/Styles.swift".to_string(),
                contents: self.emit_module(m),
            },
            GeneratedFile {
                path: "Sources/AzulStyles/main.swift".to_string(),
                contents: main,
            },
        ]
    }
}

/// The SwiftPM manifest of an executable named `name` (its sources in
/// `Sources/<name>`).
fn package(name: &str) -> String {
    PACKAGE.replace("AzulStyles", name)
}

const PACKAGE: &str = r#"// swift-tools-version:5.7
// Copy target/codegen/swift/ to ./azul-swift and libazul next to the binary,
// then: swift build -Xlinker -L. && ./.build/debug/AzulStyles
import PackageDescription

let package = Package(
    name: "AzulStyles",
    dependencies: [
        .package(path: "azul-swift"),
    ],
    targets: [
        .executableTarget(
            name: "AzulStyles",
            dependencies: [.product(name: "Azul", package: "azul-swift")],
            path: "Sources/AzulStyles"
        ),
    ]
)
"#;
