//! Zig: `azul.zig` (generated by `doc/src/codegen/v2/lang_zig`), which
//! exposes the C API of `azul.h` as `azul.C` (pre-translated, in the
//! spelling `zig translate-c` produces: the same names, fields and unions).
//!
//! The wrapper namespaces mix raw C returns with `{inner, consumed}`
//! wrappers and take C-like enums as raw integers anyway, so the generated
//! code uses `azul.C` directly: C functions (`C.AzCssProperty_textColor(..)`,
//! variant constructors `C.AzLayoutWidth_px(..)`), enum constants
//! (`C.AzLayoutDisplay_Flex`), anonymous-struct literals for structs and
//! union members (`C.AzColorU{ .r = 255, .. }`,
//! `C.AzLayoutWidthValue{ .Exact = .{ .tag = 6, .payload = .. } }`), a Vec
//! copied from an array literal (`C.AzXxxVec_copyFromPtr(&[_]C.AzXxx{ .. }, n)`)
//! and strings from byte literals (`C.AzString_copyFromBytes("..", 0, n)`,
//! non-printable bytes as `\xNN`: Zig has no octal escapes).
//! Top-level `const`s must be comptime-known, so styles are `pub fn`s.
//!
//! A DOM uses `azul.C` too: the wrapper structs' builder methods take
//! `self: *Self`, which a call result (a temporary, always const in Zig)
//! cannot bind, so they do not chain. A DOM is nested C calls
//! (`C.AzDom_withChild(C.AzDom_withCss(C.AzDom_createDiv(), s), child)`),
//! parameters are `[]const u8` slices copied by
//! `C.AzString_copyFromBytes(title.ptr, 0, title.len)`, a joined text is
//! `azConcat(&[_][]const u8{ "by ", author })`, and a parameter the body
//! never reads is discarded (`_ = name;`: Zig rejects unused parameters).
//! A component instance calls the component's function with `[]const u8`
//! arguments (`renderBadge(tag)`); a text joined from parameters would need
//! memory the caller frees, so such a call is a limitation (as in C).
//! A component library gets the registration of the C export, transliterated
//! (`azul.C` mirrors `azul.h`: the same functions, fields and union members):
//! `callconv(.c)` render functions, a `C.AzComponentDef` per component (code
//! calls it through its render function: `C.AzComponentCodegen_renderFunction()`)
//! and a `register<Library>Library()` for
//! `AzAppConfig_addComponentLibrary`. An app is `build.zig`, `ui.zig` and a
//! `main.zig` in the style of the binding's hello world:
//! `azul.WindowCreateOptions.create(layout)` with a layout function over
//! `azul.ReflectModel(AppData).Ref`, the window title and
//! `azul.App.create(AppData{}, azul.AppConfig.create())`.

use alloc::{
    format,
    string::{String, ToString},
    vec,
    vec::Vec,
};
use core::fmt::Write;

use crate::codegen::{
    doc::{render, Doc},
    ir::{snake_to_lower_camel, EnumShape, Expr, Ident, Item, LibrarySpec, Module, Prim},
    lang::{
        dom::{is_dom_item, one_line, unused_params, uses_concat},
        item_comments, item_doc, uses_nonfinite_float, variant_ctor_method, ConcatPart,
        ExprSyntax, MethodLayout,
    },
    lower_types::union_tag,
    CodegenBackend, GeneratedFile,
};

/// The Zig printer.
#[derive(Debug, Copy, Clone, Default)]
pub struct Zig;

const KEYWORDS: &[&str] = &[
    "addrspace", "align", "allowzero", "and", "anyframe", "anytype", "asm", "async", "await",
    "break", "callconv", "catch", "comptime", "const", "continue", "defer", "else", "enum",
    "errdefer", "error", "export", "extern", "fn", "for", "if", "inline", "linksection",
    "noalias", "noinline", "nosuspend", "opaque", "or", "orelse", "packed", "pub", "resume",
    "return", "struct", "suspend", "switch", "test", "threadlocal", "try", "type", "union",
    "unreachable", "usingnamespace", "var", "volatile", "while",
];

fn field(name: &str) -> String {
    if KEYWORDS.contains(&name) {
        format!("@\"{name}\"")
    } else {
        name.to_string()
    }
}

/// Zig's primitive type and value names (a parameter may not shadow one).
const PRIMITIVES: &[&str] = &[
    "anyerror", "anyopaque", "bool", "c_char", "c_int", "c_long", "c_longdouble", "c_longlong",
    "c_short", "c_uint", "c_ulong", "c_ulonglong", "c_ushort", "comptime_float", "comptime_int",
    "f16", "f32", "f64", "f80", "f128", "false", "isize", "noreturn", "null", "true", "type",
    "undefined", "usize", "void",
];

/// A parameter's Zig name (snake_case, Zig's style for parameters). A
/// keyword, a primitive (`u8`, `i32`, `bool`, ...) or a container-level
/// declaration of the module (`std`, `azul`) gets a trailing `_`: Zig
/// rejects a parameter that shadows one.
fn zig_param(name: &Ident) -> String {
    let n = name.snake();
    let int_type = n.len() > 1
        && (n.starts_with('u') || n.starts_with('i'))
        && n[1..].bytes().all(|b| b.is_ascii_digit());
    if KEYWORDS.contains(&n.as_str())
        || PRIMITIVES.contains(&n.as_str())
        || int_type
        || n == "std"
        || n == "azul"
    {
        format!("{n}_")
    } else {
        n
    }
}

/// Escape `s` as the body of a Zig string literal: `\\`, `\"`, `\n`, `\r`,
/// `\t`, every other non-printable or non-ASCII byte as `\xNN` (Zig has no
/// octal escapes). The literal has exactly `s.len()` bytes.
fn zig_escape(s: &str) -> String {
    let mut out = String::new();
    for b in s.bytes() {
        match b {
            b'\\' => out.push_str("\\\\"),
            b'"' => out.push_str("\\\""),
            b'\n' => out.push_str("\\n"),
            b'\r' => out.push_str("\\r"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7e => out.push(char::from(b)),
            _ => out.push_str(&format!("\\x{b:02x}")),
        }
    }
    out
}

/// A Zig string literal (a `[]const u8` argument).
fn zig_lit(s: &str) -> String {
    format!("\"{}\"", zig_escape(s))
}

/// `base` with `suffix` words, lowerCamel (`card` + `render fn` ->
/// `cardRenderFn`).
fn camel(base: &Ident, suffix: &[&str]) -> String {
    let mut words = base.words.clone();
    words.extend(suffix.iter().map(ToString::to_string));
    Ident { words }.lower_camel()
}

impl ExprSyntax for Zig {
    fn int(&self, value: i128, _ty: Prim) -> String {
        value.to_string()
    }

    fn float(&self, text: &str, ty: Prim) -> String {
        let t = if ty == Prim::F64 { "f64" } else { "f32" };
        match text {
            "nan" => format!("std.math.nan({t})"),
            "inf" => format!("std.math.inf({t})"),
            "-inf" => format!("-std.math.inf({t})"),
            _ => text.to_string(),
        }
    }

    fn boolean(&self, b: bool) -> String {
        b.to_string()
    }

    fn string(&self, s: &str) -> Doc {
        Doc::text(format!(
            "C.AzString_copyFromBytes(\"{}\", 0, {})",
            zig_escape(s),
            s.len()
        ))
    }

    fn call(&self, class: &str, method: &str, args: Vec<Doc>, broken: bool) -> Doc {
        Doc::call(format!("C.Az{class}_{}", snake_to_lower_camel(method)), args, broken)
    }

    fn variant(&self, ty: &str, shape: EnumShape, variant: &str, args: Vec<Doc>, broken: bool) -> Doc {
        match shape {
            EnumShape::CLike => Doc::text(format!("C.Az{ty}_{variant}")),
            EnumShape::Tagged => Doc::call(
                format!("C.Az{ty}_{}", variant_ctor_method(variant)),
                args,
                broken,
            ),
            EnumShape::TaggedShadowed | EnumShape::Generic { .. } => {
                let tag = union_tag(ty, variant).unwrap_or(0);
                let mut inner = vec![Doc::text(format!(".tag = {tag}"))];
                if let Some(payload) = args.into_iter().next() {
                    inner.push(Doc::cat(vec![Doc::text(".payload = "), payload]));
                }
                Doc::cat(vec![
                    Doc::text(format!("C.Az{ty}")),
                    Doc::list(
                        "{",
                        vec![Doc::cat(vec![
                            Doc::text(format!(".{variant} = .")),
                            Doc::list("{", inner, ", ", "}", true, broken, false),
                        ])],
                        ", ",
                        "}",
                        true,
                        broken,
                        false,
                    ),
                ])
            }
        }
    }

    fn strukt(&self, ty: &str, fields: Vec<(String, Doc)>, broken: bool) -> Doc {
        let fields = fields
            .into_iter()
            .map(|(k, v)| Doc::cat(vec![Doc::text(format!(".{} = ", field(&k))), v]))
            .collect();
        Doc::cat(vec![
            Doc::text(format!("C.Az{ty}")),
            Doc::list("{", fields, ", ", "}", true, broken, true),
        ])
    }

    fn vec(&self, ty: &str, elem: &str, items: Vec<Doc>, broken: bool) -> Doc {
        if items.is_empty() {
            return Doc::text(format!("C.Az{ty}_create()"));
        }
        let n = items.len();
        Doc::cat(vec![
            Doc::text(format!("C.Az{ty}_copyFromPtr(&[_]C.Az{elem}")),
            Doc::list("{", items, ", ", "}", true, broken, true),
            Doc::text(format!(", {n})")),
        ])
    }

    fn unsupported(&self, what: &str) -> Doc {
        Doc::text(format!("@compileError({:?})", format!("not expressible: {what}")))
    }

    fn dom_limitation(&self) -> Option<&'static str> {
        None
    }

    /// The C API, like every other node: `C.AzDom_withChild(recv, child)`.
    fn method(&self, recv: Doc, class: &str, method: &str, args: Vec<Doc>, layout: MethodLayout) -> Doc {
        let mut all = vec![recv];
        all.extend(args);
        Doc::call(
            format!("C.Az{class}_{}", snake_to_lower_camel(method)),
            all,
            layout.node_tall,
        )
    }

    /// A `[]const u8` parameter, copied into a fresh `AzString` at every use
    /// (a call takes its `AzString` by value).
    fn param(&self, name: &Ident) -> Doc {
        let p = zig_param(name);
        Doc::text(format!("C.AzString_copyFromBytes({p}.ptr, 0, {p}.len)"))
    }

    /// `azConcat(&[_][]const u8{ "by ", author })` (see [`AZ_CONCAT`]).
    fn concat(&self, parts: &[ConcatPart<'_>]) -> Doc {
        let parts: Vec<String> = parts
            .iter()
            .map(|p| match p {
                ConcatPart::Lit(s) => zig_lit(s),
                ConcatPart::Param(i) => zig_param(i),
            })
            .collect();
        Doc::text(format!("azConcat(&[_][]const u8{{ {} }})", parts.join(", ")))
    }

    fn limitation(&self, e: &Expr) -> Option<String> {
        match e {
            Expr::ItemCall { args, .. } if args.iter().any(|a| matches!(a, Expr::Concat(_))) => {
                Some(ZIG_JOINED_ARG.to_string())
            }
            _ => None,
        }
    }

    fn item_call_limitation(&self) -> Option<&'static str> {
        None
    }

    /// `renderCard("Hi", title)`: another function of the file (Zig
    /// resolves top-level declarations in any order).
    fn item_call(&self, item: &Ident, _params: &[Ident], args: Vec<Doc>, broken: bool) -> Doc {
        Doc::call(item.lower_camel(), args, broken)
    }

    /// A `[]const u8` argument: a literal or a parameter passed on.
    fn native_string(&self, parts: &[ConcatPart<'_>]) -> Doc {
        match parts {
            [] => Doc::text("\"\""),
            [ConcatPart::Lit(s)] => Doc::text(zig_lit(s)),
            [ConcatPart::Param(p)] => Doc::text(zig_param(p)),
            _ => self.unsupported(ZIG_JOINED_ARG),
        }
    }
}

/// Why Zig cannot pass a text joined from parameters to a component's
/// render function.
const ZIG_JOINED_ARG: &str = "a component's text is a `[]const u8`: a text joined from parameters \
                              would need memory the caller frees";

/// What a joined text ([`ExprSyntax::concat`]) calls: the parts are
/// runtime slices, so the joined bytes need memory of their own.
const AZ_CONCAT: &str = "
// Joins `parts` into an AzString (AzString_copyFromBytes copies the bytes).
fn azConcat(parts: []const []const u8) C.AzString {
    const joined = std.mem.concat(std.heap.page_allocator, u8, parts) catch @panic(\"out of memory\");
    defer std.heap.page_allocator.free(joined);
    return C.AzString_copyFromBytes(joined.ptr, 0, joined.len);
}
";

/// A DOM item: a `pub fn` taking its parameters as `[]const u8` slices.
fn dom_item_fn(item: &Item) -> String {
    let mut out = String::new();
    for line in &item_comments(&Zig, item) {
        out.push_str(&format!("// {line}\n"));
    }
    let name = item.name.lower_camel();
    let params = item
        .params
        .iter()
        .map(|p| format!("{}: []const u8", zig_param(&p.name)))
        .collect::<Vec<_>>()
        .join(", ");
    let unused: String = unused_params(item)
        .iter()
        .map(|p| format!("    _ = {};\n", zig_param(&p.name)))
        .collect();
    match item_doc(&Zig, item) {
        Ok(doc) => out.push_str(&format!(
            "pub fn {name}({params}) C.Az{} {{\n{unused}    return {};\n}}\n",
            item.ty,
            render(&doc, "    ", 1)
        )),
        Err(reason) => out.push_str(&format!(
            "// not expressible with the Zig bindings: {reason}\n"
        )),
    }
    out
}

/// What the registration of a component with parameters calls.
const REGISTRATION_HELPERS: &str = "
// The String value of the data-model field `name` (a view into the model,
// which outlives the render call), or `fallback`.
fn azModelString(model: [*c]const C.AzComponentDataModel, name: []const u8, fallback: []const u8) []const u8 {
    const fields = model.*.fields;
    for (0..fields.len) |i| {
        const f = fields.ptr[i];
        if (f.name.vec.len == name.len and std.mem.eql(u8, f.name.vec.ptr[0..name.len], name) and
            f.default_value.Some.tag == C.AzOptionComponentDefaultValue_Tag_Some and
            f.default_value.Some.payload.String.tag == C.AzComponentDefaultValue_Tag_String)
        {
            const s = f.default_value.Some.payload.String.payload;
            if (s.vec.len == 0) return \"\";
            return s.vec.ptr[0..s.vec.len];
        }
    }
    return fallback;
}

// A String field of a component's data model.
fn azStringField(name: []const u8, value: []const u8, description: []const u8) C.AzComponentDataField {
    return .{
        .name = C.AzString_copyFromBytes(name.ptr, 0, name.len),
        .field_type = C.AzComponentFieldType_string(),
        .default_value = C.AzOptionComponentDefaultValue_some(
            C.AzComponentDefaultValue_string(C.AzString_copyFromBytes(value.ptr, 0, value.len)),
        ),
        .required = false,
        .description = C.AzString_copyFromBytes(description.ptr, 0, description.len),
    };
}
";

/// The registration of a component library: the C export's
/// (`dom::c_family_registration`) in Zig. Per component a default-arguments
/// wrapper, a `callconv(.c)` render function reading the data model and its
/// `C.AzComponentDef` (code calls it through its render function:
/// `ComponentCodegen::RenderFunction`); then `register<Library>Library()`.
/// Items the module does not have are skipped.
fn zig_registration(m: &Module, lib: &LibrarySpec) -> String {
    let az = |s: &str| Zig.string(s).flat();
    let mut s = String::from("\n// -- registration --\n");
    let any_params = lib
        .components
        .iter()
        .filter_map(|c| m.item(&c.item))
        .any(|i| !i.params.is_empty());
    if any_params {
        s.push_str(REGISTRATION_HELPERS);
    }
    let mut defs: Vec<String> = Vec::new();
    for c in &lib.components {
        let Some(item) = m.item(&c.item) else {
            continue;
        };
        let item_fn = item.name.lower_camel();
        let default_fn = camel(&item.name, &["default"]);
        let cn = Ident::from_text(&c.name);
        let render_fn = camel(&cn, &["render", "fn"]);
        let def_fn = camel(&cn, &["def"]);
        let qn = format!("{}:{}", lib.name, c.name);
        let defaults: Vec<String> = item.params.iter().map(|p| zig_lit(p.default_text())).collect();
        let _ = write!(
            s,
            "\n// `{}` with its default arguments.\npub fn {default_fn}() C.AzDom {{\n    return \
             {item_fn}({});\n}}\n",
            one_line(&qn),
            defaults.join(", ")
        );
        let _ = writeln!(
            s,
            "\nfn {render_fn}(def: [*c]const C.AzComponentDef, model: [*c]const \
             C.AzComponentDataModel, map: [*c]const C.AzComponentMap) callconv(.c) \
             C.AzResultStyledDomRenderDomError {{"
        );
        s.push_str("    _ = def;\n    _ = map;\n");
        if item.params.is_empty() {
            s.push_str("    _ = model;\n");
        }
        let args: Vec<String> = item
            .params
            .iter()
            .map(|p| {
                format!(
                    "azModelString(model, {}, {})",
                    zig_lit(&p.name.snake()),
                    zig_lit(p.default_text())
                )
            })
            .collect();
        let _ = writeln!(s, "    const dom = {item_fn}({});", args.join(", "));
        s.push_str(
            "    return C.AzResultStyledDomRenderDomError_ok(C.AzStyledDom_createFromDom(dom));\n}\n",
        );
        let _ = writeln!(s, "\nfn {def_fn}() C.AzComponentDef {{");
        s.push_str("    var def: C.AzComponentDef = .{};\n");
        let _ = writeln!(
            s,
            "    def.id = C.AzComponentId_create({}, {});",
            az(&lib.name),
            az(&c.name)
        );
        let _ = writeln!(s, "    def.display_name = {};", az(&c.display_name));
        let _ = writeln!(s, "    def.description = {};", az(&c.description));
        let _ = writeln!(s, "    // The CSS is applied per node by {item_fn}.");
        let _ = writeln!(s, "    def.css = {};", az(""));
        s.push_str("    def.source = C.AzComponentSource_UserDefined;\n");
        let _ = writeln!(s, "    def.data_model.name = {};", az(&c.data_model));
        let _ = writeln!(
            s,
            "    def.data_model.description = {};",
            az(&c.data_model_description)
        );
        if item.params.is_empty() {
            s.push_str("    def.data_model.fields = C.AzComponentDataFieldVec_create();\n");
        } else {
            let n = item.params.len();
            let _ = writeln!(s, "    var fields: [{n}]C.AzComponentDataField = undefined;");
            for (i, p) in item.params.iter().enumerate() {
                let desc = c.field_descriptions.get(i).map_or("", String::as_str);
                let _ = writeln!(
                    s,
                    "    fields[{i}] = azStringField({}, {}, {});",
                    zig_lit(&p.name.snake()),
                    zig_lit(p.default_text()),
                    zig_lit(desc)
                );
            }
            let _ = writeln!(
                s,
                "    def.data_model.fields = C.AzComponentDataFieldVec_copyFromPtr(&fields, {n});"
            );
            s.push_str(
                "    // copyFromPtr cloned them.\n    for (&fields) |*f| \
                 C.AzComponentDataField_delete(f);\n",
            );
        }
        let _ = writeln!(s, "    def.render_fn = &{render_fn};");
        s.push_str("    def.codegen = C.AzComponentCodegen_renderFunction();\n");
        s.push_str("    def.render_fn_source = C.AzOptionString_none();\n    return def;\n}\n");
        defs.push(format!("{def_fn}()"));
    }
    let mut words = vec!["register".to_string()];
    words.extend(Ident::from_text(&lib.name).words);
    words.push("library".to_string());
    let register_fn = Ident { words }.lower_camel();
    let n = defs.len();
    let _ = write!(
        s,
        "\n// The component library `{}`:\n//     C.AzAppConfig_addComponentLibrary(&config, {}, \
         &{register_fn});\npub fn {register_fn}() callconv(.c) C.AzComponentLibrary {{\n",
        one_line(&lib.name),
        one_line(&az(&lib.name))
    );
    if n > 0 {
        let _ = writeln!(s, "    var defs: [{n}]C.AzComponentDef = undefined;");
        for (i, d) in defs.iter().enumerate() {
            let _ = writeln!(s, "    defs[{i}] = {d};");
        }
    }
    s.push_str("    var lib: C.AzComponentLibrary = .{};\n");
    let _ = writeln!(s, "    lib.name = {};", az(&lib.name));
    let _ = writeln!(s, "    lib.version = {};", az(&lib.version));
    let _ = writeln!(s, "    lib.description = {};", az("Exported from AzBuilder"));
    if n == 0 {
        s.push_str("    lib.components = C.AzComponentDefVec_create();\n");
    } else {
        let _ = writeln!(
            s,
            "    lib.components = C.AzComponentDefVec_copyFromPtr(&defs, {n});\n    // \
             copyFromPtr cloned them.\n    for (&defs) |*d| C.AzComponentDef_delete(d);"
        );
    }
    s.push_str("    lib.exportable = true;\n    lib.modifiable = false;\n");
    s.push_str("    lib.data_models = C.AzComponentDataModelVec_create();\n");
    s.push_str("    lib.enum_models = C.AzComponentEnumModelVec_create();\n    return lib;\n}\n");
    s
}

/// The app's `main.zig` around a DOM module (`m.app`) in `ui.zig`.
fn app_main(m: &Module) -> String {
    let Some(app) = &m.app else {
        return String::new();
    };
    let root = format!("ui.{}()", app.root.lower_camel());
    let body = if app.is_body {
        root
    } else {
        format!("C.AzDom_withChild(C.AzDom_createBody(), {root})")
    };
    format!(
        "// {} - generated by AzBuilder (azul-css codegen, Zig).\n// Copy target/codegen/azul.zig \
         and libazul next to build.zig, then: zig build run\nconst azul = \
         @import(\"azul.zig\");\nconst C = azul.C;\nconst ui = @import(\"ui.zig\");\n\n// The \
         app's data: the layout callback gets it back.\nconst AppData = struct {{\n    unused: u8 \
         = 0,\n}};\n\nconst AppDataRef = azul.ReflectModel(AppData).Ref;\n\nfn layout(_: \
         AppDataRef, _: azul.LayoutCallbackInfo) azul.Dom {{\n    return azul.Dom{{ .inner = \
         {body} }};\n}}\n\npub fn main() void {{\n    var window = \
         azul.WindowCreateOptions.create(layout);\n    window.inner.window_state.title = {};\n    \
         var app = azul.App.create(AppData{{}}, azul.AppConfig.create());\n    \
         app.run(window);\n}}\n",
        one_line(&app.title),
        Zig.string(&app.title).flat()
    )
}

fn item_fn(item: &Item) -> String {
    if is_dom_item(item) {
        return dom_item_fn(item);
    }
    let mut out = String::new();
    for line in &item_comments(&Zig, item) {
        out.push_str(&format!("// {line}\n"));
    }
    let name = item.name.lower_camel();
    match item_doc(&Zig, item) {
        Ok(doc) => out.push_str(&format!(
            "pub fn {name}() C.Az{} {{\n    return {};\n}}\n",
            item.ty,
            render(&doc, "    ", 1)
        )),
        Err(reason) => out.push_str(&format!(
            "// not expressible with the Zig bindings: {reason}\n"
        )),
    }
    out
}

impl CodegenBackend for Zig {
    fn lang(&self) -> &'static str {
        "zig"
    }

    fn display_name(&self) -> &'static str {
        "Zig"
    }

    fn extension(&self) -> &'static str {
        "zig"
    }

    fn exports_dom(&self) -> bool {
        true
    }

    fn emit_module(&self, m: &Module) -> String {
        let mut out = String::from("// Generated by azul-css codegen (Zig). Do not edit by hand.\n");
        let concat = uses_concat(m);
        if uses_nonfinite_float(m) || concat || m.library.is_some() {
            out.push_str("const std = @import(\"std\");\n");
        }
        out.push_str("const azul = @import(\"azul.zig\");\nconst C = azul.C;\n");
        if concat {
            out.push_str(AZ_CONCAT);
        }
        for item in &m.items {
            out.push('\n');
            out.push_str(&item_fn(item));
        }
        if let Some(lib) = &m.library {
            out.push_str(&zig_registration(m, lib));
        }
        out
    }

    fn emit_project_files(&self, m: &Module) -> Vec<GeneratedFile> {
        if m.app.is_some() {
            return vec![
                GeneratedFile {
                    path: "build.zig".to_string(),
                    contents: build_zig("azul-app"),
                },
                GeneratedFile {
                    path: "ui.zig".to_string(),
                    contents: self.emit_module(m),
                },
                GeneratedFile {
                    path: "main.zig".to_string(),
                    contents: app_main(m),
                },
            ];
        }
        let mut main = String::from(
            "const std = @import(\"std\");\nconst styles = @import(\"styles.zig\");\n\npub fn main() \
             void {\n",
        );
        for item in &m.items {
            let name = item.name.lower_camel();
            main.push_str(&format!(
                "    const {name} = styles.{name}();\n    std.debug.print(\"{name}: {{d}} \
                 properties\\n\", .{{{name}.len}});\n"
            ));
        }
        main.push_str("}\n");
        vec![
            GeneratedFile {
                path: "build.zig".to_string(),
                contents: build_zig("azul-styles"),
            },
            GeneratedFile {
                path: "styles.zig".to_string(),
                contents: self.emit_module(m),
            },
            GeneratedFile {
                path: "main.zig".to_string(),
                contents: main,
            },
        ]
    }
}

/// The build of an executable named `name` from `main.zig`.
fn build_zig(name: &str) -> String {
    BUILD_ZIG.replace("\"azul-styles\"", &format!("\"{name}\""))
}

const BUILD_ZIG: &str = r#"// Copy target/codegen/azul.zig + azul.h and libazul next to this file, then: zig build run
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const exe_mod = b.createModule(.{
        .root_source_file = b.path("main.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    exe_mod.addIncludePath(b.path("."));
    exe_mod.addLibraryPath(b.path("."));
    exe_mod.linkSystemLibrary("azul", .{});
    const exe = b.addExecutable(.{ .name = "azul-styles", .root_module = exe_mod });
    b.installArtifact(exe);
    const run = b.addRunArtifact(exe);
    b.step("run", "Run the app").dependOn(&run.step);
}
"#;
