--  Generated by azul-css codegen (Ada). Do not edit by hand.
--  Two compilation units (styles.ads + styles.adb): split them with
--  `gnatchop styles.adb`.
with Azul; use Azul;

package Styles is

   function Style_Card return Az_CssPropertyWithConditionsVec;
   function Style_List_Li_Nth_Child_2 return Az_CssPropertyWithConditionsVec;
   function Style_Main_Title return Az_CssPropertyWithConditionsVec;
   function Style_Div_Note_First return Az_CssPropertyWithConditionsVec;

end Styles;

with Interfaces.C;

package body Styles is

   function To_Az_String (S : String) return Az_String is
      Buf : aliased constant String (1 .. S'Length) := S;
   begin
      return Az_String_Copy_From_Bytes (Buf'Address, 0, Interfaces.C.size_t (S'Length));
   end To_Az_String;

   --  CSS: .card, .card:hover, .card:active, .card:focus, .card (conditional), .card:hover (conditional)
   --  dropped a value these bindings cannot build: Ada has no literal for NaN / infinity
   function Style_Card return Az_CssPropertyWithConditionsVec is
      t1 : aliased array (0 .. 1) of Az_DynamicSelector;
      t2 : aliased array (0 .. 10) of Az_CssPropertyWithConditions;
   begin
      t1 (0) := Az_DynamicSelector_Pseudo_State (Az_PseudoStateType'(Hover));
      t1 (1) := Az_DynamicSelector_Mode (Az_ModeCondition'(Dark));
      t2 (0) := Az_CssPropertyWithConditions_Simple (Az_CssProperty_Padding_Top (Az_LayoutPaddingTop'(Inner => Az_PixelValue_Px (8.0))));
      t2 (1) := Az_CssPropertyWithConditions_On_Hover (Az_CssProperty_Padding_Top (Az_LayoutPaddingTop'(Inner => Az_PixelValue_Px (9.0))));
      t2 (2) := Az_CssPropertyWithConditions_On_Active (Az_CssProperty_Padding_Top (Az_LayoutPaddingTop'(Inner => Az_PixelValue_Px (10.0))));
      t2 (3) := Az_CssPropertyWithConditions_On_Focus (Az_CssProperty_Border_Top_Color (Az_StyleBorderTopColor'(Inner => Az_ColorU'(R => 51, G => 153, B => 255, A => 255))));
      t2 (4) := Az_CssPropertyWithConditions_On_Macos (Az_CssProperty_Font_Size (Az_StyleFontSize'(Inner => Az_PixelValue_Px (13.0))));
      t2 (5) := Az_CssPropertyWithConditions_On_Windows (Az_CssProperty_Font_Size (Az_StyleFontSize'(Inner => Az_PixelValue_Px (12.0))));
      t2 (6) := Az_CssPropertyWithConditions_On_Linux (Az_CssProperty_Font_Size (Az_StyleFontSize'(Inner => Az_PixelValue_Px (11.0))));
      t2 (7) := Az_CssPropertyWithConditions_On_Os (Az_CssProperty_Font_Size (Az_StyleFontSize'(Inner => Az_PixelValue_Px (15.0))), Az_OsCondition'(Android));
      t2 (8) := Az_CssPropertyWithConditions_Dark_Mode (Az_CssProperty_Text_Color (Az_StyleTextColor'(Inner => Az_ColorU'(R => 255, G => 255, B => 255, A => 255))));
      t2 (9) := Az_CssPropertyWithConditions_With_Conditions (Az_CssProperty_Text_Color (Az_StyleTextColor'(Inner => Az_ColorU'(R => 204, G => 204, B => 204, A => 255))), Az_DynamicSelectorVec_Copy_From_Ptr (t1 (0)'Address, 2));
      t2 (10) := Az_CssPropertyWithConditions_With_Condition (Az_CssProperty_Letter_Spacing (Az_StyleLetterSpacing'(Inner => Az_PixelValue_Px (1.0))), Az_DynamicSelector_Language (Az_LanguageCondition_Prefix (To_Az_String ("de-DE"))));
      return Az_CssPropertyWithConditionsVec_Copy_From_Ptr (t2 (0)'Address, 11);
   end Style_Card;

   --  CSS: .list li:nth-child(2)
   function Style_List_Li_Nth_Child_2 return Az_CssPropertyWithConditionsVec is
      t1 : aliased array (0 .. 0) of Az_CssPropertyWithConditions;
   begin
      t1 (0) := Az_CssPropertyWithConditions_Simple (Az_CssProperty_Text_Color (Az_StyleTextColor'(Inner => Az_ColorU'(R => 153, G => 153, B => 153, A => 255))));
      return Az_CssPropertyWithConditionsVec_Copy_From_Ptr (t1 (0)'Address, 1);
   end Style_List_Li_Nth_Child_2;

   --  CSS: #main>.title
   function Style_Main_Title return Az_CssPropertyWithConditionsVec is
      t1 : aliased array (0 .. 0) of Az_CssPropertyWithConditions;
   begin
      t1 (0) := Az_CssPropertyWithConditions_Simple (Az_CssProperty_Font_Weight (Az_StyleFontWeight'(Bold)));
      return Az_CssPropertyWithConditionsVec_Copy_From_Ptr (t1 (0)'Address, 1);
   end Style_Main_Title;

   --  CSS: div .note:first
   function Style_Div_Note_First return Az_CssPropertyWithConditionsVec is
      t1 : aliased array (0 .. 0) of Az_CssPropertyWithConditions;
   begin
      t1 (0) := Az_CssPropertyWithConditions_Simple (Az_CssProperty_Font_Style (Az_StyleFontStyle'(Italic)));
      return Az_CssPropertyWithConditionsVec_Copy_From_Ptr (t1 (0)'Address, 1);
   end Style_Div_Note_First;

end Styles;
