# Generated by azul-css codegen (Julia). Do not edit by hand.
# Load the bindings first: include("azul/azul.jl"); using .Azul

# Copies the items into a Julia array; the C API clones them into the Vec.
function az_vec(copy, ::Type{T}, items...) where {T}
    arr = T[items...]
    GC.@preserve arr copy(pointer(arr), Csize_t(length(arr)))
end

# Unions are opaque blobs in azul.jl: build the variant struct V by field
# name (its tag, its payload if it has one, zeroes for the `_pad0` bytes
# azul.h puts between them when the payload is less aligned than the union)
# and store it into one.
function az_union(::Type{U}, ::Type{V}, tag, payload...) where {U,V}
    fields = map(fieldnames(V)) do f
        if f === :tag
            tag
        elseif f === :payload
            payload[1]
        else
            ntuple(_ -> 0x00, fieldcount(fieldtype(V, f)))
        end
    end
    variant = V(fields...)
    r = Ref{U}()
    GC.@preserve r unsafe_store!(Ptr{V}(Base.unsafe_convert(Ptr{U}, r)), variant)
    r[]
end

# CSS: .hero
function style_hero()
    az_vec(
        Azul.AzCssPropertyWithConditionsVec_copyFromPtr,
        Azul.AzCssPropertyWithConditions,
        Azul.AzCssPropertyWithConditions_simple(
            Azul.AzCssProperty_backgroundContent(
                az_vec(
                    Azul.AzStyleBackgroundContentVec_copyFromPtr,
                    Azul.AzStyleBackgroundContent,
                    Azul.AzStyleBackgroundContent_linearGradient(
                        Azul.AzLinearGradient(
                            Azul.AzDirection_angle(Azul.AzAngleValue(Azul.AzAngleMetric_Degree, Azul.AzFloatValue_create(135.0f0))),
                            Azul.AzExtendMode_Clamp,
                            az_vec(
                                Azul.AzNormalizedLinearColorStopVec_copyFromPtr,
                                Azul.AzNormalizedLinearColorStop,
                                Azul.AzNormalizedLinearColorStop(Azul.AzPercentageValue(Azul.AzFloatValue_create(0.0f0)), Azul.AzColorOrSystem_color(Azul.AzColorU(255, 0, 0, 255))),
                                Azul.AzNormalizedLinearColorStop(Azul.AzPercentageValue(Azul.AzFloatValue_create(50.0f0)), Azul.AzColorOrSystem_color(Azul.AzColorU(0, 255, 0, 255))),
                                Azul.AzNormalizedLinearColorStop(Azul.AzPercentageValue(Azul.AzFloatValue_create(100.0f0)), Azul.AzColorOrSystem_color(Azul.AzColorU(0, 0, 255, 255)))
                            )
                        )
                    )
                )
            )
        ),
        Azul.AzCssPropertyWithConditions_simple(Azul.AzCssProperty_boxShadowLeft(Azul.AzStyleBoxShadow(Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(0.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(4.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(12.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(2.0f0)), Azul.AzBoxShadowClipMode_Outset, Azul.AzColorU(0, 0, 0, 77)))),
        Azul.AzCssPropertyWithConditions_simple(Azul.AzCssProperty_boxShadowRight(Azul.AzStyleBoxShadow(Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(0.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(4.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(12.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(2.0f0)), Azul.AzBoxShadowClipMode_Outset, Azul.AzColorU(0, 0, 0, 77)))),
        Azul.AzCssPropertyWithConditions_simple(Azul.AzCssProperty_boxShadowTop(Azul.AzStyleBoxShadow(Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(0.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(4.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(12.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(2.0f0)), Azul.AzBoxShadowClipMode_Outset, Azul.AzColorU(0, 0, 0, 77)))),
        Azul.AzCssPropertyWithConditions_simple(Azul.AzCssProperty_boxShadowBottom(Azul.AzStyleBoxShadow(Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(0.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(4.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(12.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(2.0f0)), Azul.AzBoxShadowClipMode_Outset, Azul.AzColorU(0, 0, 0, 77)))),
        Azul.AzCssPropertyWithConditions_simple(
            Azul.AzCssProperty_transform(
                az_vec(
                    Azul.AzStyleTransformVec_copyFromPtr,
                    Azul.AzStyleTransform,
                    Azul.AzStyleTransform_translate(Azul.AzStyleTransformTranslate2D(Azul.AzPixelValue_px(10.0f0), Azul.AzPixelValue_px(20.0f0))),
                    Azul.AzStyleTransform_rotate(Azul.AzAngleValue(Azul.AzAngleMetric_Degree, Azul.AzFloatValue_create(45.0f0))),
                    Azul.AzStyleTransform_scale(Azul.AzStyleTransformScale2D(Azul.AzFloatValue_create(1.5f0), Azul.AzFloatValue_create(1.5f0))),
                    Azul.AzStyleTransform_skew(Azul.AzStyleTransformSkew2D(Azul.AzAngleValue(Azul.AzAngleMetric_Degree, Azul.AzFloatValue_create(10.0f0)), Azul.AzAngleValue(Azul.AzAngleMetric_Degree, Azul.AzFloatValue_create(5.0f0))))
                )
            )
        ),
        Azul.AzCssPropertyWithConditions_simple(
            Azul.AzCssProperty_filter(
                az_union(
                    Azul.AzStyleFilterVecValue,
                    Azul.AzStyleFilterVecValueVariant_Exact,
                    UInt8(6),
                    az_vec(
                        Azul.AzStyleFilterVec_copyFromPtr,
                        Azul.AzStyleFilter,
                        Azul.AzStyleFilter_blur(Azul.AzStyleBlur(Azul.AzPixelValue_px(4.0f0), Azul.AzPixelValue_px(4.0f0))),
                        Azul.AzStyleFilter_grayscale(Azul.AzPercentageValue(Azul.AzFloatValue_create(50.0f0))),
                        Azul.AzStyleFilter_dropShadow(Azul.AzStyleBoxShadow(Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(2.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(2.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(4.0f0)), Azul.AzPixelValueNoPercent(Azul.AzPixelValue_px(0.0f0)), Azul.AzBoxShadowClipMode_Outset, Azul.AzColorU(0, 0, 0, 255)))
                    )
                )
            )
        ),
        Azul.AzCssPropertyWithConditions_simple(
            Azul.AzCssProperty_backdropFilter(
                az_union(
                    Azul.AzStyleFilterVecValue,
                    Azul.AzStyleFilterVecValueVariant_Exact,
                    UInt8(6),
                    az_vec(
                        Azul.AzStyleFilterVec_copyFromPtr,
                        Azul.AzStyleFilter,
                        Azul.AzStyleFilter_brightness(Azul.AzPercentageValue(Azul.AzFloatValue_create(120.0f0))),
                        Azul.AzStyleFilter_contrast(Azul.AzPercentageValue(Azul.AzFloatValue_create(80.0f0)))
                    )
                )
            )
        )
    )
end

# CSS: .halo
function style_halo()
    az_vec(
        Azul.AzCssPropertyWithConditionsVec_copyFromPtr,
        Azul.AzCssPropertyWithConditions,
        Azul.AzCssPropertyWithConditions_simple(
            Azul.AzCssProperty_backgroundContent(
                az_vec(
                    Azul.AzStyleBackgroundContentVec_copyFromPtr,
                    Azul.AzStyleBackgroundContent,
                    Azul.AzStyleBackgroundContent_radialGradient(
                        Azul.AzRadialGradient(
                            Azul.AzShape_Circle,
                            Azul.AzRadialGradientSize_FarthestCorner,
                            Azul.AzStyleBackgroundPosition(Azul.AzBackgroundPositionHorizontal_left(), Azul.AzBackgroundPositionVertical_top()),
                            Azul.AzExtendMode_Clamp,
                            az_vec(
                                Azul.AzNormalizedLinearColorStopVec_copyFromPtr,
                                Azul.AzNormalizedLinearColorStop,
                                Azul.AzNormalizedLinearColorStop(Azul.AzPercentageValue(Azul.AzFloatValue_create(0.0f0)), Azul.AzColorOrSystem_color(Azul.AzColorU(255, 255, 255, 255))),
                                Azul.AzNormalizedLinearColorStop(Azul.AzPercentageValue(Azul.AzFloatValue_create(100.0f0)), Azul.AzColorOrSystem_color(Azul.AzColorU(0, 0, 0, 255)))
                            )
                        )
                    )
                )
            )
        )
    )
end

# CSS: .dial
function style_dial()
    az_vec(
        Azul.AzCssPropertyWithConditionsVec_copyFromPtr,
        Azul.AzCssPropertyWithConditions,
        Azul.AzCssPropertyWithConditions_simple(
            Azul.AzCssProperty_backgroundContent(
                az_vec(
                    Azul.AzStyleBackgroundContentVec_copyFromPtr,
                    Azul.AzStyleBackgroundContent,
                    Azul.AzStyleBackgroundContent_conicGradient(
                        Azul.AzConicGradient(
                            Azul.AzExtendMode_Clamp,
                            Azul.AzStyleBackgroundPosition(Azul.AzBackgroundPositionHorizontal_left(), Azul.AzBackgroundPositionVertical_top()),
                            Azul.AzAngleValue(Azul.AzAngleMetric_Degree, Azul.AzFloatValue_create(90.0f0)),
                            az_vec(
                                Azul.AzNormalizedRadialColorStopVec_copyFromPtr,
                                Azul.AzNormalizedRadialColorStop,
                                Azul.AzNormalizedRadialColorStop(Azul.AzAngleValue(Azul.AzAngleMetric_Degree, Azul.AzFloatValue_create(0.0f0)), Azul.AzColorOrSystem_color(Azul.AzColorU(255, 0, 0, 255))),
                                Azul.AzNormalizedRadialColorStop(Azul.AzAngleValue(Azul.AzAngleMetric_Degree, Azul.AzFloatValue_create(360.0f0)), Azul.AzColorOrSystem_color(Azul.AzColorU(0, 0, 255, 255)))
                            )
                        )
                    )
                )
            )
        )
    )
end

# CSS: .photo
function style_photo()
    az_vec(
        Azul.AzCssPropertyWithConditionsVec_copyFromPtr,
        Azul.AzCssPropertyWithConditions,
        Azul.AzCssPropertyWithConditions_simple(Azul.AzCssProperty_backgroundContent(az_vec(Azul.AzStyleBackgroundContentVec_copyFromPtr, Azul.AzStyleBackgroundContent, Azul.AzStyleBackgroundContent_image(Azul.az_string("images/photo.png"))))),
        Azul.AzCssPropertyWithConditions_simple(Azul.AzCssProperty_backgroundSize(az_vec(Azul.AzStyleBackgroundSizeVec_copyFromPtr, Azul.AzStyleBackgroundSize, Azul.AzStyleBackgroundSize_cover()))),
        Azul.AzCssPropertyWithConditions_simple(Azul.AzCssProperty_backgroundPosition(az_vec(Azul.AzStyleBackgroundPositionVec_copyFromPtr, Azul.AzStyleBackgroundPosition, Azul.AzStyleBackgroundPosition(Azul.AzBackgroundPositionHorizontal_center(), Azul.AzBackgroundPositionVertical_center())))),
        Azul.AzCssPropertyWithConditions_simple(Azul.AzCssProperty_backgroundRepeat(az_vec(Azul.AzStyleBackgroundRepeatVec_copyFromPtr, Azul.AzStyleBackgroundRepeat, Azul.AzStyleBackgroundRepeat_NoRepeat)))
    )
end

# CSS: .caption
function style_caption()
    az_vec(
        Azul.AzCssPropertyWithConditionsVec_copyFromPtr,
        Azul.AzCssPropertyWithConditions,
        Azul.AzCssPropertyWithConditions_simple(
            Azul.AzCssProperty_fontFamily(
                az_vec(
                    Azul.AzStyleFontFamilyVec_copyFromPtr,
                    Azul.AzStyleFontFamily,
                    Azul.AzStyleFontFamily_system(Azul.az_string("Fira Code")),
                    Azul.AzStyleFontFamily_system(Azul.az_string("monospace"))
                )
            )
        ),
        Azul.AzCssPropertyWithConditions_simple(Azul.AzCssProperty_content(Azul.AzContent(Azul.az_string("\"say \\\"hi\\\" \\\\ bye\""))))
    )
end
