//! ASDF system-definition emission for the Common Lisp generator.
//!
//! ASDF is the de facto Common Lisp build system; an `azul.asd` file
//! lets users `(asdf:load-system :azul)` (or `(ql:quickload :azul)`
//! when Quicklisp is installed) to bring the bindings into their
//! image.
//!
//! The native shared library (`libazul.so`/`.dylib`/`.dll`) is **not**
//! shipped through ASDF; CFFI loads it at runtime from the dynamic
//! loader's search path (or from a path the user adds via
//! `cffi:*foreign-library-directories*`).

/// Generate the contents of `azul.asd` as a `String`.
pub fn generate_asd(version: &str) -> String {
    format!(
        r#";;;; azul.asd
;;;; Auto-generated by azul-doc codegen v2.
;;;;
;;;; Common Lisp system definition for the Azul GUI framework bindings.
;;;; The single dependency is CFFI (the portable Common FFI). The native
;;;; shared library `libazul.so` / `libazul.dylib` / `azul.dll` must be
;;;; available on the dynamic loader's search path at load time.

(asdf:defsystem #:azul
  :description     "CFFI bindings for the Azul GUI framework"
  :author          "Azul contributors"
  :license         "MPL-2.0 OR MIT OR Apache-2.0"
  :version         "{version}"
  :homepage        "https://azul.rs"
  :depends-on      (#:cffi)
  :serial          t
  :components ((:file "azul")))
"#,
    )
}
