//! Common Lisp (CFFI) binding generator.
//!
//! Generates a single `azul.lisp` source file that exposes the C-ABI of
//! `libazul` to Common Lisp implementations (SBCL, CCL, ECL, ABCL,
//! Allegro CL, ...) via the portable **CFFI** library.
//!
//! ## File structure
//!
//! 1. File banner (Lisp `;;;` line comments).
//! 2. Two `defpackage` forms:
//!    - `:azul-internal` — holds the raw `%az-*` FFI symbols (the leading
//!      `%` follows the convention of "internal/raw" in many Lisp
//!      libraries: `cl-fad`, `bordeaux-threads`, etc.).
//!    - `:azul` — the user-facing package; exports CLOS classes,
//!      `with-*` macros, idiomatic `make-*` constructors and named
//!      methods. Uses `:cl` and `:cffi`.
//! 3. `cffi:define-foreign-library` + `cffi:use-foreign-library` that
//!    locate `libazul.{so,dylib}` / `azul.dll` automatically.
//! 4. Type definitions inside `:azul-internal`:
//!    - `cffi:defcenum` for unit-only enums.
//!    - `cffi:defcstruct` for POD structs.
//!    - For tagged unions: a `cffi:defcenum` for the tag plus a
//!      `cffi:defcstruct` per variant payload plus a wrapping
//!      `cffi:defcunion`. (See [`types`].)
//! 5. `cffi:defcfun` declarations — one per IR function, mapping the
//!    C-ABI symbol to a `%az-*` Lisp function.
//! 6. CLOS wrappers in `:azul`:
//!    - `(defclass app () ((ptr ...)))` per heap-owning type.
//!    - `(defmethod close-app ...)` calling the matching `_delete`.
//!    - `(defmacro with-app ...)` doing the `unwind-protect` for users.
//!    - Idiomatic `make-app`, `app-run`, ... wrappers that call the
//!      `%az-*` raw FFI symbols.
//!
//! ## Why CFFI
//!
//! CFFI is the de facto portable Lisp FFI; it works on every major
//! implementation. Its `defcfun` / `defcstruct` / `defcunion` /
//! `defcenum` macros are structurally close to LuaJIT's `ffi.cdef`:
//! declare types, declare functions, then load the library — which
//! makes the Lua generator a useful structural reference, even though
//! the actual S-expression syntax differs.
//!
//! ## Wiring
//!
//! This module is intentionally *not* wired from `v2/mod.rs` yet. The
//! orchestrator is responsible for adding `pub mod lang_lisp;` and the
//! corresponding `generate_all` step that writes `azul.lisp` and
//! `azul.asd`.

pub mod asd;
pub mod functions;
pub mod types;
pub mod wrappers;

use anyhow::Result;

use super::config::CodegenConfig;
use super::generator::CodeBuilder;
use super::ir::CodegenIR;

/// Library name used in `cffi:define-foreign-library`. Matches the
/// prebuilt artifact name without extension. CFFI resolves
/// `libazul.so` / `libazul.dylib` / `azul.dll` automatically.
pub const LIB_NAME: &str = "azul";

/// Public entry point. Produces the complete `azul.lisp` source as a
/// `String`. The caller writes it to disk (e.g.
/// `target/codegen/v2/azul.lisp`) and emits the accompanying
/// `azul.asd` via [`asd::generate_asd`].
pub fn generate(ir: &CodegenIR, config: &CodegenConfig) -> Result<String> {
    let mut builder = CodeBuilder::new("  ");

    // 1. Banner
    emit_header(&mut builder);

    // 2. Package declarations
    emit_packages(&mut builder);

    // 3. Library load
    builder.line("(in-package :azul-internal)");
    builder.blank();
    emit_library_load(&mut builder);

    // 4. Type declarations (enums, structs, tagged unions, callbacks)
    types::generate_types(&mut builder, ir, config)?;

    // 5. defcfun bindings (one per IR function)
    functions::generate_defcfuns(&mut builder, ir, config)?;

    // 6. CLOS wrappers in :azul
    builder.blank();
    builder.line("(in-package :azul)");
    builder.blank();
    wrappers::generate_wrappers(&mut builder, ir, config)?;

    Ok(builder.finish())
}

fn emit_header(builder: &mut CodeBuilder) {
    builder.line(";;;; ============================================================================");
    builder.line(";;;; Auto-generated Common Lisp (CFFI) bindings for the Azul GUI framework.");
    builder.line(";;;; Generated by azul-doc codegen v2 (lang_lisp).");
    builder.line(";;;; DO NOT EDIT MANUALLY -- re-run the generator instead.");
    builder.line(";;;;");
    builder.line(";;;; Compatible with any Common Lisp implementation supported by CFFI:");
    builder.line(";;;;   SBCL, CCL, ECL, ABCL, Allegro CL, LispWorks, CMUCL, CLISP, ...");
    builder.line(";;;;");
    builder.line(";;;; Two packages:");
    builder.line(";;;;   :azul-internal -- raw FFI symbols (`%az-*`).");
    builder.line(";;;;   :azul          -- idiomatic CLOS wrappers + with-* macros.");
    builder.line(";;;; ============================================================================");
    builder.blank();
}

fn emit_packages(builder: &mut CodeBuilder) {
    // Internal package: holds raw %az-* FFI symbols.
    builder.line("(cl:in-package :cl-user)");
    builder.blank();
    builder.line("(cl:defpackage :azul-internal");
    builder.line("  (:use :cl :cffi))");
    builder.blank();

    // Public package: re-exports CLOS classes + idiomatic helpers.
    builder.line("(cl:defpackage :azul");
    builder.line("  (:use :cl)");
    builder.line("  ;; Public symbols are exported via (export ...) calls below to keep");
    builder.line("  ;; the package definition lean and additive.");
    builder.line("  )");
    builder.blank();
}

fn emit_library_load(builder: &mut CodeBuilder) {
    builder.line(";; -----------------------------------------------------------------------------");
    builder.line(";; Foreign library");
    builder.line(";; -----------------------------------------------------------------------------");
    builder.line("(define-foreign-library libazul");
    builder.line(&format!(
        "  (:darwin (:or \"lib{}.dylib\" \"{}.dylib\"))",
        LIB_NAME, LIB_NAME
    ));
    builder.line(&format!(
        "  (:unix    (:or \"lib{}.so\" \"{}.so\"))",
        LIB_NAME, LIB_NAME
    ));
    builder.line(&format!(
        "  (:windows (:or \"{}.dll\" \"lib{}.dll\"))",
        LIB_NAME, LIB_NAME
    ));
    builder.line(&format!("  (t (:default \"lib{}\")))", LIB_NAME));
    builder.blank();
    builder.line("(use-foreign-library libazul)");
    builder.blank();
}

// =============================================================================
// Shared helpers (used by submodules)
// =============================================================================

/// Convert an `Az`-prefixed C-ABI name like `AzWindowCreateOptions` or a
/// Rust-style `WindowCreateOptions` to kebab-case
/// `az-window-create-options`. Always emits a leading `az-` so the
/// returned symbol unambiguously belongs to the bindings namespace.
pub fn to_kebab_case(name: &str) -> String {
    // Strip a leading `Az` if present so we don't double-prefix.
    let body = name.strip_prefix("Az").unwrap_or(name);
    let mut out = String::from("az-");
    let mut prev_lower = false;
    let mut prev_digit = false;
    for c in body.chars() {
        if c == '_' {
            out.push('-');
            prev_lower = false;
            prev_digit = false;
        } else if c.is_uppercase() {
            if prev_lower || prev_digit {
                out.push('-');
            }
            for lc in c.to_lowercase() {
                out.push(lc);
            }
            prev_lower = false;
            prev_digit = false;
        } else if c.is_ascii_digit() {
            out.push(c);
            prev_lower = false;
            prev_digit = true;
        } else {
            out.push(c);
            prev_lower = true;
            prev_digit = false;
        }
    }
    // Squash any double dashes introduced by adjacent transitions.
    while out.contains("--") {
        out = out.replace("--", "-");
    }
    out
}

/// Convert a snake_case / camelCase / PascalCase identifier (e.g. a
/// field or argument name) to plain kebab-case **without** an `az-`
/// prefix. Used inside slot/argument lists where the prefix is implied
/// by the enclosing form.
pub fn ident_to_kebab(name: &str) -> String {
    let mut out = String::new();
    let mut prev_lower = false;
    let mut prev_digit = false;
    for c in name.chars() {
        if c == '_' {
            if !out.is_empty() && !out.ends_with('-') {
                out.push('-');
            }
            prev_lower = false;
            prev_digit = false;
        } else if c.is_uppercase() {
            if (prev_lower || prev_digit) && !out.is_empty() && !out.ends_with('-') {
                out.push('-');
            }
            for lc in c.to_lowercase() {
                out.push(lc);
            }
            prev_lower = false;
            prev_digit = false;
        } else {
            out.push(c);
            prev_lower = c.is_ascii_lowercase();
            prev_digit = c.is_ascii_digit();
        }
    }
    sanitize_lisp_ident(&out)
}

/// Convert `AzWindowCreateOptions_create` style C symbols into the
/// matching `%`-prefixed raw-FFI Lisp symbol (e.g.
/// `%az-window-create-options-create`). The `%` prefix is the
/// convention used to mark "internal raw FFI" symbols throughout the
/// Common Lisp ecosystem.
pub fn raw_fn_name(c_name: &str) -> String {
    // The C name is `Az<Class>_<method>`; replace the underscore with `-`
    // and run the whole thing through the kebab-case mapper.
    let unified = c_name.replace('_', "-");
    let kebab = to_kebab_case(&unified);
    format!("%{}", kebab)
}

/// Strip the leading `Az` from a class name and emit a kebab-cased
/// idiomatic Lisp class name (e.g. `WindowCreateOptions` ->
/// `window-create-options`).
pub fn idiomatic_class_name(name: &str) -> String {
    let body = name.strip_prefix("Az").unwrap_or(name);
    let kebab_with_prefix = to_kebab_case(body);
    // to_kebab_case always prepends "az-"; trim it for the user-facing class.
    kebab_with_prefix
        .strip_prefix("az-")
        .unwrap_or(&kebab_with_prefix)
        .to_string()
}

/// Mangle a Lisp identifier if it would shadow a Common Lisp special
/// operator / common reserved name. Returns the original on success;
/// returns `lisp-<name>` when it collides with anything we don't want
/// to override accidentally.
pub fn sanitize_lisp_ident(name: &str) -> String {
    if is_lisp_reserved(name) {
        format!("lisp-{}", name)
    } else {
        name.to_string()
    }
}

/// Common Lisp special operators and a few reserved-by-convention
/// identifiers that we never want to shadow when mapping field/argument
/// names. CL has very few hard reserved words, so this list is short.
fn is_lisp_reserved(name: &str) -> bool {
    matches!(
        name,
        "block"
            | "catch"
            | "eval-when"
            | "flet"
            | "function"
            | "go"
            | "if"
            | "labels"
            | "let"
            | "let*"
            | "load-time-value"
            | "locally"
            | "macrolet"
            | "multiple-value-call"
            | "multiple-value-prog1"
            | "progn"
            | "progv"
            | "quote"
            | "return-from"
            | "setq"
            | "symbol-macrolet"
            | "tagbody"
            | "the"
            | "throw"
            | "unwind-protect"
            | "t"
            | "nil"
            | "lambda"
    )
}

/// Map a Rust/IR type name to the corresponding CFFI type expression.
///
/// CFFI accepts plain keywords for primitives (`:uint32`, `:float`,
/// `:pointer`, ...). Struct types are represented as `(:struct
/// az-foo)`; pointers as `:pointer`; arrays as `(:array <elem> N)`.
pub fn map_type_to_cffi(rust_type: &str, ir: &CodegenIR) -> String {
    let trimmed = rust_type.trim();

    // Pointers and references collapse to :pointer.
    if let Some(rest) = trimmed.strip_prefix("*const ") {
        if matches!(rest.trim(), "c_char" | "char" | "i8" | "u8") {
            return ":string".to_string();
        }
        return ":pointer".to_string();
    }
    if let Some(rest) = trimmed.strip_prefix("*mut ") {
        let _ = rest;
        return ":pointer".to_string();
    }
    if let Some(rest) = trimmed.strip_prefix("&mut ") {
        let _ = rest;
        return ":pointer".to_string();
    }
    if let Some(rest) = trimmed.strip_prefix('&') {
        let _ = rest;
        return ":pointer".to_string();
    }

    // Arrays: `[T; N]` -> `(:array <elem> N)`.
    if trimmed.starts_with('[') && trimmed.ends_with(']') {
        let inner = &trimmed[1..trimmed.len() - 1];
        if let Some(semi) = inner.rfind(';') {
            let elem = inner[..semi].trim();
            if let Ok(count) = inner[semi + 1..].trim().parse::<usize>() {
                let cffi_elem = map_type_to_cffi(elem, ir);
                return format!("(:array {} {})", cffi_elem, count);
            }
        }
    }

    match trimmed {
        // Void / unit
        "void" | "c_void" | "()" => ":void".to_string(),

        // Booleans -- CFFI boolean translates 0/1 automatically.
        "bool" | "GLboolean" => ":bool".to_string(),

        // Integers
        "i8" | "c_char" | "char" => ":int8".to_string(),
        "u8" | "c_uchar" => ":uint8".to_string(),
        "i16" => ":int16".to_string(),
        "u16" => ":uint16".to_string(),
        "i32" | "c_int" | "GLint" | "GLsizei" => ":int32".to_string(),
        "u32" | "c_uint" | "GLuint" | "GLenum" | "GLbitfield" => ":uint32".to_string(),
        "i64" | "GLint64" => ":int64".to_string(),
        "u64" | "GLuint64" => ":uint64".to_string(),

        // Floats
        "f32" | "GLfloat" | "GLclampf" => ":float".to_string(),
        "f64" | "GLdouble" | "GLclampd" => ":double".to_string(),

        // Size / pointer-sized ints
        "usize" | "size_t" | "uintptr_t" => ":size".to_string(),
        "isize" | "ssize_t" | "intptr_t" | "GLsizeiptr" | "GLintptr" => ":ssize".to_string(),

        // Anything else: known IR type by value -> (:struct az-foo).
        // Unknown -> :pointer.
        _ => {
            if ir.find_struct(trimmed).is_some() {
                format!("(:struct {})", to_kebab_case(trimmed))
            } else if ir.find_enum(trimmed).is_some() {
                // Tagged unions are emitted as `defcunion`; pass-by-value
                // surfaces them as `(:union az-foo)`. Unit enums use
                // `defcenum`; CFFI accepts the keyword form at the call
                // site and converts to/from the underlying integer.
                let kebab = to_kebab_case(trimmed);
                let enum_def = ir.find_enum(trimmed).unwrap();
                if enum_def.is_union {
                    format!("(:union {})", kebab)
                } else {
                    kebab
                }
            } else if ir.find_type_alias(trimmed).is_some() {
                to_kebab_case(trimmed)
            } else if ir.callback_typedefs.iter().any(|c| c.name == trimmed) {
                // Function-pointer typedefs: pass as :pointer in CFFI.
                ":pointer".to_string()
            } else {
                // Unknown -> opaque pointer.
                ":pointer".to_string()
            }
        }
    }
}
