<?php
// Generated by azul-css codegen (PHP). Do not edit by hand.
// Needs the FFI binding Azul.php (target/codegen) and `php -d ffi.enable=1`.
require_once __DIR__ . '/Azul.php';

// A PHP string as an AzString (a fresh copy at every use: the C calls take
// their AzString by value).
if (!function_exists("azul_str")) {
    function azul_str(string $s)
    {
        $L = \Azul\Azul::lib();
        $n = strlen($s);
        $bytes = $L->new("uint8_t[" . max(1, $n) . "]");
        \FFI::memcpy($bytes, $s, $n);
        return $L->AzString_fromUtf8($bytes, $n);
    }
}

function render_ui(): \FFI\CData
{
    $L = \Azul\Azul::lib();
    return $L->AzDom_withChild(
        $L->AzDom_withChild($L->AzDom_createBody(), $L->AzDom_createH1WithText(azul_str("My App"))),
        $L->AzDom_createPWithText(azul_str("Hello"))
    );
}
