//! VISUAL text-layout regression harness for the `text3` engine.
//!
//! Each test renders one text-layout scenario through the FULL solver3 + text3
//! pipeline and CPU-rasterizes it to a coloured PNG under
//! `target/text3_visual/<scenario>.png`. Because every mock-font glyph outline
//! is a filled rectangle, the PNG shows exactly where each glyph box landed
//! after shaping + layout — a human or agent can open the image and confirm at
//! a glance that wrapping / justification / dropcap / RTL shaping / vertical
//! text / ligatures / kerning are working.
//!
//! Fonts:
//!  * built-in embedded "Azul Mock Mono" (0.5 em) / "Azul Mock Wide" (1.0 em);
//!  * on-disk stress fonts in `tests/fonts/` (liga, kern, arabic, vertical,
//!    prop) loaded at RUNTIME with `std::fs::read` (never `include_bytes!`, so
//!    they stay excludable from the published crate);
//!  * an in-memory rectangle "CJK" font generated by `rect_font::build_rect_font`.
//!
//! Run SAFELY (memory-capped — a prior unbounded parallel run rebooted the box):
//! ```text
//! systemd-run --user --scope -p MemoryMax=8G -p MemorySwapMax=0 -q -- \
//!   bash -c 'cd /home/fs/Development/azul && timeout 700 cargo test -p azul-layout \
//!     --test text3_visual -- --test-threads=2 --nocapture 2>&1' | tail -40
//! ```

#![cfg(all(feature = "cpurender", feature = "text_layout", feature = "font_loading"))]

use std::path::PathBuf;

use azul_css::props::basic::FontRef;
use azul_layout::{
    cpurender::{render_component_preview, ComponentPreviewOptions},
    font::loading::build_font_cache,
    font_traits::FontManager,
    xml::DomXmlExt,
};
use azul_core::dom::Dom;
use rust_fontconfig::UnicodeRange;

#[path = "common/rect_font.rs"]
mod rect_font;

fn range(start: u32, end: u32) -> UnicodeRange {
    UnicodeRange { start, end }
}

/// Absolute path to `layout/tests/fonts/<name>`.
fn font_path(name: &str) -> PathBuf {
    PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fonts")).join(name)
}

/// Output directory `target/text3_visual/` (gitignored under target/).
fn out_dir() -> PathBuf {
    // CARGO_MANIFEST_DIR = .../azul/layout ; workspace target is .../azul/target
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop(); // -> azul/
    p.push("target");
    p.push("text3_visual");
    std::fs::create_dir_all(&p).expect("create target/text3_visual");
    p
}

/// Build a `FontManager` with the built-in mock fonts PLUS the on-disk stress
/// fonts registered by family name and true coverage.
fn font_manager_with_stress_fonts() -> FontManager<FontRef> {
    let mut fm = FontManager::<FontRef>::new(build_font_cache()).expect("font manager");

    let load = |name: &str| std::fs::read(font_path(name)).unwrap_or_else(|e| {
        panic!("read stress font {name}: {e}");
    });

    // ASCII-covered fonts.
    fm.register_named_font("Azul Mock Liga", &load("azul-mock-liga.ttf"), vec![range(0x20, 0x7E)]);
    fm.register_named_font("Azul Mock Kern", &load("azul-mock-kern.ttf"), vec![range(0x20, 0x7E)]);
    fm.register_named_font("Azul Mock Prop", &load("azul-mock-prop.ttf"), vec![range(0x20, 0x7E)]);
    // Arabic block + space.
    fm.register_named_font(
        "Azul Mock Arabic",
        &load("azul-mock-arabic.ttf"),
        vec![range(0x20, 0x20), range(0x0600, 0x06FF)],
    );
    // 16 CJK ideographs U+4E00..U+4E0F + space.
    fm.register_named_font(
        "Azul Mock Vertical",
        &load("azul-mock-vertical.ttf"),
        vec![range(0x20, 0x20), range(0x4E00, 0x4E0F)],
    );
    fm
}

/// Render `html` at a FIXED canvas `w`x`h` and write the PNG to
/// `target/text3_visual/<scenario>.png`. Returns the absolute path.
///
/// Asserts the PNG is non-empty and the rendered canvas matches `w`x`h`, so a
/// broken render fails loudly instead of writing a blank/garbage file.
fn render_to_png(scenario: &str, html: &str, fm: &FontManager<FontRef>, w: f32, h: f32) -> PathBuf {
    let styled_dom = Dom::from_xml_string(html);
    let opts = ComponentPreviewOptions {
        width: Some(w),
        height: Some(h),
        dpi_factor: 1.0,
        ..Default::default()
    };
    let result = render_component_preview(&styled_dom, fm, opts, None)
        .unwrap_or_else(|e| panic!("[{scenario}] render_component_preview failed: {e}"));

    assert!(
        !result.png_data.is_empty(),
        "[{scenario}] png_data is empty — nothing rendered"
    );
    assert!(
        (result.content_width - w).abs() < 0.5,
        "[{scenario}] content_width {} != requested {w}",
        result.content_width
    );
    assert!(
        (result.content_height - h).abs() < 0.5,
        "[{scenario}] content_height {} != requested {h}",
        result.content_height
    );

    let path = out_dir().join(format!("{scenario}.png"));
    std::fs::write(&path, &result.png_data)
        .unwrap_or_else(|e| panic!("[{scenario}] write PNG: {e}"));
    println!(
        "[{scenario}] wrote {} ({} bytes, {}x{})",
        path.display(),
        result.png_data.len(),
        result.content_width,
        result.content_height
    );
    path
}

// ============================================================================
// Scenarios
// ============================================================================

/// 1. Knuth-Plass / greedy wrapping: a multi-word paragraph in a fixed-width
///    box that forces several lines; alternating word colours.
#[test]
fn knuth_plass_wrap() {
    let fm = font_manager_with_stress_fonts();
    let html = r#"
<html><head><style>
  body { margin: 0; background: white; }
  #p { font-family: "Azul Mock Prop"; font-size: 32px; width: 360px; line-height: 40px; }
  .a { color: #cc2222; } .b { color: #2266cc; } .c { color: #118844; }
</style></head><body>
  <div id="p"><span class="a">the</span> <span class="b">quick</span> <span class="c">brown</span> <span class="a">fox</span> <span class="b">jumps</span> <span class="c">over</span> <span class="a">lazy</span> <span class="b">dogs</span> <span class="c">while</span> <span class="a">running</span> <span class="b">home</span></div>
</body></html>"#;
    render_to_png("knuth_plass_wrap", html, &fm, 400.0, 260.0);
}

/// 2. Block justify: same paragraph with `text-align: justify` — inter-word
///    space stretches so right edges align (except the last line).
#[test]
fn block_justify() {
    let fm = font_manager_with_stress_fonts();
    let html = r#"
<html><head><style>
  body { margin: 0; background: white; }
  #p { font-family: "Azul Mock Prop"; font-size: 32px; width: 360px; line-height: 40px; text-align: justify; }
  .a { color: #cc2222; } .b { color: #2266cc; } .c { color: #118844; }
</style></head><body>
  <div id="p"><span class="a">the</span> <span class="b">quick</span> <span class="c">brown</span> <span class="a">fox</span> <span class="b">jumps</span> <span class="c">over</span> <span class="a">lazy</span> <span class="b">dogs</span> <span class="c">while</span> <span class="a">running</span> <span class="b">home</span></div>
</body></html>"#;
    render_to_png("block_justify", html, &fm, 400.0, 260.0);
}

/// 3. Dropcap: a `float: left` large first letter that body text wraps around,
///    then reflows full-width below the float.
#[test]
fn dropcap() {
    let fm = font_manager_with_stress_fonts();
    let html = r#"
<html><head><style>
  body { margin: 0; background: white; }
  #cap { float: left; font-family: "Azul Mock Mono"; font-size: 80px; color: #cc2222; line-height: 80px; margin-right: 6px; }
  #body { font-family: "Azul Mock Mono"; font-size: 24px; width: 380px; line-height: 30px; color: #2266cc; }
</style></head><body>
  <div id="cap">A</div>
  <div id="body">lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</div>
</body></html>"#;
    render_to_png("dropcap", html, &fm, 420.0, 260.0);
}

/// 4. Arabic RTL: a short joined string incl. lam+alef, `direction: rtl`.
///    Glyphs order right-to-left; lam+alef collapses to one box.
#[test]
fn arabic_rtl() {
    let fm = font_manager_with_stress_fonts();
    // beh teh meem  space  lam alef  space  beh lam alef
    let html = "\
<html><head><style>\
  body { margin: 0; background: white; }\
  #a { font-family: \"Azul Mock Arabic\"; font-size: 48px; direction: rtl; color: #cc2222; }\
</style></head><body>\
  <div id=\"a\">\u{0628}\u{062A}\u{0645} \u{0644}\u{0627} \u{0628}\u{0644}\u{0627}</div>\
</body></html>";
    render_to_png("arabic_rtl", html, &fm, 500.0, 100.0);
}

/// 5. Vertical writing mode: ideographs stack top-to-bottom in `vertical-rl`.
#[test]
fn vertical_rl() {
    let fm = font_manager_with_stress_fonts();
    // U+4E00..U+4E05 (6 ideographs), two coloured spans.
    let html = "\
<html><head><style>\
  body { margin: 0; background: white; }\
  #v { font-family: \"Azul Mock Vertical\"; font-size: 40px; writing-mode: vertical-rl; height: 320px; }\
  .a { color: #cc2222; } .b { color: #2266cc; }\
</style></head><body>\
  <div id=\"v\"><span class=\"a\">\u{4E00}\u{4E01}\u{4E02}</span><span class=\"b\">\u{4E03}\u{4E04}\u{4E05}</span></div>\
</body></html>";
    let path = render_to_png("vertical_rl", html, &fm, 120.0, 340.0);

    // Numeric regression guard for the block-axis column order (CSS Writing
    // Modes §3.1): in vertical-rl, successive columns advance RIGHT-to-LEFT, so
    // the FIRST (red) span must be the RIGHTMOST column and the second (blue)
    // span sits to its left. Decode the rendered PNG and compare the horizontal
    // centroid of the red vs blue glyph boxes: red must be to the RIGHT of blue.
    // (Before the fix in text3/cache.rs perform_fragment_layout, columns advanced
    // left-to-right and red landed on the LEFT — this assertion catches a regress.)
    let png = std::fs::read(&path).expect("read vertical_rl.png");
    let pm = azul_layout::cpurender::AzulPixmap::decode_png(&png).expect("decode vertical_rl.png");
    let (w, h) = (pm.width() as usize, pm.height() as usize);
    let data = pm.data();
    let (mut red_sum, mut red_n, mut blue_sum, mut blue_n) = (0.0f64, 0u64, 0.0f64, 0u64);
    for y in 0..h {
        for x in 0..w {
            let i = (y * w + x) * 4;
            let (r, g, b) = (data[i], data[i + 1], data[i + 2]);
            if r > 150 && g < 110 && b < 110 {
                red_sum += x as f64;
                red_n += 1;
            } else if b > 150 && r < 110 {
                blue_sum += x as f64;
                blue_n += 1;
            }
        }
    }
    assert!(
        red_n > 0 && blue_n > 0,
        "vertical_rl: expected both red and blue glyph pixels (red_n={red_n}, blue_n={blue_n})"
    );
    let red_cx = red_sum / red_n as f64;
    let blue_cx = blue_sum / blue_n as f64;
    assert!(
        red_cx > blue_cx,
        "vertical-rl column order: first (red) span must be the RIGHTMOST column — \
         red centroid x={red_cx:.1} should be > blue centroid x={blue_cx:.1}"
    );
}

/// 6. Ligatures: "office affix" style string with ffi/fi. Top row uses the
///    liga font (ffi collapses to one wider box); bottom row uses non-liga
///    Mono for contrast (f, f, i stay separate).
#[test]
fn ligatures() {
    let fm = font_manager_with_stress_fonts();
    let html = r#"
<html><head><style>
  body { margin: 0; background: white; }
  .liga { font-family: "Azul Mock Liga"; font-size: 48px; color: #cc2222; }
  .mono { font-family: "Azul Mock Mono"; font-size: 48px; color: #2266cc; }
  div { line-height: 60px; }
</style></head><body>
  <div class="liga">office ffi fi</div>
  <div class="mono">office ffi fi</div>
</body></html>"#;
    render_to_png("ligatures", html, &fm, 500.0, 140.0);
}

/// 7. Kerning: "AVAVA WAVE" in the kern font — A+V pairs pull tighter (-200).
#[test]
fn kerning() {
    let fm = font_manager_with_stress_fonts();
    let html = r#"
<html><head><style>
  body { margin: 0; background: white; }
  #k { font-family: "Azul Mock Kern"; font-size: 48px; }
  .a { color: #cc2222; } .b { color: #2266cc; }
</style></head><body>
  <div id="k"><span class="a">AVAVA</span> <span class="b">WAVE</span></div>
</body></html>"#;
    render_to_png("kerning", html, &fm, 500.0, 100.0);
}

/// 8. In-memory CJK: generate a ~20k-glyph rectangle font (U+4E00..U+9FFF)
///    at runtime, register it, and lay out a handful of ideographs. Proves the
///    in-memory generator + big-cmap path.
#[test]
fn cjk_inmemory() {
    let mut fm = font_manager_with_stress_fonts();

    // Full CJK Unified Ideographs block: ~20992 glyphs.
    let codepoints: Vec<u32> = (0x4E00u32..=0x9FFFu32).collect();
    let bytes = rect_font::build_rect_font(
        "Azul Rect CJK",
        /* upem */ 1000,
        /* advance */ 1000,
        /* ascent */ 800,
        /* descent (positive magnitude) */ 200,
        &codepoints,
    );
    assert!(bytes.len() > 100_000, "generated CJK font suspiciously small: {} bytes", bytes.len());
    fm.register_named_font("Azul Rect CJK", &bytes, vec![range(0x4E00, 0x9FFF)]);

    // A few ideographs spread across the block, in two colours.
    let html = "\
<html><head><style>\
  body { margin: 0; background: white; }\
  #c { font-family: \"Azul Rect CJK\"; font-size: 48px; }\
  .a { color: #cc2222; } .b { color: #2266cc; }\
</style></head><body>\
  <div id=\"c\"><span class=\"a\">\u{4E00}\u{5B57}\u{6C34}</span><span class=\"b\">\u{9F8D}\u{9FFF}</span></div>\
</body></html>";
    render_to_png("cjk_inmemory", html, &fm, 340.0, 90.0);
}
