// Generated by azul-css codegen (Zig). Do not edit by hand.
const std = @import("std");
const azul = @import("azul.zig");
const C = azul.C;

// CSS: .card, .card:hover, .card:active, .card:focus, .card (conditional), .card:hover (conditional)
pub fn styleCard() C.AzCssPropertyWithConditionsVec {
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(&[_]C.AzCssPropertyWithConditions{
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_paddingTop(C.AzLayoutPaddingTop{ .inner = C.AzPixelValue_px(8.0) })),
        C.AzCssPropertyWithConditions_onHover(C.AzCssProperty_paddingTop(C.AzLayoutPaddingTop{ .inner = C.AzPixelValue_px(9.0) })),
        C.AzCssPropertyWithConditions_onActive(C.AzCssProperty_paddingTop(C.AzLayoutPaddingTop{ .inner = C.AzPixelValue_px(10.0) })),
        C.AzCssPropertyWithConditions_onFocus(C.AzCssProperty_borderTopColor(C.AzStyleBorderTopColor{ .inner = C.AzColorU{ .r = 51, .g = 153, .b = 255, .a = 255 } })),
        C.AzCssPropertyWithConditions_withCondition(C.AzCssProperty_paddingLeft(C.AzLayoutPaddingLeft{ .inner = C.AzPixelValue_px(16.0) }), C.AzDynamicSelector_viewportWidth(C.AzMinMaxRange{ .min = 600.0, .max = std.math.nan(f32) })),
        C.AzCssPropertyWithConditions_withConditions(
            C.AzCssProperty_paddingLeft(C.AzLayoutPaddingLeft{ .inner = C.AzPixelValue_px(24.0) }),
            C.AzDynamicSelectorVec_copyFromPtr(&[_]C.AzDynamicSelector{
                C.AzDynamicSelector_media(C.AzMediaType_Screen),
                C.AzDynamicSelector_viewportWidth(C.AzMinMaxRange{ .min = 1024.0, .max = std.math.nan(f32) }),
            }, 2)
        ),
        C.AzCssPropertyWithConditions_onMacos(C.AzCssProperty_fontSize(C.AzStyleFontSize{ .inner = C.AzPixelValue_px(13.0) })),
        C.AzCssPropertyWithConditions_onWindows(C.AzCssProperty_fontSize(C.AzStyleFontSize{ .inner = C.AzPixelValue_px(12.0) })),
        C.AzCssPropertyWithConditions_onLinux(C.AzCssProperty_fontSize(C.AzStyleFontSize{ .inner = C.AzPixelValue_px(11.0) })),
        C.AzCssPropertyWithConditions_onOs(C.AzCssProperty_fontSize(C.AzStyleFontSize{ .inner = C.AzPixelValue_px(15.0) }), C.AzOsCondition_Android),
        C.AzCssPropertyWithConditions_darkMode(C.AzCssProperty_textColor(C.AzStyleTextColor{ .inner = C.AzColorU{ .r = 255, .g = 255, .b = 255, .a = 255 } })),
        C.AzCssPropertyWithConditions_withConditions(
            C.AzCssProperty_textColor(C.AzStyleTextColor{ .inner = C.AzColorU{ .r = 204, .g = 204, .b = 204, .a = 255 } }),
            C.AzDynamicSelectorVec_copyFromPtr(&[_]C.AzDynamicSelector{
                C.AzDynamicSelector_pseudoState(C.AzPseudoStateType_Hover),
                C.AzDynamicSelector_mode(C.AzModeCondition_Dark),
            }, 2)
        ),
        C.AzCssPropertyWithConditions_withCondition(C.AzCssProperty_letterSpacing(C.AzStyleLetterSpacing{ .inner = C.AzPixelValue_px(1.0) }), C.AzDynamicSelector_language(C.AzLanguageCondition_prefix(C.AzString_copyFromBytes("de-DE", 0, 5)))),
    }, 13);
}

// CSS: .list li:nth-child(2)
pub fn styleListLiNthChild2() C.AzCssPropertyWithConditionsVec {
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(&[_]C.AzCssPropertyWithConditions{
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_textColor(C.AzStyleTextColor{ .inner = C.AzColorU{ .r = 153, .g = 153, .b = 153, .a = 255 } })),
    }, 1);
}

// CSS: #main>.title
pub fn styleMainTitle() C.AzCssPropertyWithConditionsVec {
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(&[_]C.AzCssPropertyWithConditions{
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_fontWeight(C.AzStyleFontWeight_Bold)),
    }, 1);
}

// CSS: div .note:first
pub fn styleDivNoteFirst() C.AzCssPropertyWithConditionsVec {
    return C.AzCssPropertyWithConditionsVec_copyFromPtr(&[_]C.AzCssPropertyWithConditions{
        C.AzCssPropertyWithConditions_simple(C.AzCssProperty_fontStyle(C.AzStyleFontStyle_Italic)),
    }, 1);
}
