// Generated by azul-css codegen (Zig). Do not edit by hand.
const std = @import("std");
const azul = @import("azul.zig");
const C = azul.C;

// Joins `parts` into an AzString (AzString_copyFromBytes copies the bytes).
fn azConcat(parts: []const []const u8) C.AzString {
    const joined = std.mem.concat(std.heap.page_allocator, u8, parts) catch @panic("out of memory");
    defer std.heap.page_allocator.free(joined);
    return C.AzString_copyFromBytes(joined.ptr, 0, joined.len);
}

// `user:card`: its texts and its link are parameters
pub fn renderCard(title: []const u8, text: []const u8, href: []const u8, author: []const u8) C.AzDom {
    return C.AzDom_withChild(
        C.AzDom_withChild(
            C.AzDom_withChild(
                C.AzDom_withChild(
                    C.AzDom_withClass(
                        C.AzDom_withCss(C.AzDom_createDiv(), C.AzString_copyFromBytes("padding: 8px", 0, 12)),
                        C.AzString_copyFromBytes("card", 0, 4)
                    ),
                    C.AzDom_createH2WithText(C.AzString_copyFromBytes(title.ptr, 0, title.len))
                ),
                C.AzDom_createPWithText(C.AzString_copyFromBytes(text.ptr, 0, text.len))
            ),
            C.AzDom_createA(C.AzString_copyFromBytes(href.ptr, 0, href.len), C.AzString_copyFromBytes("Read more", 0, 9), C.AzSmallAriaInfo_label(C.AzString_copyFromBytes("Read more", 0, 9)))
        ),
        C.AzDom_createSpanWithText(azConcat(&[_][]const u8{ "by ", author }))
    );
}

// -- registration --

// The String value of the data-model field `name` (a view into the model,
// which outlives the render call), or `fallback`.
fn azModelString(model: [*c]const C.AzComponentDataModel, name: []const u8, fallback: []const u8) []const u8 {
    const fields = model.*.fields;
    for (0..fields.len) |i| {
        const f = fields.ptr[i];
        if (f.name.vec.len == name.len and std.mem.eql(u8, f.name.vec.ptr[0..name.len], name) and
            f.default_value.Some.tag == C.AzOptionComponentDefaultValue_Tag_Some and
            f.default_value.Some.payload.String.tag == C.AzComponentDefaultValue_Tag_String)
        {
            const s = f.default_value.Some.payload.String.payload;
            if (s.vec.len == 0) return "";
            return s.vec.ptr[0..s.vec.len];
        }
    }
    return fallback;
}

// A String field of a component's data model.
fn azStringField(name: []const u8, value: []const u8, description: []const u8) C.AzComponentDataField {
    return .{
        .name = C.AzString_copyFromBytes(name.ptr, 0, name.len),
        .field_type = C.AzComponentFieldType_string(),
        .default_value = C.AzOptionComponentDefaultValue_some(
            C.AzComponentDefaultValue_string(C.AzString_copyFromBytes(value.ptr, 0, value.len)),
        ),
        .required = false,
        .description = C.AzString_copyFromBytes(description.ptr, 0, description.len),
    };
}

// `user:card` with its default arguments.
pub fn renderCardDefault() C.AzDom {
    return renderCard("Hello", "Some text", "https://azul.rs", "me");
}

fn cardRenderFn(def: [*c]const C.AzComponentDef, model: [*c]const C.AzComponentDataModel, map: [*c]const C.AzComponentMap) callconv(.c) C.AzResultStyledDomRenderDomError {
    _ = def;
    _ = map;
    const dom = renderCard(azModelString(model, "title", "Hello"), azModelString(model, "text", "Some text"), azModelString(model, "href", "https://azul.rs"), azModelString(model, "author", "me"));
    return C.AzResultStyledDomRenderDomError_ok(C.AzStyledDom_createFromDom(dom));
}

fn cardDef() C.AzComponentDef {
    var def: C.AzComponentDef = .{};
    def.id = C.AzComponentId_create(C.AzString_copyFromBytes("user", 0, 4), C.AzString_copyFromBytes("card", 0, 4));
    def.display_name = C.AzString_copyFromBytes("Card", 0, 4);
    def.description = C.AzString_copyFromBytes("Converted from a <div> subtree in AzBuilder", 0, 43);
    // The CSS is applied per node by renderCard.
    def.css = C.AzString_copyFromBytes("", 0, 0);
    def.source = C.AzComponentSource_UserDefined;
    def.data_model.name = C.AzString_copyFromBytes("CardData", 0, 8);
    def.data_model.description = C.AzString_copyFromBytes("Converted from a <div> subtree in AzBuilder", 0, 43);
    var fields: [4]C.AzComponentDataField = undefined;
    fields[0] = azStringField("title", "Hello", "Text of the <h2>");
    fields[1] = azStringField("text", "Some text", "Text of the <p>");
    fields[2] = azStringField("href", "https://azul.rs", "`href` of the <a>");
    fields[3] = azStringField("author", "me", "Text of the <span>");
    def.data_model.fields = C.AzComponentDataFieldVec_copyFromPtr(&fields, 4);
    // copyFromPtr cloned them.
    for (&fields) |*f| C.AzComponentDataField_delete(f);
    def.render_fn = &cardRenderFn;
    def.codegen = C.AzComponentCodegen_renderFunction();
    def.render_fn_source = C.AzOptionString_none();
    return def;
}

// The component library `user`:
//     C.AzAppConfig_addComponentLibrary(&config, C.AzString_copyFromBytes("user", 0, 4), &registerUserLibrary);
pub fn registerUserLibrary() callconv(.c) C.AzComponentLibrary {
    var defs: [1]C.AzComponentDef = undefined;
    defs[0] = cardDef();
    var lib: C.AzComponentLibrary = .{};
    lib.name = C.AzString_copyFromBytes("user", 0, 4);
    lib.version = C.AzString_copyFromBytes("0.1.0", 0, 5);
    lib.description = C.AzString_copyFromBytes("Exported from AzBuilder", 0, 23);
    lib.components = C.AzComponentDefVec_copyFromPtr(&defs, 1);
    // copyFromPtr cloned them.
    for (&defs) |*d| C.AzComponentDef_delete(d);
    lib.exportable = true;
    lib.modifiable = false;
    lib.data_models = C.AzComponentDataModelVec_create();
    lib.enum_models = C.AzComponentEnumModelVec_create();
    return lib;
}
