;;;; Generated by azul-css codegen (Common Lisp). Do not edit by hand.
(defpackage #:azul-styles
  (:use #:cl)
  (:export #:style-azul-native-button))

(in-package #:azul-styles)

(defun css-type (name)
  "The CFFI type of the api.json type NAME: its union, struct or enum."
  (or (find-if (lambda (spec) (ignore-errors (cffi:foreign-type-size spec)))
               (list (list :union name) (list :struct name)))
      name))

(defun css-vec (copy-fn elem items)
  "Copies ITEMS into a foreign array of ELEM; COPY-FN clones them into a Vec."
  (let ((type (css-type elem))
        (n (length items)))
    (cffi:with-foreign-object (arr type n)
      (loop for item in items
            for i from 0
            do (setf (cffi:mem-aref arr type i) item))
      (funcall copy-fn arr n))))

;; CSS: .__azul-native-button:hover, .__azul-native-button:active, .__azul-native-button:focus, .__azul-native-button:hover (conditional), .__azul-native-button:active (conditional), .__azul-native-button:focus (conditional)
(defun style-azul-native-button ()
  (css-vec
    #'azul-internal::%az-css-property-with-conditions-vec-copy-from-ptr
    'azul-internal::az-css-property-with-conditions
    (list
      (azul-internal::%az-css-property-with-conditions-on-hover (azul-internal::%az-css-property-background-content (css-vec #'azul-internal::%az-style-background-content-vec-copy-from-ptr 'azul-internal::az-style-background-content (list (azul-internal::%az-style-background-content-color (list 'azul-internal::r 241 'azul-internal::g 243 'azul-internal::b 245 'azul-internal::a 255))))))
      (azul-internal::%az-css-property-with-conditions-on-hover (azul-internal::%az-css-property-border-top-color (list 'azul-internal::inner (list 'azul-internal::r 173 'azul-internal::g 181 'azul-internal::b 189 'azul-internal::a 255))))
      (azul-internal::%az-css-property-with-conditions-on-hover (azul-internal::%az-css-property-border-bottom-color (list 'azul-internal::inner (list 'azul-internal::r 173 'azul-internal::g 181 'azul-internal::b 189 'azul-internal::a 255))))
      (azul-internal::%az-css-property-with-conditions-on-hover (azul-internal::%az-css-property-border-left-color (list 'azul-internal::inner (list 'azul-internal::r 173 'azul-internal::g 181 'azul-internal::b 189 'azul-internal::a 255))))
      (azul-internal::%az-css-property-with-conditions-on-hover (azul-internal::%az-css-property-border-right-color (list 'azul-internal::inner (list 'azul-internal::r 173 'azul-internal::g 181 'azul-internal::b 189 'azul-internal::a 255))))
      (azul-internal::%az-css-property-with-conditions-on-active (azul-internal::%az-css-property-background-content (css-vec #'azul-internal::%az-style-background-content-vec-copy-from-ptr 'azul-internal::az-style-background-content (list (azul-internal::%az-style-background-content-color (list 'azul-internal::r 222 'azul-internal::g 226 'azul-internal::b 230 'azul-internal::a 255))))))
      (azul-internal::%az-css-property-with-conditions-on-focus (azul-internal::%az-css-property-border-top-color (list 'azul-internal::inner (list 'azul-internal::r 13 'azul-internal::g 110 'azul-internal::b 253 'azul-internal::a 255))))
      (azul-internal::%az-css-property-with-conditions-on-focus (azul-internal::%az-css-property-border-bottom-color (list 'azul-internal::inner (list 'azul-internal::r 13 'azul-internal::g 110 'azul-internal::b 253 'azul-internal::a 255))))
      (azul-internal::%az-css-property-with-conditions-on-focus (azul-internal::%az-css-property-border-left-color (list 'azul-internal::inner (list 'azul-internal::r 13 'azul-internal::g 110 'azul-internal::b 253 'azul-internal::a 255))))
      (azul-internal::%az-css-property-with-conditions-on-focus (azul-internal::%az-css-property-border-right-color (list 'azul-internal::inner (list 'azul-internal::r 13 'azul-internal::g 110 'azul-internal::b 253 'azul-internal::a 255))))
      (azul-internal::%az-css-property-with-conditions-with-conditions
        (azul-internal::%az-css-property-background-content (css-vec #'azul-internal::%az-style-background-content-vec-copy-from-ptr 'azul-internal::az-style-background-content (list (azul-internal::%az-style-background-content-color (list 'azul-internal::r 73 'azul-internal::g 80 'azul-internal::b 87 'azul-internal::a 255)))))
        (css-vec
          #'azul-internal::%az-dynamic-selector-vec-copy-from-ptr
          'azul-internal::az-dynamic-selector
          (list
            (azul-internal::%az-dynamic-selector-pseudo-state :hover)
            (azul-internal::%az-dynamic-selector-mode :dark)
          )
        )
      )
      (azul-internal::%az-css-property-with-conditions-with-conditions
        (azul-internal::%az-css-property-border-top-color (list 'azul-internal::inner (list 'azul-internal::r 73 'azul-internal::g 80 'azul-internal::b 87 'azul-internal::a 255)))
        (css-vec
          #'azul-internal::%az-dynamic-selector-vec-copy-from-ptr
          'azul-internal::az-dynamic-selector
          (list
            (azul-internal::%az-dynamic-selector-pseudo-state :hover)
            (azul-internal::%az-dynamic-selector-mode :dark)
          )
        )
      )
      (azul-internal::%az-css-property-with-conditions-with-conditions
        (azul-internal::%az-css-property-background-content (css-vec #'azul-internal::%az-style-background-content-vec-copy-from-ptr 'azul-internal::az-style-background-content (list (azul-internal::%az-style-background-content-color (list 'azul-internal::r 43 'azul-internal::g 48 'azul-internal::b 53 'azul-internal::a 255)))))
        (css-vec
          #'azul-internal::%az-dynamic-selector-vec-copy-from-ptr
          'azul-internal::az-dynamic-selector
          (list
            (azul-internal::%az-dynamic-selector-pseudo-state :active)
            (azul-internal::%az-dynamic-selector-mode :dark)
          )
        )
      )
      (azul-internal::%az-css-property-with-conditions-with-conditions
        (azul-internal::%az-css-property-border-top-color (list 'azul-internal::inner (list 'azul-internal::r 59 'azul-internal::g 130 'azul-internal::b 246 'azul-internal::a 255)))
        (css-vec
          #'azul-internal::%az-dynamic-selector-vec-copy-from-ptr
          'azul-internal::az-dynamic-selector
          (list
            (azul-internal::%az-dynamic-selector-pseudo-state :focus)
            (azul-internal::%az-dynamic-selector-mode :dark)
          )
        )
      )
    )
  ))
