//! My App - generated by AzBuilder (azul-css codegen, Rust).

mod ui;

use azul::prelude::*;

struct AppData {}

extern "C" fn layout(_data: RefAny, _info: LayoutCallbackInfo) -> Dom {
    ui::render_ui()
}

fn main() {
    let app = App::create(RefAny::new(AppData {}), AppConfig::create());
    let mut window = WindowCreateOptions::create(layout);
    window.window_state.title = azul::str::String::from("My App");
    app.run(window);
}
