//! Zig binding generator.
//!
//! Emits two source files:
//!
//! * `azul_c.zig` — the C ABI of `libazul` pre-translated to Zig (see [`c_decls`]): every
//!   struct/union/enum, callback typedef, constant and `pub extern fn`, with the names and
//!   layouts of `azul.h`.
//! * `azul.zig` — `pub const C = @import("azul_c.zig");` plus idiomatic wrapper structs with
//!   `deinit()` methods around the heap-owning types, so users can write `defer app.deinit();`
//!   instead of `defer C.AzApp_delete(&app);`.
//!
//! # Why not `@cImport(@cInclude("azul.h"))`?
//!
//! That is what this generator did first, and it is the smallest possible binding: Zig
//! translates the C header itself. But `azul.h` is 5.6 MB (the types, ~20k `extern`
//! declarations and ~100k lines of `static inline` helpers), and Zig re-translates and
//! analyses the whole translation unit on every cold build — 91–123 s for a hello-world,
//! ~5 s warm, 28 s in `ReleaseSafe`. Emitting the declarations from the IR, the way every
//! other binding gets them, costs a few seconds instead and drops the header from the
//! include path entirely. The pre-translation keeps the `translate-c` spellings (`[*c]`
//! pointers, `c_uint` enums with `c_int` constants, zeroed struct defaults), so code that was
//! written against the `@cImport` namespace compiles unchanged.
//!
//! # Build / link requirements
//!
//! Users must:
//!
//! 1. keep `azul.zig` and `azul_c.zig` next to each other (the import is relative),
//! 2. link the `azul` system library (e.g. `exe.linkSystemLibrary("azul");` and
//!    `exe.addLibraryPath(.{ .path = "." });`),
//! 3. link `libc` (`exe.linkLibC();`).
//!
//! See [`build_zig::generate_build_zig`] for a ready-to-use example
//! `build.zig`.

pub mod build_zig;
pub mod c_decls;
pub mod wrappers;

use anyhow::Result;

use super::{config::CodegenConfig, generator::CodeBuilder, ir::CodegenIR};

/// The C library name used in `linkSystemLibrary("azul")`.
/// Must match the prebuilt artifact name (`libazul.so` / `libazul.dylib`
/// / `azul.dll`).
pub const LIB_NAME: &str = "azul";

/// Generate the full `azul.zig` source file.
///
/// The output has three layers, top-to-bottom:
///
/// 1. A doc-comment header explaining the two-file layout and the user-side build/link
///    requirements.
/// 2. `pub const C = @import("azul_c.zig");` — the entire FFI surface, pre-translated by
///    [`c_decls::generate_c_decls`].
/// 3. Idiomatic wrapper structs with `deinit()` and method delegates (see
///    [`wrappers::generate_wrappers`]).
///
/// `config` is currently unused (Zig bindings have no per-target
/// dialects) but is taken by reference to match the signatures of
/// other language entry points.
pub fn generate(ir: &CodegenIR, _config: &CodegenConfig) -> Result<String> {
    let mut builder = CodeBuilder::new("    ");

    emit_header(&mut builder);
    emit_c_import(&mut builder);
    builder.raw(&wrappers::generate_wrappers(ir));

    Ok(builder.finish())
}

/// Generate the companion `azul_c.zig` (the pre-translated C ABI).
pub fn generate_c_decls(ir: &CodegenIR, config: &CodegenConfig) -> String {
    c_decls::generate_c_decls(ir, config)
}

// ============================================================================
// Header / preamble
// ============================================================================

fn emit_header(b: &mut CodeBuilder) {
    b.line("// ============================================================================");
    b.line("// azul.zig — Zig bindings for the Azul GUI framework");
    b.line("// Auto-generated by azul-doc codegen v2 (lang_zig). DO NOT EDIT MANUALLY.");
    b.line("// ============================================================================");
    b.line("//");
    b.line("// Strategy: the C ABI of libazul is pre-translated into the companion file");
    b.line("// `azul_c.zig` (every type, constant and `extern fn` of `azul.h`, in the");
    b.line("// spelling `zig translate-c` would produce) and re-exported here as `C`.");
    b.line("// No `@cImport`: the 5.6 MB header is not translated or analysed at build");
    b.line("// time, and `azul.h` does not need to be on the include path.");
    b.line("//");
    b.line("// Build / link requirements:");
    b.line("//   * `azul_c.zig` must sit next to this file (the import is relative)");
    b.line("//   * the `azul` shared library must be linkable");
    b.line("//     (e.g. `exe.linkSystemLibrary(\"azul\");`)");
    b.line("//   * `libc` must be linked (`exe.linkLibC();`).");
    b.line("//");
    b.line("// The wrapper structs at the bottom of this file follow Zig conventions:");
    b.line("//   * heap-owning types expose `deinit()` (call it via `defer x.deinit();`)");
    b.line("//   * static factories live as `pub fn create(...)` on the wrapper struct");
    b.line("//   * instance methods take `*Self` and forward to the underlying C call.");
    b.line("//");
    b.line("// Drop the `Az` prefix at the call site: `App.create(...)` instead of");
    b.line("// `AzApp_create(...)`. The raw C API is still reachable via `azul.C.*`.");
    b.line("// ============================================================================");
    b.blank();
    b.line("const std = @import(\"std\");");
    b.blank();
}

fn emit_c_import(b: &mut CodeBuilder) {
    b.line("/// The raw C-ABI of libazul, pre-translated from the IR into `azul_c.zig`.");
    b.line("///");
    b.line("/// Every struct, union, enum, callback typedef, integer constant and exported");
    b.line("/// function of `azul.h` is declared there under its C name. Power users can");
    b.line("/// call C functions directly via `azul.C.AzApp_create(...)`; most users should");
    b.line("/// prefer the idiomatic wrapper structs below.");
    b.line(&format!("pub const C = @import(\"{}\");", c_decls::C_DECLS_FILE));
    b.blank();
}

// ============================================================================
// Naming helpers (shared with wrappers)
// ============================================================================

/// The `Az`-prefixed FFI type name for an IR type
/// (e.g. `Dom` → `AzDom`).
pub fn ffi_type_name(name: &str) -> String {
    format!("Az{}", name)
}

/// Sanitize a name for use as a Zig identifier. Zig keywords get an
/// `@"…"` quoted-identifier wrapper.
pub fn sanitize_identifier(name: &str) -> String {
    if is_zig_keyword(name) {
        format!("@\"{}\"", name)
    } else {
        name.to_string()
    }
}

fn is_zig_keyword(s: &str) -> bool {
    matches!(
        s,
        "addrspace"
            | "align"
            | "allowzero"
            | "and"
            | "anyframe"
            | "anytype"
            | "asm"
            | "async"
            | "await"
            | "break"
            | "callconv"
            | "catch"
            | "comptime"
            | "const"
            | "continue"
            | "defer"
            | "else"
            | "enum"
            | "errdefer"
            | "error"
            | "export"
            | "extern"
            | "fn"
            | "for"
            | "if"
            | "inline"
            | "linksection"
            | "noalias"
            | "nosuspend"
            | "noinline"
            | "or"
            | "orelse"
            | "packed"
            | "pub"
            | "resume"
            | "return"
            | "linksection_"
            | "struct"
            | "suspend"
            | "switch"
            | "test"
            | "threadlocal"
            | "try"
            | "type"
            | "union"
            | "unreachable"
            | "usingnamespace"
            | "var"
            | "volatile"
            | "while"
            // Primitive type names — Zig 0.16 treats them as
            // reserved identifiers ("name shadows primitive 'X'") when
            // they appear in declaration position (`pub fn null()` /
            // `pub fn u8()` / etc.). The C ABI legitimately exposes
            // methods named after primitives (e.g. `RawImageData.u8`,
            // `Json.null`); they need the `@"..."` escape just like
            // language keywords.
            | "anyerror"
            | "anyopaque"
            | "bool"
            | "c_int"
            | "c_long"
            | "c_longdouble"
            | "c_longlong"
            | "c_short"
            | "c_uint"
            | "c_ulong"
            | "c_ulonglong"
            | "c_ushort"
            | "comptime_float"
            | "comptime_int"
            | "f128"
            | "f16"
            | "f32"
            | "f64"
            | "f80"
            | "false"
            | "i128"
            | "i16"
            | "i32"
            | "i64"
            | "i8"
            | "isize"
            | "noreturn"
            | "null"
            | "true"
            | "u128"
            | "u16"
            | "u32"
            | "u64"
            | "u8"
            | "undefined"
            | "usize"
            | "void"
    )
}
