//! Makefile emission for Fortran examples.
//!
//! Fortran has no canonical package manifest the way C# has `.csproj`
//! or Ruby has `.gemspec`. The `fpm` (Fortran Package Manager) project
//! is gaining adoption but requires `fpm` to be installed; gfortran +
//! a plain Makefile is still the universal lowest common denominator.
//!
//! The emitted Makefile compiles every generated module (`.o` + a
//! compiler-managed `.mod` each) in dependency order — a module must be
//! compiled before the modules that `use` it, which is why the generator
//! writes the Makefile rather than a glob rule — then the example program
//! against them. The dependencies are real prerequisites, so `make -j`
//! compiles independent modules in parallel. The user is expected to drop
//! `libazul.so` / `azul.dll` / `libazul.dylib` next to the example before
//! running `make`.

/// Generate the Makefile for the split binding + the Fortran hello-world
/// example.
///
/// - `type_units`: the `azul_types_<unit>` modules with the modules each
///   one `use`s, in dependency order.
/// - `ffi_units`: the `azul_ffi_<module>` modules (each `use`s `azul_types`).
/// - `api_modules`: the api.json module names, one `azul_<module>` facade
///   each (each `use`s `azul_types`, `azul_ffi_<module>` and `azul_api`).
///
/// The user can override `FC=` on the command line to swap compilers
/// (e.g. `make FC=ifort`).
pub fn generate_makefile(
    type_units: &[(String, Vec<String>)],
    ffi_units: &[String],
    api_modules: &[String],
) -> String {
    let mut all: Vec<String> = Vec::new();
    let mut rules = String::new();
    let obj = |u: &str| format!("{}.o", u);

    for (unit, deps) in type_units {
        all.push(unit.clone());
        let d: Vec<String> = deps.iter().map(|x| obj(x)).collect();
        rules.push_str(&format!("{}: {}.f90 {}\n", obj(unit), unit, d.join(" ")));
    }
    let type_objs: Vec<String> = type_units.iter().map(|(u, _)| obj(u)).collect();
    all.push("azul_types".to_string());
    rules.push_str(&format!("azul_types.o: azul_types.f90 {}\n", type_objs.join(" ")));

    for unit in ffi_units {
        all.push(unit.clone());
        rules.push_str(&format!("{}: {}.f90 azul_types.o\n", obj(unit), unit));
    }
    let ffi_objs: Vec<String> = ffi_units.iter().map(|u| obj(u)).collect();
    all.push("azul_ffi".to_string());
    rules.push_str(&format!("azul_ffi.o: azul_ffi.f90 {}\n", ffi_objs.join(" ")));

    all.push("azul_api".to_string());
    rules.push_str("azul_api.o: azul_api.f90 azul_types.o azul_ffi.o\n");

    let mut facade_objs = Vec::new();
    for m in api_modules {
        let unit = format!("azul_{}", m);
        all.push(unit.clone());
        facade_objs.push(obj(&unit));
        rules.push_str(&format!(
            "{}: {}.f90 azul_types.o azul_ffi_{}.o azul_api.o\n",
            obj(&unit),
            unit,
            m
        ));
    }
    all.push("azul".to_string());
    rules.push_str("azul.o: azul.f90 azul_types.o azul_ffi.o azul_api.o\n");

    let objs: Vec<String> = all.iter().map(|u| obj(u)).collect();
    let mut objs_lines = String::new();
    for (i, o) in objs.iter().enumerate() {
        if i % 4 == 0 {
            objs_lines.push_str(if i == 0 { "AZUL_OBJS := " } else { " \\\n    " });
        } else {
            objs_lines.push(' ');
        }
        objs_lines.push_str(o);
    }

    format!(
        r#"# ============================================================================
# Auto-generated Makefile for the Fortran hello-world example.
# Generated by azul-doc codegen v2 (lang_fortran::makefile).
# ============================================================================
#
# Usage:
#   make            - build hello_world (add -j8 to compile modules in parallel)
#   make clean      - remove build artifacts
#   make run        - run the example
#
# Override FC=ifort or FC=ifx to use the Intel Fortran compiler.

# NOT `FC ?=`: GNU make PREDEFINES FC=f77 as a builtin default, so `?=`
# never fires and `make` tries the nonexistent f77. $(origin) tells the
# builtin default apart from a real user override (env / command line).
ifeq ($(origin FC),default)
FC      = gfortran
endif
# -ffree-line-length-none: the generated modules have declaration lines
# beyond the F2008 132-column limit (long widget/callback type names);
# without it -std=f2008 truncates them into hard errors. Intel ifort/ifx
# allows 7200-char lines by default, so the flag is gfortran-only anyway.
FFLAGS  ?= -O2 -std=f2008 -ffree-line-length-none -fimplicit-none
LDFLAGS ?= -L. -Wl,-rpath,'$$ORIGIN'
LIBS    ?= -lazul

EXE     := hello_world

# The binding is one module per api.json module (and per dependency slice
# of it for the types); `azul.f90` is the facade that `use`s them all. Every
# module produces a `.o` and a compiler-managed `.mod` the modules after it
# USE, so the rules below are real prerequisites and `make -j` is safe.
{objs}

all: $(EXE)

%.o: %.f90
	$(FC) $(FFLAGS) -c $<

{rules}
hello_world.o: hello_world.f90 azul.o

$(EXE): hello_world.o $(AZUL_OBJS)
	$(FC) $(FFLAGS) hello_world.o $(AZUL_OBJS) $(LDFLAGS) $(LIBS) -o $(EXE)

run: $(EXE)
	./$(EXE)

clean:
	rm -f *.o *.mod *.smod $(EXE)

.PHONY: all run clean
"#,
        objs = objs_lines,
        rules = rules,
    )
}
