# Generated by azul-css codegen (PowerShell). Do not edit by hand.
# Dot-source after Import-Module Azul.psd1: . ./styles.ps1

# An AzString holding the UTF-8 bytes of $S.
function New-CssString([string]$S) {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($S)
    $buf = [System.Runtime.InteropServices.Marshal]::AllocHGlobal([Math]::Max(1, $bytes.Length))
    try {
        [System.Runtime.InteropServices.Marshal]::Copy($bytes, 0, $buf, $bytes.Length)
        return [Azul.NativeMethods]::AzString_fromUtf8($buf, [UIntPtr][uint64]$bytes.Length)
    }
    finally { [System.Runtime.InteropServices.Marshal]::FreeHGlobal($buf) }
}

# Get-RenderUi: not expressible with the PowerShell bindings: DOM export (builder methods and parameters) is not implemented for this language's printer yet
