//! Java binding generator (JNA — Java Native Access).
//!
//! Generates idiomatic Java bindings from the IR. Unlike most other
//! generators in `v2/`, the Java target *cannot* live in a single
//! source file: the JCP convention is one public top-level class per
//! `.java` file. We therefore emit a multi-file string whose chunks
//! are demarcated with [`FILE_MARKER`] / [`END_MARKER`]. The
//! orchestrator (or the test harness) splits the string and writes each
//! chunk to disk under `src/main/java/com/azul/<ClassName>.java`.
//!
//! The high-level layout of the output is:
//!
//! 1. `AzulNative.java`   — `interface AzulNative extends Library` with
//!    every C-ABI symbol declared verbatim. Uses
//!    [`net.java.dev.jna.Native.load`] to bind to the prebuilt
//!    `azul.{dll,so,dylib}`.
//! 2. `<Type>.java` per FFI struct — a JNA `Structure` subclass with
//!    public fields, a `getFieldOrder()` override, and `ByValue` /
//!    `ByReference` inner classes for pass-by-value vs pointer
//!    parameters.
//! 3. `<Type>_Tag.java` per tagged-union enum — a Java `enum` for the
//!    discriminator and `<Type>.java` for the outer payload `Union`
//!    helper structure.
//! 4. `<Type>.java` wrapper class for every type that has a matching
//!    `_delete` C function. Implements `AutoCloseable`.
//!
//! All of the JNA boilerplate (Structure subclass, ByValue, ByReference,
//! Union, Pointer) is dropped in by [`types`] and [`wrappers`]; this
//! module owns only orchestration and the file-marker plumbing.
//!
//! ## Wiring
//!
//! Not yet referenced from `v2/mod.rs`. The orchestrator is responsible
//! for adding `pub mod lang_java;` and a `generate_java(...)` helper
//! that splits the multi-file string and writes each chunk.
//!
//! ## Shared with `lang_kotlin`
//!
//! Kotlin and Java target the same JNA runtime. The primitive-type
//! mapping ([`map_jvm_type`]) is therefore shared with Kotlin via
//! `pub` exports; the Kotlin generator imports `super::lang_java`
//! type helpers and surfaces them with Kotlin sugar
//! (`Pointer?`, `Long`, `Int`).

pub mod functions;
pub mod managed;
pub mod pom;
pub mod types;
pub mod wrappers;

use anyhow::Result;

use super::config::CodegenConfig;
use super::generator::CodeBuilder;
use super::ir::CodegenIR;

/// Library name that JNA passes to `Native.load(...)`. Resolves to
/// `azul.dll` on Windows, `libazul.so` on Linux, `libazul.dylib` on
/// macOS.
pub const LIBRARY_NAME: &str = "azul";

/// Java package the generated sources land in. Mirrors
/// `com.azul.<ClassName>` on disk.
pub const PACKAGE: &str = "com.azul";

/// Marker emitted before every Java source file in the multi-file
/// output. The orchestrator splits on this marker.
///
///     // ==FILE: AzulNative.java ==
///     package com.azul;
///     ...
///     // ==END==
///
/// Must remain stable; downstream tooling treats it as a contract.
pub const FILE_MARKER: &str = "// ==FILE: ";

/// Closing marker for a single Java source file.
pub const END_MARKER: &str = " ==";

/// Closing END marker line (used after each file body). Kept symmetric
/// with [`FILE_MARKER`] for ease of parsing.
pub const END_LINE: &str = "// ==END==";

/// Public entry point. Returns a single `String` containing every
/// `.java` source file the binding consists of, separated by
/// [`FILE_MARKER`] / [`END_LINE`] markers. The orchestrator splits on
/// these markers and writes each file separately.
pub fn generate(ir: &CodegenIR, config: &CodegenConfig) -> Result<String> {
    let mut out = String::new();

    // 1. Native FFI interface (one file: AzulNative.java)
    out.push_str(&emit_file(
        "AzulNative.java",
        |builder| functions::generate_native_interface(builder, ir, config),
        config,
    )?);

    // 2. POD/struct types — one file per type. Tagged-union enums are
    //    flattened into `<Type>_Tag.java` + `<Type>.java`.
    types::emit_all_type_files(&mut out, ir, config)?;

    // 3. Idiomatic AutoCloseable wrappers — one file per wrapped type.
    wrappers::emit_all_wrapper_files(&mut out, ir, config)?;

    // 4. Managed-FFI runtime helpers (host-invoker pattern). Two extra
    //    Java source files: AzulNativeManaged.java + AzulHostInvoker.java.
    managed::emit_files(&mut out, ir, config)?;

    Ok(out)
}

/// Helper: build a single Java source file using the supplied closure
/// and return it wrapped in `FILE_MARKER` / `END_LINE` markers.
pub(crate) fn emit_file<F>(filename: &str, body: F, config: &CodegenConfig) -> Result<String>
where
    F: FnOnce(&mut CodeBuilder) -> Result<()>,
{
    let mut builder = CodeBuilder::new(&config.indent);
    builder.line(&format!("{}{}{}", FILE_MARKER, filename, END_MARKER));
    builder.line(&format!("// Auto-generated by azul-doc codegen v2 (lang_java)."));
    builder.line("// DO NOT EDIT MANUALLY — re-run the generator instead.");
    builder.blank();
    builder.line(&format!("package {};", PACKAGE));
    builder.blank();
    emit_imports(&mut builder);
    body(&mut builder)?;
    builder.blank();
    builder.line(END_LINE);
    builder.blank();
    Ok(builder.finish())
}

/// Standard imports every generated Java source file needs.
fn emit_imports(builder: &mut CodeBuilder) {
    builder.line("import com.sun.jna.Library;");
    builder.line("import com.sun.jna.Native;");
    builder.line("import com.sun.jna.Pointer;");
    builder.line("import com.sun.jna.Structure;");
    builder.line("import com.sun.jna.Union;");
    builder.line("import java.util.Arrays;");
    builder.line("import java.util.List;");
    builder.blank();
}

// ============================================================================
// Shared name + type helpers (also re-used from lang_kotlin)
// ============================================================================

/// The Az-prefixed FFI type name for a given IR type
/// (e.g. `Dom` -> `AzDom`).
pub fn ffi_type_name(name: &str) -> String {
    format!("Az{}", name)
}

/// Map a Rust/IR type name to its Java/JNA-friendly equivalent. The
/// JVM has no unsigned types, so unsigned C types widen to their
/// signed Java counterpart of equal size where safe (`u8` → `byte`,
/// `u32` → `int`) or to `long` when the wider type is more idiomatic
/// (`usize` → `long`).
///
/// Pointers, references, and unknown types collapse to JNA's
/// `Pointer`. Nested struct field types resolve to the `Az<Name>`
/// generated class.
///
/// Mirrors [`csharp::map_type_to_csharp`]'s shape; kept Java-flavoured
/// to leave room for divergent edge cases (`Pointer` vs `IntPtr`, etc).
pub fn map_jvm_type(rust_type: &str, ir: &CodegenIR) -> String {
    let trimmed = rust_type.trim();

    // Pointers / references all collapse to JNA Pointer.
    if let Some(rest) = trimmed.strip_prefix("*const ") {
        let _ = rest;
        return "Pointer".to_string();
    }
    if let Some(rest) = trimmed.strip_prefix("*mut ") {
        let _ = rest;
        return "Pointer".to_string();
    }
    if let Some(rest) = trimmed.strip_prefix("&mut ") {
        let _ = rest;
        return "Pointer".to_string();
    }
    if let Some(rest) = trimmed.strip_prefix('&') {
        let _ = rest;
        return "Pointer".to_string();
    }

    match trimmed {
        // Primitives — JVM has no unsigned, widen-or-truncate as needed.
        //
        // C's `bool` is 1 byte (sizeof(_Bool) == 1) but JNA marshals
        // Java `boolean` as a 4-byte Windows BOOL by default — every
        // bool field shifts subsequent offsets by 3, breaking layout
        // for any struct that holds one (AzTitlebarButtons, AzAppConfig,
        // AzWindowFlags, ...). Use `byte` for FFI struct fields and
        // expose `isXxx()` / `setXxx(boolean)` helpers in the idiomatic
        // wrapper layer.
        "bool" => "byte".to_string(),
        "u8" | "c_uchar" | "char" | "i8" | "c_char" => "byte".to_string(),
        "u16" | "i16" => "short".to_string(),
        "u32" | "c_uint" | "i32" | "c_int" => "int".to_string(),
        "u64" | "i64" => "long".to_string(),
        "f32" => "float".to_string(),
        "f64" => "double".to_string(),
        // SKIPPED: usize/isize have no JVM-native sized integer; we
        // approximate as `long`. This is correct on every 64-bit
        // host, which is the only configuration JNA supports for the
        // azul runtime.
        "usize" | "isize" => "long".to_string(),
        "c_void" | "()" | "void" => "void".to_string(),

        // Az-prefixed types — refer to the generated Structure class.
        _ => {
            // Resolve simple type aliases (e.g. `GLuint = u32`) recursively
            // to their target type, so the Java field carries `int` rather
            // than `AzGLuint` (Java has no typedef syntax). Aliases with a
            // `monomorphized_def` ARE emitted as full Java types and we
            // keep the `Az<Name>` reference for those.
            if let Some(ta) = ir.find_type_alias(trimmed) {
                if ta.monomorphized_def.is_none() {
                    return map_jvm_type(&ta.target, ir);
                }
                return ffi_type_name(trimmed);
            }
            // Recursive struct/enum types can't be expanded inline (Java
            // structures laid out by JNA would loop infinitely on a
            // self-referential field). Collapse to `Pointer` — same
            // strategy the C header uses (forward-declared union).
            if let Some(s) = ir.find_struct(trimmed) {
                if matches!(s.category, super::super::ir::TypeCategory::Recursive) {
                    return "Pointer".to_string();
                }
                return ffi_type_name(trimmed);
            }
            if let Some(e) = ir.find_enum(trimmed) {
                if matches!(e.category, super::super::ir::TypeCategory::Recursive) {
                    return "Pointer".to_string();
                }
                if !e.is_union {
                    // Unit enums (C `enum X`) are 4 bytes (sizeof(int))
                    // in the C ABI. The codegen-emitted Java `public enum
                    // AzX` is a heap object, which JNA can't size in a
                    // struct field. Emit `int` for FFI struct fields;
                    // consumers can convert via `AzX.fromInt(...)`.
                    return "int".to_string();
                }
                return ffi_type_name(trimmed);
            }
            if ir.callback_typedefs.iter().any(|c| c.name == trimmed) {
                ffi_type_name(trimmed)
            } else {
                "Pointer".to_string()
            }
        }
    }
}

/// Like [`map_jvm_type`] but returns the `.ByValue` form when the
/// target is a generated FFI Structure (struct or tagged-union enum).
/// Java `public enum` types don't have a `.ByValue` inner class, so
/// they pass through unchanged. Used for fields/return values whose
/// ABI is "struct by value".
pub fn map_jvm_type_byvalue(rust_type: &str, ir: &CodegenIR) -> String {
    let raw = map_jvm_type(rust_type, ir);
    if !raw.starts_with("Az") {
        return raw;
    }
    // Strip the `Az` prefix to match the IR type-name lookup.
    let unprefixed = raw.strip_prefix("Az").unwrap_or(&raw);
    // Tagged-union enums emit a Structure-flavoured class — they take
    // `.ByValue`. Plain unit enums emit a Java `public enum` — no
    // `.ByValue`. Structs (POD or otherwise) take `.ByValue`. Callback
    // typedefs are JNA `Callback` *interfaces* — no `.ByValue` either;
    // they're passed as the interface type directly.
    let is_unit_enum = ir
        .find_enum(unprefixed)
        .map(|e| !e.is_union)
        .unwrap_or(false);
    let is_callback_typedef = ir
        .callback_typedefs
        .iter()
        .any(|c| c.name == unprefixed);
    if is_unit_enum || is_callback_typedef {
        raw
    } else {
        format!("{}.ByValue", raw)
    }
}

/// Sanitise a name for use as a Java identifier. Java reserved words
/// get an underscore suffix. (Java has no verbatim-identifier syntax.)
pub fn sanitize_identifier(name: &str) -> String {
    if is_java_reserved(name) {
        format!("{}_", name)
    } else {
        name.to_string()
    }
}

/// Check if a name collides with a Java reserved word, contextual
/// keyword, or built-in literal.
pub fn is_java_reserved(name: &str) -> bool {
    matches!(
        name,
        "abstract"
            | "assert"
            | "boolean"
            | "break"
            | "byte"
            | "case"
            | "catch"
            | "char"
            | "class"
            | "const"
            | "continue"
            | "default"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "extends"
            | "final"
            | "finally"
            | "float"
            | "for"
            | "goto"
            | "if"
            | "implements"
            | "import"
            | "instanceof"
            | "int"
            | "interface"
            | "long"
            | "native"
            | "new"
            | "null"
            | "package"
            | "private"
            | "protected"
            | "public"
            | "return"
            | "short"
            | "static"
            | "strictfp"
            | "super"
            | "switch"
            | "synchronized"
            | "this"
            | "throw"
            | "throws"
            | "transient"
            | "true"
            | "false"
            | "try"
            | "void"
            | "volatile"
            | "while"
            | "yield"
            | "record"
            | "sealed"
            | "permits"
            | "var"
    )
}

/// Convert a snake_case name to lowerCamelCase for Java method names.
pub fn snake_to_lower_camel(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper = false;
    let mut first = true;
    for c in s.chars() {
        if c == '_' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else if first {
            out.extend(c.to_lowercase());
            first = false;
        } else {
            out.push(c);
        }
    }
    out
}
