//! PHP (built-in `FFI` extension) binding generator.
//!
//! Emits a single `Azul.php` source file. The generated file has three
//! layers, top-to-bottom:
//!
//! 1. A `<<<CDEF ... CDEF;` heredoc carrying the entire `azul.h` payload
//!    with C preprocessor directives stripped via the existing helper
//!    [`super::lang_lua::cdef::strip_for_cdef`]. PHP's FFI parser is
//!    structurally identical to LuaJIT's: it accepts plain C declarations
//!    but rejects preprocessor directives and `extern "C"` blocks. We
//!    therefore reuse the LuaJIT stripper verbatim instead of forking it.
//! 2. A `final class Azul` static facade exposing `Azul::$ffi` plus a
//!    `Azul::lib()` accessor that lazily calls `FFI::cdef($cdef, libname)`
//!    where `libname` is platform-resolved (`libazul.so` / `.dylib` /
//!    `azul.dll`).
//! 3. Idiomatic wrapper classes — one per FFI struct/tagged-union enum
//!    that has a `_delete` C function, plus per-variant predicates and
//!    payload extractors for tagged unions. See
//!    [`wrappers::generate_wrappers`].
//!
//! ## PHP version requirement
//!
//! Requires **PHP 7.4 or newer** with the `ffi` extension enabled
//! (`ffi.enable=true` in `php.ini`, or `ffi.enable=preload` for OPcache
//! preloading). The generated file emits a runtime guard.
//!
//! ## Cross-module call to the C generator
//!
//! Mirrors `lang_lua::generate`: we obtain the cdef payload by calling
//! the production C-header generator with the standard `c_header`
//! configuration, then piping the result through
//! `lang_lua::cdef::strip_for_cdef`. This guarantees the PHP cdef stays
//! in lockstep with `azul.h`.

pub mod composer;
pub mod wrappers;

use anyhow::Result;

use super::config::CodegenConfig;
use super::generator::{CodeBuilder, LanguageGenerator};
use super::ir::CodegenIR;
use super::lang_c::CGenerator;

/// Generate the full `Azul.php` source file.
///
/// `config` is currently unused for output shaping (PHP bindings have
/// no per-target dialects), but is taken by reference to match the
/// signatures of other language entry points.
pub fn generate(ir: &CodegenIR, _config: &CodegenConfig) -> Result<String> {
    // 1. Run the production C-header generator and strip preprocessor
    //    directives so the result is acceptable inside FFI::cdef().
    //    We reuse the LuaJIT stripper because PHP's FFI parser shares
    //    the same restrictions (no #include / #ifdef / extern "C").
    let c_config = CodegenConfig::c_header();
    let c_header = CGenerator.generate(ir, &c_config)?;
    let cdef_payload = super::lang_lua::cdef::strip_for_cdef(&c_header);

    // 2. Build the PHP source.
    let mut builder = CodeBuilder::new("    ");

    // Header banner
    builder.line("<?php");
    builder.line("// ============================================================================");
    builder.line("// Auto-generated PHP bindings for the Azul GUI framework.");
    builder.line("// Generated by azul-doc codegen v2 (lang_php).");
    builder.line("// DO NOT EDIT MANUALLY.");
    builder.line("//");
    builder.line("// Requirements:");
    builder.line("//   * PHP >= 7.4");
    builder.line("//   * The `ffi` extension must be enabled. Set one of the following in");
    builder.line("//     your `php.ini`:");
    builder.line("//");
    builder.line("//         ffi.enable=true        ; works in CLI and (when permitted) in CGI/FPM");
    builder.line("//         ffi.enable=preload     ; OPcache preloading only — recommended for FPM");
    builder.line("//");
    builder.line("//   * The native shared library (`libazul.so` / `libazul.dylib` /");
    builder.line("//     `azul.dll`) must be on the dynamic loader's search path or in the");
    builder.line("//     current working directory.");
    builder.line("// ============================================================================");
    builder.blank();

    builder.line("declare(strict_types=1);");
    builder.blank();

    builder.line("namespace Azul;");
    builder.blank();

    builder.line("use FFI;");
    builder.line("use FFI\\CData;");
    builder.blank();

    // Runtime guard: the FFI extension must be loaded.
    builder.line("if (!\\extension_loaded('ffi')) {");
    builder.indent();
    builder.line("throw new \\RuntimeException(");
    builder.indent();
    builder.line(
        "'Azul.php requires the PHP FFI extension. Install php-ffi and set ffi.enable=true in php.ini.'",
    );
    builder.dedent();
    builder.line(");");
    builder.dedent();
    builder.line("}");
    builder.blank();

    // ------------------------------------------------------------------
    // Static facade class. Holds the lazy-initialised FFI instance and
    // exposes the cdef heredoc as a private constant.
    // ------------------------------------------------------------------
    builder.line("/**");
    builder.line(" * Static facade around the loaded `azul` shared library.");
    builder.line(" *");
    builder.line(" * Use `Azul::lib()` (or `Azul::$ffi` after the first call) to access the");
    builder.line(" * raw FFI object. Idiomatic per-type wrapper classes live in this same");
    builder.line(" * namespace and dispatch through `Azul::lib()` internally.");
    builder.line(" */");
    builder.line("final class Azul");
    builder.line("{");
    builder.indent();

    builder.line("/** @var FFI|null */");
    builder.line("public static ?FFI $ffi = null;");
    builder.blank();

    // Private cdef constant. We use a heredoc so the embedded C source
    // does not need any escaping. The CDEF terminator must appear on its
    // own line, unindented, per PHP heredoc rules.
    builder.line("/**");
    builder.line(" * The full C declarations passed to FFI::cdef(). Generated from azul.h");
    builder.line(" * with C preprocessor directives stripped (see lang_lua::cdef).");
    builder.line(" */");
    builder.line("private const CDEF = <<<'CDEF'");
    // Emit the payload verbatim. The CDEF marker must start at column 0,
    // and so must the closing `CDEF;` — the payload itself is left
    // unindented because PHP's heredoc does not understand language-level
    // indentation here.
    builder.raw(&cdef_payload);
    if !cdef_payload.ends_with('\n') {
        builder.raw("\n");
    }
    builder.raw("CDEF;\n");
    builder.blank();

    // Library path resolver — mirrors how other bindings (csharp, lua)
    // pick the platform-specific filename.
    builder.line("/**");
    builder.line(" * Resolve the platform-appropriate shared-library filename.");
    builder.line(" *");
    builder.line(" * @return string `azul.dll` on Windows, `libazul.dylib` on macOS, `libazul.so`");
    builder.line(" *                everywhere else.");
    builder.line(" */");
    builder.line("public static function libraryName(): string");
    builder.line("{");
    builder.indent();
    builder.line("$os = \\PHP_OS_FAMILY;");
    builder.line("if ($os === 'Windows') {");
    builder.indent();
    builder.line("return 'azul.dll';");
    builder.dedent();
    builder.line("}");
    builder.line("if ($os === 'Darwin') {");
    builder.indent();
    builder.line("return 'libazul.dylib';");
    builder.dedent();
    builder.line("}");
    builder.line("return 'libazul.so';");
    builder.dedent();
    builder.line("}");
    builder.blank();

    // Lazy library loader.
    builder.line("/**");
    builder.line(" * Lazily load (or return the cached) FFI handle for libazul.");
    builder.line(" *");
    builder.line(" * Subsequent calls reuse the same FFI instance. The C declarations are");
    builder.line(" * parsed exactly once.");
    builder.line(" *");
    builder.line(" * @return FFI");
    builder.line(" */");
    builder.line("public static function lib(): FFI");
    builder.line("{");
    builder.indent();
    builder.line("if (self::$ffi === null) {");
    builder.indent();
    builder.line("self::$ffi = FFI::cdef(self::CDEF, self::libraryName());");
    builder.dedent();
    builder.line("}");
    builder.line("return self::$ffi;");
    builder.dedent();
    builder.line("}");
    builder.blank();

    // Expose the raw cdef text — useful for debugging / OPcache preload.
    builder.line("/**");
    builder.line(" * Return the raw C declarations passed to FFI::cdef().");
    builder.line(" *");
    builder.line(" * Useful for OPcache preloading scenarios where the user wants to");
    builder.line(" * supply their own `FFI::load(...)` invocation against a pre-generated");
    builder.line(" * `.h` file rather than re-parsing the cdef on each request.");
    builder.line(" *");
    builder.line(" * @return string");
    builder.line(" */");
    builder.line("public static function cdef(): string");
    builder.line("{");
    builder.indent();
    builder.line("return self::CDEF;");
    builder.dedent();
    builder.line("}");

    builder.dedent();
    builder.line("}");
    builder.blank();

    // ------------------------------------------------------------------
    // Idiomatic wrapper classes (one per disposable type / tagged union).
    // ------------------------------------------------------------------
    builder.raw(&wrappers::generate_wrappers(ir));

    Ok(builder.finish())
}
