//! Azul DLL - C API bindings for the Azul GUI framework
//!
//! This crate provides the C-ABI functions for the Azul library.
//! The API is auto-generated from api.json using `azul-doc codegen all`.
//!
//! To regenerate all bindings:
//!   cd doc && cargo run --release -- codegen all
//!
//! ## Feature Flags
//!
//! ### Build Modes
//! - `build-dll`: Build the shared library (libazul.dylib/so/dll) with C-API exports
//!
//! ### Link Modes (for consumers)
//! - `link-static`: Statically link Azul (types + trait impls via transmute)
//! - `link-dynamic`: Dynamically link against libazul.dylib/so/dll (extern "C" calls)
//!
//! These link modes are mutually exclusive. If neither is enabled, only the
//! desktop module is exported as a regular Rust library.

#![deny(improper_ctypes_definitions)]
#![allow(unused_imports)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

#[macro_use]
extern crate alloc;

// Internal crates - only needed for build-dll and link-static
#[cfg(any(feature = "build-dll", feature = "link-static"))]
extern crate azul_core;
#[cfg(any(feature = "build-dll", feature = "link-static"))]
extern crate azul_css;
#[cfg(any(feature = "build-dll", feature = "link-static"))]
extern crate azul_layout;

// Desktop windowing implementation (OpenGL, fonts, event loop, etc.)
// Compiled for both build-dll AND link-static (only link-dynamic excludes it)
#[cfg(all(
    any(feature = "build-dll", feature = "link-static"),
    not(target_arch = "wasm32")
))]
pub mod desktop;

// =============================================================================
// Build DLL: Include C-API functions with #[no_mangle] for export
// This is used when building libazul.dylib/so/dll
// Generated by: cd doc && cargo run --release -- codegen all
// =============================================================================

#[cfg(feature = "build-dll")]
mod __ffi_build {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../target/codegen/v2/dll_api_build.rs"
    ));
}

#[cfg(feature = "build-dll")]
pub use __ffi_build::__dll_api_inner::dll;

#[cfg(feature = "build-dll")]
pub mod ffi {
    pub use crate::__ffi_build::__dll_api_inner::*;
}

// =============================================================================
// Static Linking: Types + trait impls via transmute (NO C-API functions)
// This is used when statically linking Azul into your Rust application
// Generated by: cd doc && cargo run --release -- codegen all
// =============================================================================

#[cfg(all(feature = "link-static", not(feature = "build-dll")))]
mod __ffi_static {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../target/codegen/v2/dll_api_static.rs"
    ));
}

#[cfg(all(feature = "link-static", not(feature = "build-dll")))]
pub use __ffi_static::__dll_api_inner::dll;

#[cfg(all(feature = "link-static", not(feature = "build-dll")))]
pub mod ffi {
    pub use crate::__ffi_static::__dll_api_inner::*;
}

// =============================================================================
// Dynamic Linking: Types + extern "C" declarations
// This is used when linking against a pre-built libazul.dylib/so/dll
// Generated by: cd doc && cargo run --release -- codegen all
// =============================================================================

#[cfg(all(
    feature = "link-dynamic",
    not(feature = "link-static"),
    not(feature = "build-dll")
))]
mod __ffi_dynamic {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../target/codegen/v2/dll_api_dynamic.rs"
    ));
}

#[cfg(all(
    feature = "link-dynamic",
    not(feature = "link-static"),
    not(feature = "build-dll")
))]
pub use __ffi_dynamic::__dll_api_inner::dll;

#[cfg(all(
    feature = "link-dynamic",
    not(feature = "link-static"),
    not(feature = "build-dll")
))]
pub mod ffi {
    pub use crate::__ffi_dynamic::__dll_api_inner::*;
}

// =============================================================================
// Public Rust API: Re-exports without Az prefix
// Generated by: cd doc && cargo run --release -- codegen all
//
// This provides a nice Rust API:
//   use azul::prelude::*;
//   use azul::app::App;
//   use azul::dom::Dom;
// =============================================================================

#[cfg(any(
    feature = "link-static",
    feature = "link-dynamic",
    feature = "build-dll"
))]
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../target/codegen/v2/reexports.rs"
));

// =============================================================================
// Python Extension Module
// Generated by: cd doc && cargo run --release -- codegen all
// =============================================================================

#[cfg(feature = "python-extension")]
mod python {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../target/codegen/v2/python_api.rs"
    ));
}

// Re-export the pymodule function at crate root for PyInit_azul to work
#[cfg(feature = "python-extension")]
pub use python::azul;

// =============================================================================
// Memory Tests: Size and alignment verification
// Generated by: cd doc && cargo run --release -- codegen all
// Run with: cd dll && cargo test
// =============================================================================

#[cfg(test)]
mod memtest {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../target/codegen/v2/memtest.rs"
    ));
}
