//! PHP extension entry point (feature `php-extension`).
//!
//! Built as a Zend-engine native extension via the `ext-php-rs` crate.
//! Unlike the standard php-ffi path (which rejects closure-to-fnpointer
//! by design), the Zend engine supports calling back into PHP from a C
//! function pointer pinned at extension-load time. This unblocks the
//! host-invoker pattern that all the other managed-FFI hosts use.
//!
//! ## Building
//!
//! ```sh
//! cargo build --release --features php-extension
//! # The resulting libazul.dylib (macOS) / libazul.so (Linux) is the
//! # PHP extension binary. Load it via:
//! php -d extension=/path/to/libazul.dylib hello-world.php
//! ```
//!
//! ## Surface
//!
//! Today this is a minimal scaffolding extension that proves the
//! toolchain wiring works. It exposes one PHP function,
//! `azul_version()`, returning the crate version string.
//!
//! ## Build prerequisites
//!
//! 1. **`LIBCLANG_PATH` + `DYLD_FALLBACK_LIBRARY_PATH`** — ext-php-rs's
//!    build script links against `libclang.dylib`. On macOS set:
//!    `LIBCLANG_PATH=/Library/Developer/CommandLineTools/usr/lib`
//!    and `DYLD_FALLBACK_LIBRARY_PATH=$LIBCLANG_PATH` (the second is
//!    required because the build-script binary itself dlopens
//!    libclang at runtime via its @rpath).
//! 2. **Dynamic linker flags for Zend symbols** — PHP's runtime
//!    provides `zend_*` symbols at extension-load time, not link
//!    time. On macOS pass:
//!    `RUSTFLAGS="-C link-arg=-undefined -C link-arg=dynamic_lookup"`.
//!    On Linux pass
//!    `RUSTFLAGS="-C link-arg=-Wl,--unresolved-symbols=ignore-in-object-files"`.
//!
//! Full invocation:
//!
//! ```sh
//! LIBCLANG_PATH=/Library/Developer/CommandLineTools/usr/lib \
//! DYLD_FALLBACK_LIBRARY_PATH=$LIBCLANG_PATH \
//! RUSTFLAGS="-C link-arg=-undefined -C link-arg=dynamic_lookup" \
//!   cargo build --release -p azul-dll --features php-extension
//! ```
//!
//! The full host-invoker surface (`azul_refany_create`,
//! `azul_register_callback`, the Dom builders, App::run) lives in
//! `target/codegen/php_api.rs` generated by `azul-doc codegen all`
//! — same pattern Python uses through `python_api.rs`. The codegen
//! pass for PHP isn't written yet; until it lands, this file
//! documents the path forward and keeps the feature flag green.

use std::collections::HashMap;
use std::sync::Mutex;

use ext_php_rs::prelude::*;
use once_cell::sync::Lazy;

// ----------------------------------------------------------------------------
// libazul host-invoker C-ABI (statically linked in via build-dll)
// ----------------------------------------------------------------------------

// libazul C-ABI host-invoker symbols live in the same .dylib (we ARE
// libazul under feature `php-extension`) — they're exported by
// target/codegen/dll_api_internal.rs via `#[no_mangle] extern "C"`.
// Cross-call by referring to them as extern "C" symbols without a
// `#[link]` directive (no separate link target).
extern "C" {
    fn AzApp_setHostHandleReleaser(
        releaser: Option<unsafe extern "C" fn(id: u64)>,
    );
    /// Returns the host-handle id previously stored in `refany`.
    fn AzRefAny_getHostHandle(refany: *const std::ffi::c_void) -> u64;
}

// ----------------------------------------------------------------------------
// PHP-side handle table
// ----------------------------------------------------------------------------

/// Persistent handle table mapping the host-handle id libazul stamps
/// onto its `AzRefAny`s to a JSON-encoded snapshot of the user's PHP
/// value. We store JSON (not a raw `Zval`) so the value can outlive
/// the original request — Zvals are GC-rooted in the executor's call
/// frame and would leak or dangle if held across requests.
static HANDLES: Lazy<Mutex<HashMap<u64, String>>> = Lazy::new(|| Mutex::new(HashMap::new()));
static NEXT_HANDLE_ID: Lazy<Mutex<u64>> = Lazy::new(|| Mutex::new(0));

unsafe extern "C" fn host_handle_releaser(id: u64) {
    if let Ok(mut tbl) = HANDLES.lock() {
        tbl.remove(&id);
    }
}

// ----------------------------------------------------------------------------
// PHP-exposed functions
// ----------------------------------------------------------------------------

/// PHP function: `azul_version() : string`.
///
/// Smoke test for the extension load path. Returning a literal here
/// instead of `env!("CARGO_PKG_VERSION")` keeps the string lifetime
/// trivial.
#[php_function]
pub fn azul_version() -> &'static str {
    "0.0.7"
}

/// PHP function: `azul_refany_create(string $json_value) : int`.
///
/// Allocates a host-handle id for `$json_value` and returns the id.
/// PHP callers should pass `json_encode($value)`; recovery via
/// `azul_refany_get` returns the JSON string for the caller to
/// `json_decode`. This sidesteps the Zval-lifetime problem until the
/// full codegen pass surfaces a real `Azul\RefAny` class.
#[php_function]
pub fn azul_refany_create(value: String) -> u64 {
    let mut next = NEXT_HANDLE_ID.lock().unwrap();
    *next += 1;
    let id = *next;
    HANDLES.lock().unwrap().insert(id, value);
    id
}

/// PHP function: `azul_refany_get(int $id) : ?string`.
///
/// Returns the JSON snapshot previously stored under `$id`, or null
/// if the id is unknown / has been released.
#[php_function]
pub fn azul_refany_get(id: u64) -> Option<String> {
    HANDLES.lock().unwrap().get(&id).cloned()
}

/// PHP function: `azul_host_invoker_init() : void`.
///
/// Idempotent — installs the releaser callback with libazul. Tests
/// confirm libazul's destructor fires the releaser on RefAny clone
/// drop; the handle table entry vanishes immediately afterwards.
#[php_function]
pub fn azul_host_invoker_init() {
    unsafe {
        AzApp_setHostHandleReleaser(Some(host_handle_releaser));
    }
}

#[php_module]
pub fn get_module(module: ModuleBuilder) -> ModuleBuilder {
    // The `#[php_function]` macro alone declares the function but
    // doesn't register it; the module builder needs an explicit
    // `wrap_function!` call per function. Without this PHP loads the
    // extension successfully but `get_extension_funcs('azul-dll')`
    // returns an empty array.
    module
        .function(wrap_function!(azul_version))
        .function(wrap_function!(azul_refany_create))
        .function(wrap_function!(azul_refany_get))
        .function(wrap_function!(azul_host_invoker_init))
}
