//! LuaJIT FFI binding generator.
//!
//! Emits a single `azul.lua` source file that exposes the C-ABI of
//! `libazul` to LuaJIT scripts via the built-in `ffi` module. The
//! generated file has three layers, top-to-bottom:
//!
//! 1. `ffi.cdef[[ ... ]]` — the entire `azul.h` payload, with C
//!    preprocessor directives stripped (see [`cdef::strip_for_cdef`]).
//! 2. `local C = ffi.load('azul')` — load the native library.
//! 3. Idiomatic wrappers — methods tables + metatypes + an `azul`
//!    namespace where method names drop the `Az<TypeName>_` prefix
//!    (see [`wrappers::generate_wrappers`]).
//!
//! ## LuaJIT-only
//!
//! PUC Lua does not ship the FFI module. The generated file requires
//! LuaJIT 2.0+ and emits a runtime check.
//!
//! ## Cross-module call to the C generator
//!
//! We obtain the cdef payload by calling the production C-header
//! generator with the standard `c_header` configuration, then piping
//! the result through `strip_for_cdef`. This guarantees the LuaJIT
//! cdef stays in lockstep with `azul.h`.

pub mod cdef;
pub mod managed;
pub mod rockspec;
pub mod wrappers;

use anyhow::Result;

use super::config::CodegenConfig;
use super::generator::{CodeBuilder, LanguageGenerator};
use super::ir::CodegenIR;
use super::lang_c::CGenerator;

/// Generate the full `azul.lua` source file.
///
/// `config` is currently unused for output shaping (LuaJIT bindings have
/// no per-target dialects), but is taken by reference to match the
/// signatures of other language entry points and so future configuration
/// hooks can be threaded through without breaking callers.
pub fn generate(ir: &CodegenIR, _config: &CodegenConfig) -> Result<String> {
    // 1. Run the production C-header generator and strip preprocessor
    //    directives so the result is acceptable inside `ffi.cdef[[...]]`.
    let c_config = CodegenConfig::c_header();
    let c_header = CGenerator.generate(ir, &c_config)?;
    let cdef_payload = cdef::strip_for_cdef(&c_header);

    // 2. Build the Lua source.
    let mut builder = CodeBuilder::new("    ");

    builder.line("-- azul.lua — LuaJIT bindings for the Azul GUI framework");
    builder.line("-- WARNING: autogenerated by azul-doc codegen v2 — DO NOT EDIT");
    builder.line("--");
    builder.line("-- LuaJIT-only: requires the `ffi` module which is NOT part of");
    builder.line("-- standard PUC Lua. Use LuaJIT 2.0 or newer.");
    builder.blank();

    // Runtime guard: bail out clearly if loaded under stock Lua.
    builder.line("if not jit then");
    builder.line("    error('azul.lua requires LuaJIT (the `ffi` module is not available in standard Lua)')");
    builder.line("end");
    builder.blank();

    builder.line("local ffi = require('ffi')");
    builder.blank();

    // 3. cdef block.
    builder.line("ffi.cdef[[");
    // Emit the payload verbatim (it already contains its own newlines).
    builder.raw(&cdef_payload);
    if !cdef_payload.ends_with('\n') {
        builder.raw("\n");
    }
    builder.line("]]");
    builder.blank();

    // 4. Load the native library. `ffi.load` resolves
    //    libazul.so / libazul.dylib / azul.dll automatically across
    //    platforms.
    builder.line("local C = ffi.load('azul')");
    builder.blank();

    // 5. Public namespace table.
    builder.line("local azul = {}");
    builder.line("-- Re-export the raw C-ABI table for power users / advanced FFI casts.");
    builder.line("azul.C = C");
    builder.blank();

    // 6. Managed-FFI prelude: per-kind invoker registrations + RefAny
    //    user-data store. Must be emitted before the wrappers because
    //    wrapper methods reference `azul._register_callback(...)` for
    //    callback-typed arguments. The prelude is data-driven from the
    //    IR so adding a new callback kind to api.json contributes one
    //    cdef + one libffi closure registration automatically.
    let mut managed_buf = String::new();
    managed::emit_managed_prelude(&mut managed_buf, ir);
    builder.raw(&managed_buf);

    // 7. Wrapper layer.
    builder.raw(&wrappers::generate_wrappers(ir));

    // 8. Postlude: ergonomic helpers that need to attach to wrapper tables
    //    after the wrappers have created them.
    //    - `azul.String.from_lua(s)` — explicit Lua-string → AzString.
    //    - `azul._az_string(v)` — auto-conversion helper used by the
    //      wrapper codegen for every Owned `String` arg, so plain Lua
    //      strings flow through `Dom.create_text("hi")` directly.
    builder.line("");
    builder.line("-- Postlude: convenience helpers that hang off generated wrappers.");
    builder.line("azul.String.from_lua = function(s)");
    builder.line("    -- User-facing factory: the CALLER owns the returned AzString.");
    builder.line("    -- LuaJIT's metatype __gc does NOT fire for by-value C returns, so");
    builder.line("    -- arm the finalizer explicitly — a dropped result then frees its");
    builder.line("    -- heap buffer. A consuming C call disarms it via azul._consume");
    builder.line("    -- (owned AzString args are always consumed by the C ABI).");
    builder.line("    return ffi.gc(C.AzString_copyFromBytes(");
    builder.line("        ffi.cast('const uint8_t*', s), 0, #s), C.AzString_delete)");
    builder.line("end");
    builder.blank();
    builder.line("-- Auto-AzString-conversion helper. Wrapper methods route every Owned");
    builder.line("-- `String` arg through this so user code can pass plain Lua strings");
    builder.line("-- directly. Idempotent for cdata/AzString values already passed in.");
    builder.line("--");
    builder.line("-- OWNERSHIP: the AzString produced here is a TRANSIENT that is always");
    builder.line("-- immediately consumed by the C call it feeds (owned by-value arg =");
    builder.line("-- consumed by the Az C ABI; Rust then owns the bytes). It must NOT be");
    builder.line("-- ffi.gc-armed: arming it would double-free the buffer Rust took over");
    builder.line("-- (once at the temp's __gc, once at the owning struct's _delete). The");
    builder.line("-- wrapper emitter still emits a defensive azul._consume on the temp,");
    builder.line("-- which is a harmless no-op while this stays unarmed.");
    builder.line("azul._az_string = function(v)");
    builder.line("    if v == nil then return v end");
    builder.line("    local t = type(v)");
    builder.line("    if t == 'string' then");
    builder.line("        return C.AzString_copyFromBytes(ffi.cast('const uint8_t*', v), 0, #v)");
    builder.line("    end");
    builder.line("    return v");
    builder.line("end");
    builder.blank();

    // CC-4: recursive opts-table applier — mirrors Ruby's `_apply_opts`
    // (commit fa0b5f06b) and Node's `_applyOpts` (commit 070a3c946).
    // Routed through every struct wrapper's `:with(opts)` method so users
    // can replace
    //   window.window_state.title = azul._az_string('Hello World')
    //   window.window_state.size.dimensions.width = 400.0
    //   …
    // with
    //   window:with({ window_state = { title = 'Hello World',
    //                  size = { dimensions = { width = 400.0 } } } })
    // The LuaJIT FFI lets us assign nested cdata struct fields directly
    // (`struct.field = value`); we only need to recurse into Lua tables
    // and auto-convert strings. cdata values (including wrapper
    // instances, numeric enum constants from `C.AzFoo_Variant`, and
    // numeric primitives) all fall through to direct assignment — the
    // FFI handles the byte-copy.
    builder.line("-- CC-4 recursive opts-table applier. Each struct wrapper's");
    builder.line("-- `:with(opts)` method routes through this. Lua strings auto-convert");
    builder.line("-- to AzString via `_az_string`; nested tables recurse; cdata values");
    builder.line("-- (wrapper instances, enum constants, numbers) direct-assign.");
    builder.line("azul._apply_opts = function(struct, opts)");
    // `opts` is always a plain Lua table; `not opts` is safe to falsy-
    // check. We deliberately do NOT check `struct == nil` because cdata
    // types with a `__eq` metamethod (Phase I.2.7) crash LuaJIT when
    // compared against a non-cdata `nil` — `__eq` is invoked with `nil`
    // as the second operand, which the C-side `_partialEq` dereferences.
    builder.line("    if not opts then return end");
    builder.line("    for k, v in pairs(opts) do");
    builder.line("        local t = type(v)");
    builder.line("        if t == 'string' then");
    builder.line("            struct[k] = azul._az_string(v)");
    builder.line("        elseif t == 'table' then");
    builder.line("            azul._apply_opts(struct[k], v)");
    builder.line("        else");
    builder.line("            struct[k] = v");
    builder.line("        end");
    builder.line("    end");
    builder.line("end");
    builder.blank();

    // 9. Trailer.
    builder.line("return azul");

    Ok(builder.finish())
}
