//! LuaJIT FFI binding generator.
//!
//! Emits a single `azul.lua` source file that exposes the C-ABI of
//! `libazul` to LuaJIT scripts via the built-in `ffi` module. The
//! generated file has three layers, top-to-bottom:
//!
//! 1. `ffi.cdef[[ ... ]]` — the entire `azul.h` payload, with C
//!    preprocessor directives stripped (see [`cdef::strip_for_cdef`]).
//! 2. `local C = ffi.load('azul')` — load the native library.
//! 3. Idiomatic wrappers — methods tables + metatypes + an `azul`
//!    namespace where method names drop the `Az<TypeName>_` prefix
//!    (see [`wrappers::generate_wrappers`]).
//!
//! ## LuaJIT-only
//!
//! PUC Lua does not ship the FFI module. The generated file requires
//! LuaJIT 2.0+ and emits a runtime check.
//!
//! ## Cross-module call to the C generator
//!
//! We obtain the cdef payload by calling the production C-header
//! generator with the standard `c_header` configuration, then piping
//! the result through `strip_for_cdef`. This guarantees the LuaJIT
//! cdef stays in lockstep with `azul.h`.

pub mod cdef;
pub mod rockspec;
pub mod wrappers;

use anyhow::Result;

use super::config::CodegenConfig;
use super::generator::{CodeBuilder, LanguageGenerator};
use super::ir::CodegenIR;
use super::lang_c::CGenerator;

/// Generate the full `azul.lua` source file.
///
/// `config` is currently unused for output shaping (LuaJIT bindings have
/// no per-target dialects), but is taken by reference to match the
/// signatures of other language entry points and so future configuration
/// hooks can be threaded through without breaking callers.
pub fn generate(ir: &CodegenIR, _config: &CodegenConfig) -> Result<String> {
    // 1. Run the production C-header generator and strip preprocessor
    //    directives so the result is acceptable inside `ffi.cdef[[...]]`.
    let c_config = CodegenConfig::c_header();
    let c_header = CGenerator.generate(ir, &c_config)?;
    let cdef_payload = cdef::strip_for_cdef(&c_header);

    // 2. Build the Lua source.
    let mut builder = CodeBuilder::new("    ");

    builder.line("-- azul.lua — LuaJIT bindings for the Azul GUI framework");
    builder.line("-- WARNING: autogenerated by azul-doc codegen v2 — DO NOT EDIT");
    builder.line("--");
    builder.line("-- LuaJIT-only: requires the `ffi` module which is NOT part of");
    builder.line("-- standard PUC Lua. Use LuaJIT 2.0 or newer.");
    builder.blank();

    // Runtime guard: bail out clearly if loaded under stock Lua.
    builder.line("if not jit then");
    builder.line("    error('azul.lua requires LuaJIT (the `ffi` module is not available in standard Lua)')");
    builder.line("end");
    builder.blank();

    builder.line("local ffi = require('ffi')");
    builder.blank();

    // 3. cdef block.
    builder.line("ffi.cdef[[");
    // Emit the payload verbatim (it already contains its own newlines).
    builder.raw(&cdef_payload);
    if !cdef_payload.ends_with('\n') {
        builder.raw("\n");
    }
    builder.line("]]");
    builder.blank();

    // 4. Load the native library. `ffi.load` resolves
    //    libazul.so / libazul.dylib / azul.dll automatically across
    //    platforms.
    builder.line("local C = ffi.load('azul')");
    builder.blank();

    // 5. Public namespace table.
    builder.line("local azul = {}");
    builder.line("-- Re-export the raw C-ABI table for power users / advanced FFI casts.");
    builder.line("azul.C = C");
    builder.blank();

    // 6. Wrapper layer.
    builder.raw(&wrappers::generate_wrappers(ir));

    // 7. Trailer.
    builder.line("return azul");

    Ok(builder.finish())
}
