// Generated by azul-css codegen (Odin). Do not edit by hand.
package main

import azul "azul"

// CSS: .__azul-native-button:hover, .__azul-native-button:active, .__azul-native-button:focus, .__azul-native-button:hover (conditional), .__azul-native-button:active (conditional), .__azul-native-button:focus (conditional)
style_azul_native_button :: proc() -> azul.AzCssPropertyWithConditionsVec {
	return azul.AzCssPropertyWithConditionsVec_copyFromPtr(&[]azul.AzCssPropertyWithConditions{
		azul.AzCssPropertyWithConditions_onHover(azul.AzCssProperty_backgroundContent(azul.AzStyleBackgroundContentVec_copyFromPtr(&[]azul.AzStyleBackgroundContent{azul.AzStyleBackgroundContent_color(azul.AzColorU{r = 241, g = 243, b = 245, a = 255})}[0], 1))),
		azul.AzCssPropertyWithConditions_onHover(azul.AzCssProperty_borderTopColor(azul.AzStyleBorderTopColor{inner = azul.AzColorU{r = 173, g = 181, b = 189, a = 255}})),
		azul.AzCssPropertyWithConditions_onHover(azul.AzCssProperty_borderBottomColor(azul.AzStyleBorderBottomColor{inner = azul.AzColorU{r = 173, g = 181, b = 189, a = 255}})),
		azul.AzCssPropertyWithConditions_onHover(azul.AzCssProperty_borderLeftColor(azul.AzStyleBorderLeftColor{inner = azul.AzColorU{r = 173, g = 181, b = 189, a = 255}})),
		azul.AzCssPropertyWithConditions_onHover(azul.AzCssProperty_borderRightColor(azul.AzStyleBorderRightColor{inner = azul.AzColorU{r = 173, g = 181, b = 189, a = 255}})),
		azul.AzCssPropertyWithConditions_onActive(azul.AzCssProperty_backgroundContent(azul.AzStyleBackgroundContentVec_copyFromPtr(&[]azul.AzStyleBackgroundContent{azul.AzStyleBackgroundContent_color(azul.AzColorU{r = 222, g = 226, b = 230, a = 255})}[0], 1))),
		azul.AzCssPropertyWithConditions_onFocus(azul.AzCssProperty_borderTopColor(azul.AzStyleBorderTopColor{inner = azul.AzColorU{r = 13, g = 110, b = 253, a = 255}})),
		azul.AzCssPropertyWithConditions_onFocus(azul.AzCssProperty_borderBottomColor(azul.AzStyleBorderBottomColor{inner = azul.AzColorU{r = 13, g = 110, b = 253, a = 255}})),
		azul.AzCssPropertyWithConditions_onFocus(azul.AzCssProperty_borderLeftColor(azul.AzStyleBorderLeftColor{inner = azul.AzColorU{r = 13, g = 110, b = 253, a = 255}})),
		azul.AzCssPropertyWithConditions_onFocus(azul.AzCssProperty_borderRightColor(azul.AzStyleBorderRightColor{inner = azul.AzColorU{r = 13, g = 110, b = 253, a = 255}})),
		azul.AzCssPropertyWithConditions_withConditions(
			azul.AzCssProperty_backgroundContent(azul.AzStyleBackgroundContentVec_copyFromPtr(&[]azul.AzStyleBackgroundContent{azul.AzStyleBackgroundContent_color(azul.AzColorU{r = 73, g = 80, b = 87, a = 255})}[0], 1)),
			azul.AzDynamicSelectorVec_copyFromPtr(&[]azul.AzDynamicSelector{
				azul.AzDynamicSelector_pseudoState(azul.AzPseudoStateType.Hover),
				azul.AzDynamicSelector_mode(azul.AzModeCondition.Dark),
			}[0], 2)
		),
		azul.AzCssPropertyWithConditions_withConditions(
			azul.AzCssProperty_borderTopColor(azul.AzStyleBorderTopColor{inner = azul.AzColorU{r = 73, g = 80, b = 87, a = 255}}),
			azul.AzDynamicSelectorVec_copyFromPtr(&[]azul.AzDynamicSelector{
				azul.AzDynamicSelector_pseudoState(azul.AzPseudoStateType.Hover),
				azul.AzDynamicSelector_mode(azul.AzModeCondition.Dark),
			}[0], 2)
		),
		azul.AzCssPropertyWithConditions_withConditions(
			azul.AzCssProperty_backgroundContent(azul.AzStyleBackgroundContentVec_copyFromPtr(&[]azul.AzStyleBackgroundContent{azul.AzStyleBackgroundContent_color(azul.AzColorU{r = 43, g = 48, b = 53, a = 255})}[0], 1)),
			azul.AzDynamicSelectorVec_copyFromPtr(&[]azul.AzDynamicSelector{
				azul.AzDynamicSelector_pseudoState(azul.AzPseudoStateType.Active),
				azul.AzDynamicSelector_mode(azul.AzModeCondition.Dark),
			}[0], 2)
		),
		azul.AzCssPropertyWithConditions_withConditions(
			azul.AzCssProperty_borderTopColor(azul.AzStyleBorderTopColor{inner = azul.AzColorU{r = 59, g = 130, b = 246, a = 255}}),
			azul.AzDynamicSelectorVec_copyFromPtr(&[]azul.AzDynamicSelector{
				azul.AzDynamicSelector_pseudoState(azul.AzPseudoStateType.Focus),
				azul.AzDynamicSelector_mode(azul.AzModeCondition.Dark),
			}[0], 2)
		),
	}[0], 14)
}
