>>SOURCE FORMAT IS FREE
*> Generated by azul-css codegen (COBOL). Do not edit by hand.
*> One subprogram per style: CALL "<PROGRAM-ID>" USING BY REFERENCE <result record>.

*> RENDER-CARD: not expressible with the COBOL bindings: the copybook's records are packed (no SYNC or FILLER), so an AzDom record is smaller than the C struct `AzDom_withChildByref` writes into it (its AzDomVec ends in a 1-byte FLAGS-X without the C padding), and COBOL cannot define the C function an app's layout callback must be
