>>SOURCE FORMAT IS FREE
*> Generated by azul-css codegen (COBOL). Do not edit by hand.
*> One subprogram per style: CALL "<PROGRAM-ID>" USING BY REFERENCE <result record>.

*> dropped `text-shadow: 1px 1px 2px`: CssProperty::TextShadow holds a BoxOrStaticStyleBoxShadow (a pointer wrapper) and api.json has no constructor for it
*> dropped a value these bindings cannot build: the COBOL copybook gives `CssProperty` only a raw TAG + PAYLOAD-ANCHOR record (no constructor, no payload layout)
*> dropped a value these bindings cannot build: the COBOL copybook gives `CaretWidthValue` only a raw TAG + PAYLOAD-ANCHOR record (no constructor, no payload layout)
IDENTIFICATION DIVISION.
PROGRAM-ID. KEYWORDS.
DATA DIVISION.
WORKING-STORAGE SECTION.
COPY "azul.cpy".
01  t1 USAGE TYAZ-CSS-PROPERTY.
01  t2 USAGE TYAZ-CSS-PROPERTY-WITH-CO-b793.
01  t3 USAGE TYAZ-CSS-PROPERTY.
01  t4 USAGE TYAZ-CSS-PROPERTY-WITH-CO-b793.
01  t5.
    05  t5-item USAGE TYAZ-CSS-PROPERTY-WITH-CO-b793 OCCURS 2 TIMES.
01  t6 USAGE BINARY-DOUBLE UNSIGNED VALUE 2.
01  t7 USAGE TYAZ-CSS-PROPERTY-WITH-CO-8550.
LINKAGE SECTION.
01  ls-result USAGE TYAZ-CSS-PROPERTY-WITH-CO-8550.
PROCEDURE DIVISION USING ls-result.
    CALL "AzCssProperty_autoByref" USING BY REFERENCE t1 BY VALUE AZ-CSS-PROPERTY-TYPE-HEIGHT-X END-CALL
    CALL "AzCssPropertyWithConditions_simpleByref" USING BY REFERENCE t2 BY REFERENCE t1 END-CALL
    CALL "AzCssProperty_noneByref" USING BY REFERENCE t3 BY VALUE AZ-CSS-PROPERTY-TYPE-TEXT-bb42 END-CALL
    CALL "AzCssPropertyWithConditions_simpleByref" USING BY REFERENCE t4 BY REFERENCE t3 END-CALL
    MOVE t2 TO t5-item (1)
    MOVE t4 TO t5-item (2)
    CALL "AzCssPropertyWithConditionsVec_copyFromPtrByref" USING BY REFERENCE t7 BY REFERENCE t5 BY VALUE t6 END-CALL
    MOVE t7 TO ls-result
    GOBACK.
END PROGRAM KEYWORDS.
