pub mod brush_solid;
pub mod brush_solid_alpha_pass;
pub mod brush_image_texture_2d;
pub mod brush_opacity_alpha_pass;
pub mod brush_image_texture_rect;
pub mod brush_image_alpha_pass_texture_2d;
pub mod brush_image_alpha_pass_texture_rect;
pub mod brush_image_antialiasing_repetition_texture_2d;
pub mod brush_image_antialiasing_repetition_texture_rect;
pub mod brush_opacity_antialiasing;
pub mod brush_opacity_alpha_pass_antialiasing;
pub mod brush_linear_gradient;
pub mod brush_linear_gradient_alpha_pass;
pub mod brush_yuv_image_texture_2d_yuv;
pub mod brush_yuv_image_alpha_pass_texture_2d_yuv;
pub mod brush_yuv_image_texture_rect_yuv;
pub mod brush_yuv_image_alpha_pass_texture_rect_yuv;
pub mod cs_scale_texture_2d;
pub mod cs_scale_texture_rect;
pub mod composite_texture_2d;
pub mod composite_texture_rect;
pub mod composite_fast_path_texture_2d;
pub mod composite_fast_path_texture_rect;
pub mod composite_texture_2d_yuv;
pub mod composite_texture_rect_yuv;
pub mod ps_quad_textured;
pub mod ps_quad_mask;
pub mod ps_quad_mask_fast_path;
pub mod ps_quad_radial_gradient;
pub mod ps_quad_conic_gradient;
pub mod ps_text_run_alpha_pass_texture_2d;
pub mod ps_text_run_alpha_pass_glyph_transform_texture_2d;
pub mod ps_text_run_alpha_pass_dual_source_blending_texture_2d;
pub mod ps_text_run_alpha_pass_dual_source_blending_glyph_transform_texture_2d;
pub mod cs_linear_gradient;
pub mod cs_fast_linear_gradient;
pub mod cs_radial_gradient;
pub mod cs_conic_gradient;
pub mod cs_blur_alpha_target;
pub mod cs_clip_rectangle;
pub mod cs_clip_rectangle_fast_path;
pub mod cs_clip_box_shadow_texture_2d;
pub mod brush_blend;
pub mod brush_blend_alpha_pass;
pub mod brush_mix_blend;
pub mod cs_svg_filter_node;
pub mod ps_clear;
pub mod ps_split_composite;
pub mod debug_font;
pub mod brush_image_advanced_blend_alpha_pass_antialiasing_repetition_texture_2d;
pub mod brush_image_advanced_blend_alpha_pass_antialiasing_repetition_texture_rect;
pub mod brush_image_advanced_blend_alpha_pass_texture_2d;
pub mod brush_image_advanced_blend_alpha_pass_rect;
pub mod brush_image_alpha_pass_antialiasing_dual_source_blending_repetition_texture_2d;

// Helper function to compare CStr with &str, mirroring strcmp
pub fn strcmp(cstr: &CStr, s: &str) -> bool {
    cstr.to_bytes() == s.as_bytes()
}
