# AzDrives Texte. Dieselben Schlüssel wie en.ftl (src/l10n_tests.rs).

## Die Registerkarten des Menübands
azdrive-tab-home = Start

## Die Meldungsleiste über dem Inhalt
azdrive-message-dismiss = Schließen
azdrive-list-failed = Dieser Ordner konnte nicht aufgelistet werden:
azdrive-transfer-failed = { $count ->
    [one] Ein Element ist fehlgeschlagen
   *[other] { $count } Elemente sind fehlgeschlagen
    }; „{ $name }“:

## Menüband und Datei-Menü
azdrive-file-about = Info zu AzDrive
azdrive-file-about-about = Version, Lizenz, Danksagungen.
azdrive-file-azterm = AzTerm
azdrive-file-azterm-about = Azlins Terminal im geöffneten Ordner.
azdrive-file-back-forward = Zurück und Vor
azdrive-file-back-forward-about = Vergisst, wohin „Zurück“ und „Vor“ führen.
azdrive-file-delete-history = Verlauf löschen
azdrive-file-everything = Alles
azdrive-file-everything-about = Beides.
azdrive-file-frequent-places = Häufig besuchte Orte
azdrive-file-help = Hilfe
azdrive-file-new-window = Neues Fenster öffnen
azdrive-file-new-window-about = Ein weiteres AzDrive-Fenster an diesem Ort.
azdrive-file-recent-places = Zuletzt besuchte Orte
azdrive-file-shortcuts = Tastenkombinationen
azdrive-file-shortcuts-about = Alle Tasten, die AzDrive kennt (F1).
azdrive-file-terminal = Terminal
azdrive-file-terminal-here = Terminal hier öffnen
azdrive-file-terminal-system = Das Terminal des Systems im geöffneten Ordner.
azdrive-group-clipboard = Zwischenablage
azdrive-group-cloud = Cloud
azdrive-group-current-view = Aktuelle Ansicht
azdrive-group-layout = Layout
azdrive-group-location = Speicherort
azdrive-group-network = Netzwerk
azdrive-group-new = Neu
azdrive-group-organize = Organisieren
azdrive-group-panes = Bereiche
azdrive-group-refine = Verfeinern
azdrive-group-saved = Gespeichert
azdrive-group-select = Auswählen
azdrive-group-send = Senden
azdrive-group-share-with = Freigeben für
azdrive-group-show-hide = Ein-/ausblenden
azdrive-group-sync = Synchronisieren
azdrive-group-system = System
azdrive-ribbon-add-columns = Spalten hinzufügen
azdrive-ribbon-add-drive = Laufwerk hinzufügen
azdrive-ribbon-add-folder-drive = Ordner als Laufwerk hinzufügen
azdrive-ribbon-advanced-security = Erweiterte Sicherheit
azdrive-ribbon-all-subfolders = Alle Unterordner
azdrive-ribbon-burn = Auf Datenträger brennen
azdrive-ribbon-burn-why = AzDrive kann keine Datenträger beschreiben: Dieser Computer hat keinen Brenner, den es nutzen kann.
azdrive-ribbon-close = Schließen
azdrive-ribbon-close-search = Suche schließen
azdrive-ribbon-copy = Kopieren
azdrive-ribbon-copy-link = Link kopieren
azdrive-ribbon-copy-path = Pfad kopieren
azdrive-ribbon-copy-to = Kopieren nach
azdrive-ribbon-current-folder = Aktueller Ordner
azdrive-ribbon-cut = Ausschneiden
azdrive-ribbon-date-modified = Änderungsdatum
azdrive-ribbon-delete = Löschen
azdrive-ribbon-details-pane = Detailbereich
azdrive-ribbon-download = Herunterladen
azdrive-ribbon-easy-access = Einfacher Zugriff
azdrive-ribbon-edit = Bearbeiten
azdrive-ribbon-email = E-Mail
azdrive-ribbon-extensions = Dateinamenerweiterungen
azdrive-ribbon-fax = Faxen
azdrive-ribbon-fax-why = Es ist kein Faxgerät eingerichtet.
azdrive-ribbon-file-contents = Dateiinhalte
azdrive-ribbon-fit-columns = Größe aller Spalten anpassen
azdrive-ribbon-free-up-space = Speicherplatz freigeben
azdrive-ribbon-group-by = Gruppieren nach
azdrive-ribbon-hidden-items = Ausgeblendete Elemente
azdrive-ribbon-hide-selected = Ausgewählte Elemente ausblenden
azdrive-ribbon-history = Verlauf
azdrive-ribbon-index-cloud = Dateien in der Cloud indizieren
azdrive-ribbon-index-drive = Dieses Laufwerk indizieren
azdrive-ribbon-invert-selection = Auswahl umkehren
azdrive-ribbon-item-checkboxes = Elementkontrollkästchen
azdrive-ribbon-keep-on-device = Immer auf diesem Gerät behalten
azdrive-ribbon-kind = Art
azdrive-ribbon-move-to = Verschieben nach
azdrive-ribbon-navigation-pane = Navigationsbereich
azdrive-ribbon-new-folder = Neuer Ordner
azdrive-ribbon-new-item = Neues Element
azdrive-ribbon-open = Öffnen
azdrive-ribbon-open-file-location = Dateispeicherort öffnen
azdrive-ribbon-options = Optionen
azdrive-ribbon-paste = Einfügen
azdrive-ribbon-paste-shortcut = Verknüpfung einfügen
azdrive-ribbon-paste-shortcut-why = Eine Verknüpfung ist eine Windows-Linkdatei; ein Laufwerk hier enthält nur Dateien und Ordner.
azdrive-ribbon-pause-sync = Synchronisierung anhalten
azdrive-ribbon-preview-pane = Vorschaufenster
azdrive-ribbon-print = Drucken
azdrive-ribbon-properties = Eigenschaften
azdrive-ribbon-refresh = Aktualisieren
azdrive-ribbon-remove-drive = Laufwerk entfernen
azdrive-ribbon-rename = Umbenennen
azdrive-ribbon-resume-sync = Synchronisierung fortsetzen
azdrive-ribbon-save-search = Suche speichern
azdrive-ribbon-saved-searches = Gespeicherte Suchen
azdrive-ribbon-select-all = Alles auswählen
azdrive-ribbon-select-none = Nichts auswählen
azdrive-ribbon-size = Größe
azdrive-ribbon-skip-ignored = Ignorierte Dateien überspringen
azdrive-ribbon-sort-by = Sortieren nach
azdrive-ribbon-sync-now = Jetzt synchronisieren
azdrive-ribbon-sync-with-folder = Mit einem Ordner synchronisieren
azdrive-ribbon-unhide-selected = Ausgewählte Elemente einblenden
azdrive-ribbon-upload = Hochladen
azdrive-ribbon-zip = ZIP
azdrive-tab-computer = Computer
azdrive-tab-file = Datei
azdrive-tab-search = Suchen
azdrive-tab-share = Freigeben
azdrive-tab-view = Ansicht
azdrive-undo = Rückgängig
azdrive-ribbon-history-why = Frühere Versionen brauchen einen versionierten Bucket; AzDrive behält eine Version jeder Datei.
azdrive-ribbon-advanced-security-why = Wer ein Cloud-Laufwerk lesen darf, legt seine Bucket-Richtlinie fest; bei einem lokalen Ordner die Freigabeeinstellungen des Systems.
azdrive-file-recent-places-about = Vergisst die Orte, die „Zuletzt besuchte Orte“ und „Häufig besuchte Orte“ sich merken (die angehefteten bleiben).
azdrive-refine-chosen = { $name }: { $chosen }
