# AzDrive's words. Every key the source names (`azdrive-...`) is here and in de.ftl
# (src/l10n_tests.rs). azcloud-kit's error table (`azlin-error-...`) and appkit's words
# (`kit-...`) are registered with these.

## The ribbon's tabs
azdrive-tab-home = Home

## The message bar over the content
azdrive-message-dismiss = Dismiss
azdrive-list-failed = Could not list this folder:
azdrive-transfer-failed = { $count ->
    [one] One item failed
   *[other] { $count } items failed
    }; "{ $name }":

## The ribbon and the File menu
azdrive-file-about = About AzDrive
azdrive-file-about-about = The version, the license, the credits.
azdrive-file-azterm = AzTerm
azdrive-file-azterm-about = Azlin's terminal, in the open folder.
azdrive-file-back-forward = Back and forward
azdrive-file-back-forward-about = Forget where Back and Forward go.
azdrive-file-delete-history = Delete history
azdrive-file-everything = Everything
azdrive-file-everything-about = Both.
azdrive-file-frequent-places = Frequent places
azdrive-file-help = Help
azdrive-file-new-window = Open new window
azdrive-file-new-window-about = Another AzDrive window, at this place.
azdrive-file-recent-places = Recent places
azdrive-file-shortcuts = Keyboard shortcuts
azdrive-file-shortcuts-about = Every key AzDrive knows (F1).
azdrive-file-terminal = Terminal
azdrive-file-terminal-here = Open terminal here
azdrive-file-terminal-system = The system's terminal, in the open folder.
azdrive-group-clipboard = Clipboard
azdrive-group-cloud = Cloud
azdrive-group-current-view = Current view
azdrive-group-layout = Layout
azdrive-group-location = Location
azdrive-group-network = Network
azdrive-group-new = New
azdrive-group-organize = Organize
azdrive-group-panes = Panes
azdrive-group-refine = Refine
azdrive-group-saved = Saved
azdrive-group-select = Select
azdrive-group-send = Send
azdrive-group-share-with = Share with
azdrive-group-show-hide = Show/hide
azdrive-group-sync = Sync
azdrive-group-system = System
azdrive-ribbon-add-columns = Add columns
azdrive-ribbon-add-drive = Add drive
azdrive-ribbon-add-folder-drive = Add folder as drive
azdrive-ribbon-advanced-security = Advanced security
azdrive-ribbon-all-subfolders = All subfolders
azdrive-ribbon-burn = Burn to disc
azdrive-ribbon-burn-why = AzDrive cannot write discs: this computer has no burner it can use.
azdrive-ribbon-close = Close
azdrive-ribbon-close-search = Close search
azdrive-ribbon-copy = Copy
azdrive-ribbon-copy-link = Copy link
azdrive-ribbon-copy-path = Copy path
azdrive-ribbon-copy-to = Copy to
azdrive-ribbon-current-folder = Current folder
azdrive-ribbon-cut = Cut
azdrive-ribbon-date-modified = Date modified
azdrive-ribbon-delete = Delete
azdrive-ribbon-details-pane = Details pane
azdrive-ribbon-download = Download
azdrive-ribbon-easy-access = Easy access
azdrive-ribbon-edit = Edit
azdrive-ribbon-email = Email
azdrive-ribbon-extensions = File name extensions
azdrive-ribbon-fax = Fax
azdrive-ribbon-fax-why = No fax device is set up.
azdrive-ribbon-file-contents = File contents
azdrive-ribbon-fit-columns = Size all columns to fit
azdrive-ribbon-free-up-space = Free up space
azdrive-ribbon-group-by = Group by
azdrive-ribbon-hidden-items = Hidden items
azdrive-ribbon-hide-selected = Hide selected items
azdrive-ribbon-history = History
azdrive-ribbon-index-cloud = Index files in the cloud
azdrive-ribbon-index-drive = Index this drive
azdrive-ribbon-invert-selection = Invert selection
azdrive-ribbon-item-checkboxes = Item check boxes
azdrive-ribbon-keep-on-device = Always keep on this device
azdrive-ribbon-kind = Kind
azdrive-ribbon-move-to = Move to
azdrive-ribbon-navigation-pane = Navigation pane
azdrive-ribbon-new-folder = New folder
azdrive-ribbon-new-item = New item
azdrive-ribbon-open = Open
azdrive-ribbon-open-file-location = Open file location
azdrive-ribbon-options = Options
azdrive-ribbon-paste = Paste
azdrive-ribbon-paste-shortcut = Paste shortcut
azdrive-ribbon-paste-shortcut-why = A shortcut is a Windows link file; a drive here holds files and folders only.
azdrive-ribbon-pause-sync = Pause syncing
azdrive-ribbon-preview-pane = Preview pane
azdrive-ribbon-print = Print
azdrive-ribbon-properties = Properties
azdrive-ribbon-refresh = Refresh
azdrive-ribbon-remove-drive = Remove drive
azdrive-ribbon-rename = Rename
azdrive-ribbon-resume-sync = Resume syncing
azdrive-ribbon-save-search = Save search
azdrive-ribbon-saved-searches = Saved searches
azdrive-ribbon-select-all = Select all
azdrive-ribbon-select-none = Select none
azdrive-ribbon-size = Size
azdrive-ribbon-skip-ignored = Skip ignored files
azdrive-ribbon-sort-by = Sort by
azdrive-ribbon-sync-now = Sync now
azdrive-ribbon-sync-with-folder = Sync with a folder
azdrive-ribbon-unhide-selected = Unhide selected items
azdrive-ribbon-upload = Upload
azdrive-ribbon-zip = Zip
azdrive-tab-computer = Computer
azdrive-tab-file = File
azdrive-tab-search = Search
azdrive-tab-share = Share
azdrive-tab-view = View
azdrive-undo = Undo
azdrive-ribbon-history-why = Earlier versions need a versioned bucket; AzDrive keeps one version of a file.
azdrive-ribbon-advanced-security-why = Who may read a cloud drive is set in its bucket policy; a local folder's in the system's sharing settings.
azdrive-file-recent-places-about = Forget the places Recent locations and Frequent places remember (the pins stay).
azdrive-refine-chosen = { $name }: { $chosen }
