// Generated by azul-css codegen (Java). Do not edit by hand.
package com.azul;

import com.sun.jna.Memory;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.nio.charset.StandardCharsets;
import java.util.function.BiFunction;
import java.util.function.Consumer;

public final class AzulStyles {
    private AzulStyles() {}

    // `user:card`: its texts and its link are parameters
    // not expressible with the Java bindings: DOM export (builder methods and parameters) is not implemented for this language's printer yet
    public static AzDom.ByValue renderCard() {
        return null;
    }
}

final class AzulCodegen {
    private AzulCodegen() {}

    // Runs `init` on `value` and returns it: struct / union literals as expressions.
    static <T> T with(T value, Consumer<T> init) {
        init.accept(value);
        return value;
    }

    // Copies the items into native memory; AzXxxVec_copyFromPtr clones them.
    static <V> V vec(BiFunction<Pointer, Long, V> copy, Structure... items) {
        int size = items[0].size();
        Memory mem = new Memory((long) size * items.length);
        for (int i = 0; i < items.length; i++) {
            items[i].write();
            mem.write((long) i * size, items[i].getPointer().getByteArray(0, size), 0, size);
        }
        return copy.apply(mem, (long) items.length);
    }

    // The same for a Vec of C-like enum values.
    static <V> V vec(BiFunction<Pointer, Long, V> copy, int... items) {
        Memory mem = new Memory(4L * items.length);
        for (int i = 0; i < items.length; i++) {
            mem.setInt(4L * i, items[i]);
        }
        return copy.apply(mem, (long) items.length);
    }

    static AzString.ByValue str(String s) {
        byte[] bytes = s.getBytes(StandardCharsets.UTF_8);
        Memory mem = new Memory(Math.max(1, bytes.length));
        mem.write(0, bytes, 0, bytes.length);
        return AzulNativeStr.AzString_fromUtf8(mem, bytes.length);
    }
}
