// Generated by azul-css codegen (Java). Do not edit by hand.
package com.azul;

public final class AzulUi {
    private AzulUi() {}

    // `user:card`: its texts and its link are parameters
    public static Dom renderCard(String title, String text, String href, String author) {
        return Dom.createDiv()
            .withCss("padding: 8px")
            .withClass("card")
            .withChild(Dom.createH2WithText(title))
            .withChild(Dom.createPWithText(text))
            .withChild(Dom.createA(href, "Read more", SmallAriaInfo.label("Read more")))
            .withChild(Dom.createSpanWithText("by " + author));
    }
}
