//! Julia binding generator.
//!
//! Emits a single `azul.jl` source file (`module Azul`) that exposes the
//! C-ABI of `libazul` to Julia programs. Julia is an archetype-A
//! (C-ABI-direct) target — like Odin, Zig, Go and C — so this backend is
//! modelled directly on `lang_odin`: every struct becomes an isbits Julia
//! `struct`, every enum an `@enum`, every tagged union an isbits byte-blob
//! `struct`, and every exported C symbol a thin `ccall` wrapper function.
//!
//! # Callbacks are C-direct (the key simplification)
//!
//! Julia's `@cfunction(f, Ret, (Args...,))` mints a **real C function
//! pointer** from any top-level Julia function, so the counter's
//! `on_click` / `layout` callbacks are passed straight to
//! `AzButton_setOnClick` / `AzWindowCreateOptions_create` as a plain
//! `Ptr{Cvoid}`. There is NO host-invoker table and NO handle
//! registration — exactly the model `lang_odin` uses. (Callbacks fired
//! from a *foreign* thread would need `@cfunction` care, but the counter
//! callbacks fire on the main event-loop thread, so this is fine.)
//!
//! # Deviations from `lang_odin` (Julia-specific)
//!
//! 1. **Topological type ordering.** Julia has no forward declaration for
//!    concrete structs, so — unlike order-independent Odin — types are
//!    emitted in `sort_order` (the topological order the IR builder
//!    computed for C/C++). By-value struct dependencies are provably
//!    acyclic, so this order always resolves.
//! 2. **Tagged unions.** Julia has no C `union`. A `#[repr(C, u8)]` tagged
//!    union is emitted as one isbits `struct` per variant (so its
//!    `sizeof` is known) plus an `@eval`'d blob struct whose size and
//!    alignment are computed *at module load* from the variant structs.
//!    The blob is isbits and byte-for-byte ABI-compatible with the C
//!    union; the counter only ever constructs unions via C functions and
//!    passes them straight back, never reading union fields in Julia.
//! 3. **Opaque pointers.** Every pointer/reference maps to `Ptr{Cvoid}`
//!    (ABI-identical to any typed pointer), which removes all type
//!    *ordering* hazards from by-pointer references (e.g. `Vec.ptr`
//!    fields, recursive `Box` fields) — only by-value deps constrain the
//!    order.
//! 4. **`@enum` variant names are `Az`-prefixed** (`AzUpdate_RefreshDom`)
//!    because `@enum` injects variant names into the enclosing module
//!    scope; prefixing avoids collisions between enums that share a
//!    variant name (`None`, `Some`, …).
//! 5. **`setfields` helper.** isbits structs are immutable, so nested
//!    field assignment (`window.window_state.title = …`) is expressed as
//!    a functional update `setfields(x; field = …)` that reconstructs the
//!    value via the default positional constructor.
//!
//! # Build / link requirements
//!
//! `ccall((:AzApp_create, LIBAZUL), …)` `dlopen`s `libazul` at call time;
//! the user drops `libazul.{so,dylib}` / `azul.dll` on the loader path
//! (or points `AZUL_LIB` at its absolute path). The generated `azul.jl`
//! is `include`d and `using .Azul`'d by the driver.

pub mod functions;
pub mod types;

use anyhow::Result;

use super::config::CodegenConfig;
use super::generator::CodeBuilder;
use super::ir::{
    ArgRefKind, CodegenIR, EnumDef, FieldRefKind, FunctionDef, StructDef, TypeCategory,
};

/// Generate the full `azul.jl` source file.
pub fn generate(ir: &CodegenIR, config: &CodegenConfig) -> Result<String> {
    // Julia idiom is 4-space indentation.
    let mut b = CodeBuilder::new("    ");

    emit_header(&mut b);
    b.line("module Azul");
    b.blank();
    emit_prelude(&mut b);

    types::generate_types(&mut b, ir, config);
    functions::generate_functions(&mut b, ir, config);
    functions::generate_aliases(&mut b, ir, config);

    b.blank();
    b.line("export az_string, setfields");
    b.line("end # module Azul");

    Ok(b.finish())
}

fn emit_header(b: &mut CodeBuilder) {
    b.line("# ============================================================================");
    b.line("# azul.jl — Julia bindings for the Azul GUI framework");
    b.line("# Auto-generated by azul-doc codegen v2 (lang_julia). DO NOT EDIT MANUALLY.");
    b.line("# ============================================================================");
    b.line("#");
    b.line("# The C-ABI surface is translated explicitly: structs -> isbits `struct`,");
    b.line("# enums -> `@enum`, tagged unions -> isbits byte-blob `struct`, and every");
    b.line("# exported symbol -> a thin `ccall` wrapper. Symbol names match the C");
    b.line("# bindings verbatim (AzApp_create, ...).");
    b.line("#");
    b.line("# Callbacks are C-direct: `@cfunction(f, Ret, (Args...,))` mints a real C");
    b.line("# function pointer passed straight to AzButton_setOnClick /");
    b.line("# AzWindowCreateOptions_create — no host-invoker, like the Odin / C bindings.");
    b.line("#");
    b.line("# Load: `include(\"azul/azul.jl\"); using .Azul` with libazul on the loader");
    b.line("# path (or point AZUL_LIB at its absolute path).");
    b.line("# ============================================================================");
    b.blank();
}

/// Module prelude: the shared C-library handle and the runtime helpers the
/// generated types / examples rely on.
fn emit_prelude(b: &mut CodeBuilder) {
    b.line("# The libazul shared library. `ccall` dlopen's it at call time; set the");
    b.line("# AZUL_LIB env var to an absolute path, or keep the library on the loader");
    b.line("# path (LD_LIBRARY_PATH / DYLD_LIBRARY_PATH / PATH).");
    b.line("const LIBAZUL = get(ENV, \"AZUL_LIB\", Sys.iswindows() ? \"azul\" : \"libazul\")");
    b.blank();
    b.line("# --- tagged-union blob helpers (used by @eval'd union structs) --------------");
    b.line("# Element type giving a Julia value the requested C alignment.");
    b.line("_az_blob_eltype(a::Integer) = a >= 8 ? UInt64 : a == 4 ? UInt32 : a == 2 ? UInt16 : UInt8");
    b.line("# Alignment of an isbits type (matches the C union's alignment).");
    b.line("_az_alignof(@nospecialize(T)) = Base.datatype_alignment(T)");
    b.blank();
    b.line("# --- convenience helpers ----------------------------------------------------");
    b.line("\"\"\"");
    b.line("    az_string(s::AbstractString) -> AzString");
    b.line("");
    b.line("Copy a Julia string into a refcounted AzString (AzString_fromUtf8 copies the");
    b.line("bytes, so passing a temporary buffer is safe).");
    b.line("\"\"\"");
    b.line("function az_string(s::AbstractString)");
    b.line("    bytes = Vector{UInt8}(codeunits(String(s)))");
    b.line("    return GC.@preserve bytes AzString_fromUtf8(pointer(bytes), length(bytes))");
    b.line("end");
    b.blank();
    b.line("\"\"\"");
    b.line("    setfields(x::T; field = value, ...) -> T");
    b.line("");
    b.line("Functional update for an immutable isbits struct: returns a copy of `x` with");
    b.line("the named fields replaced. Used instead of field assignment (isbits structs");
    b.line("are immutable) to customize e.g. `window.window_state.title`.");
    b.line("\"\"\"");
    b.line("function setfields(x::T; kwargs...) where {T}");
    b.line("    names = fieldnames(T)");
    b.line("    vals = Any[getfield(x, i) for i in 1:fieldcount(T)]");
    b.line("    for (k, v) in kwargs");
    b.line("        idx = findfirst(==(k), names)");
    b.line("        idx === nothing && throw(ArgumentError(\"$(T) has no field $(k)\"))");
    b.line("        vals[idx] = v");
    b.line("    end");
    b.line("    return T(vals...)");
    b.line("end");
    b.blank();
}

// ============================================================================
// Shared name / type helpers (used by submodules)
// ============================================================================

/// The `Az`-prefixed FFI type name for an IR type (e.g. `Dom` -> `AzDom`).
pub fn ffi_type_name(name: &str) -> String {
    format!("Az{}", name)
}

/// Is `name` a type declared somewhere in the IR (so it resolves to an
/// `Az`-prefixed Julia declaration)?
pub fn is_ir_type(name: &str, ir: &CodegenIR) -> bool {
    let n = name.trim();
    ir.find_struct(n).is_some()
        || ir.find_enum(n).is_some()
        || ir.find_type_alias(n).is_some()
        || ir.callback_typedefs.iter().any(|c| c.name == n)
}

/// Map a Rust/IR value type to its Julia equivalent (by-value position).
///
/// Primitives map to Julia's native fixed-width types; `usize`/`isize`
/// map to `Csize_t`/`Cssize_t` (== C `size_t`/`ssize_t`).
/// Pointers/references are delegated to [`ptr_to_julia`] (always
/// `Ptr{Cvoid}`). Anything the IR knows becomes `Az<Name>`; anything else
/// degrades to `Ptr{Cvoid}`.
pub fn map_type_to_julia(rust_type: &str, ir: &CodegenIR) -> String {
    let t = rust_type.trim();

    if let Some(rest) = t.strip_prefix("*const ") {
        return ptr_to_julia(rest, ir);
    }
    if let Some(rest) = t.strip_prefix("*mut ") {
        return ptr_to_julia(rest, ir);
    }
    if let Some(rest) = t.strip_prefix("&mut ") {
        return ptr_to_julia(rest, ir);
    }
    if let Some(rest) = t.strip_prefix('&') {
        return ptr_to_julia(rest, ir);
    }

    // Arrays: `[T; N]` -> `NTuple{N, <JuliaT>}` (C array layout, isbits).
    if t.starts_with('[') && t.ends_with(']') {
        let inner = &t[1..t.len() - 1];
        if let Some(semi) = inner.rfind(';') {
            let elem = inner[..semi].trim();
            if let Ok(n) = inner[semi + 1..].trim().parse::<usize>() {
                return format!("NTuple{{{}, {}}}", n, map_type_to_julia(elem, ir));
            }
        }
    }

    match t {
        // Void in value position never really occurs (void returns emit
        // `Cvoid`); degrade to an opaque ptr.
        "void" | "c_void" | "()" => "Ptr{Cvoid}".to_string(),

        "bool" | "GLboolean" => "Bool".to_string(),

        "u8" | "c_uchar" => "UInt8".to_string(),
        "i8" | "c_char" => "Int8".to_string(),
        "u16" | "c_ushort" => "UInt16".to_string(),
        "i16" | "c_short" => "Int16".to_string(),
        "u32" | "c_uint" | "GLuint" | "GLenum" | "GLbitfield" => "UInt32".to_string(),
        "i32" | "c_int" | "GLint" | "GLsizei" => "Int32".to_string(),
        // C `long`/`unsigned long` are 8 bytes on the LP64 targets azul
        // ships; azul's public surface does not use them, so 64-bit is safe.
        "u64" | "c_ulong" | "c_ulonglong" | "GLuint64" => "UInt64".to_string(),
        "i64" | "c_long" | "c_longlong" | "GLint64" => "Int64".to_string(),
        "f32" | "c_float" | "GLfloat" | "GLclampf" => "Float32".to_string(),
        "f64" | "c_double" | "GLdouble" | "GLclampd" => "Float64".to_string(),
        // Pointer-sized integers: Csize_t/Cssize_t == C size_t/ssize_t.
        "usize" | "size_t" | "uintptr_t" => "Csize_t".to_string(),
        "isize" | "ssize_t" | "intptr_t" | "GLsizeiptr" | "GLintptr" => "Cssize_t".to_string(),

        _ => {
            if is_ir_type(t, ir) {
                ffi_type_name(t)
            } else {
                "Ptr{Cvoid}".to_string()
            }
        }
    }
}

/// Map the pointee of a pointer/reference to a Julia pointer expression.
///
/// Every pointer becomes an opaque `Ptr{Cvoid}` — ABI-identical to any
/// typed pointer, and (unlike a typed `Ptr{AzX}`) it imposes no ordering
/// constraint on the referenced type, which is what lets Julia's
/// forward-declaration-free type section resolve `Vec.ptr` / recursive
/// `Box` fields.
pub fn ptr_to_julia(_inner: &str, _ir: &CodegenIR) -> String {
    "Ptr{Cvoid}".to_string()
}

/// Map a `(type_name, FieldRefKind)` pair to the Julia field type.
pub fn field_type_for_ref_kind(
    type_name: &str,
    ref_kind: &FieldRefKind,
    ir: &CodegenIR,
) -> String {
    match ref_kind {
        FieldRefKind::Owned => map_type_to_julia(type_name, ir),
        FieldRefKind::Ref
        | FieldRefKind::RefMut
        | FieldRefKind::Ptr
        | FieldRefKind::PtrMut
        | FieldRefKind::Boxed
        | FieldRefKind::OptionBoxed => ptr_to_julia(type_name, ir),
    }
}

/// Map a `(type_name, ArgRefKind)` pair to the Julia argument type.
pub fn arg_type_for_ref_kind(type_name: &str, ref_kind: &ArgRefKind, ir: &CodegenIR) -> String {
    match ref_kind {
        ArgRefKind::Owned => map_type_to_julia(type_name, ir),
        ArgRefKind::Ref | ArgRefKind::RefMut | ArgRefKind::Ptr | ArgRefKind::PtrMut => {
            ptr_to_julia(type_name, ir)
        }
    }
}

/// Backing integer type for a Julia `@enum`. Rust `#[repr(C, u8)]` -> `UInt8`,
/// otherwise a `#[repr(C)]` enum is C-`int` sized -> `Int32`.
pub fn enum_backing(repr: Option<&str>) -> &'static str {
    match repr {
        Some(r) if r.contains("u8") => "UInt8",
        Some(r) if r.contains("u16") => "UInt16",
        Some(r) if r.contains("u32") => "UInt32",
        Some(r) if r.contains("i64") || r.contains("u64") => "Int64",
        _ => "Int32",
    }
}

/// Discriminant field width for a tagged-union variant struct.
pub fn tag_type(repr: Option<&str>) -> &'static str {
    match repr {
        Some(r) if r.contains("u8") => "UInt8",
        Some(r) if r.contains("u16") => "UInt16",
        Some(r) if r.contains("u32") => "UInt32",
        _ => "Int32",
    }
}

/// Sanitize a name for use as a Julia identifier. Julia reserved words get
/// a trailing underscore (Julia is case-sensitive, so only exact keyword
/// matches collide).
pub fn sanitize_identifier(name: &str) -> String {
    if is_julia_keyword(name) {
        format!("{}_", name)
    } else {
        name.to_string()
    }
}

fn is_julia_keyword(s: &str) -> bool {
    matches!(
        s,
        "baremodule"
            | "begin"
            | "break"
            | "catch"
            | "const"
            | "continue"
            | "do"
            | "else"
            | "elseif"
            | "end"
            | "export"
            | "false"
            | "finally"
            | "for"
            | "function"
            | "global"
            | "if"
            | "import"
            | "in"
            | "isa"
            | "let"
            | "local"
            | "macro"
            | "module"
            | "quote"
            | "return"
            | "struct"
            | "true"
            | "try"
            | "using"
            | "where"
            | "while"
            // context-sensitive words that still break as bare identifiers
            | "abstract"
            | "mutable"
            | "primitive"
            | "type"
            | "outer"
    )
}

/// Strip characters that would break a Julia `#` line comment.
pub fn sanitize_comment(s: &str) -> String {
    s.replace('\n', " ").replace('\r', " ")
}

// ============================================================================
// Shared inclusion filters (mirror the Odin / Pascal backend rules)
// ============================================================================

/// A struct gets a real Julia `struct`; skipped ones become opaque
/// `const AzName = Ptr{Cvoid}` aliases. Only Recursive / GenericTemplate
/// are skipped.
pub fn include_struct(s: &StructDef, config: &CodegenConfig) -> bool {
    if !config.should_include_type(&s.name) {
        return false;
    }
    if !s.generic_params.is_empty() {
        return false;
    }
    !matches!(
        s.category,
        TypeCategory::Recursive | TypeCategory::GenericTemplate
    )
}

pub fn include_enum(e: &EnumDef, config: &CodegenConfig) -> bool {
    if !config.should_include_type(&e.name) {
        return false;
    }
    if !e.generic_params.is_empty() {
        return false;
    }
    !matches!(
        e.category,
        TypeCategory::Recursive | TypeCategory::GenericTemplate
    )
}

/// Whether a function should get a `ccall` wrapper. Mirrors the Odin
/// filter: skip functions whose owning class is a recursive / VecRef /
/// destructor / generic-template type.
pub fn should_emit_function(func: &FunctionDef, ir: &CodegenIR, config: &CodegenConfig) -> bool {
    if !config.should_include_type(&func.class_name) {
        return false;
    }
    if let Some(s) = ir.find_struct(&func.class_name) {
        if matches!(
            s.category,
            TypeCategory::Recursive
                | TypeCategory::VecRef
                | TypeCategory::DestructorOrClone
                | TypeCategory::GenericTemplate
        ) {
            return false;
        }
        if !s.generic_params.is_empty() {
            return false;
        }
    }
    if let Some(e) = ir.find_enum(&func.class_name) {
        if matches!(
            e.category,
            TypeCategory::Recursive
                | TypeCategory::DestructorOrClone
                | TypeCategory::GenericTemplate
        ) {
            return false;
        }
        if !e.generic_params.is_empty() {
            return false;
        }
    }
    true
}
