//! V (vlang) binding generator.
//!
//! Emits a single `azul.v` source file (`module azul`) that exposes the
//! C-ABI of `libazul` to V programs. This is the **archetype-A**
//! (C-ABI-direct) model, cloned from the Odin backend: V has no C-header
//! importer we rely on here, so — like Odin / Pascal / Nim — we translate
//! the whole FFI surface explicitly. Every struct becomes a plain V
//! `struct`, every enum a V `enum` with an explicit backing integer,
//! every tagged union a V `union` of per-variant structs (mirroring the
//! tested `lang_c` layout), every callback typedef a V `fn`-type alias,
//! and every exported symbol a top-level `fn C.AzFoo(...)` extern
//! declaration.
//!
//! # Why plain V structs (not `struct C.Foo`)
//!
//! V only *emits* a struct definition for structs it owns (`struct Foo`);
//! a `struct C.Foo` is assumed to come from a `#include`d header, which we
//! deliberately do not ship (this is the explicit-translation model). So
//! the records are declared as ordinary `pub struct AzFoo`, which V lays
//! out with C ABI (no field reordering, natural alignment). The extern
//! `fn C.AzFoo_bar(x AzFoo)` declarations reference those same records, so
//! passing them by value is ABI-identical to the C bindings — the linker
//! only matches the bare symbol name (`AzApp_create`, …).
//!
//! # Callbacks are C-direct (the key simplification)
//!
//! A top-level V `fn` compiles to a plain C function, so a V function
//! whose signature matches a callback typedef **is** a real C function
//! pointer. `on_click` / `layout` in the counter example are passed
//! straight to `C.AzButton_setOnClick` / `C.AzWindowCreateOptions_create`
//! — there is NO host-invoker table and NO handle registration, exactly
//! like the C / Zig / Odin / Nim bindings. For each callback typedef we
//! emit a V fn-type alias (`pub type AzButtonOnClickCallbackType =
//! fn (AzRefAny, AzCallbackInfo) AzUpdate`), and functions that take a
//! callback-wrapper arg bind the RAW C symbol taking that bare fn-pointer
//! typedef (matching the raw `_setOnClick` variant the DLL exports).
//!
//! # Order-independence
//!
//! V resolves module-scope declarations regardless of source order, so —
//! unlike C / Pascal — no forward declarations or topological sort are
//! needed. Types skipped for codegen (recursive / generic template) are
//! emitted as opaque pointer aliases (`pub type AzXmlNode = voidptr`) so
//! any by-pointer reference still resolves, mirroring the Odin backend.
//!
//! # Build / link requirements
//!
//! `#flag -L.` + `#flag -lazul` (plus the macOS `#flag darwin -framework
//! …` set) make V's C backend link `libazul`. The user drops
//! `libazul.{so,dylib}` / `azul.dll` on the library path and builds with
//! `v run .`. The generated `azul.v` is meant to live in an `azul/`
//! subdirectory imported via `import azul`.

pub mod functions;
pub mod types;

use std::collections::BTreeSet;

use anyhow::Result;

use super::config::CodegenConfig;
use super::generator::CodeBuilder;
use super::ir::{
    ArgRefKind, CodegenIR, EnumDef, FieldRefKind, FunctionDef, StructDef, TypeCategory,
};

/// The C library name linked via `#flag -lazul`.
/// Resolves to `libazul.so` / `libazul.dylib` / `azul.dll` per platform.
pub const LIB_NAME: &str = "azul";

/// Generate the full `azul.v` source file.
pub fn generate(ir: &CodegenIR, config: &CodegenConfig) -> Result<String> {
    // V idiom is tab indentation.
    let mut b = CodeBuilder::new("\t");

    emit_header(&mut b);
    b.line("module azul");
    b.blank();
    emit_flags(&mut b);
    b.blank();

    // Track every emitted top-level name so a duplicate (a struct + a
    // type-alias sharing a name, a case-collision, …) can never produce a
    // V "redefinition" error.
    let mut emitted: BTreeSet<String> = BTreeSet::new();

    types::generate_types(&mut b, ir, config, &mut emitted);
    functions::generate_externs(&mut b, ir, config);

    Ok(b.finish())
}

fn emit_header(b: &mut CodeBuilder) {
    b.line("// ============================================================================");
    b.line("// azul.v — V (vlang) bindings for the Azul GUI framework");
    b.line("// Auto-generated by azul-doc codegen v2 (lang_v). DO NOT EDIT MANUALLY.");
    b.line("// ============================================================================");
    b.line("//");
    b.line("// The C-ABI surface is translated explicitly: structs -> struct, enums ->");
    b.line("// enum, tagged unions -> union, callback typedefs -> `fn`-type aliases, and");
    b.line("// every exported symbol is declared as a top-level `fn C.AzFoo(...)` extern.");
    b.line("// Symbol names match the C bindings verbatim (AzApp_create, ...); call them");
    b.line("// through the `C.` namespace (C.AzApp_create) and use the `azul.Az*` types.");
    b.line("//");
    b.line("// Callbacks are C-direct: a top-level V `fn` is a real C function pointer, so");
    b.line("// pass `on_click` / `layout` straight to C.AzButton_setOnClick /");
    b.line("// C.AzWindowCreateOptions_create — no host-invoker table, like the C / Zig");
    b.line("// / Odin / Nim bindings.");
    b.line("//");
    b.line("// Build: place libazul.{so,dylib}/azul.dll on the link path (`#flag -L.`)");
    b.line("// and build the directory with `v run .`.");
    b.line("// ============================================================================");
    b.blank();
}

/// Emit the `#flag` lines that tell V's C backend how to link `libazul`.
fn emit_flags(b: &mut CodeBuilder) {
    b.line("// Link against libazul. `-L.` points the linker at the current directory;");
    b.line("// drop libazul.{so,dylib}/azul.dll there. macOS also needs the system");
    b.line("// frameworks WebRender / the windowing backend pull in.");
    b.line("#flag -L.");
    b.line(&format!("#flag -l{}", LIB_NAME));
    b.line("#flag darwin -framework Foundation -framework AppKit -framework OpenGL -framework CoreGraphics -framework CoreText");
}

// ============================================================================
// Shared name / type helpers (used by submodules)
// ============================================================================

/// The `Az`-prefixed FFI type name for an IR type (e.g. `Dom` -> `AzDom`).
pub fn ffi_type_name(name: &str) -> String {
    format!("Az{}", name)
}

/// Is `name` a type declared somewhere in the IR (so it resolves to an
/// `Az`-prefixed V declaration)?
pub fn is_ir_type(name: &str, ir: &CodegenIR) -> bool {
    let n = name.trim();
    ir.find_struct(n).is_some()
        || ir.find_enum(n).is_some()
        || ir.find_type_alias(n).is_some()
        || ir.callback_typedefs.iter().any(|c| c.name == n)
}

/// Map a Rust/IR value type to its V equivalent (by-value position).
///
/// Primitives map to V's native fixed-width types; `usize`/`isize` map to
/// V's pointer-sized `usize`/`isize` (== C `size_t`/`ssize_t`). C `int` /
/// `i32` map to V's 32-bit `int`. Pointers/references are delegated to
/// [`ptr_to_v`]. Anything the IR knows becomes `Az<Name>`; anything else
/// degrades to `voidptr`.
pub fn map_type_to_v(rust_type: &str, ir: &CodegenIR) -> String {
    let t = rust_type.trim();

    if let Some(rest) = t.strip_prefix("*const ") {
        return ptr_to_v(rest, ir);
    }
    if let Some(rest) = t.strip_prefix("*mut ") {
        return ptr_to_v(rest, ir);
    }
    if let Some(rest) = t.strip_prefix("&mut ") {
        return ptr_to_v(rest, ir);
    }
    if let Some(rest) = t.strip_prefix('&') {
        return ptr_to_v(rest, ir);
    }

    // Arrays: `[T; N]` -> `[N]<VT>`
    if t.starts_with('[') && t.ends_with(']') {
        let inner = &t[1..t.len() - 1];
        if let Some(semi) = inner.rfind(';') {
            let elem = inner[..semi].trim();
            if let Ok(n) = inner[semi + 1..].trim().parse::<usize>() {
                return format!("[{}]{}", n, map_type_to_v(elem, ir));
            }
        }
    }

    match t {
        // Void in value position never really occurs (void returns are
        // handled by omitting the return type); degrade to an opaque ptr.
        "void" | "c_void" | "()" => "voidptr".to_string(),

        "bool" | "GLboolean" => "bool".to_string(),

        "u8" | "c_uchar" => "u8".to_string(),
        "i8" | "c_char" => "i8".to_string(),
        "u16" | "c_ushort" => "u16".to_string(),
        "i16" | "c_short" => "i16".to_string(),
        "u32" | "c_uint" | "GLuint" | "GLenum" | "GLbitfield" => "u32".to_string(),
        // V's 32-bit signed integer is `int`.
        "i32" | "c_int" | "GLint" | "GLsizei" => "int".to_string(),
        // C `long`/`unsigned long` are 8 bytes on the LP64 targets azul
        // ships (Linux/macOS) and 4 on Windows LLP64; azul's public
        // surface does not use them, so mapping to 64-bit is safe here.
        "u64" | "c_ulong" | "c_ulonglong" | "GLuint64" => "u64".to_string(),
        "i64" | "c_long" | "c_longlong" | "GLint64" => "i64".to_string(),
        "f32" | "c_float" | "GLfloat" | "GLclampf" => "f32".to_string(),
        "f64" | "c_double" | "GLdouble" | "GLclampd" => "f64".to_string(),
        // Pointer-sized integers: V `usize`/`isize` == C size_t/ssize_t.
        "usize" | "size_t" | "uintptr_t" => "usize".to_string(),
        "isize" | "ssize_t" | "intptr_t" | "GLsizeiptr" | "GLintptr" => "isize".to_string(),

        _ => {
            if is_ir_type(t, ir) {
                ffi_type_name(t)
            } else {
                "voidptr".to_string()
            }
        }
    }
}

/// Map the pointee of a pointer/reference to a V pointer expression.
///
/// - `void`/`c_void` -> `voidptr`
/// - a known IR type -> `&Az<Name>`
/// - a primitive -> `&<VT>`
/// - anything else -> `voidptr`
pub fn ptr_to_v(inner: &str, ir: &CodegenIR) -> String {
    let inner = inner.trim();
    match inner {
        "c_void" | "void" | "()" => "voidptr".to_string(),
        _ => {
            if is_ir_type(inner, ir) {
                format!("&{}", ffi_type_name(inner))
            } else {
                let mapped = map_type_to_v(inner, ir);
                if mapped == "voidptr" {
                    "voidptr".to_string()
                } else {
                    format!("&{}", mapped)
                }
            }
        }
    }
}

/// Map a `(type_name, FieldRefKind)` pair to the V field/param type.
pub fn field_type_for_ref_kind(type_name: &str, ref_kind: &FieldRefKind, ir: &CodegenIR) -> String {
    match ref_kind {
        FieldRefKind::Owned => map_type_to_v(type_name, ir),
        FieldRefKind::Ref
        | FieldRefKind::RefMut
        | FieldRefKind::Ptr
        | FieldRefKind::PtrMut
        | FieldRefKind::Boxed
        | FieldRefKind::OptionBoxed => ptr_to_v(type_name, ir),
    }
}

/// Map a `(type_name, ArgRefKind)` pair to the V argument type.
pub fn arg_type_for_ref_kind(type_name: &str, ref_kind: &ArgRefKind, ir: &CodegenIR) -> String {
    match ref_kind {
        ArgRefKind::Owned => map_type_to_v(type_name, ir),
        ArgRefKind::Ref | ArgRefKind::RefMut | ArgRefKind::Ptr | ArgRefKind::PtrMut => {
            ptr_to_v(type_name, ir)
        }
    }
}

/// Sanitize a name for use as a V identifier. V reserved words get a
/// trailing underscore (V is case-sensitive, so only exact keyword matches
/// collide).
pub fn sanitize_identifier(name: &str) -> String {
    if is_v_keyword(name) {
        format!("{}_", name)
    } else {
        name.to_string()
    }
}

fn is_v_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "asm"
            | "assert"
            | "atomic"
            | "break"
            | "const"
            | "continue"
            | "defer"
            | "else"
            | "enum"
            | "false"
            | "fn"
            | "for"
            | "go"
            | "goto"
            | "if"
            | "import"
            | "in"
            | "interface"
            | "is"
            | "isreftype"
            | "lock"
            | "match"
            | "module"
            | "mut"
            | "none"
            | "or"
            | "pub"
            | "return"
            | "rlock"
            | "select"
            | "shared"
            | "sizeof"
            | "spawn"
            | "static"
            | "struct"
            | "true"
            | "type"
            | "typeof"
            | "union"
            | "unsafe"
            | "volatile"
            | "__global"
            | "__offsetof"
    )
}

// ============================================================================
// Shared inclusion filters (mirror the Odin / Pascal backend's rules)
// ============================================================================

/// A struct gets a real V `struct`; skipped ones become opaque pointer
/// aliases. Only Recursive / GenericTemplate are skipped — VecRef /
/// DestructorOrClone are kept because Vec wrappers embed them as fields
/// and eliding them would corrupt surrounding field offsets.
pub fn include_struct(s: &StructDef, config: &CodegenConfig) -> bool {
    if !config.should_include_type(&s.name) {
        return false;
    }
    if !s.generic_params.is_empty() {
        return false;
    }
    !matches!(
        s.category,
        TypeCategory::Recursive | TypeCategory::GenericTemplate
    )
}

pub fn include_enum(e: &EnumDef, config: &CodegenConfig) -> bool {
    if !config.should_include_type(&e.name) {
        return false;
    }
    if !e.generic_params.is_empty() {
        return false;
    }
    !matches!(
        e.category,
        TypeCategory::Recursive | TypeCategory::GenericTemplate
    )
}

/// Whether a function should get an extern declaration. Mirrors the Odin /
/// Pascal filter: skip functions whose owning class is a recursive /
/// VecRef / destructor / generic-template type.
pub fn should_emit_function(func: &FunctionDef, ir: &CodegenIR, config: &CodegenConfig) -> bool {
    if !config.should_include_type(&func.class_name) {
        return false;
    }
    if let Some(s) = ir.find_struct(&func.class_name) {
        if matches!(
            s.category,
            TypeCategory::Recursive
                | TypeCategory::VecRef
                | TypeCategory::DestructorOrClone
                | TypeCategory::GenericTemplate
        ) {
            return false;
        }
        if !s.generic_params.is_empty() {
            return false;
        }
    }
    if let Some(e) = ir.find_enum(&func.class_name) {
        if matches!(
            e.category,
            TypeCategory::Recursive
                | TypeCategory::DestructorOrClone
                | TypeCategory::GenericTemplate
        ) {
            return false;
        }
        if !e.generic_params.is_empty() {
            return false;
        }
    }
    true
}
