// Generated by azul-css codegen (Swift). Do not edit by hand.
import Azul

// CSS: .__azul-native-button:hover, .__azul-native-button:active, .__azul-native-button:focus, .__azul-native-button:hover (conditional), .__azul-native-button:active (conditional), .__azul-native-button:focus (conditional)
public func styleAzulNativeButton() -> [CssPropertyWithConditions] {
    return [
        CssPropertyWithConditions.onHover(CssProperty.backgroundContent([StyleBackgroundContent.color(ColorU(r: 241, g: 243, b: 245, a: 255))])),
        CssPropertyWithConditions.onHover(CssProperty.borderTopColor(StyleBorderTopColor(inner: ColorU(r: 173, g: 181, b: 189, a: 255)))),
        CssPropertyWithConditions.onHover(CssProperty.borderBottomColor(StyleBorderBottomColor(inner: ColorU(r: 173, g: 181, b: 189, a: 255)))),
        CssPropertyWithConditions.onHover(CssProperty.borderLeftColor(StyleBorderLeftColor(inner: ColorU(r: 173, g: 181, b: 189, a: 255)))),
        CssPropertyWithConditions.onHover(CssProperty.borderRightColor(StyleBorderRightColor(inner: ColorU(r: 173, g: 181, b: 189, a: 255)))),
        CssPropertyWithConditions.onActive(CssProperty.backgroundContent([StyleBackgroundContent.color(ColorU(r: 222, g: 226, b: 230, a: 255))])),
        CssPropertyWithConditions.onFocus(CssProperty.borderTopColor(StyleBorderTopColor(inner: ColorU(r: 13, g: 110, b: 253, a: 255)))),
        CssPropertyWithConditions.onFocus(CssProperty.borderBottomColor(StyleBorderBottomColor(inner: ColorU(r: 13, g: 110, b: 253, a: 255)))),
        CssPropertyWithConditions.onFocus(CssProperty.borderLeftColor(StyleBorderLeftColor(inner: ColorU(r: 13, g: 110, b: 253, a: 255)))),
        CssPropertyWithConditions.onFocus(CssProperty.borderRightColor(StyleBorderRightColor(inner: ColorU(r: 13, g: 110, b: 253, a: 255)))),
        CssPropertyWithConditions.withConditions(
            CssProperty.backgroundContent([StyleBackgroundContent.color(ColorU(r: 73, g: 80, b: 87, a: 255))]),
            conditions: [
                DynamicSelector.pseudoState(PseudoStateType.hover),
                DynamicSelector.theme(ThemeCondition.dark),
            ]
        ),
        CssPropertyWithConditions.withConditions(
            CssProperty.borderTopColor(StyleBorderTopColor(inner: ColorU(r: 73, g: 80, b: 87, a: 255))),
            conditions: [
                DynamicSelector.pseudoState(PseudoStateType.hover),
                DynamicSelector.theme(ThemeCondition.dark),
            ]
        ),
        CssPropertyWithConditions.withConditions(
            CssProperty.backgroundContent([StyleBackgroundContent.color(ColorU(r: 43, g: 48, b: 53, a: 255))]),
            conditions: [
                DynamicSelector.pseudoState(PseudoStateType.active),
                DynamicSelector.theme(ThemeCondition.dark),
            ]
        ),
        CssPropertyWithConditions.withConditions(
            CssProperty.borderTopColor(StyleBorderTopColor(inner: ColorU(r: 59, g: 130, b: 246, a: 255))),
            conditions: [
                DynamicSelector.pseudoState(PseudoStateType.focus),
                DynamicSelector.theme(ThemeCondition.dark),
            ]
        ),
    ]
}
