# Generated by azul-css codegen (Python). Do not edit by hand.
from azul import *

def _with(value, **fields):
    for name, field in fields.items():
        setattr(value, name, field)
    return value

# CSS: .card, .card:hover, .card:active, .card:focus, .card (conditional), .card:hover (conditional)
# dropped a value these bindings cannot build: the Python bindings cannot build a DynamicSelectorVec of 2+ items (only create() / from_item())
# dropped a value these bindings cannot build: the Python bindings cannot build a DynamicSelectorVec of 2+ items (only create() / from_item())
# dropped a value these bindings cannot build: LanguageCondition.Prefix has a String payload, which the Python bindings do not expose
def style_card():
    return [
        CssPropertyWithConditions.simple(CssProperty.padding_top(_with(LayoutPaddingTop.default(), inner=PixelValue.px(8.0)))),
        CssPropertyWithConditions.on_hover(CssProperty.padding_top(_with(LayoutPaddingTop.default(), inner=PixelValue.px(9.0)))),
        CssPropertyWithConditions.on_active(CssProperty.padding_top(_with(LayoutPaddingTop.default(), inner=PixelValue.px(10.0)))),
        CssPropertyWithConditions.on_focus(CssProperty.border_top_color(_with(StyleBorderTopColor.default(), inner=_with(ColorU.default(), r=51, g=153, b=255, a=255)))),
        CssPropertyWithConditions.with_condition(CssProperty.padding_left(_with(LayoutPaddingLeft.default(), inner=PixelValue.px(16.0))), DynamicSelector.ViewportWidth(_with(MinMaxRange.default(), min=600.0, max=float("nan")))),
        CssPropertyWithConditions.on_macos(CssProperty.font_size(_with(StyleFontSize.default(), inner=PixelValue.px(13.0)))),
        CssPropertyWithConditions.on_windows(CssProperty.font_size(_with(StyleFontSize.default(), inner=PixelValue.px(12.0)))),
        CssPropertyWithConditions.on_linux(CssProperty.font_size(_with(StyleFontSize.default(), inner=PixelValue.px(11.0)))),
        CssPropertyWithConditions.on_os(CssProperty.font_size(_with(StyleFontSize.default(), inner=PixelValue.px(15.0))), OsCondition.Android),
        CssPropertyWithConditions.dark_theme(CssProperty.text_color(_with(StyleTextColor.default(), inner=_with(ColorU.default(), r=255, g=255, b=255, a=255)))),
    ]

# CSS: .list li:nth-child(2)
def style_list_li_nth_child_2():
    return [
        CssPropertyWithConditions.simple(CssProperty.text_color(_with(StyleTextColor.default(), inner=_with(ColorU.default(), r=153, g=153, b=153, a=255)))),
    ]

# CSS: #main>.title
def style_main_title():
    return [
        CssPropertyWithConditions.simple(CssProperty.font_weight(StyleFontWeight.Bold)),
    ]

# CSS: div .note:first
def style_div_note_first():
    return [
        CssPropertyWithConditions.simple(CssProperty.font_style(StyleFontStyle.Italic)),
    ]
