//! Perl language binding generator (v2)
//!
//! Generates a single `lib/Azul.pm` module using the standard
//! `FFI::Platypus` distribution. No XS, no compile-time glue, no
//! `Makefile.PL` build step is required — Perl loads the prebuilt
//! `azul.dll` / `libazul.so` / `libazul.dylib` at runtime via `lib =>`.
//!
//! # Output structure
//!
//! ```perl
//! package Azul;
//! use strict;
//! use warnings;
//! use FFI::Platypus 2.00;
//!
//! our $ffi = FFI::Platypus->new(
//!     api => 2,
//!     lib => [FFI::CheckLib::find_lib_or_die(lib => 'azul')],
//! );
//!
//! # FFI::Platypus::Record packages for every C-API struct (AzFoo)
//! package Azul::AzApp { use FFI::Platypus::Record; record_layout_1($Azul::ffi, ...) }
//!
//! # `attach` declarations (raw C-ABI surface)
//! $Azul::ffi->attach('AzApp_create' => ['opaque', 'opaque'] => 'opaque');
//!
//! # Idiomatic wrappers (drop Az prefix)
//! package Azul::App {
//!     sub new { my ($class, $ptr) = @_; bless \$ptr, $class }
//!     sub DESTROY { my $self = shift; Azul::FFI::AzApp_delete($$self) }
//!     sub create { my $class = shift; $class->new(Azul::FFI::AzApp_create(@_)) }
//!     sub run { my $self = shift; Azul::FFI::AzApp_run($$self, @_) }
//! }
//!
//! 1;
//! ```
//!
//! # Notes
//!
//! - Like Ruby's generator, Perl emits a free function `generate(ir, config)` instead of
//!   implementing the `LanguageGenerator` trait. The trait targets Rust/C/C++/Python output
//!   formats; Perl (like Ruby, C#, Lua, etc.) doesn't fit that interface cleanly.
//! - Skipped types (Recursive, VecRef, GenericTemplate, DestructorOrClone) get `# SKIPPED:`
//!   comments rather than `# TODO`.
//! - Generated Perl code uses single-quoted strings everywhere except where we explicitly need
//!   escapes — Perl interpolates `$var` inside double quotes, and we don't want accidental
//!   `$ffi`/`@list` interpolation in string literals.

use anyhow::Result;

use super::{config::CodegenConfig, generator::CodeBuilder, ir::CodegenIR};

pub mod cpanfile;
pub mod functions;
pub mod managed;
pub mod types;
pub mod wrappers;

/// Entry point: generate the full `lib/Azul.pm` source as a String.
pub fn generate(ir: &CodegenIR, config: &CodegenConfig) -> Result<String> {
    let mut builder = CodeBuilder::new("    ");

    // File header + FFI::Platypus initialisation.
    emit_header(&mut builder, ir);

    // Raw FFI surface lives under `Azul::FFI` (analogous to Ruby's
    // `Azul::Native`). All the `attach` calls and record layouts go here so
    // user code only ever talks to the idiomatic wrappers.
    builder.line("# ============================================================");
    builder.line("# Native FFI bindings (raw C-API surface; AZ-prefixed types).");
    builder.line("# Use the idiomatic wrappers below in user code instead.");
    builder.line("# ============================================================");
    builder.blank();

    // Forward declarations: empty `package` blocks so subsequent record_layout_1
    // calls can reference each type via 'record(Azul::AzFoo)' regardless of
    // emission order.
    types::emit_forward_declarations(&mut builder, ir, config);

    // Simple (unit) enums: `package Azul::AzFoo { sub Bar() { 0 } sub Baz() { 1 } }`.
    types::emit_simple_enums(&mut builder, ir, config);

    // Callback typedefs as `$ffi->type('(args)->ret' => 'AzFooCb')`.
    types::emit_callback_typedefs(&mut builder, ir, config);

    // Struct + tagged-union record layouts. Interleaved by the IR
    // builder's `sort_order` so dependencies always land before
    // dependents — FFI::Platypus::Record raises
    // `Use of uninitialized value $align ... Illegal modulus zero`
    // when a layout references a record type whose `record_layout_1`
    // call hasn't run yet.
    types::emit_records_in_sort_order(&mut builder, ir, config);

    // `$ffi->attach(...)` for every C-ABI symbol.
    functions::emit_attach_functions(&mut builder, ir, config);

    // Managed-FFI runtime prelude (host-invoker pattern):
    // handle table, releaser, per-kind invoker pins, register_callback,
    // refany_create / refany_get. Must come after attach so the FFI
    // symbols (AzApp_setHostHandleReleaser etc.) are available.
    managed::emit_managed_prelude(&mut builder, ir);

    builder.blank();

    // Idiomatic wrappers (Azul::App, Azul::Dom, etc.) under `package Azul::Foo`.
    wrappers::emit_wrappers(&mut builder, ir, config);

    builder.blank();
    builder.line("# Module load truth value (required by `use Azul;`).");
    builder.line("1;");

    Ok(builder.finish())
}

fn emit_header(builder: &mut CodeBuilder, ir: &CodegenIR) {
    builder.line("# WARNING: autogenerated Perl bindings for the Azul GUI toolkit.");
    builder.line("# Generated by azul-doc codegen v2 -- DO NOT EDIT MANUALLY.");
    builder.line("#");
    builder.line("# Loads the prebuilt native library (azul.dll / libazul.so / libazul.dylib)");
    builder.line("# via FFI::Platypus 2.x; no XS / native compile step is required.");
    builder.line("#");
    builder.line("# Idiomatic API lives under `Azul::<Type>`. The raw C-ABI surface lives");
    builder.line("# under `Azul::FFI::*` and is what the wrapper packages call internally.");
    builder.blank();
    builder.line("package Azul;");
    builder.line("use strict;");
    builder.line("use warnings;");
    builder.line("use FFI::Platypus 2.00;");
    builder.line("use FFI::CheckLib qw(find_lib_or_die);");
    builder.line("use Scalar::Util qw(blessed);");
    builder.blank();
    builder.line(&format!("our $VERSION = '{}';", ir.api_version));
    builder.blank();
    builder.line("# Single FFI::Platypus instance shared by every package below.");
    builder.line("# `our $ffi` so `package Azul::FFI` and the wrapper packages can");
    builder.line("# reference it as `$Azul::ffi`.");
    builder.line("#");
    builder.line("# Library lookup: FFI::CheckLib::find_lib only searches the system");
    builder.line("# loader's path by default, which on macOS's hardened runtime won't");
    builder.line("# honour DYLD_LIBRARY_PATH for non-system processes. Look at");
    builder.line("# AZ_LIB_DIR and the directory containing this .pm file first so");
    builder.line("# absolute-path lookup works alongside the system search path.");
    builder.line("my @_azul_lib_dirs;");
    builder.line("if (my $env = $ENV{AZ_LIB_DIR}) { push @_azul_lib_dirs, $env if length $env; }");
    builder.line("{");
    builder.indent();
    builder.line("require File::Basename;");
    builder.line("my $here = File::Basename::dirname(__FILE__);");
    builder.line("push @_azul_lib_dirs, $here if length $here;");
    builder.dedent();
    builder.line("}");
    builder.line("our $ffi = FFI::Platypus->new(");
    builder.indent();
    builder.line("api => 2,");
    builder.line("lib => [ scalar find_lib_or_die(lib => 'azul', libpath => \\@_azul_lib_dirs) ],");
    builder.dedent();
    builder.line(");");
    builder.blank();
    builder.line("package Azul::FFI;");
    builder.line("our $ffi = $Azul::ffi;");
    builder.blank();
}

#[cfg(test)]
mod field_accessor_tests {
    use super::super::config::CodegenConfig;
    use super::*;

    /// `Azul.pm` for the real api.json, generated once.
    fn azul_pm() -> &'static str {
        static OUT: std::sync::OnceLock<String> = std::sync::OnceLock::new();
        OUT.get_or_init(|| {
            generate(super::super::bug_classes::ir(), &CodegenConfig::c_header())
                .expect("perl codegen")
        })
    }

    /// The text from the line `head` to the next line that is exactly `}`
    /// or starts with `} # package`.
    fn block(head: &str) -> &'static str {
        let out = azul_pm();
        let i = out
            .find(&format!("\n{}\n", head))
            .unwrap_or_else(|| panic!("no `{}` in Azul.pm", head));
        let rest = &out[i + 1..];
        let end = rest.find("\n}").unwrap_or(rest.len());
        &rest[..end]
    }

    /// `sub <name> {` in `body`, up to its closing brace.
    fn sub_body<'a>(body: &'a str, name: &str) -> &'a str {
        let head = format!("sub {} {{", name);
        let i = body
            .find(&head)
            .unwrap_or_else(|| panic!("`sub {}` is missing in:\n{}", name, body));
        let rest = &body[i..];
        &rest[..rest.find("\n    }\n").unwrap_or(rest.len())]
    }

    #[test]
    fn a_wrapper_hands_a_pointer_receiver_the_address_of_its_bytes_not_the_record_object() {
        let app = block("package Azul::App {");
        let run = sub_body(app, "run");
        assert!(run.contains("Azul::FFI::AzApp_run(Azul::_addr($self), "), "{}", run);
        assert!(run.contains("Azul::_consume($root_window)"), "the window is moved:\n{}", run);
        let destroy = sub_body(app, "DESTROY");
        assert!(destroy.contains("Azul::FFI::AzApp_delete(Azul::_addr($self))"), "{}", destroy);
    }

    #[test]
    fn a_window_title_reads_as_a_perl_string_and_its_setter_releases_the_old_title() {
        let fws = block("package Azul::FullWindowState {");
        let get = sub_body(fws, "get_title");
        assert!(get.contains("Azul::_read_string("), "{}", get);
        let set = sub_body(fws, "set_title");
        assert!(set.contains("Azul::FFI::AzString_delete(Azul::_addr($self) + "), "{}", set);
        assert!(set.contains("Azul::_string_bytes($v)"), "{}", set);
    }

    #[test]
    fn window_state_is_deep_copied_out_and_moved_back_in() {
        let wco = block("package Azul::WindowCreateOptions {");
        let get = sub_body(wco, "get_window_state");
        assert!(
            get.contains("Azul::FullWindowState->new(Azul::FFI::AzFullWindowState_clone(Azul::_addr($self) + "),
            "{}",
            get
        );
        let set = sub_body(wco, "set_window_state");
        assert!(set.contains("Azul::FFI::AzFullWindowState_delete(Azul::_addr($self) + "), "{}", set);
        assert!(set.contains("Azul::_take_bytes($v, "), "{}", set);
    }

    #[test]
    fn the_window_size_is_reachable_down_to_its_width() {
        let fws = block("package Azul::FullWindowState {");
        assert!(sub_body(fws, "get_size").contains("Azul::_rec('AzWindowSize', "), "{}", fws);
        let ws = block("package Azul::AzWindowSize { # field accessors");
        assert!(sub_body(ws, "get_dimensions").contains("Azul::_rec('AzLogicalSize', "), "{}", ws);
        let ls = block("package Azul::AzLogicalSize { # field accessors");
        assert!(sub_body(ls, "set_width").contains("pack('f', $v)"), "{}", ls);
    }

    #[test]
    fn checked_and_text_have_accessors() {
        let cb = block("package Azul::AzCheckBoxState { # field accessors");
        assert!(sub_body(cb, "get_checked").contains("unpack('C', "), "{}", cb);
        let ti = block("package Azul::TextInputState {");
        assert!(sub_body(ti, "set_text").contains("Azul::FFI::AzU32Vec_delete("), "{}", ti);
    }
}
