//! Algol 68 (Algol 68 Genie / a68g) binding generator.
//!
//! Produces a single `azul.a68` source file targeting **Algol 68 Genie
//! (a68g)** — the modern, GPL-licensed open-source Algol 68 implementation
//! by Marcel van der Veer. **Standard Algol 68 (the 1968/1973 Revised
//! Report) defines no FFI mechanism**; the `ALIEN` declaration used here
//! is an a68g-specific extension that lets Algol 68 PROCs link against
//! C shared objects at runtime.
//!
//! # Audience
//!
//! Effectively zero. This binding exists as a "universal framework"
//! showcase: if the v2 IR can drive Algol 68 — a language whose newest
//! production-ready implementation is one person's GPL hobby project
//! and whose syntax is from 1968 — it can drive anything.
//!
//! # File layout
//!
//! The single emitted file has four conceptual sections, top to bottom:
//!
//! 1. **MODE forward declarations** — `MODE AZAPP = STRUCT (...);`
//!    Algol 68 is single-pass; types must be declared before use. We
//!    emit unit enums (as INT constants) first, then plain-record
//!    MODEs, then tagged-union MODEs (which use Algol 68's native
//!    `UNION` plus a discriminator INT field).
//! 2. **Enum constants** — Algol 68 has no native enum keyword; we
//!    emit named INT constants (`INT azbuttontype primary = 0;`).
//! 3. **ALIEN PROC declarations** — every C-ABI symbol becomes a
//!    `PROC name = (...) RETURN: ALIEN "az_..." ! "azul";`. The C
//!    symbol literal is preserved verbatim; only the Algol-side
//!    identifier is renamed to lowercase-with-spaces (a68g identifier
//!    convention).
//! 4. **Convention helpers** (wrappers.rs) — Algol 68 has no
//!    destructors and no reference-counted GC. We emit a paired
//!    `delete <type> = (REF <TYPE> x) VOID: ...` PROC for every type
//!    that owns native memory and document the manual-cleanup
//!    convention.
//!
//! # Comment syntax
//!
//! Algol 68 supports two styles. We use the **matching `# ... #`** form
//! throughout for consistency. The legacy `CO ... CO` form is also
//! valid; either can appear in user code.
//!
//! # Wiring
//!
//! This module is intentionally **not** wired from `v2/mod.rs` here. The
//! orchestrator is responsible for adding `pub mod lang_algol68;` and a
//! `pub fn generate_algol68(api_data) -> Result<String>` helper that
//! mirrors `generate_pascal` and is invoked from
//! `GenerationTargets::generate_all`.

use anyhow::Result;

use super::config::CodegenConfig;
use super::generator::CodeBuilder;
use super::ir::CodegenIR;

pub mod functions;
pub mod types;
pub mod wrappers;

/// Library name passed to a68g's `! "<lib>"` suffix on every `ALIEN`
/// declaration. a68g's loader resolves this to `libazul.so` (Linux),
/// `libazul.dylib` (macOS), or `azul.dll` (Windows) at runtime.
pub const LIB_NAME: &str = "azul";

/// Public entry point. Produces the full `azul.a68` source as a `String`.
///
/// The caller is expected to write the result to disk (e.g.
/// `target/codegen/v2/azul.a68`). Algol 68 compilation units do not
/// require an accompanying manifest file; the generated file is included
/// at the top of a user program with a `PR include "azul.a68" PR`
/// pragmat (a68g extension) or simply concatenated.
pub fn generate(ir: &CodegenIR, config: &CodegenConfig) -> Result<String> {
    let mut builder = CodeBuilder::new(&config.indent);

    emit_header(&mut builder);
    emit_pragmats(&mut builder);

    // 1. MODE / type definitions (forward decls + records + unions + enums).
    types::generate_types(&mut builder, ir, config)?;

    // 2. ALIEN PROC declarations for every C-ABI symbol.
    functions::generate_aliens(&mut builder, ir, config)?;

    // 3. Convention helpers: paired `delete` PROCs + cleanup notes.
    wrappers::generate_wrappers(&mut builder, ir, config)?;

    Ok(builder.finish())
}

fn emit_header(builder: &mut CodeBuilder) {
    builder.line("# ============================================================================ #");
    builder.line("# Auto-generated Algol 68 bindings for the Azul GUI framework.                  #");
    builder.line("# Generated by azul-doc codegen v2 (lang_algol68). DO NOT EDIT MANUALLY.        #");
    builder.line("#                                                                                #");
    builder.line("# TARGET: Algol 68 Genie (a68g) >= 3.0. Standard Algol 68 (Revised Report 1973) #");
    builder.line("# defines no foreign-function interface; the ALIEN declarations below are an    #");
    builder.line("# a68g-specific extension. a68g is distributed under the GNU General Public     #");
    builder.line("# License (GPL-3.0+); programs that LINK with libazul through ALIEN inherit no  #");
    builder.line("# license restrictions on libazul itself, but the a68g RUNTIME is GPL — review  #");
    builder.line("# your licensing obligations before redistribution.                             #");
    builder.line("#                                                                                #");
    builder.line("# Run with:   a68g your-program.a68                                              #");
    builder.line("# Linux:      LD_LIBRARY_PATH=. a68g your-program.a68                            #");
    builder.line("# macOS:      DYLD_LIBRARY_PATH=. a68g your-program.a68                          #");
    builder.line("# Windows:    place azul.dll next to your .a68 source, then a68g your-program.a68 #");
    builder.line("# ============================================================================ #");
    builder.blank();
}

/// PRAGMATs are a68g compiler hints. We declare the C calling convention
/// for every following `ALIEN` PROC. A68G accepts `cdecl` on every
/// supported platform; on x86_64 the calling convention is uniform.
fn emit_pragmats(builder: &mut CodeBuilder) {
    builder.line("PRAGMAT");
    builder.indent();
    builder.line("# Use the C cdecl ABI for every following ALIEN declaration. #");
    builder.line("alien convention \"cdecl\"");
    builder.dedent();
    builder.line("PRAGMAT");
    builder.blank();
}

// ============================================================================
// Shared name helpers (used by submodules)
// ============================================================================

/// The C-ABI symbol prefix. Every exported C function and type in
/// `libazul` starts with `Az` (e.g. `AzApp_create`, `AzDom`). We reuse
/// this exact form when emitting the C-symbol literal in `ALIEN "..."`.
pub const PREFIX: &str = "Az";

/// The Algol 68 MODE name for a given IR type (`Dom` -> `AZDOM`).
///
/// Algol 68 identifier convention is mostly lowercase, but **MODE names
/// are conventionally written in UPPERCASE** in the Revised Report
/// examples (`MODE INT`, `MODE STRING`, `MODE BOOL`). We follow the
/// same convention for our generated MODEs so they are visually
/// distinct from PROCs and variables.
pub fn algol_mode_name(name: &str) -> String {
    format!("{}{}", PREFIX, name).to_ascii_uppercase()
}

/// The C-ABI type symbol for a given IR type (`Dom` -> `AzDom`). This is
/// the verbatim name used in the linker / shared-object symbol table —
/// never mangled.
pub fn ffi_type_symbol(name: &str) -> String {
    format!("{}{}", PREFIX, name)
}

/// Convert a method name to an Algol 68 PROC identifier.
///
/// a68g identifiers are case-sensitive but keywords are case-insensitive.
/// The community convention is lowercase letters with optional embedded
/// spaces (Algol 68 *does* allow multi-word identifiers — `make app`
/// is one identifier, not two). We translate `addChild` and `add_child`
/// alike to the spaced form `add child`. To keep things simple we map to
/// **lowercase-with-spaces**.
pub fn algol_proc_name(class: &str, method: &str) -> String {
    // Mirror the C symbol shape `AzClass_method` -> `az class method` so a
    // reader can recognise the underlying C function at a glance.
    let class_lower = camel_or_snake_to_spaced_lower(class);
    let method_lower = camel_or_snake_to_spaced_lower(method);
    format!("az {} {}", class_lower, method_lower)
}

/// snake_case / camelCase / PascalCase -> "lowercase with spaces".
///
/// `addChild`     -> "add child"
/// `add_child`    -> "add child"
/// `AppConfig`    -> "app config"
pub fn camel_or_snake_to_spaced_lower_pub(s: &str) -> String {
    camel_or_snake_to_spaced_lower(s)
}

fn camel_or_snake_to_spaced_lower(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let mut chars = s.chars().peekable();
    let mut first = true;
    while let Some(c) = chars.next() {
        if c == '_' {
            if !out.ends_with(' ') && !first {
                out.push(' ');
            }
            continue;
        }
        if c.is_ascii_uppercase() && !first && !out.ends_with(' ') {
            out.push(' ');
        }
        for lc in c.to_lowercase() {
            out.push(lc);
        }
        first = false;
    }
    out.trim().to_string()
}

/// Sanitize an identifier for use as an Algol 68 variable / field name.
///
/// a68g reserved words are case-INSENSITIVE keywords, but quite numerous.
/// To avoid collisions in field names we rename anything matching a
/// keyword by appending an underscore.
pub fn sanitize_identifier(name: &str) -> String {
    let lower = name.to_ascii_lowercase();
    if is_algol_reserved(&lower) {
        format!("{}_", name)
    } else {
        name.to_string()
    }
}

/// Algol 68 keyword set (subset relevant to identifier collisions).
fn is_algol_reserved(s: &str) -> bool {
    matches!(
        s,
        "abs"
            | "alien"
            | "and"
            | "andth"
            | "begin"
            | "bits"
            | "bool"
            | "by"
            | "bytes"
            | "case"
            | "channel"
            | "char"
            | "co"
            | "comment"
            | "complex"
            | "compl"
            | "do"
            | "elif"
            | "else"
            | "empty"
            | "end"
            | "esac"
            | "exit"
            | "false"
            | "fi"
            | "file"
            | "finish"
            | "flex"
            | "for"
            | "format"
            | "from"
            | "go"
            | "goto"
            | "heap"
            | "if"
            | "in"
            | "int"
            | "is"
            | "isnt"
            | "long"
            | "loc"
            | "mode"
            | "nil"
            | "not"
            | "od"
            | "of"
            | "op"
            | "or"
            | "orel"
            | "ouse"
            | "out"
            | "par"
            | "pr"
            | "pragmat"
            | "priority"
            | "proc"
            | "real"
            | "ref"
            | "sema"
            | "short"
            | "skip"
            | "string"
            | "struct"
            | "then"
            | "to"
            | "true"
            | "union"
            | "until"
            | "void"
            | "while"
    )
}

// ============================================================================
// Type mapping (IR / Rust → Algol 68 MODE)
// ============================================================================

/// Map an IR / Rust type expression to an Algol 68 MODE.
///
/// Pointer / reference forms collapse to `REF <MODE>` when the inner
/// type is a known IR struct / enum / typedef, or to the generic
/// `REF VOID` otherwise. (Algol 68's `VOID` is normally restricted to
/// PROC return types, but a68g accepts `REF VOID` as the C `void *`
/// equivalent.) Strings collapse to the built-in `STRING` MODE; a68g's
/// runtime marshals `STRING` to a null-terminated `char *` automatically.
pub fn map_type_to_algol(rust_type: &str, ir: &CodegenIR) -> String {
    let t = rust_type.trim();

    // Pointer / reference prefixes.
    if let Some(rest) = t.strip_prefix("*const ") {
        return ptr_type(rest, ir);
    }
    if let Some(rest) = t.strip_prefix("*mut ") {
        return ptr_type(rest, ir);
    }
    if let Some(rest) = t.strip_prefix("&mut ") {
        return ptr_type(rest, ir);
    }
    if let Some(rest) = t.strip_prefix('&') {
        return ptr_type(rest, ir);
    }

    match t {
        // Algol 68 has no `void` MODE for variables; map to `REF VOID`
        // (a68g accepts this as the void* equivalent).
        "void" | "c_void" | "()" => "REF VOID".to_string(),

        "bool" | "GLboolean" => "BOOL".to_string(),
        "char" | "c_char" | "i8" | "u8" | "c_uchar" => "CHAR".to_string(),

        "i16" | "u16" => "SHORT INT".to_string(),
        "i32" | "u32" | "c_int" | "c_uint" | "GLint" | "GLuint" | "GLenum" | "GLsizei"
        | "GLbitfield" => "INT".to_string(),
        "i64" | "u64" | "GLint64" | "GLuint64" | "usize" | "isize" | "size_t" => {
            "LONG INT".to_string()
        }

        "f32" | "GLfloat" | "GLclampf" => "REAL".to_string(),
        "f64" | "GLdouble" | "GLclampd" => "LONG REAL".to_string(),

        // Known IR types -> the AZ-prefixed uppercase MODE.
        _ => {
            if ir.find_struct(t).is_some()
                || ir.find_enum(t).is_some()
                || ir.find_type_alias(t).is_some()
                || ir.callback_typedefs.iter().any(|c| c.name == t)
            {
                algol_mode_name(t)
            } else {
                // Unknown -> opaque void pointer.
                "REF VOID".to_string()
            }
        }
    }
}

/// Helper: turn the inner type after a pointer / reference sigil into an
/// Algol 68 `REF <MODE>` expression.
pub fn ptr_type(inner: &str, ir: &CodegenIR) -> String {
    let inner = inner.trim();
    match inner {
        "c_char" | "char" => "STRING".to_string(),
        "c_void" | "void" | "()" => "REF VOID".to_string(),
        _ => {
            if ir.find_struct(inner).is_some()
                || ir.find_enum(inner).is_some()
                || ir.find_type_alias(inner).is_some()
            {
                format!("REF {}", algol_mode_name(inner))
            } else {
                "REF VOID".to_string()
            }
        }
    }
}

/// Sanitize a doc comment for inclusion in Algol 68's `# ... #`
/// comment delimiters: an embedded `#` would close the comment, so we
/// replace it with a `?` and collapse newlines to spaces.
pub fn sanitize_comment(s: &str) -> String {
    s.replace('#', "?").replace('\n', " ").replace('\r', " ")
}
